<?php
$array = [
     'creategroup' => 'Loo uus jutuka grupp',
     'badpass' => 'Parool vigane.',
     'modrules' => 'reeglitele kohandatud',
     'access' => 'access the existing groups here',
     'yourname' => 'Sinu nimi:',
     'desc' => 'Grupi kirjeldus:',
     'let2050' => '(20-50 tähemärki)',
     'grt6' => 'Vähemalt 6 tähemärki, tõusutundlikud - MITTE JAGADA (parool on mõeldud grupisätete muutmiseks)',
     'noshare' => 'ÄRA JAGA',
     'passonly' => '(parool on vaid grupi sätete muutmiseks)',
     'tags' => 'Märksõnad:',
     'sepcom' => '(Eraldatud komadega)',
     'taginfo' => 'Märksõnad on jutukat kirjeldavad sõnad, mis aitab otsides vastava jutuka leidmisel. Nt grupp, mis käsitleb teemana võidusõite võiks sisaldada järgnevaid märksõnu: võidusõit,f1,auto jne. Kui teretulnud on eelkõige eestlased, siis kaasa tagidesse: eestlased,estonians jne.',
     'mustvalid' => 'GRUPI AKTIVEERIMISEKS PEAB TEGEMIST OLEMA KEHTIVA MEILIAADRESSIGA.',
     'grpres' => 'grupinimi reserveeritud',
     'grpexist' => 'grupinimi juba eksisteerub',
     'urlinfo' => 'Valikuline - Veebilehe aadress, kuhu see grupp kaasatakse',
     'grpac1' => '<p>Täname, sinu grupi avaldus on töödeldud. <br /> 
Saatsime sinu meiliaadressile kinnitusmeili. Sul tuleb nüüd grupi aktiveerimiseks kirjas toodud lingile vajutada.</p>
<p><strong>Tähelepanu! Kui kinnitusmeil ei jõua kohale, kontrolli rämpskausta.</strong></p>
<p><strong>(kirja saabumisele võib kuluda kuni 30 minutit)</strong></p>
<p>Kui sa endiselt ei leia kinnituskirja, siis tuleb sul avaldus uuesti koostada, kasutades e-posti teenust, mis töötab (proovi <a href="https://gmail.com">Gmaili</a>). Kui e-posti teenusepakkuja ei luba kirjasid '.XAT_NAME.'’ilt, siis paraku ei saa sa oma jutukat töösse lasta.</p>',
     'grpac2' => 'Palun aktiveeri '.XAT_NAME.'’i jutuka grupp:%s',
     'grpac3' => 'Tere %s,

Vajuta allolevale lingile, et aktiveerida grupp %s ning omandada peaomaniku õigused:

%s

(Tähelepanu! Gruppi ei saa kasutada ning seda ei aktiveerida enne, kui oled ülaltoodud lingile vajutanud)

Aktiveerimise kinnitamiseks saadetakse uus kiri.',
     'grpinfo' => 'Jutuka grupid on jututoad, kus inimesed saavad kokku ühiste huvide jagamiseks. Arutelu võib toimuda kindlal teemal (nt muusika, anime, arvutimängud), olla konkreetsele vanusegrupile või inimesetüübile (nt 20 aastastele, õpilastele) või esindada konkreetset riiki ning selle keelt. Olemasolevatele gruppidele <a href="//'.DOMAIN.'/groups">pääsed ligi siit</a>',
     'az' => 'Lubatud tähemärgid A-Z a-z 0-9 _, nt: Gamefriik',
     'grpwarn' => '<p>Sinu grupp võidakse ettehoiatamata eemaldada, kui:</p>
<p>Sa ei kaasa kehtivat meiliaadressi<br>
 Grupinimi on ebasobilik (vaata <a href="//'.DOMAIN.'/terms" target="_blank">kasutustingimusi</a>)<br>
 Gruppi ei kasutata või sellel puudub moderaatori järelvalve</p>',
     'iam14' => 'Olen 14 aastane või vanem ning nõustun <a href="//'.DOMAIN.'/terms" target="_blank">kasutustingimustega</a>',
     'sendfbk' => 'Saada jutuka grupi omanikule tagasisidet',
     'contact' => 'Kui soovid %s grupi omanikuga ühendust võtta, saad sa seda siin teha. Omanikud ei ole kohustatud sinu kirjadele vastama ning kui sa neile korrektset meiliaadressi ei jaga, siis nad ei saagi seda teha',
     'grpmess1' => 'xat’i grupp: %s - Sõnum',
     'grpmes2' => 'Tere %s Sinu jutuka grupi %s külastaja saatis sulle sõnumi järgneva tekstiga. (LINKIDELE VAJUTAMINE ON MITTESOOVITATAV).',
     'noemail' => 'Kasutaja ei esitanud oma meiliaadress',
     'thxsent' => 'Täname, sinu sõnum on saadetud',
     'optemail' => 'Valikuline, kuid sa ei saa vastust, kui see ei kehti',
     'message' => 'Sõnum',
     'send' => 'Saada',
     'grpmess2' => 'Tere %s Sinu jutuka grupi %s külastaja saatis sulle sõnumi järgneva tekstiga. (LINKIDELE VAJUTAMINE ON MITTESOOVITATAV).',
     'reportgrp' => 'Teavita sobimatust, ropust jututoast',
     'plzsel' => 'Palun valige...',
     'badlang' => 'Ebasobilik, ropp kõnepruuk',
     'scamming' => 'Petmine, andmevargus või häkkimine',
     'badimg' => 'Ebasobilikud pildid või videod',
     'bully' => 'Ahistamine, küberkiusamine, kellegi imiteerimine',
     'unwanted' => 'Soovimatu kontakt',
     'otherissue' => 'Teiste kasutustingimuste rikkumine (palun täpsustage)',
     'readcare' => 'Tähtis: Palun loe tähelepanelikult, enne jutuka sobimatuna teavitamist',
     'mustsel' => 'pead valima olukorda kirjeldava kategooria',
     'bademail' => 'meiliaadress ei kehti',
     'mustchars' => 'peab sisaldama vähemalt 8 tähemärki',
     'complaint' => 'Kaebus:',
     'bedetailed' => '(Palun ole probleemi kirjeldamises nii detailne kui võimalik, et saaksime edasisi otsuseid teha)',
     'nonotify' => 'Me ei pruugi sind teavituse tulemusest ning selle tagajärgedest teavitada.',
     'repimg' => 'Tõestuspildid',
     'canreport' => 'Kui miski rikub meie <a href="//'.DOMAIN.'/terms.html">kasutustingimusi</a>, võid sellest allolevas kastis teada anda. Kui leiad, et miski on muul moel ebasobilik, siis täpsusta miks. Pea meeles, et '.XAT_NAME.' ei lahenda kasutajate vahelisi lahkarvamusi. Palume ilma mõjuva põhjuseta mitte teavitada, korduvad süsteemi kuritarvitamised ning põhjuseta teavitamised võivad lõppeda antud teenusest blokeerimisega.',
     'addinfo' => 'Täiendav info:<br>
(Palun ole probleemi kirjeldamises nii detailne kui võimalik, et saaksime edasisi otsuseid teha)',
     'reportpro' => 'Teavita sobimatust '.XAT_NAME.'.me profiilist',
     'repuser' => 'Kasutajast teavitamine',
     'grpknown' => 'Grupp (kui on teada)',
     'postcom' => 'Postita kommentaar',
     'todelete' => 'Vaid omanikud saavad kommentaare eemaldada',
     'topost' => 'Vaid liikmed saavad kommentaare postitada',
     'confdel' => 'Kommentaari kustutamise kinnitamine',
     'typecom' => 'Trüki oma kommentaarid siia. Võid kasutada põhilisi HTML-i funktsioone ja pilte. (Piirang 5000 baiti)',
     'delcom' => 'Kustuta kommentaar',
     'savcom' => 'Salvesta kommentaar',
     'activategrp' => 'Aktiveeri uus jutuka grupp',
     'expired' => 'Teie grupi taotlus on aegunud. Võid proovida uuesti.',
     'already' => 'Antud grupp on juba aktiveeritud.',
     'taken' => 'Vabandame, kuid antud grupinimi on kasutusel. Võid teist nime kasutades uuesti proovida.',
     'activated' => 'Grupp on nüüd aktiveeritud! Emaililt leiad täpsemad juhised. Grupi aadressiks on:',
     'grpok1' => 'Grupp %s on aktiveeritud',
     'grpok2' => 'Tere %s,

Sinu jutuka grupp, nimega %s on nüüd aktiveeritud.
Link, mille alt grupi leiad: %s

Grupi %s sätete muutmiseks vajuta lehe all asetsevale ’Edit’ nupule ning sisesta nõudmisel parool. Peaomaniku positsiooni taastamiseks vajuta nupule ’Muuda jututuba’.

Kui grupp ei allu kasutustingimustele %s või on ebaaktiivne, võidakse see kustutada. Individuaalid vastutavad ise selle eest, mis materjali nad jutukasse postitavad, kuid moderaatorid ning omanikud peaksid andma kõik endast oleneva, et jutukas viibijad järgiksid kasutustingimusi.

Edu!

xat',
     'seachchat' => 'Otsi jututubadest',
     'searchinfo' => 'Privaatsed jututoad, privaatsed sõnumid ning jututoad, mis on ainult liikmetele, mis pole avalikustatud ning mille sõnumeid ei säilitata POLE otsitavad. <a href="//util.'.DOMAIN.'/wiki/index.php?title=Special:MyLanguage/Search">Rohkem teavet.</a>',
     'moreinfo' => 'Rohkem teavet.',
     'nores' => 'Vabandame, tulemusi ei antud',
     'moreresults' => 'Veel tulemusi',
     'minsago' => 'minutit tagasi, lehel',
     'hoursago' => 'tundi tagasi, lehel',
     'searchingfor' => 'Otsin märksõnu:',
     'results' => 'Tulemused',
     'search' => 'Otsi',
     'mustbe' => 'peab olema vähemalt',
     'letters' => 'tähemärki',
     'unfair' => 'Põhjuseta jututoast eemaldamine',
     'noctrl' => 'Reklaamimine: Ebasobilik või kontrolli alt väljunud',
     'addcom' => 'Lisa kommentaar',
     'dispcom' => 'Kuvab kommentaari',
     'delete' => 'kustuta',
     'news' => 'Uudised',
     'events' => 'Sündmused',
     'inapp' => 'sobimatu',
     'comments' => 'Kommentaarid',
     'grid' => 'võre',
     'player' => 'mängija',
     'doodle' => 'joonistusrakendus',
     'translate' => 'tõlgi',
     'games' => 'mängud',
     'apps' => 'rakendused',
     'embed' => 'Embeedi',
     'chglang' => 'Muuda keelt',
     'sellang' => 'Vali keel:',
     'eventsfor' => 'Jututoa sündmused',
     'oldres' => 'Vanemad tulemused',
     'duration' => 'Kestvus',
     'text' => 'Tekst',
     'canevents' => 'Võid otsida jututoa sündmusi (vt <a href="//util.'.DOMAIN.'/wiki/index.php?title=Special:MyLanguage/Events">viki</a>)',
     'all' => 'Kõik',
     'time' => 'Aeg',
     'emailsent' => 'Kiri saadetud',
     'needlogin' => 'Palun <a href="//'.DOMAIN.'/login">logi sisse</a> selle lehekülje kasutamiseks.',
     'needevents' => 'Vabandame, selle lehe sirvimiseks vajad ’Events’ võimet.',
     'nodays' => 'Vabandame, sinu tellija päevad said otsa.',
     'continue' => 'Jätka',
     'name' => 'Nimi',
     'grassmod' => 'Teavita moderaatorist',
     'feelunfair' => 'Kui tunned, et jututoa moderaator on sind ebaõiglaselt kohelnud, saad sellest vastava jututoa peaomanikku teavitada. Omanikud ei ole kohustatud meilidele vastama ning vale meiliaadressi jagamisel nad ei saagi seda teha.',
     'modrpt1' => 'xat’i grupp: %s - Teavitus moderaatorist',
     'modrpt2' => 'Tere %s Teile on esitatud kaebus moderaatori kohta grupist',
     'modrpt3' => 'Vajuta siia: %s, et näha logi toimunust.',
     'transcript' => 'Logi vestlusest',
     'youneed' => '<p>Sinu ülesanne on veenduda selles, et su moderaatorid teeksid head tööd ning oleksid õiglased sinu külastajate vastu. Piisab vaid ühest halvast tujust, et jututuba jäädavalt rikkuda. Mida parem ning sõbralikum on jutukas toimetav meeskond, seda populaarsemaks jututuba ajapikku kasvab.</p><p>Palun vaata see kaebus hoolega üle ning kui sa ei jää rahule moderaatori tehtud otsustega, siis räägi temaga läbi, kuidas edaspidi toimida või eemalda temalt õigused.</p>',
     'banby' => 'eemaldati jututoast, eemaldajaks:',
     'clkunmod' => 'Õiguste eemaldamiseks vajutage',
     'unfriendly' => '<p>Märkus: Sinu grupp võidakse avalikest nimekirjadest eemaldada, kui sina või sinu meeskond on ebasõbralikud.</p>',
     'transno' => 'Logi ei eksisteeri, võimalik, et see kustutati. Neid peetakse vaid nädala',
     'unmod' => 'Eemalda moderaatorilt õigused',
     'yesunmod' => 'Jah - Eemalda õigused',
     'sureunmod' => 'Oled kindel, et soovid moderaatorilt õigused eemaldada',
     'chatconf' => 'Palun kinnita jutukas külaliseks tegemist',
     'tounmod' => 'Vajuta linki ülal õiguste eemaldamiseks',
     'istrans' => 'Allpool kuvab logi vestlusest, mis lõppes jutukast eemaldamisega',
     'chatid' => 'Jututoa ID:',
     'seeall' => 'Siin näed kõiki gruppidele määratud taustapilte ning saad ühtlasi sobimatud välja noppida ja nendest vastavatele pildimajutajatele teavitada.'
	 ]
?>