<?php
$array = [
     'groups' => 'Grupid',
     'store' => 'Pood',
     'buyxats' => 'Osta '.XAT_NAME.'’e, tellija päevi',
     'powers' => 'Võimed',
     'xavi' => 'xavis',
     'xatgroup' => 'xat’i grupp',
     'shortname' => 'Lühinimi',
     'promotion' => 'Reklaamimine',
     'auctions' => 'Oksjonid',
     'community' => 'Foorum',
     'more' => 'Veel',
     'twitter' => 'Twitter',
     'wiki' => 'Viki',
     'support' => 'Tugi',
     'contact' => 'Kontakt',
     'help' => 'Abi',
     'trade' => 'Kauplemine',
     'widgets' => 'Vidinad',
     'login' => 'Logi sisse',
     'language' => 'Keel',
     'privacy' => 'Privaatsus',
     'terms' => 'Kasutustingimused',
     'safety' => 'Turvalisus',
     'failed' => 'ebaõnnestus',
     'evalid' => 'meiliaadress ei kehti',
     'recaperr' => 'Sisestasid kontrollkoodi valesti. Palun proovi uuesti. (reCAPTCHA ütles',
     'notbot' => 'ning veendumaks selles, et oled inimene',
     'numinbox' => 'Palun sisesta kastis olev number',
     'cancel' => 'Katkesta',
     'submit' => 'Kinnita',
     'wrongnum' => 'Sisestasid vale numbri!',
     'ayaherr' => 'Pead tõestama inimeseks olemist.'
	 ]
?>