<?php


$array = [
     'quizq1' => 'Você recebe uma mensagem de um usuário que diz ser voluntário. Essa pessoa diz que sua conta está bloqueada e para resolver o problema, você deve dar a sua senha e o seu endereço de e-mail, ou sua conta continuará bloqueada. O que você faz?',
     'quizq1a1' => 'Não da nenhuma informação.',
     'quizq1a2' => 'Você não quer perder sua conta, então você da toda a informação.',
     'quizq1a3' => 'Pede por provas de que são voluntários de verdade.',
     'quizq1info' => 'Correto! A equipe do '. XAT_NAME .' e os voluntários nunca vão pedir por informações pessoais no chat privado. Denuncie o usuário tomando screenshots do ID e das mensagens, em seguida abra um ticket na área de Report Scam.',
     'quizq1image' => '<br img src="https://'. DOMAIN .'/wiki/images/quiz/Securityimage1.png" class="img-fluid"/>',
     'quizq2' => 'Você está no chat Trade tentando comprar days. Você é contatado por uma pessoa que pede para você transferir os '. XAT_NAME .'s primeiro. O que você faz?',
     'quizq2a1' => 'Nega e sugere o uso do aplicativo de trade seguro (Safe Trade) que é o método recomendado.',
     'quizq2a2' => 'Transfere seus '. XAT_NAME .'s primeiro.',
     'quizq2a3' => 'Ao invés disso, pede os days dele primeiro.',
     'quizq2info' => 'Isso aí! Certo. Ao comprar '. XAT_NAME .'s, days, ou powers você deve sempre usar o Safe Trade (aplicativo de trade). A partir desse aplicativo, você pode ver em tempo real o que está sendo negociado. Nunca negocie usando a opção de Transfer (transferir), pois as transações não podem ser desfeitas depois de completadas.',
     'quizq2image' => '<br img src="https://'. DOMAIN .'/wiki/images/quiz/Securityimage2.png" class="img-fluid"/>',
     'quizq3' => 'Seu provedor de e-mail oferece proteção de autenticação por 2 fatores Será que você deve ativar essa opção?',
     'quizq3a1' => 'Sim. Isso aumentará a segurança do endereço de e-mail.',
     'quizq3a2' => 'Não. Minha senha já é forte o suficiente.',
     'quizq3a3' => 'Nunca. Essa proteção não é útil.',
     'quizq3info' => 'Correto! A autenticação por 2 fatores no seu endereço de e-mail vai adicionar uma camada adicional de segurança (pelo celular) para garantir que ninguém além de você possa acessar o seu e-mail - mesmo se sua senha for comprometida.<br><br>Por favor entre em contato com o seu provedor de e-mail para mais instruções de como ativar a autenticação na sua conta de e-mail. Para usuários do Gmail, por favor confira <a href="https://www.google.com/landing/2step/" target="_blank">esta página</a>.',
     'quizq3image' => '<br img src="https://'. DOMAIN .'/wiki/images/quiz/Securityimage3.png" class="img-fluid"/>',
     'quizq4' => 'Você é informado sobre uma atualização na página de login do '. XAT_NAME .'. O usuário envia um link para testes, que é: https://xaatt.com/login. O que você faz?',
     'quizq4a1' => 'Não clica no link sabendo que não é um domínio https://'. DOMAIN .'.',
     'quizq4a2' => 'Clica no link para ver o que mudou.',
     'quizq4info' => 'Correto! Sempre verifique a barra de endereço para assegurar que você está no domínio <a href="https://'. DOMAIN .'" target="_blank">https://'. DOMAIN .'</a> antes de logar, visitar um chat ou entrar com qualquer informação do '. XAT_NAME .'.',
     'quizq4image' => '<br img src="https://'. DOMAIN .'/wiki/images/quiz/Securityimage4.png" class="img-fluid"/>',
     'quizq5' => 'Um usuário oferece para duplicar os seus powers mas você deve transferir-los para ele primeiro. O que você faz?',
     'quizq5a1' => 'Powers não podem ser duplicados. Você não transfere os powers.',
     'quizq5a2' => 'Aceita a oferta. Powers duplicados significam lucros em dobro.',
     'quizq5a3' => 'Pede por provas de que ele pode duplicar seus itens',
     'quizq5info' => 'Isso aí! Ta certo. '. XAT_NAME .'s, days e powers não podem ser duplicados. Ladrões usam frequentemente esta técnica para conseguir sua atenção e seus itens. Denuncie o usuário tomando screenshots do ID e das mensagens, em seguida abra um ticket na área de Report Scam.',
     'quizq5image' => '<br img src="https://'. DOMAIN .'/wiki/images/quiz/Securityimage5.png" class="img-fluid"/>',
     'quizq6' => 'Você recebe um e-mail do info@'. DOMAIN .' dizendo que seus powers devem ser checados manualmente por um funcionário do '. XAT_NAME .'. A instrução diz que você deve transferir os powers no chat para uma pessoa específica. Se você recusar, sua conta ficará bloqueada por três (3) meses. O que você faz?',
     'quizq6a1' => 'Ignora e denuncia o e-mail como spam.',
     'quizq6a2' => 'Aceita a oferta sem questionar! Sem bloqueio, por favor.',
     'quizq6a3' => 'Responde o e-mail solicitando mais informações.',
     'quizq6info' => 'Isso aí! Ta certo. Você nunca receberá um e-mail do '. XAT_NAME .' dizendo isso. Todas as notificações sobre a sua conta do '. XAT_NAME .' são informadas apenas pelo sistema de suporte <a href="https://'. DOMAIN .'/ticket" target="_blank">'. DOMAIN .'/ticket</a> e em nenhum outro lugar.',
     'quizq6image' => '<br img src="https://'. DOMAIN .'/wiki/images/quiz/Securityimage6.png" class="img-fluid"/>',
     'quizq7' => 'Todo mundo sabe que senhas são difíceis de lembrar. Então para tornar sua vida mais fácil, você decide usar o mesmo código para senha no seu e-mail e na sua conta de '. XAT_NAME .'. Será que isso é seguro?',
     'quizq7a1' => 'Não!',
     'quizq7a2' => 'Claro que sim! Assim nunca vou ter problemas de esquecer a senha.',
     'quizq7info' => 'Ta certo! Dificuldade pode ser recompensada. Sempre use senhas diferentes para cada uma de suas contas online para aumentar a sua proteção.',
     'quizq7image' => '<br img src="https://'. DOMAIN .'/wiki/images/2/2b/Securityimage7.png" class="img-fluid"/>',
     'quizq8' => 'Você é informado sobre um gerador de '. XAT_NAME .'s de graça que precisa fazer o download. O que você faz?',
     'quizq8a1' => 'Você sabe que '. XAT_NAME .'s não podem ser gerados, então você ignora.',
     'quizq8a2' => 'Pede por mais informações.',
     'quizq8a3' => 'Pede por provas de que os '. XAT_NAME .'s podem ser gerados.',
     'quizq8info' => 'Você está certo! '. XAT_NAME .'s não podem ser gerados de graça! Tenha cuidado para não fazer o download de arquivos desconhecidos pois podem ser maliciosos e conter vírus.',
     'quizq8image' => '<br img src="https://'. DOMAIN .'/wiki/images/quiz/Securityimage8.png" class="img-fluid"/>',
     'quizq9' => 'Você recebe uma mensagem dizendo que sua conta será bloqueada em 24 horas exceto a não ser que você pague 10000 '. XAT_NAME .'s. O que você faz?',
     'quizq9a1' => 'Não envio os '. XAT_NAME .'s e ignoro o usuário.',
     'quizq9a2' => 'Bloqueio!? Nunca! Pago a multa.',
     'quizq9a3' => 'Pede por uma explicação.',
     'quizq9info' => 'Correto! A equipe do '. XAT_NAME .' e os voluntários nunca vão pedir por '. XAT_NAME .'s. Denuncie o usuário tomando screenshots do ID e das mensagens, em seguida abra um ticket na área de Report Scam.',
     'quizq9image' => '<br img src="https://'. DOMAIN .'/wiki/images/quiz/Securityimage9.png" class="img-fluid"/>',
     'quizq10' => 'Você recebe uma oferta muita alta pelos seus powers, de 50000 '. XAT_NAME .'s. Durante o trade, ocorre muitas tentativas que deram erro devido a senha errada e outros erros. O que você faz?',
     'quizq10a1' => 'Diz respeitosamente ao usuário que você irá reiniciar o trade.',
     'quizq10a2' => 'Ignora o problema e continua o trade.',
     'quizq10a3' => 'Ignora o usuário.',
     'quizq10info' => 'Correto! Golpistas vão tentar roubar seus '. XAT_NAME .'s, days e powers mudando a quantidade de '. XAT_NAME .'s e days ou até dos powers no aplicativo de trade.<br><br>Sempre tenha muita cuidado e verifique duas vezes todos os powers no trade após cada tentativa que der erro. Tome mais um momento para rechecar os detalhes do trade antes de clicar em confirmar (confirm).',
     'quizq10image' => '<br img src="https://'. DOMAIN .'/wiki/images/quiz/Securityimage10.png" class="img-fluid"/>',
     'quizq11' => 'Você recebe uma mensagem privada no fórum de uma pessoa dizendo ser um funcionário do '. XAT_NAME .'. Essa mensagem pede pelos detalhes da sua conta (senha e e-mail), do contrário sua conta será bloqueada pelo '. XAT_NAME .'. O que você faz?',
     'quizq11a1' => 'Ignora o usuário e o reporta para a equipe do fórum.',
     'quizq11a2' => 'Responde a mensagem com as informações solicitadas.',
     'quizq11a3' => 'Pede por mais informações sobre o bloqueio.',
     'quizq11info' => 'Correto! A equipe do '. XAT_NAME .' e os voluntários nunca vão contatar você no privado sobre problemas de conta como bloqueios. Todos os problemas de conta são resolvidos no sistema de suporte em <a href="https://'. DOMAIN .'/ticket" target="_blank">'. DOMAIN .'/ticket</a> e você deve reportar as mensagens privadas maliciosas e impróprias.',
     'quizq11image' => '<br img src="https://'. DOMAIN .'/wiki/images/quiz/Securityimage11.png" class="img-fluid"/>',
     'quizq12' => 'Você é informado em um chat por um funcionário do '. XAT_NAME .' para desativar a proteção de autenticação em 2 fatores do seu endereço de e-mail. O que você faz?',
     'quizq12a1' => 'Nega e ignora.',
     'quizq12a2' => 'Desativa a proteção de autenticação em 2 fatores.',
     'quizq12info' => 'Sim, você está certo! A equipe do '. XAT_NAME .' e os voluntários nunca vão pedir para você desativar a proteção por autenticação em 2 fatores sob nenhuma circunstância. Não hesite em denunciar os usuários que tentarem desativar as proteções da sua conta.',
     'quizq12image' => '<br img src="https://'. DOMAIN .'/wiki/images/quiz/Securityimage12.png" class="img-fluid"/>',
     'quizq13' => 'Você é informado sobre uma página de gerador de '. XAT_NAME .'s de graça em um site. Mas o gerador de '. XAT_NAME .'s precisa da sua senha e endereço de e-mail. O que você faz?',
     'quizq13a1' => 'Ignora o site sabendo que '. XAT_NAME .'s não podem ser gerados de graça.',
     'quizq13a2' => 'Procede e faz login.',
     'quizq13a3' => 'Pede por provas de que os '. XAT_NAME .'s podem ser gerados.',
     'quizq13info' => 'Você está certo! '. XAT_NAME .'s não podem ser gerados de graça. Apenas entre com sua senha de '. XAT_NAME .' em páginas oficiais do <a href="https://'. DOMAIN .'" target="_blank">https://'. DOMAIN .'</a>. Sempre verifique a barra de endereço do navegador para assegurar que você está no <a href="https://'. DOMAIN .'" target="_blank">'. DOMAIN .'</a>',
     'quizq13image' => '<br img src="https://'. DOMAIN .'/wiki/images/5/57/Securityimage13.png" class="img-fluid"/>',
     'quizq14' => 'Você negociou um acordo para comprar powers de um usuário no chat Trade. O user diz que vai transferir metade dos powers agora e a outra metade depois. O que você faz?',
     'quizq14a1' => 'Recusa a oferta - ele deve adicionar todos os powers agora',
     'quizq14a2' => 'Aceita a oferta. Nada vai dar errado mesmo.',
     'quizq14a3' => 'Pede por provas de que ele tem todos os powers.',
     'quizq14info' => 'Correto! Golpistas vão tentar vacilar nos trades fazendo ofertas com uma quantia inicial e prometendo pagar o resto no futuro. Nunca acredite nestes usuários e apenas aceite a quantia acordada em um trade completo. O usuário dificilmente vai retornar depois.',
     'quizq14image' => '<br img src="https://'. DOMAIN .'/wiki/images/5/59/Securityimage14.png" class="img-fluid"/>',
     'quizq15' => 'Você é informado sobre um programa gratuito que faz avatares animados (gifs). Uma pessoa no chat envia um link de download para o programa que está disponível em um site desconhecido. O que você faz?',
     'quizq15a1' => 'Nunca faça download de arquivos desconhecidos pois podem conter vírus.',
     'quizq15a2' => 'Faz o download.',
     'quizq15info' => 'Correto! Golpistas vão tentar você oferecendo downloads de vírus enquanto se passam como amigos ajudantes. Seja cuidadoso para não baixar arquivos desconhecidos. Algumas dicas para evitar o download de coisas maliciosas são:<br><br ol><li>Procure pelo nome do arquivo no Google (verifique a credibilidade do programa, e se ele realmente existe).</li><li>Verifique por fontes alternativas de download (outros sites para baixar).</li><li>Escaneie o arquivo com um anti-vírus online.</li></ol>',
     'quizq15image' => '<br img src="https://'. DOMAIN .'/wiki/images/quiz/Securityimage15.png" class="img-fluid"/>',
     'quizq16' => 'Uma pessoa que você conheceu no chat pede pelas suas informações pessoais, como seu nome, sua rua e seu endereço de e-mail. O que você faz?',
     'quizq16a1' => 'Mude de assunto falando que você não quer falar de suas informações pessoais.',
     'quizq16a2' => 'Ele parece ser legal o suficiente, então você responde ele com suas informações reais.',
     'quizq16a3' => 'Ignora o usuário.',
     'quizq16info' => 'Isso aí! Ta certo. Você não deve compartilhar suas informações pessoais com ninguém online. Nunca compartilhe o seu endereço de e-mail ou senha!',
     'quizq16image' => '<br img src="https://'. DOMAIN .'/wiki/images/quiz/Securityimage16.png" class="img-fluid"/>',
     'quizq17' => 'Você é notificado no chat que sua conta de '. XAT_NAME .' tem um problema, e para corrigi-lo você precisa desativar as proteções da sua conta na página de login. O que você faz?',
     'quizq17a1' => 'Nunca desative as proteções da sua conta quando solicitado.',
     'quizq17a2' => 'Você confia em qualquer estranho. Você faz login com as proteções desativas.',
     'quizq17a3' => 'Pede por mais informações antes de considerar o pedido.',
     'quizq17info' => 'Correto! Você nunca deve desativar as proteções da sua conta de '. XAT_NAME .' sob nenhuma circunstância. Os funcionários do '. XAT_NAME .' e os voluntários nunca vão pedir para que você desative as suas proteções.',
     'quizq17image' => '<br img src="https://'. DOMAIN .'/wiki/images/quiz/Securityimage17.png" class="img-fluid"/>',
     'quizq18' => 'Um amigo pede pelo seu power namecolor emprestado por um tempo, porque quer testar os seus efeitos. O que você faz?',
     'quizq18a1' => 'Não da o power, pois têm chances de você não obtê-lo de volta.',
     'quizq18a2' => 'Não tem problema emprestar. Você consegue seus powers de volta em qualquer hora.',
     'quizq18a3' => 'Melhores amigos para sempre. Você clica em trade, sem pensar duas vezes!',
     'quizq18info' => 'Isso aí! Ta certo. Seus '. XAT_NAME .'s, days e powers são de sua exclusiva responsabilidade. Empréstimos não existem no '. XAT_NAME .', e serão vistos como se você tivesse doado os itens. Se você completou um trade ou uma transferência, ela não pode ser desfeita. Seja cuidadoso em todos os momentos. <a href="//'. DOMAIN .'/wiki/index.php?title=Trading" target="_blank">Leia mais aqui. </a>',
     'quizq18image' => '<br img src="https://'. DOMAIN .'/wiki/images/quiz/Securityimage18.png" class="img-fluid"/>',
     'start' => 'começar o quiz',
     'desc' => 'Para obter o power <a href="//'. DOMAIN .'/wiki/index.php?title=Tickle" target="_blank">tickle</a> de graça, você deve completar o quiz abaixo e responder cada pergunta corretamente.',
     'wronganswer' => 'Incorreto. Por favor tente novamente.',
     'next' => 'próximo',
     'continuein' => 'Continuar em',
     'gratz' => 'Parabéns, você completou o quiz! Agora você deve ter mais conhecimento sobre segurança no '. XAT_NAME .'.',
     'tickle' => 'Você recebeu o power (tickle).',
     'redirect' => 'Por favor aguarde enquanto redirecionamos você para a página de login.'
	]
?>