<?php
$array = [
      'login' => 'Bejelentkezés',
     'cancel' => 'Törlés',
     'logout' => 'Kijelentkezés',
     'done' => 'Kész',
     'edit' => 'Szerkesztés',
     'searchgroup' => 'Csoportok között kereső',
     'addsmilie' => 'Smiley hozzáadása',
     'backchats' => '❮ Chatek',
     'backmessages' => '❮ Üzenetek',
     'backback' => '❮ Vissza',
     'pchats' => 'Privát Chatek',
     'search' => 'Keresés',
     'me' => 'Magam',
     'actions' => 'Akció',
     'visitors' => 'Látogatók',
     'groups' => 'Csoportok',
     'chats' => 'Chatek',
     'friends' => 'Barátok',
     'profile' => 'Profil',
     'powers' => 'Powerek',
     'favorites' => 'Kedvencek',
     'featured' => 'Kiemelt',
     'popular' => 'Népszerű',
     'new' => 'Új',
     'standard' => 'Alapértelmezett',
     'rare' => 'Ritka',
     'epic' => 'Epic',
     'settings' => 'Beállítások',
     'help' => 'Segítség',
     'more' => 'Több',
     'message' => 'Üzenet',
     'close' => 'Bezár',
     'xats' => 'xats',
     'days' => 'days',
     'store' => 'Store',
     'justnow' => 'just most',
     'minsago' => 'percekkel ezelőtt',
     'hoursago' => 'órával ezelőtt',
     'daysago' => 'nappal ezelőtt',
     'buyxats' => 'Vásárlás xats',
     'back' => 'Vissza']


?>