<?php
$array = [
     'login' => 'Login',
     'cancel' => 'Cancella',
     'logout' => 'Logout',
     'done' => 'Fatto',
     'edit' => 'Modifica',
     'searchgroup' => 'Cerca un Gruppo',
     'addsmilie' => 'Aggiungi Smiley',
     'backchats' => '❮ Chats',
     'backmessages' => '❮ Messaggi',
     'backback' => '❮ Indietro',
     'pchats' => 'Chat Private',
     'search' => 'Ricerca',
     'me' => 'Me',
     'actions' => 'Azioni',
     'visitors' => 'Utenti',
     'groups' => 'Gruppi',
     'chats' => 'Chats',
     'friends' => 'Amici',
     'profile' => 'Profilo',
     'powers' => 'Poteri',
     'favorites' => 'Favoriti',
     'featured' => 'In primo piano',
     'popular' => 'Popolari',
     'new' => 'Nuovo',
     'standard' => 'Standard',
     'rare' => 'Raro',
     'epic' => 'Epico',
     'settings' => 'Impostazioni',
     'help' => 'Help',
     'more' => 'Altro',
     'message' => 'Message',
     'close' => 'Close',
     'xats' => 'xats',
     'days' => 'days',
     'store' => 'Store',
     'justnow' => 'just now',
     'minsago' => 'mins ago',
     'hoursago' => 'hours ago',
     'daysago' => 'days ago',
     'buyxats' => 'Buy xats',
     'back' => 'Back']



?>