<?php
$array = [
     'login' => 'Entrar',
     'cancel' => 'Cancelar',
     'logout' => 'Sair',
     'done' => 'Feito',
     'edit' => 'Editar',
     'searchgroup' => 'Pesquisar um Grupo',
     'addsmilie' => 'Adicionar Smiley',
     'backchats' => '❮ Chats',
     'backmessages' => '❮ Mensagens',
     'backback' => '❮ Voltar',
     'pchats' => 'Chats Privados',
     'search' => 'Pesquisar',
     'me' => 'Eu',
     'actions' => 'Ações',
     'visitors' => 'Visitantes',
     'groups' => 'Grupos',
     'chats' => 'Chats',
     'friends' => 'Amigos',
     'profile' => 'Perfil',
     'powers' => 'Powers',
     'favorites' => 'Favoritos',
     'featured' => 'Destaque',
     'popular' => 'Popular',
     'new' => 'Novo',
     'standard' => 'Padrão',
     'rare' => 'Raro',
     'epic' => 'Épico',
     'settings' => 'Configurações',
     'help' => 'Ajuda',
     'more' => 'Mais',
     'message' => 'Mensagem',
     'close' => 'Fechar',
     'xats' => 'xats',
     'days' => 'dias',
     'store' => 'Loja',
     'justnow' => 'agora',
     'minsago' => 'mins atrás',
     'hoursago' => 'horas atrás',
     'daysago' => 'dias atrás',
     'buyxats' => 'Comprar xats',
     'back' => 'Voltar']



?>