<?php
$array = [
     'login' => 'Login',
     'cancel' => 'Anulat',
     'logout' => 'Logout',
     'done' => 'Terminat',
     'edit' => 'Editați',
     'searchgroup' => 'Căutați un Grup',
     'addsmilie' => 'Adăugați Emoticon',
     'backchats' => '❮ Chat-uri',
     'backmessages' => '❮ Mesaje',
     'backback' => '❮ Înapoi',
     'pchats' => 'Chat-uri Private',
     'search' => 'Căutare',
     'me' => 'Eu',
     'actions' => 'Activitate',
     'visitors' => 'Vizitatori',
     'groups' => 'Grupuri',
     'chats' => 'Chat-uri',
     'friends' => 'Prieteni',
     'profile' => 'Profil',
     'powers' => 'Puteri',
     'favorites' => 'Favoriți',
     'featured' => 'Recomandate',
     'popular' => 'Populare',
     'new' => 'Nou',
     'standard' => 'Standard',
     'rare' => 'Rar',
     'epic' => 'Epic',
     'settings' => 'Setări',
     'help' => 'Ajutor',
     'more' => 'Mai mult',
     'message' => 'Mesaj',
     'close' => 'Închide',
     'xats' => 'xats',
     'days' => 'zile',
     'store' => 'Magazin',
     'justnow' => 'doar acum',
     'minsago' => 'acum câteva minute',
     'hoursago' => 'acum câteva ore',
     'daysago' => 'acum câteva zile',
     'buyxats' => 'Cumpărați xats',
     'back' => 'Înapoi']


?>