(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes
lib.webFontTxtInst = {}; 
var loadedTypekitCount = 0;
var loadedGoogleCount = 0;
var gFontsUpdateCacheList = [];
var tFontsUpdateCacheList = [];

// library properties:
lib.properties = {
	width: 250,
	height: 200,
	fps: 12,
	color: "#FFFFFF",
	opacity: 1.00,
	webfonts: {},
	manifest: []
};



lib.ssMetadata = [];



lib.updateListCache = function (cacheList) {		
	for(var i = 0; i < cacheList.length; i++) {		
		if(cacheList[i].cacheCanvas)		
			cacheList[i].updateCache();		
	}		
};		

lib.addElementsToCache = function (textInst, cacheList) {		
	var cur = textInst;		
	while(cur != exportRoot) {		
		if(cacheList.indexOf(cur) != -1)		
			break;		
		cur = cur.parent;		
	}		
	if(cur != exportRoot) {	//we have found an element in the list		
		var cur2 = textInst;		
		var index = cacheList.indexOf(cur);		
		while(cur2 != cur) { //insert all it's children just before it		
			cacheList.splice(index, 0, cur2);		
			cur2 = cur2.parent;		
			index++;		
		}		
	}		
	else {	//append element and it's parents in the array		
		cur = textInst;		
		while(cur != exportRoot) {		
			cacheList.push(cur);		
			cur = cur.parent;		
		}		
	}		
};		

lib.gfontAvailable = function(family, totalGoogleCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], gFontsUpdateCacheList);		

	loadedGoogleCount++;		
	if(loadedGoogleCount == totalGoogleCount) {		
		lib.updateListCache(gFontsUpdateCacheList);		
	}		
};		

lib.tfontAvailable = function(family, totalTypekitCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], tFontsUpdateCacheList);		

	loadedTypekitCount++;		
	if(loadedTypekitCount == totalTypekitCount) {		
		lib.updateListCache(tFontsUpdateCacheList);		
	}		
};
// symbols:



(lib.smShad = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.rf(["rgba(0,0,0,0)","rgba(0,0,0,0)","rgba(0,0,0,0.251)"],[0,0.698,1],-1,-1.2,0,-1,-1.2,10.6).s().p("AhCBDQgPgQgHgSQgFgQgBgRQABghAVgaIAGgHQAIgHAIgFQATgNAZgCIAGAAQAdgBAYARIACACIALAJQAcAcAAAmQAAAngcAcQgcAbgmABQgmgBgcgbg");
	this.shape.setTransform(9.5,9.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,19,19.1);


(lib.star = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFCC00").s().p("AgeAXIhAggIBIgNIAMhIIAhBAIBHgJIgxAyIAfBBIhBgfIgyAyg");
	this.shape.setTransform(9.5,9.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,19,19);


(lib.Shine2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.rf(["#FFFFFF","rgba(255,255,255,0)"],[0,1],-0.2,0,0,-0.2,0,21.9).s().p("AgODyIAAjJQAAgFgFAAIgSgXQgDgDgBAAIjFAAIAAgTIDFAAQACAAACgDIAUgXQADgDAAgCIAAjJIAXAAIAADJIAAAAQAAADADACIAUAYIAEACIDLAAIAAATIjLAAQgFAAAAAFIgSAVQgEAAAAAFIAADJg");
	this.shape.setTransform(0.3,0);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Layer 1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.rf(["#FFFFFF","rgba(255,255,255,0)"],[0,1],0.1,-2.3,0,0.1,-2.3,16.9).s().p("AgREJIAAjwIgbgcIj2AAIAAglID2AAIAbgeIAAjCIAmAAIAADCIAaAeID0AAIAAAlIj0AAIABAAIgbAcIAADwg");
	this.shape_1.setTransform(-0.1,2.3);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-29.3,-24.2,58.4,53.2);


(lib.smBack = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FEDA18").s().p("AhCBDQgcgcAAgnQABghAVgaIAGgHQAIgHAIgFQATgNAZgCIAGAAQAdgBAYARQAHAFAGAGQAcAcAAAmQAAAngcAcQgcAbgmABQgmgBgcgbg");
	this.shape.setTransform(9.5,9.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,19,19.1);


(lib.Hook = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("AAAgcIAAA5");
	this.shape.setTransform(3.8,3.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#FFCC00").ss(2,1,1).p("AABgyQAAAGgBAEQAAAEgBADQgCAGgHAEQgCABgBABQgGADgEADQgQALADAWQADASAKAIQABACACABQALAGAMgFQAOgFAKgNQAKgOAAgQIgPAP");
	this.shape_1.setTransform(3.8,12.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#000000").ss(1,1,1).p("AAAgEQABAEgBAF");
	this.shape_2.setTransform(3.9,6.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-0.5,9.6,19.1);


(lib.Face = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AghALQAAgZAjAAQAOAAAKADQAIgBAAAHQAAAEgGAAQgNgDgNAAQgdAAgEATQgCAAAAgEg");
	this.shape.setTransform(9.5,13.8);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Layer 4
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#000000").ss(1,1,1).p("AAOgVQAFgJAHAAQAIAAAFAJQAFAKAAALQAAAMgFAKQgFAJgIAAQgHAAgFgJQgFgKAAgMQAAgLAFgKgAgdgeQACAAABAAQAHAAAFAJQAFAKAAALQAAAMgFAKQgFAJgHAAQgHAAgFgJQgFgKAAgMQAAgLAFgKIAAgBQAEgGAFgCg");
	this.shape_1.setTransform(9.6,6.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#E1D294").s().p("AAAABIAAgBIAAAAIAAABg");
	this.shape_2.setTransform(17.8,10.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AAQAsIgBgHQAAgQAMAAQANAAAAAKQAAACgFAJQgGAJgEAAQgHAAgCgHgAgkAsIgBgHQAAgQANAAQAMAAAAAKQAAACgFAJQgGAJgDAAQgHAAgDgHgAAsACQgDgFgEgBQgWgeAAgIQAAgBAAgBQAAgBAAAAQABgBAAAAQABAAAAAAQABAAAPAYIARAYQAAAEgDAAIgDgEgAgxAAIAZgaQAVgYABAAQACAAAAAEQAAAJgfAdQgFABgEAHIgFADQgEAAAAgDg");
	this.shape_3.setTransform(9.8,3.9);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAOAWQgEgKAAgMQAAgMAEgJQAGgJAHAAQAHAAAFAJQAFAJAAAMQAAAMgFAKQgFAJgHAAQgHAAgGgJgAARAPIABAIQACAGAIAAQADAAAGgJQAFgJAAgCQAAgJgNAAQgMAAAAAPgAgmAWQgFgKAAgMQAAgMAFgJIAAAAQAEgHAFgCIADAAQAIAAAEAJQAFAJABAMQgBAMgFAKQgEAJgIAAQgHAAgFgJgAgiAPIABAIQACAGAHAAQAEAAAGgJQAEgJAAgCQAAgJgMAAQgMAAAAAPg");
	this.shape_4.setTransform(9.6,6.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(4.2,-1.2,13.7,16.6);


(lib.cry2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00CCFF").s().p("AADACIgGABQgLAAAAgDQAAgEARAAQAMAAAAAEQAAAFgFAAIgHgDg");
	this.shape.setTransform(1.5,0.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#00CCFF").s().p("AAIAFIgFgCIgDAAIgDAAIgCgBQgHgBgBgBIgBAAQAAgEAOgBIAFABIADAAIAEACIAAAAQABABAAAAQABABAAAAQAAAAAAAAQAAAAAAABIAAAAQAAABAAAAQAAABAAAAQAAABAAAAQgBAAAAABIgBAAIgCABIgCgBg");
	this.shape_1.setTransform(1.5,0.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#00CCFF").s().p("AAIAGIgFgBIgDgBIgCgBIgDgCQgHAAAAgCIgBAAQAAgEANgBIAHABIADABIABACIACAAQAAABAAAAQAAABABAAQAAAAAAAAQAAAAAAABIAAABQAAAAAAABQAAAAAAABQgBAAAAAAQAAABAAAAIgBABIgCABIgCgBg");
	this.shape_2.setTransform(1.5,0.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#00CCFF").s().p("AAIAHIgFgBIgDgCQAAAAAAAAQAAAAgBAAQAAgBAAAAQgBAAAAgBIgCgCQgIAAAAgCIgBAAQAAgEAOgBIAHABIADACQABAAAAABQAAAAAAABQAAAAAAAAQAAAAAAAAQACACAAABIAAABQAAAAAAABQAAAAgBABQAAAAAAABQgBAAAAABIAAABIgCABIgCgBg");
	this.shape_3.setTransform(1.4,0.8);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#00CCFF").s().p("AAIAJIgFgCQAAAAgBAAQAAgBgBAAQAAAAAAgBQgBAAAAAAQAAAAAAAAQAAgBgBAAQAAAAAAgBQgBAAAAgBIgBgCQgJAAAAgDIAAAAQAAgEAOgBIAIABIADADQAAAAAAABQAAAAAAABQAAAAAAAAQAAABgBAAIAAAAQABABAAACIAAAAIgBAEIAAACIgCABIgCAAg");
	this.shape_4.setTransform(1.4,0.9);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#00CCFF").s().p("AAHAKIgFgCQAAAAgBAAQAAgBgBAAQAAAAAAgBQAAAAAAgBQgCAAAAgEIgBgBQgJAAgBgEIAAAAQAAgEAPgBQAGAAADACQABAAAAAAQABABAAAAQAAAAAAABQAAAAAAABQABAAAAABQAAABgBAAQAAABAAAAQgBAAAAAAIgCAAQACABAAACQAAABAAAAQAAABAAAAQAAABgBABQAAAAgBABIABACIgCABIgCAAg");
	this.shape_5.setTransform(1.4,1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#00CCFF").s().p("AABAKQgBgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQgEAAABgFIAAgCQgKAAAAgFQAAgEAQAAQAGAAADACQAAAAABAAQAAABAAAAQABABAAAAQAAABAAAAQABAEgEAAIgCgBQACACAAACIAAAAQAAABAAABQgBAAAAABQAAAAAAABQgBAAAAABIAAACIAAACIgCAAIgGgBg");
	this.shape_6.setTransform(1.5,1.2);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#00CCFF").s().p("AgBAHQgEgBACgFIAAgDQgLAAAAgFQAAgEARAAQAMAAAAAGQAAAFgFAAIgCgBQACABAAACQAAADgDADIABACQAAABAAAAQAAAAAAABQgBAAAAAAQgBAAAAAAQgHgBAAgEg");
	this.shape_7.setTransform(1.5,1.3);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#00CCFF").s().p("AAEAOQgEgBgBgEIAAgDQgBAAAAAAQAAAAAAAAQAAAAgBgBQAAAAAAgBIABgEIAAgCIAAgCIgCgBIgDAAIgCAAQgEgBAAgDIAAAAQAAgEANgBIAGABIAEABIABAAQACABABAEIAAADIAAADIAAAAIgCABIgBAAIABACIAAAFIgEAFIAAABIgCACIgCgBg");
	this.shape_8.setTransform(1.5,1.5);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#00CCFF").s().p("AACARQgEgCgBgFIAAgDIAAgDIABgEIABgDIgBgDIgCgBIgDgBIgDAAQgDgBgBgCIAAgBQAAgEAOAAIAIABIADACIABABIAAAFIABAEIAAADIAAAAIAAACIAAACIABACQABADgCADQgBACgEACIAAAAIgBABIgBAAIgEAAg");
	this.shape_9.setTransform(1.5,1.8);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#00CCFF").s().p("AAAATQgFgDAAgHIAAgDIABgEQABgBABgCIAAgEIAAgDIgCgCIgEgBIgCAAQgEgBgBgCIAAgBQAAgEAQAAQAFAAADABQABABAAAAQABAAAAABQAAAAAAAAQABABAAAAIAAACQgCAAAAAGIABAEIABADIAAAAIABADIACAEIABACQAAAEgCADQgCADgFABIgBAAQgEAAgCgBg");
	this.shape_10.setTransform(1.6,2.1);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#00CCFF").s().p("AgIAJIACgIQAEgBAAgHQgBgFgCgBIgEgBIgDAAQgEgBAAgDQAAgEARAAQAMAAAAAGIgBACQgFAAAAAGQAAADADAFIAAAAIAHAMQAAALgLAAQgOAAAAgOgAAFgCIAAABIAAgBg");
	this.shape_11.setTransform(1.8,2.4);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#00CCFF").s().p("AgMACIACgGQAEgEAAgGIAAgBIAJAAQAAADADAGIAAAAIAHAKQAAAMgLAAQgOAAAAgOgAABgJIAAABIAAgBg");
	this.shape_12.setTransform(2.1,4.1);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#00CCFF").s().p("AAAAHQgBgEgCgCIgDgBIgDABQgFgBAAgBQAAgFARAAQAMAAAAAGIgBAAQgEABAAAGg");
	this.shape_13.setTransform(1.5,0.7);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#00CCFF").s().p("AgJAaIACgJQADgDABgGIAAgBIAJAAQAAADADAFIAAABIAHAMQAAAMgKAAQgPAAAAgOgAAEANIAAABIAAgBgAgBgYQgBgEgCgCIgEgBIgDABQgEgBAAgDQAAgFARAAQAMAAAAAGIgBACQgFABAAAGg");
	this.shape_14.setTransform(1.7,4);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#00CCFF").s().p("AgJAmIACgIQADgEAAgGIAAgBIAKAAQAAADADAFIAAABIAHAMQAAAMgLAAQgOAAAAgOgAAEAZIAAAAIAAgBgAgBgkQgBgEgCgCIgDgBIgDABQgFgBAAgDQAAgFARAAQAMAAAAAGIgBACQgEABAAAGg");
	this.shape_15.setTransform(1.6,5.2);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#00CCFF").s().p("AgUAxQAAgGAZAAQAQAAAAAFQAAAGgbAAQgRABADgGgAABgnQAAgEgBgCIgDAAIgDAAQgFgBAAgDQAAgEARgBQAMAAAAAHIAAACQgFAAAAAGg");
	this.shape_16.setTransform(1.2,5.5);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#00CCFF").s().p("AgaAxQAAgGAhAAQAUAAAAAFQAAAGgjAAQgVAAADgFgAABgnQAAgEgBgBIgDgBIgDAAQgEgBAAgDQAAgEARAAQALAAAAAGIAAACQgFAAAAAGg");
	this.shape_17.setTransform(1.2,5.5);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#00CCFF").s().p("AgdAwQAAgGAlAAQAWAAAAAFQAAAHgnAAQgYAAAEgGgAAAgmQAAgEgBgCIgEgBIgDABQgEgBAAgDQAAgFARAAQALAAAAAGIAAACQgFABAAAGg");
	this.shape_18.setTransform(1.4,5.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape}]}).to({state:[{t:this.shape}]},14).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_4}]},1).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_7}]},1).to({state:[{t:this.shape_8}]},1).to({state:[{t:this.shape_9}]},1).to({state:[{t:this.shape_10}]},1).to({state:[{t:this.shape_11}]},1).to({state:[{t:this.shape_13},{t:this.shape_12}]},1).to({state:[{t:this.shape_14}]},1).to({state:[{t:this.shape_15}]},1).to({state:[{t:this.shape_16}]},1).to({state:[{t:this.shape_17}]},1).to({state:[{t:this.shape_18}]},1).wait(5));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,3.1,1.1);


(lib.Cry_ = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00CCFF").s().p("AADACIgGABQgLAAAAgDQAAgEARAAQAMAAAAAEQAAAFgFAAIgHgDg");
	this.shape.setTransform(1.5,0.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#00CCFF").s().p("AAIAFIgFgCIgCAAIgEAAIgCAAQgHgBgBgCIgBAAQAAgDANgBIAFAAIAEAAIAEACIABAAQAAABABAAQAAABAAAAQAAAAAAAAQAAAAAAABIAAAAIgBAEIgBAAIgBAAIgDAAg");
	this.shape_1.setTransform(1.5,0.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#00CCFF").s().p("AAIAFIgFgBIgDgBIgCAAIgDgBQgHgBgBgBIAAgBQAAgDANgBIAFABIAEAAIADACIABABQAAAAAAAAQABABAAAAQAAAAAAAAQAAAAAAAAIAAABIgBAEIgBAAIgCABIgCgBg");
	this.shape_2.setTransform(1.5,0.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#00CCFF").s().p("AAIAGIgFgCIgDgBIgCgBIgDgBQgHAAgBgBIAAgBQAAgDANgCIAGABIADABIADACIAAAAQABABAAAAQABABAAAAQAAAAAAAAQAAAAAAABIAAAAQAAABAAAAQAAABAAAAQAAABgBAAQAAABAAAAIgBABIgCABIgCgBg");
	this.shape_3.setTransform(1.5,0.7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#00CCFF").s().p("AAIAGIgFgBIgDgBQAAAAAAAAQAAAAgBAAQAAgBAAAAQgBAAAAAAIgDgCQgHAAAAgCIgBgBQAAgDANgBIAHABIADABIABACIABAAQAAABABAAQAAABAAAAQABAAAAAAQAAAAAAABIAAABQAAAAAAABQAAAAAAABQgBAAAAABQAAAAAAABIgBAAIgCABIgCgBg");
	this.shape_4.setTransform(1.5,0.8);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#00CCFF").s().p("AAIAHIgFgBIgDgCQAAAAAAAAQAAAAgBAAQAAgBAAAAQgBAAAAgBIgCgCQgIAAAAgCIgBAAQAAgEANgBIAIABIADACQABAAAAABQAAAAAAAAQAAABAAAAQAAAAAAAAQACACAAABIAAABIgCAEIAAABIgCABIgCgBg");
	this.shape_5.setTransform(1.4,0.8);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#00CCFF").s().p("AAIAIIgFgBIgDgCQAAAAAAAAQAAgBAAAAQgBAAAAgBQAAAAgBgBIgBgCQgIAAgBgCIgBgBQABgEAOAAIAIABIACACQAAAAABABQAAAAAAABQAAAAAAAAQgBABAAAAQACABgBACIAAAAIgBAEIAAABIgBABIgDAAg");
	this.shape_6.setTransform(1.4,0.9);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#00CCFF").s().p("AAIAJIgFgCQAAAAgBAAQAAgBgBAAQAAAAAAgBQgBAAAAAAQAAAAAAAAQAAgBgBAAQAAAAAAgBQgBAAAAgBIgBgCQgJAAAAgDIAAAAQAAgEAOgBIAIABIADADQAAABAAAAQAAABAAAAQAAAAAAABQAAAAgBAAIAAAAQABABAAACIAAAAQAAABAAAAQAAABAAAAQgBABAAAAQAAABgBAAIABACIgCABIgCAAg");
	this.shape_7.setTransform(1.4,0.9);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#00CCFF").s().p("AAHAJIgFgBQAAAAgBgBQAAAAgBAAQAAgBAAAAQAAgBAAAAQAAAAAAAAQgBAAAAgBQgBAAAAgBQAAgBAAgBIgBgBQgJAAgBgDIAAgBQAAgEAPgBQAFABAEABIACACQABABAAABQAAAAgBABQAAAAAAABQgBAAAAAAIgBAAQABABAAACQAAABAAAAQAAABAAAAQAAABgBAAQAAABgBABIABABIgBABIgDAAg");
	this.shape_8.setTransform(1.4,1);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#00CCFF").s().p("AAHAKIgFgCQgBAAAAAAQgBAAAAgBQAAAAAAgBQAAAAAAgBQgDAAABgEIgBgBQgJAAgBgEIAAgBQAAgEAQAAQAFAAADABQABABAAAAQAAAAABABQAAAAAAAAQABABAAAAQAAABAAABQAAABAAAAQgBAAAAABQgBAAAAAAIgCgBQACACAAACIAAAAQAAACgCADIAAACIgBABIgBAAIgBAAg");
	this.shape_9.setTransform(1.4,1.1);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#00CCFF").s().p("AABAJQAAAAgBgBQAAAAAAAAQAAgBAAAAQAAgBAAAAQgDgBAAgEIAAgCQgKAAAAgEQAAgFAQAAQAGAAADACQAAAAABABQAAAAAAAAQABABAAAAQAAABAAAAQAAABAAABQAAABgBAAQAAABgBAAQAAAAgBAAIgCgBQACACAAACQAAACgCADIABACIgBABIgCABIgGgCg");
	this.shape_10.setTransform(1.5,1.1);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#00CCFF").s().p("AAGALIgFgBQgBgBAAAAQAAAAAAgBQAAAAAAgBQAAAAgBgBQgDAAABgFIAAgCQgLAAAAgFQAAgEARAAQAGAAADACQABAAAAAAQAAABABAAQAAAAAAABQAAAAAAABQAAAEgDAAIgCAAQACABAAACIAAABQgBACgCACIABADIgBABIgBAAIgBAAg");
	this.shape_11.setTransform(1.5,1.2);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#00CCFF").s().p("AgBAHQgEgBACgFIAAgDQgLAAAAgFQAAgEARAAQAMAAAAAGQAAAFgFAAIgCgBQACABAAACQAAADgDADIABACQAAABAAAAQAAAAAAABQgBAAAAAAQgBAAAAAAQgHgBAAgEg");
	this.shape_12.setTransform(1.5,1.3);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#00CCFF").s().p("AAEAOQgEgBgBgEIAAgDQgBAAAAAAQAAAAAAAAQAAAAgBgBQAAAAAAgBIABgEIAAgCIAAgCIgCgBIgDAAIgCAAQgEgBAAgDIAAAAQAAgEANgBIAGABIAEABIABAAQACABABAEIAAADIAAADIAAAAIgCABIgBAAIABACIAAAFIgEAFIAAABIgCACIgCgBg");
	this.shape_13.setTransform(1.5,1.5);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#00CCFF").s().p("AACARQgEgCgBgFIAAgDIAAgDIABgEIABgDIgBgDIgCgBIgDgBIgDAAQgDgBgBgCIAAgBQAAgEAOAAIAIABIADACIABABIAAAFIABAEIAAADIAAAAIAAACIAAACIABACQABADgCADQgBACgEACIAAAAIgBABIgBAAIgEAAg");
	this.shape_14.setTransform(1.5,1.8);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#00CCFF").s().p("AAAATQgFgDAAgHIAAgDIABgEQABgBABgCIAAgEIAAgDIgCgCIgEgBIgCAAQgEgBgBgCIAAgBQAAgEAQAAQAFAAADABQABABAAAAQABAAAAABQAAAAAAAAQABABAAAAIAAACQgCAAAAAGIABAEIABADIAAAAIABADIACAEIABACQAAAEgCADQgCADgFABIgBAAQgEAAgCgBg");
	this.shape_15.setTransform(1.6,2.1);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#00CCFF").s().p("AgIAJIACgIQAEgBAAgHQgBgFgCgBIgEgBIgDAAQgEgBAAgDQAAgEARAAQAMAAAAAGIgBACQgFAAAAAGQAAADADAFIAAAAIAHAMQAAALgLAAQgOAAAAgOgAAFgCIAAABIAAgBg");
	this.shape_16.setTransform(1.8,2.4);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#00CCFF").s().p("AgMACIACgGQAEgEAAgGIAAgBIAJAAQAAADADAGIAAAAIAHAKQAAAMgLAAQgOAAAAgOgAABgJIAAABIAAgBg");
	this.shape_17.setTransform(2.1,4.1);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#00CCFF").s().p("AAAAHQgBgEgCgCIgDgBIgDABQgFgBAAgBQAAgFARAAQAMAAAAAGIgBAAQgEABAAAGg");
	this.shape_18.setTransform(1.5,0.7);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#00CCFF").s().p("AgJAaIACgJQADgDABgGIAAgBIAJAAQAAADADAFIAAABIAHAMQAAAMgKAAQgPAAAAgOgAAEANIAAABIAAgBgAgBgYQgBgEgCgCIgEgBIgDABQgEgBAAgDQAAgFARAAQAMAAAAAGIgBACQgFABAAAGg");
	this.shape_19.setTransform(1.7,4);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#00CCFF").s().p("AgJAmIACgIQADgEAAgGIAAgBIAKAAQAAADADAFIAAABIAHAMQAAAMgLAAQgOAAAAgOgAAEAZIAAAAIAAgBgAgBgkQgBgEgCgCIgDgBIgDABQgFgBAAgDQAAgFARAAQAMAAAAAGIgBACQgEABAAAGg");
	this.shape_20.setTransform(1.6,5.2);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#00CCFF").s().p("AgUAxQAAgGAZAAQAQAAAAAFQAAAGgbAAQgRABADgGgAABgnQAAgEgBgCIgDAAIgDAAQgFgBAAgDQAAgEARgBQAMAAAAAHIAAACQgFAAAAAGg");
	this.shape_21.setTransform(1.2,5.5);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#00CCFF").s().p("AgaAxQAAgGAhAAQAUAAAAAFQAAAGgjAAQgVAAADgFgAABgnQAAgEgBgBIgDgBIgDAAQgEgBAAgDQAAgEARAAQALAAAAAGIAAACQgFAAAAAGg");
	this.shape_22.setTransform(1.2,5.5);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#00CCFF").s().p("AgdAwQAAgGAlAAQAWAAAAAFQAAAHgnAAQgYAAAEgGgAAAgmQAAgEgBgCIgEgBIgDABQgEgBAAgDQAAgFARAAQALAAAAAGIAAACQgFABAAAGg");
	this.shape_23.setTransform(1.4,5.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape}]}).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_4}]},1).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_7}]},1).to({state:[{t:this.shape_8}]},1).to({state:[{t:this.shape_9}]},1).to({state:[{t:this.shape_10}]},1).to({state:[{t:this.shape_11}]},1).to({state:[{t:this.shape_12}]},1).to({state:[{t:this.shape_13}]},1).to({state:[{t:this.shape_14}]},1).to({state:[{t:this.shape_15}]},1).to({state:[{t:this.shape_16}]},1).to({state:[{t:this.shape_18},{t:this.shape_17}]},1).to({state:[{t:this.shape_19}]},1).to({state:[{t:this.shape_20}]},1).to({state:[{t:this.shape_21}]},1).to({state:[{t:this.shape_22}]},1).to({state:[{t:this.shape_23}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,3.1,1.1);


(lib.Cry = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAqAiIgHgEIgKgIIgCgBIgMgHIgGgCIAGABIAMAGIAGADIALAIIAHAEgAAbAKIAAgBIgEgDIgMgIIgSgNQgTgMgKAEIgBAIQAAAHAdAKQgGAAgDACQgUgEgEgDQgFgEAAgPQAAgLAPAAQAMAAAMAFQAIAEAKAJIAMAMIADADIAIAKIAFAGIgMgGg");
	this.shape.setTransform(-23.6,-70.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AjgBfQAAgHAZgTQAYgRAPgEIACAEQgrAXgNAYQAAAAAAAAQABABAAAAQAAAAABABQABAAABAAQAJgBAoggIgWAaQgPARgNAAQgPAAACgQgAAAAgQAAgJAOgJQAIgEAMgFQATgFAOgDIAHgBIAMgBIAwACQALABAEACQgTAEgrARIgQAHIgEABQgvATgGAAQgOAAAAgQgABKAFIgHADIgQAFIgTAIQgQAHgGAEIAAAEQAEAAACACQAQAAAigRIABAAIAHgEIAagOIAEgCIgIAAQgIAAgOAEgAh+gpQAAgIAYgJQAhgNAyAAIAVACQAFAAABABQgeAIhXAlQgRAAAAgSgAhygoIAAAEQAAAEAGAAQAFAAAUgMQATgLADgDQgvALgGAHgADFg/IgFgCQgMgDgQgBIgIAAIgEgBQgNgBgHgEQgGgDgDgEQgDgDgBgFIgBgHIABgFQABgDACgCQADgDAGAAIABAAIABAAQAJAAAKACIAMAEIAEACIAAAAIAMAHIAIAFIAEAEIAFAEQAOAOAOAUIAAABQgKgLgSgFgAB/hkQgCAGAAAEQAAAFACABIACACIADABQAGACAOABIAMABIASAAIAAAAIAGAAIgHgFIgLgIIgGgDIgMgFIgHgCIgGgBg");
	this.shape_1.setTransform(-37.7,-58.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("ABmB2QAFgHAAgNQAAgIgFgSQAAgLAFgKQAFgKAAgHQAAgJgQgPQgQgMAAgKQAAgMACgHQgBgEgRgXQgCgEghgNIgLgLIABAAIArgFIAFAAQAVAAAUAFIAJABIAAAAIgEAAIAAAFQAFAJABAEQgPARAAAIQAAAMAOARIANAOQgHAQAAARQAIAugBAMIgNAlIABAEIgGACQgLADgKACQAEgPAGgHgAhSAjIgEgIIgBACIgPgcIgBgBQgCAAgEgIIgBgCIAAAAIAAgBQgJgTAAgFQAAgEAHgJQAAgFgJgJQgKgIAAgIQABgGAHgKIABAAIAEAAIAAAAIAXgEQgFAEAAAGQAAAJAGAHIADAFIgFAFIgBAAIgLANQgBAHAJAKIAIAJIAAAAQABAAAAABQAAAAABABQAAAAAAABQABAAAAAAIAAAAIACABQgJAOAAAFQAAAGAJALQAHAKABAEQAAACgDADgABFhjQgGgMgRgEQgZgFgGAXIgHACIAAAAIgCAAIgFgBIAAgBIgCgGQABgCABgDQACgBAMgOQAHgJAaAAQAQAAAUAFIABACQAIAKAIANIAAgCIAHANQgRgHgWgBgAh8hmIgBgBQgCgCAAgEQAAgGADgDIgBgBIABAAQAHgNAXgFIAQgCIAGAbIACgBIAAgCIABgDIgBAOIgEAAIABgEQAAgCgDgCIgDACQgEgIgNgDQgQgDgEATIAAABIgCABIAAgBIAAABQAAAAgBAAQAAABAAAAQgBAAAAAAQgBAAAAAAIgDAAgAAahmQgBAAgBAAQAAgBAAAAQAAAAgBgBQAAAAAAgBQACgGAFABIACAEQgBAEgEAAIgBAAgAhthtQAAAAAAgBQgBAAAAAAQAAgBAAAAQAAgBAAAAQABgFAEABQAAAAABAAQAAAAAAABQABAAAAABQAAAAgBABQAAAEgDAAIgCAAg");
	this.shape_2.setTransform(2.9,-48.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFDBB7").s().p("AA4CsIgBgEQAagDAWgHQANgOAdgXQADgFALgYIAFgOIAABegAAZCpIAAgBIAFAAIABACgAgICVQgKgCgHgDQgTgDgPgTQgFgMgFgHIgGgGQgUgRgOgbIADgEIAAACIgBABQABACAGAEIAAADQAJAOAaAAIAkgEQAJAAAVAKQAXAKAPAAQAXAAADgQIAHAhQAAAIgKAIQgJAHAAAUIgDABIgSAAQgTAAgVgDgAANBxIABACIACgBQAAgBAAAAQAAAAAAAAQAAAAgBgBQAAAAAAAAIgCABgAgzBbQAAAPAkABQAPAAAAgGQAAgFAFgBQgCgFgIAAIgmgGQgIAAAAAHgABvBoQAAgKgIgxQAAgEAGgSQAAgNgNgPQgOgQAAgIQAAgLAOgPQAAgHgIgMIAAAAQAGABADADIAIAEQgIgHgKgEIgBgBIAAAAIgHgCIgHgNIABgDQABgGgHgKIAUAHQgEgMgbgJIgCgCQgIgFgNgFQgXgKgLAAQgCABgBAEQAIADAXAGIAFAAIALAFIgHgDIgEgBIgEgBIAGACIgPgCQgXAAgPALIgCACIgJALQgDANgDAFQAEABACgBIAEAGQgBAAgBAAQAAABgBAAQAAAAAAABQgBABAAABIADACIAAAAIADABQABANAhANQAjAOAAAYQAAATAOATQAOATAAAEQgGANgBAJIgDgIQAAgng/AAQglAJgSgBQgUgFgGAAQgQAAgGAJQgCgEgEgEQgIgJAAgHQAAgGAGgHIACgCQAMAFAJABQAYACAZgbIgCABQgbAIgUgDQgZgEAAgLIAAgDIAEgGIADgCIAAgEIAIgLIAGgWIAGAAIAAgEQgBgGgCAAIgBgBIAAgFIgCAAIgEAFIgDAAIAAgOQABgMgBgJIAAAAQgFgKgIgBIAAAAQgTABgKADQAIgKAegFQgBgDgHABQghAAAAALQAAADADADQgGABgDACQgCgCAAgDQAAgUAJgFIAEgDQADgEAMAAIAIABIgCgCIADgBIBCAAQABAEAGABIAHgBIADADIAOgFIACAAQAKgCAKABIAKADIAAAAIAMADQAHABAEgCQAPADANAFIADAAIAHAEQAEACACACIABAAQAJAFAHAHIABABIAAAWIAIAAIAABnIA5AAIAABIIgGANQgKASgNAMQgJAPgOALIgLAHQgBACgDACQAIggAGgFgAiUiLIABAAIgBAAgAiggpQgCgEgBgGIAAgEQAMANAAADIgEAJIgFgLgAh6hNQAAgDAKgGIADgBQAAAAABAAQABAAAAABQAAAAAAAAQAAABAAAAQAEACAAADQAAADgDADIAAAAIgEAFIgDAGIgCACQgHgIAAgIgAgKhMIACAAIgBABIgBgBgAiahcIABABIgBAAIAAgBgAiThcIAAgBIAAABIAAAAIAAAAg");
	this.shape_3.setTransform(5.8,-49.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AENC2IgBgDIgBgBIgFgBIgBAAIABABIgwgGQgqgJgqg7QgCAEgDACIgCABIACgPQgMgRgLgVQgdg2gQgzIAQhWQgJgIgCgTIAAgCIA6AAIgDABIACADIgIgBQgMAAgEADIgDADQgJAFAAAUQAAAEACACQADgCAGgCQgDgCAAgDQAAgMAhAAQAHAAABADQgeAFgIAJQAKgDATAAIAAAAQAHAAAGAKIgBAAQACAJgBAMIAAADIgBACIgCABIgGgaIgPABQgXAFgHANIgBAAIAAABQgCAEAAAFQAAAFACABIgBABIACAAIADAAQAAAAABAAQAAAAAAAAQABAAAAAAQAAgBAAAAIABAAIACAAIgBgCQAEgTARADQAMADAFAIIADgCQADACAAADIgBADIADAAIAEAAIAEgFIACABIgBAFIACAAQACAAABAHIAAADIgGAAIgGAWIgIAMIAAADIgDACIgEAHIgBABIABABQAAAMAZADQAUAEAbgJIACgBQgZAcgYgEQgJgCgNgEIgBACQgGAJAAAGQAAAGAIAJQAEAEACAFQAGgJAQgBQAGABAUAFQASAAAmgIQBAAAAAAnIADAHQABgIAGgNQAAgEgOgUQgOgTAAgSQAAgZgjgNQgjgNgBgNIgDgCIAAABIgDgDQAAgBABAAQAAgBAAAAQABgBAAAAQABAAABAAIAAAAIAEACIADgBIAAAAIAGgCQAHgXAZAGQAQADAHAMQAWACARAGIAHADIAAAAIABAAQAKAFAIAGIgJgDQgCgDgGgCIgKgBQgUgFgUAAIgFAAIgrAFIgCAAIABABIALAKQAgANADAEQAQAXABAEQgBAIAAAJQAAAKAQAPQAQAOAAAKQAAAHgFAJQgGAKAAALQAGATAAAIQAAANgFAGQgGAIgEAOQAJgBAMgDIAGgCIgCgFIAOglQAAgMgHguQAAgQAHgQIgNgRQgOgPAAgLQAAgJAOgRQAAgEgFgIIAAgGIAEAAQAIAMAAAHQgOAQAAAKQAAAJAOAOQANARAAAMQgGASAAAFQAIAwAAAKQgGAGgIAfQADgCABgBIALgHQAOgLAJgQQANgMAKgRIAGgOIAAARIgGAPQgKAXgDAFQgdAYgOANQgVAIgaACIABAFgAB9A+QAPAbAUARIAGAHQAFAGAFAMQAPAUATADQAHADAKABQAhAFAbgCIADAAQAAgUAJgIQAKgIAAgHIgHghQgDAQgXAAQgPAAgXgKQgXgLgJAAIgkAFQgaAAgJgPIgBgDQgFgDgBgDIABgBIAAgCIgEAEgAB7A4IAAAAQADgCAAgDQAAgEgIgKQgIgKAAgJQAAgEAJgOIgCAAIAAAAQAAAAgBAAQAAAAgBgBQAAAAAAgBQgBAAAAgBIAAAAIgJgIQgIgLABgHIALgMIAAAAIAGgGIgDgEQgGgIAAgJQAAgFAFgFIgXAEIAAAAIgEAAIgBAAQgIAKAAAGQAAAIAKAJQAJAIAAAFQgHAJAAAFQAAAFAJAQIAAABIgBAAIACADQAEAHACABIABACIAPAdIABgCIADAIgABIgpQABAGACADIAFALIAEgJQAAgDgMgNIAAAFgAB7hMQgKAGAAADQAAAIAHAIIACgDIADgFIAEgFIAAAAQADgEAAgDQAAgDgEgBQAAgBAAAAQAAgBAAAAQAAAAgBAAQgBgBgBAAIgCACgADnhUQAAAAAAABQAAAAABAAQAAABAAAAQABAAAAAAQAGABABgEIgCgFIgCAAQgEAAgBAGgABghcQAAABAAAAQAAABAAAAQAAAAAAABQABAAAAAAQAEABABgFQAAgBAAAAQAAgBAAAAQAAAAAAAAQgBgBAAAAIgBAAQgDAAgBAEgAD6B6QABAAAAAAQABAAAAAAQABAAAAAAQAAABAAAAIgCABgAmFBpQAAgMAJgRQAKgVANgFIADACQAJgRANgJQgFALAAAGQAAAHgPAiQgRAlgJAAQgLAAAAgQgAluBJQgNAQAAAPQAAABAAAAQAAAAAAABQAAAAABABQAAAAAAAAQAFgHAOgkIgHAJgAC4BlQAAgHAIAAIAmAGQAKAAACAEQgGACAAAFQAAAFgQAAQgkAAAAgPgAmQgSIAAgMQAQgYAHgIQATgTAdgBIACAEQgvAZgSAYIAAACQADgBAggdQAWgSAkgHQhWBBgHAAgAjVgvQAAggBVgEIgxAQQgTAHgFANIAEACQAHAAAhgRQAhgQAPgBQhNArgMAAQgLAAgEgLgAgwgyIgBgHQAAgRAUAAIAIACQgRAIgDAFIAAACIAEACQAGAAAUgIQgFAPgVAAIgLgCgAElhoIgBgCQgUgGgQAAQgaAAgHAKQgMANgCACQgCADgCABQgCABgEAAQADgFADgOIAJgKIACgCQAPgLAZAAIAPACIABAAIgDgBIAEABIAHACIgLgEIgFgBQgXgFgKgEQABgEACAAQANAAAXAJQANAGAIAFIACABQAbAKAEAMIgUgHQAHAKgBAGIgBADIgBABQgHgNgIgJgAFPiAQgHgGgJgGIgBABQgCgDgEgCIgHgDIgDgBQgNgEgPgEQgEACgHgBIgMgCIAAAAIgKgEQgMAAgKACIgCAAIgOAEIgDgDIgHABQgGgBgBgEIBrAAIACABIAXANQAKAFAIAGIAAAKIgBgBgABXiBIAAAAIAAAAgAjfiVQAAgMAWgKQAVgKAVAAIArAEIAFADQhfAkgGAAQgLAAAAgLgAjAijQgRAHgEAGIgBABQgBAAAAAAQAAABAAAAQAAAAABAAQABAAACAAQAugVASgEIgIAAQgRAAgUAKgAFEiiIAMAAIAAAMQgFgGgHgGg");
	this.shape_4.setTransform(-17.9,-50.4);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#5E2F00").s().p("AgcATIgGgCIAEABIADABIgBAAgAARgFIgVgMIgCgBIAdAAQAHAFAFAGIAAAMQgIgFgKgFg");
	this.shape_5.setTransform(12.2,-64.8);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#333333").s().p("AgDAKIADgCIgBACgAACgJIABAAIAAAAg");
	this.shape_6.setTransform(6,-26.2);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("ACyC9QAEgEAAgIIgCgMQAAgFAIgGQAJgHAAgHQAAgFgJgUQAAgFAFgOQAAgLgNgMQgOgMgDghIgRggQgEgGgQgLQgEgCgJACQgIABgGgGIgDgDIA1gGIAFAAQAYAAAWAHIAAABIADAJQAAACgJAGQgJAHAAAIQAAAHAJASQAKASAAAFQgFAMAAAGQAAAHANARQAMASAAAFQAAAEgHAHQgIAHAAAIIADARQAAAFgHANIgIAMQgLAEgMABIAEgHgAgPA5IgEgJIACgJQAAgKgLgNQAAgDAGgMQAAgBgIgJQgHgJAAgHIAGgNIAXgEIAHAAQgIAFAAANIAFALIAAACIgQAQQgCAHAJALQAEAFAFAEIgBAIQAJAZAAAKIgEALgACdgrQgHgMgRgDQgZgFgGAWIgIADIgGgCIAAAAIgDgHQACgBABgDQACgBAMgOQAIgKAaAAQAPAAAUAGIACACQAHAJAIAOIAAgCIAHAMQgRgGgVgCgAglguIAAgBQgDgBAAgFQAAgFADgEIAAgBIAAAAQAHgNAXgEIAOgCIAGAaIACgBIAAgCIABgDIgBAOIgHAAQgCgNgPgDQgQgEgEATIAAACIgBAAIgBgBIAAABQAAABgBAAQAAAAAAAAQAAAAgBABQAAAAgBAAIgDgBgABxguQgBAAAAAAQgBAAAAgBQAAAAAAAAQAAgBAAAAQABgHAFABIACAFQgBAEgDAAIgCgBgAgVg1QgBAAAAAAQAAAAAAgBQgBAAAAgBQAAAAABgBQAAgEAEAAQABAAAAABQAAAAABAAQAAABAAAAQAAABAAAAQgBAEgDAAIgBAAgAiGh9QgSgRgTgGQATAEAXATgAiViXQgvgogSAGIgBAIQAAAHAdAMQgFAAgEADQgUgHgEgDQgEgDAAgQQAAgLAPAAQAeAAAcAiIAOARIgNgHg");
	this.shape_7.setTransform(-5.9,-54.1);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFDBB7").s().p("AAxDFIAIgSIAAgBQADgIgBgHIAAgDIAAgRIABgDIAAgLQgBgHgCgDQAagCAWgIQAOgNAcgXQAEgGAKgXIABgCIAABtIgXAPQg5AlgaAAQgEAAgDgGgAAcB5IAAgBIAFAAIABACgAgGBkQgJgBgHgDQgUgDgOgUQgGgLgEgHIgGgGQgVgTgQgeQAAgDAFgOQAAgJgKgaIAAgFQALAGARADQAZAEAZgdIgDABQgaAIgVgDQgZgEABgLIAAgDQABgDANgUIAGgXIAGAAIABgDQgBgGgCgBIgCAAIAAgFIgCAAIgEAEIgDAAIABgNQABgMgCgKIABAAQgGgKgHAAIgBAAQgSAAgKADQAIgJAdgFQgBgDgGAAQghAAAAAMQAAADACADQgFABgDACQgCgCAAgEQAAgKACgGIDgAAIAAABQAFABACADIAAgBQAJAGAHAHIAGAEIAEAEQADAEAEACIgBgBIABAAIAFAAIAACgIAoAAIAAAjIgCADQgJARgNANQgJAPgPALQgJAHgMAFIABgIIAJgUIgCgQQAAgFAIgHQAIgIAAgGQAAgGgNgSQgNgQAAgEQAAgEAEgOQAAgOgTgjQAAgJAKgFQAJgFAAgGQAAgEgCgEIAPAFQgJgGgJgFIgBAAIgBAAIgHgDIgHgMIACgDQABgGgHgKIATAHQgDgMgbgJIgDgCQgIgFgMgFQgYgKgMAAQAAAAgCAEQAKAEAaAGIAMAEIgHgCIgEgBIgFgBIAHACIgPgCQgYAAgOALIgCACIgKAKQgCAOgDAFQADABADgCIADAHQgBAAAAAAQgBAAAAABQAAAAgBABQAAAAAAABIACADIABAAIAIAFIgJACQADAIATACQAYACAGAQQARAVAAAQQAAAVAPAQQAPARAAADQgGAQAAAEQAJARAAAIQAAAEgJAGQgIAGAAAHIACANQgIAJAAACQAAAAAAABQAAAAABABQAAAAAAAAQAAABABAAQgDAEgBADIgRABQgUAAgVgEgAAPBAIACADIACgCQAAAAAAAAQgBAAAAgBQAAAAAAAAQAAAAgBAAIgCAAgAgxArQAAAPAlAAQAOAAAAgFQAAgFAFgCQgCgEgIAAIgmgGQgIAAAAAHgAAKAXQAUAKANAAQAXAAAAgUQAAgmhBAAQgkAIgRAAQgUgFgGAAQgbAAAAAYQAAAEAMAHQAQAIARAAQAYAAAOgIQANAAATAKgABxinIAAAAQgDgIgFgFQAFAGADAHgAiRi7IAAAAIAAAAgAidhaQgDgDAAgGQgBgHABgHIAEgPIgCgBIADAAIABgEIABABQgEAEAAAIQAAAIAHAKIAHALQgFAKAAAEQAAAHAGAHQAFAHAAACIgBACQgPgZgEgNgAh1h2QAAgKANgFQADABAAADQAAAEgDADIABAAIgKAMIgEgIgAiXiNIABABIgCABIABgCgAiRiNIAAgBIABABIgBAAIAAAAgAB4jKIACAAIAAADIgCgDg");
	this.shape_8.setTransform(5.5,-44.7);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#5E2F00").s().p("AgiAKIgGgCIAFABIACABIgBAAgAAhAAIgBAAIgBAAIgBgCIgLgHIAQAAQAEAGACAFIgIgCg");
	this.shape_9.setTransform(12.7,-63.9);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#000000").s().p("AE9DrQgUgEgKABIAAAAQgKgOAFgTIAAgBIABgGIACgGQAGgEAAgSQABgMgFgCIgGgMIgBgBIgFgBIAAAAIAAABIgvgGQg6gNg3hlQgcg0gRg1IAQhWQgEgEgDgHIAUAAQgCAGAAAKQAAAEACACQADgCAFgCQgCgCAAgDQAAgMAhAAQAGAAABADQgeAFgIAJQALgDASAAIAAAAQAIAAAGAKIgBAAQACAJgBAMIgBADIAAACIgCABIgGgaIgQABQgXAFgHANIgBAAIABABQgDAEAAAFQAAAFACABIAAABIABAAIADAAQABAAAAAAQAAAAABAAQAAAAAAAAQABgBAAAAIABAAIABAAIAAgCQAEgTAQADQARAEACANIAHAAIADAAIAEgFIACABIAAAFIACAAQACAAABAHIgBADIgGAAIgGAWQgOAVgBADIgBABIABABQAAAMAZADQAVAEAagJIADgBQgZAegZgEQgRgDgLgHIAAAGQAKAaAAAJQgFAMAAAFQAPAeAWASIAGAHQAEAGAGAMQAOAUATADQAIADAJABQAiAFAagCQABgDACgEQAAAAAAgBQAAAAgBAAQAAgBAAAAQAAgBAAgBQAAgBAIgKIgCgMQAAgHAIgGQAJgGAAgFQAAgHgJgRQAAgFAGgQQAAgEgPgPQgPgQAAgWQAAgPgRgWQgGgPgagDQgTgCgEgIIAKgBIADACQAGAHAIgBQAJgCAEACQAQALAEAGIARAiQADAhAOAMQANAKAAAKQgFAPAAAEQAJAVAAAEQAAAIgJAHQgIAGAAAFIACALQAAAJgEADIgEAIQAMgBALgEIAIgMQAHgOAAgEIgDgSQAAgHAIgHQAHgHAAgEQAAgFgMgSQgNgSAAgEQAAgHAFgLQAAgFgKgSQgJgTAAgGQAAgKAJgHQAJgHAAgBIgDgJIAAgCQgWgGgYAAIgFAAIg1AGIgIgGIgBABIgCgDQAAgBAAAAQAAgBABAAQAAgBABAAQAAAAABAAIAAAAIAGACIAIgDQAGgXAZAGQARADAGAMQAWACARAGIAHADIABAAIAAAAQAKAFAIAGIgOgFQACAEAAADQAAAHgJAFQgKAFAAAJQATAiAAAOQgEAPAAADQAAAEANARQANASAAAGQAAAGgIAHQgIAIAAAEIACARIgJATIgBAIQAMgEAJgHQAPgLAIgQQAOgMAJgRIACgDIAAATIgBACQgKAXgEAFQgcAYgOANQgWAIgaACQACADAAAHIAAAKIAAAEIAAAQIAAAEQABAHgDAHIAAACIgIASQADAGAEgBQAaABA5glIAXgPIAAAcQgoAeghAKQgHgBgNAAgABlhzIgGAMQAAAIAHAJQAIAJAAADQgGAMAAACQALAOAAAKIgCAJIAEAJIAPAbIAGgJQAAgKgLgZIABgIQgFgEgEgFQgJgLABgHIARgSIAAgCIgFgLQAAgNAIgFIgHAAIgXAEgABahxIgCABIACABIgEAPQgBAHAAAHQABAGACADQAFANAPAZIABgCQAAgCgFgHQgGgHAAgHQAAgEAFgKIgHgMQgHgJAAgIQAAgIAEgEIgCgBIgBADgACBhlIADAIIAKgMIAAAAQADgEAAgDQAAgDgDgBQgNAEAAALgAD1h9QAAAAAAABQAAAAAAAAQAAABABAAQAAAAABAAQAFABABgEIgCgFIgBAAQgEAAgBAGgABtiFQAAABAAAAQAAABAAAAQABAAAAABQAAAAABAAQAEABABgFQAAgBAAAAQAAgBAAAAQgBAAAAAAQAAgBgBAAIgBAAQgDAAgBAEgAD4DTIAAABIAAAAgAEHBRQABAAABAAQAAAAABAAQAAAAAAAAQABABAAAAIgDABgADFA8QAAgHAIAAIAmAGQAKAAACAEQgFACAAAFQAAAFgQAAQglAAAAgPgAECAoQgVgKgNAAQgOAIgYAAQgRAAgQgJQgMgHAAgEQAAgYAbAAQAGABAUAFQARAAAmgIQBBgBAAAmQAAAVgXAAQgNAAgUgKgAmYgcQAAgIAYgSQAZgSAOgDIADAEQgrAWgNAYQAAABAAAAQAAAAABABQAAAAABAAQAAAAABAAQAJgBAogfIgWAaQgPAQgNAAQgPAAADgPgAi4hbQAAgNAkgOQAggNATAAIAxADQALABAEADQgXAFg3AXQgzAUgGAAQgQAAAAgPgAiEhuQgfAMgJAHIAAADQAEABABABQAYAAA9gjIAEgCIgJAAQgMAAghANgAEziRIgCgCQgUgGgPAAQgaAAgIAKQgMANgCACQgBADgDABQgCABgEAAQAEgFACgOIAKgKIACgCQAOgLAaAAIAOACIABAAIgDgBIAFABIAHACIgMgEQgagGgMgEQACgEABAAQANAAAYAJQAMAGAIAFIACABQAcAKADAMIgUgHQAHAKgBAGIgBADIAAABQgIgNgHgJgAk3inQAAgHAZgKQAggNAzAAIAXACQAFAAAAABQggAIhWAlQgSAAAAgSgAkrimIAAAFQAAADAHAAQAFAAAUgMQASgKADgDQguAKgHAHgAFoiWQgDgHgFgGQAGAFADAIgAFmigIgEgEIgGgFQgHgGgJgGIAAABQgDgDgEgCIgBAAIAPAAIALAHIABACIABABIABgBIAIAFQgCgIgFgGIAOAAIACADIAAAbIgFAAIgBAAIAAAAQgDgBgDgEgABliqIAAAAIAAAAgAgajDQgmgCAAgaQAAgGADgEQAEgCAFAAIACAAQASAAARAHIAMAHQAWAQAWAgIAAABQgUgVgvgCgAg3jhQgFAMAEAEQAHAGAxAAIAAAAIADAAQgVgSgTgEIgGgBg");
	this.shape_10.setTransform(-19.3,-46.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2}]},1).to({state:[{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6}]},1).wait(1));

	// Layer 2
	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#333333").s().p("AgDAKIADgCIgBACgAACgJIABAAIAAAAg");
	this.shape_11.setTransform(6,-26.2);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("ABWCEQAEgDAAgJIgCgMQAAgFAIgGQAJgHAAgHQAAgEgJgVQAAgFAGgOQAAgLgOgMQgOgMgDgfIgRgiQgEgGgQgLQgDgBgKABQgHABgHgGIgDgCIA1gGIAGAAQAXAAAXAGIAAACIACAJQAAABgJAHQgJAGAAALQAAAGAJASQAKATAAAFQgFAJABAHQAAAGAMASQAMARAAAFQABAEgIAHQgHAIAAAHIACASQAAAEgHAOIgIAMQgKADgNACIAEgIgAhqABIgFgIIACgJQABgKgMgNQAAgDAGgMQAAgCgIgJQgHgKAAgHIAHgMIAWgFIAHABQgHAEgBANIAFALIAAACIgQATQgBAHAIAKQAEAFAGAFIgBAHQAKAXAAAKIgFALgABBhkQgHgLgRgEQgZgFgGAWIgIAEIgDgDIgBAAIgDgGQACgCABgDQACgBALgOQAHgKAaAAQAPAAAVAGIABACQAIAKAHANIAAgCIAHANQgRgHgVgCgAiAhmIgBgBQgDgCABgEQgBgGADgDIAAgBIAAAAQAIgNAXgFIAPgCIAGAbIACgCIABgCIAAgCIgBAOIgHgBQgCgMgRgEQgQgDgEASIAAACIgBABIAAgBIgBABQAAAAAAAAQgBAAAAABQAAAAgBAAQAAAAAAAAIgDAAgAAVhmQgBAAAAgBQAAAAgBAAQAAAAAAgBQAAAAAAgBQABgGAFABIADAEQgBAEgEAAIgCAAgAhxhtQAAgBgBAAQAAAAAAAAQAAgBAAAAQAAgBAAAAQABgFADABQABAAAAAAQABAAAAABQAAAAAAAAQAAABAAAAQgBAFgDAAIgBAAg");
	this.shape_12.setTransform(3.3,-48.4);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFDBB7").s().p("AgED7IAGgSIABgBQACgIAAgHIgBgDIABgRIAAgDIAAgLQAAgHgCgDQAagCAWgIQAOgNAcgXQADgGALgXQAJgXABgEQABgFgCgIQgFALgFALQgKARgNANQgJAPgOALQgKAHgLAFIABgIIAJgUIgDgQQAAgFAIgHQAIgIAAgGQAAgGgNgSQgNgSAAgEQAAgEAFgOQAAgOgUghQAAgJAKgFQAKgFAAgGQAAgEgCgEIAOAGQgIgHgKgEIgBgBIAAAAIgHgDIgHgMIABgDQABgGgHgKIAUAHQgEgMgbgJIgCgCQgGgFgNgFQgXgKgNAAQgCAAgBAEQALAEAbAGIALAFIgHgDIgEgBIgEgBIAGACIgPgCQgZAAgPALIgCACIgJAKQgDAOgDAFQAEABACgCIAEAHQgBAAgBAAQAAAAgBABQAAAAAAABQgBAAAAABIADADIAAAAIAJAGIgKABQADAIAUACQAaACAFAQQASAVAAAQQAAATANAQQAOARAAAFQgGAQAAAEQAJARAAAIQAAAEgIAGQgJAGAAAHIACANQgHAJAAACQAAAAAAABQAAAAAAABQAAAAAAABQABAAAAAAQgBAEAAADQgbADghgFQgKgCgHgDQgTgDgPgTQgFgMgFgHIgGgGQgVgSgQgfQAAgFAGgOQAAgJgLgaIAAgDQAMAEARADQAYAEAZgbIgCABQgbAIgUgDQgZgEAAgLIAAgDQABgDAOgUIAGgXIAGAAIAAgDQgBgGgCgBIgBAAIAAgFIgCAAIgEAFIgDAAIAAgOQABgMgBgJIAAAAQgFgLgIAAIAAAAQgTAAgKADQAIgJAegFQgBgDgHAAQghAAAAAMQAAADADADQgGABgDACQgCgCAAgEQAAgTAJgFIAEgDQADgEAMAAIAIABIgCgDQALgBACgJQADgVgggFIgMgBIAHgUQANgjAOABIABAAQACABADAEIADADIAAAAIAEAEQALAMATATQANAMAMAJQgJAHgBAIQgCAKAGABIAAAAQABAEAHACIAHgBIADADIAOgFIACAAQAKgCAMABIAKADIAAAAIAMADQAHABAEgCQANADANAFIADAAIAHAEQAEABACADIABAAQAJAFAHAHIAFAEIAFAEQACAEAEACIAAgBIAAAAQAFABADgBIACgIQADgXgngZIAAgBIABAAQAgAUAIAVQACAHADAdIADARIgBAPIAAACIgDAMQgEASAGASQAygDACgIIAFgTIACABIAAgHIAKgYIADgBQAJgEAQAAIAGABQATACAHARQAGANgCANQgDAQgiAUQgHAEgbAJIgbAMIAAADIAFAEIgBABQAIgBAMACIAGABIAPgCIABABQgDAHABAIIAAACQAAAHADAEIAAABIAAABIgBAEIABABIABAOQAAASARAcIACAEQgKANgbAbQgTASgsAcQg5AlgaAAQgDAAgDgGgAglB3IABACIACgCQAAAAAAAAQAAAAAAgBQAAAAgBAAQAAAAAAAAIgCABgAhnBhQAAAPAkAAQAQAAAAgFQAAgFAGgCQgCgEgKAAIgmgGQgIAAAAAHgAgrBNQAVAKANAAQAUAAAAgUQAAgog+AAQgmAIgSAAQgUgFgGAAQgbAAAAAaQAAAEANAHQAPAIASAAQAYAAANgIQANAAAVAKgACcgSQgRALgBADIAFADQAVABAEgUQACgKgDgEIAGgHQAMgTAHABQANACgEAJQAFgCACgGQACgLgTgDQgNgCgMAYIgGALIgBAAIAAACQgIAKgFAAQgGgBAAACQAAACAFADQAGgBAHgFIgCAHgAA6hwIAAAAQgCgJgGgFQAFAGADAIgAjIiFIABAAIgBAAgAgZCvIAAgBIAFAAIABACgAjUgjQgCgEgBgGQgBgHACgHIAEgPIgCgBIACAAIABgDIACAAQgFAEAAAIQAAAIAHAKIAHALQgEAKAAAEQAAAHAFAHQAFAHAAACIAAABQgPgYgFgMgAishAQAAgKANgFQAEABAAADQAAAEgDADIAAAAIgKAMIgEgIgAjOhWIABAAIgBABIAAgBgAjHhXIAAAAIAAAAIAAAAIAAAAgAgjjMIgCAAIgHgHQAZAIATAJQgRgHgSgDg");
	this.shape_13.setTransform(11,-50.1);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#422100").s().p("ACjCnIABgKIAAgQQgRhwgQgEQgFANADANIAAAAQgngPgngaQgXgOgdgHIgCAAIAAAAQABAXASATQAJAKAIAHQgqgFgbghQgGgIgEgGIgCgBIgfgaIgYgRIgEADQgNALgRgDQgWgFgEgQQgCgHACgKQACgKAZgVIACgGQAMgZAOgRQAcggAsgJQgvAXAZA5QAGAMAJAGQgNADAAAUQAAAQAIAKIAHAGQAQggAZgWQABA4A3AgIAHAFIgLgdIADgMQAaAcAUAkQAKARARADIgLgOIAWguQAKA+AZBEIAAAKIABAIQAAADADACIACADIAKACIALgFIADAAQgGAFgCAIIgSAuIgWAEQACgJAFgUgACSCeIABgPIACAHIgDAKIAAgCgACuBuQAAgBAAAAQAAAAAAAAQAAgBAAABQAAAAAAAAIAAACIAAgBgAjEgMQgKgaAEgeIAEgRQAIgOAZADIACAAQgDACgCAFIgCAHQgCAPAHARQAHAQANAIQgKAWgFAYQgZgIgLgYgAhdgWIgDgCQgDgFgCAAIABAAIAAgBIAAgBIACADIAFAGgAgrhhIABAAIAAAAIgBAAg");
	this.shape_14.setTransform(4.8,-72.7);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#E17100").s().p("ABXBfQgGgSgLgNIgIAjIgYhBQgHgHAAACIgCAJIgBAMQgNglgYgQIgBADQgBAJACAGIg7gqIAJAXQgkgQgTglIABAKIgBAAQgXgjAWgXIADgEQgHAKAAAMQABAMAHgEQAFgBAAAHQABAKAHAIIADgBIAEABIABgDQgBgHADgGIADAEQANASARARIAGgSIADAGQALAYASAJIAKgjIAFAGIAUAeIAGgWIAPAgQgBADADAFIAAgKIAEAHQAGAMAFACQACgFABAIIAFAZIAGgQIAQALIAGgUIAHAGQABAAAAAAQABAAAAgBQAAAAAAgBQAAgBAAgBQgFgKgHgJQADADAEACQAOAJAGAPIgBAAIgCAAQgEAAgCADQAFAAACACQAJAIAEAHIgcgHQAFAGAAAGIAEAFQALAPgDAGQgCAAgDgCQgIgMgIAAIAAALQgDAOADAOQgFgGgDgJg");
	this.shape_15.setTransform(19.4,-79.5);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#5E2F00").s().p("AB/DrIAAgBQACgJAAgHIAIgHIAKgIQASgPAIgNQADgNAAgOIAAgQIgBABIgBgEQgDgHgDgFIgNgPQgHgDgFgDQgHgDgKgBQgagEgLAJIgDAAIgLAEIgKgCIgDgCQgCgCAAgDIgBgJIAAgJIAAABIAAgCQAAAAAAgBQAAAAAAAAQAAAAAAABQgBAAABABQgZhEgKg+IgWAwIALAMQgPgEgKgOQgUgngagbIgDAMIALAdIgHgFQg3gggBg5QgbAXgQAgIgHgGQgJgKABgQQgBgUAOgDQgKgGgFgMQgZg5AvgXQAjgHAtAHQBXAOAhAcQAMAKAKARIATAeQAIgVAPgMIgDANIgEAVQgCANAKAIQAEgBAHgFQAFgEAMACQAvAHAvBQQAOANAIASIgDALIgFAEQgHgTgTgNQAKArgYAzIgGAQQgHASgBAUIgCAQIABAAIgDAWQgFAXgNATQgSAYgWAAIgHAAgAB+AGQgCgMACgOIAAgLQAIAAAJAMQACACADAAQADgGgMgPIgDgEQgBgHgFgGIAcAHQgEgHgIgIQgDgCgEAAQACgDADAAIACAAIACAAQgGgOgOgKQgEgCgDgDQAHAJAEALQABABAAAAQAAABAAAAQgBABAAAAQgBAAAAAAIgHgGIgGAVIgQgMIgHAQIgEgZQgBgIgCAFQgGgCgFgMIgEgIIgBALQgDgEABgFIgOghIgGAWIgXgeIgEgFIgLAiQgPgJgLgYIgEgGIgFASQgSgQgNgTIgCgEQgDAGABAHIgCADIgDAAIgDAAQgIgIAAgKQAAgHgFABQgIAEAAgMQAAgMAGgKIgDAEQgVAXAXAjIABABIgBgLQASAlAlAQIgKgXIA6AsQgDgGACgJIAAgFQAaATANAkIABgMIACgJQAAgCAIAHIAYBBIAIgjQALANAGASQACAHAFAGIAAAAgAidiFIAAAAIgBAAIABAAgAhFA+IgGgCIAEABIADABIgBAAgAgBAyIAAAAIgBAAIgCgCQgIgGgKgGIgXgMIgPgEIAAgBIAAgCQgGgIgKgJQAEAAAFAAQAZAFAXAQQATAOAFATIgGgEgAiQASIAAgCQgDgMAQAEIAJAGQgJABgFAEgAj/AGIACgHIADAAQAWABADADQABABACAJQgTgFgMAFIgDAEIABgLg");
	this.shape_16.setTransform(16.3,-69.1);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#000000").s().p("AgEFmQgUgEgKAAIAAAAQgKgOAFgSIADgOQAGgDAAgSQACgMgFgDIgGgLIgBgBIgFgBIgBAAIABABIgwgGQg6gNg3hmQgcg1gRg1IAQhUQgIgJgCgSQgCgPADgPIAAgBIgGABQgpgGgKgvQgGgaAEgZQAIg1AsAHIALACIAIACQAKglAmgeQAQgNARgIQAxgXBCAKQCFAVAeA8IAOgKQALgJAIgDQAIgEgJAcIAAAdQA3ATAxAxQAvAwgFAdQgBAKgIAJQgKALgNgJQABAmgXAqIgCBFQggBSgrAFQgBgCgEAAQgDAAgBACIgCAAIAAAAIAAABIABAAQgBADAAAEQAAAFACACIAAAAIgBAAIAGASIACAAQAHANADAQIgEAGQgGAIgDAFQgdAkgsAjQgtAkglAMQgHgBgLAAgABgCcQAAAEgKAXQgKAYgEAFQgcAYgOANQgVAIgZACQACADABAHIAAAKIgBAEIAAAQIAAAEQABAHgDAHIAAACIgIASQADAFAEAAQAYAAA5gkQAtgdASgSQAcgbAKgMIgDgEQgQgcgBgTIAAgNIgCgBIACgFIAAgBIAAAAQgDgFgBgHIAAgBQAAgIACgIIAAgBIAAAAIgPADIgGgCQgNgCgHACIAAgCIgFgDIAAgDIAcgMQAbgJAHgFQAigVACgRQACgNgFgMQgHgSgTgBIgHgBQgPgBgJAFIgEAAIgJAYIgBAHIgCAAIgEATQgCAIgzADQgFgSAEgTIADgLIADgLIgCgHIgDgOQgDgdgDgHQgIgWgggTIgSgLIARALIABAAQAnAagEAXIgBAHQgDABgFAAIgBAAIABAAQgEgCgDgDIgEgFIgGgEQgGgGgKgGIAAABQgCgDgFgCIgEgDIgEgBQgMgFgQgDQgEACgGgBIgMgCIAAAAIgKgEQgNAAgJABIgCABIgPAEIgCgDIgHABQgHgBgBgFIgBAAQgFgBABgKQABgIAJgGQgMgKgMgMQgUgSgLgNIgDgEIgFgGIgCgDIAAABIgBABIgBAAIAAAAQgOgCgNAkIgHAUIAMABQAgAEgEAWQgBAJgMABIADACIgIAAQgNAAgDADIgEADQgIAFAAAUQAAAEACACQADgDAFgBQgCgCAAgEQAAgLAhAAQAGAAABACQgdAGgIAJQAKgDASAAIABAAQAHAAAGAKIgBAAQACAJgBAMIAAADIgBACIgCABIgGgaIgQABQgXAFgHANIAAAAIAAABQgDADAAAGQAAAEADACIgBABIACAAIACAAQABAAAAAAQABAAAAAAQAAAAABgBQAAAAAAAAIABAAIABAAIAAgCQAEgTAQADQARAEACANIAHAAIADAAIAEgFIACABIAAAFIACAAQACAAABAEIgBAEIgGAAIgGAWQgNAUgBAEIgBABIABABQAAAMAYADQAVAEAagJIADgBQgZAdgZgDQgRgDgLgHIAAAGQAKAaAAAJQgFAOAAAFQAQAeAVASIAGAHQAFAGAFAMQAOAUAUADQAHADAJABQAiAFAagCQABgEADgDQgBgBAAAAQAAAAAAgBQAAAAgBgBQAAAAAAgBQAAgCAIgJIgCgMQAAgHAIgGQAHgGAAgFQAAgHgHgRQAAgFAFgQQAAgFgOgQQgPgRAAgVQAAgPgRgWQgGgPgagDQgTgCgDgIIAJgBIADACQAGAGAIgBQAJgBAEACQAQAKAEAHIARAiQADAgAOANQALAMAAAKQgEAOAAAFQAIAVAAAEQAAAHgIAHQgHAHAAAEIACAMQAAAJgEADIgEAIQAMgCAJgDIAIgMQAHgOAAgEIgDgSQAAgHAIgHQAHgHAAgEQAAgGgMgRQgNgSAAgGQAAgHAFgLQAAgFgKgSQgHgTAAgGQAAgKAHgHQAJgHAAgBIgDgJIAAgCQgUgGgYAAIgFAAIg1AGIgIgGIgBABIgCgDQAAgBAAgBQABAAAAgBQAAAAABAAQABAAAAAAIABAAIAFACIAIgDQAGgVAZAGQARADAHAKQAVACAPAGIAHADIABgBIABABQAKAFAIAGIgPgFQACADAAAEQAAAGgJAGQgKAFAAAJQATAiAAAOQgEAPAAADQAAAFANASQANARAAAHQAAAGgIAHQgIAIAAAEIACARIgJATIgBAIQAMgEAJgHQAPgMAJgPQANgMAJgRQAGgLAEgLQACAHgBAFgAjcAGIgGAMQAAAHAHAKQAIAJAAACQgGANAAACQALANAAALIgCAIIAEAKIAQAdIAFgMQAAgKgLgZIABgHQgFgEgEgFQgIgLABgHIAQgSIAAgCIgFgMQAAgNAIgEIgHAAIgXAEgADRArQAAAOgEANQgIANgRAQIgKAHIgIAHQAAAHgCAJIgBABIABAAQAbAEATgbQANgUAFgWIADgWIABgDIgCACIACgPQACgVAHgQIAFgQQAYgygJguQATANAHAVIAFgEIACgLQgHgTgPgNQgvhRgugHQgNgCgEAEQgHAFgFABQgJgIACgMIAEgVIADgNQgPALgIAVIgTgeQgLgRgMgKQghgchWgOQgtgHgjAHQgsAJgcAgQgPARgLAZIgCAGQgZAVgDAKQgCAKACAHQAFAQAVAFQARADAOgLIAEgDIAYARIAeAaIACABQAEAIAHAIQAbAhAsAFQgIgHgKgJQgTgUgCgZIABAAIABAAQAgAHAWAQQAlAaAnAQIABAAIAAgBQgDgNAFgNQAPAEARBuIAAAQIAAAKQgGAUgBAJIAWgEIARguQADgGAGgFQALgJAaAEQAJABAIADQAEADAIAEIAMAMQAEAFACAHIACAEIAAgBIABAQgAjmAIIgDABIACABIgEAPQgBAHABAHQAAAFADAEQAFANAOAZIABgCQAAgCgFgHQgGgHAAgHQAAgEAFgLIgHgLQgHgKAAgHQAAgIAEgEIgBgBIgBADgAjAATIAEAJIAKgMIgBAAQADgEAAgDQAAgDgDgCQgNAFAAAKgAhMgCQAAAAAAAAQAAABAAAAQAAAAABABQAAAAABAAQAFAAABgEIgCgEIgBAAQgEAAgBAGgAjTgKQAAABAAAAQAAABAAAAQAAAAAAAAQAAABABAAQAEABABgFQAAgBAAAAQAAgBAAAAQAAAAgBgBQAAAAgBAAIgBAAQgDAAAAAEgAAmgxQgGgTgVgOQgUgQgZgFQgFgBgFABQALAJAGAIIAAACIgBABIAQAEIAVAMQAKAGAIAGIABACIABABIABgBIAIAEIAAAAgAhwhXIAAACIAJABQAEgEAJgBIgJgFIgHgCQgIAAACAJgAjdhqIgCAKIgBAKIAEgDQALgGAUAFQgCgJgBgBQgDgDgWgDIgCAAIgCAAgAg5h3IABABQASACASAHQgUgIgZgJIAIAHgAkZjiIgDARQgFAeALAaQALAaAZAIQAFgaAKgVQgOgJgHgQQgHgRACgPIACgHQACgFAEgCIgCAAIgHgBQgTAAgIAMgAhJFOIAAAAIAAABgAg6DMQABAAABAAQAAAAABAAQAAAAABAAQAAAAAAABIgCABgAh8C3QAAgIAIAAIAmAHQAKAAACAEQgFABAAAGQAAAFgQAAQglAAAAgPgAg/CjQgVgKgNAAQgOAIgYAAQgRAAgQgJQgMgHAAgEQAAgaAbAAQAGAAAUAGQARAAAmgJQBBAAAAAoQAAAVgXAAQgNAAgUgKgAB6BSIgFgCQACgDARgLIABgHQgGAFgGABQgGgDABgDQAAgBAGAAQAFABAHgLIABgCIAAAAIAGgLQANgXANACQASADgCAKQgBAHgGABQAEgJgMgBQgHgCgNATIgFAHQACAEgCAKQgDATgQAAIgGAAgAgOgXIgBgBQgVgGgPAAQgaAAgIAJQgMAOgCABQgBADgCACQgDABgDAAQADgGACgNIAKgKIACgCQAOgLAaAAIAPABIABABIgDgCIAEACIAHACIgMgEQgagGgMgEQACgEABAAQANAAAYAJQAMAFAIAGIADABQAZAJADANIgRgIQAFAKgBAHIgBADIAAABQgHgNgHgKgAAmgbQgDgHgFgHQAGAGACAIgAjcgvIAAgBIAAABg");
	this.shape_17.setTransform(13,-58.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11}]}).wait(3));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-60.3,-94.6,104,71.9);


(lib.cross = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF0000").s().p("AhKArIAJABQARAAAXgdIAFgFIgDgDQgeggAAgOQAAgMAVgQQAHAfAVAZIAAADIADgGQAdglASAAQAKAAAHAKIADAHQgXAKgbAcIgEAFIADADQAYAbAVAAIAPgCQgIAUgGAEQgEAGgKAAQgTAAgcghIgDgGIgEAEQgZAjgQAAQgNAAgNgYg");
	this.shape.setTransform(7.5,6.8);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,15,13.6);


(lib.ChatterB = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#800080").s().p("AAABPQgxAAAAgLQgBggASgZQAPgUARgCQgPAAgJgKQgKgJAAgPQAAgOAKgKQAJgJAPgBQAMABAKAJQAJAKABAOQgBAPgJAJQgJAJgNABQASAAAPAXQAQAZACAhQAAAKgsAAIgHgBg");
	this.shape.setTransform(5.1,8);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,10.2,16);


(lib.BigN = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AAvBDIhXhsIAABSQAAAMAFAEQAFAEAHAAIADAAIAAADIgvAAIAAgDQALAAAEgFQAFgEAAgLIAAhbIgDgEQgEgFgEgCQgDgBgGgBIAAgDIAvAAIA/BQIAAg3QAAgMgDgEQgFgGgLAAIAAgDIAsAAIAAADIgLADQgDACgCAEQgBAEAAAJIAABsg");
	this.shape.setTransform(6.8,6.8);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,13.7,13.6);


(lib.purple = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(1,1,1).p("AgMBAQADgrAWgQAgCgsQACgNAJgG");
	this.shape.setTransform(-0.2,3.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("rgba(0,0,0,0.651)").ss(1,1,1,3,true).p("AAWhFQAKAKAAAOQAAAOgKAKQgJAJgMABQASAAAPAXQAPAYACAiQAAAKgzgBQgxgBAAgKQgBghASgYQAPgUARgCQgOAAgKgKQgKgKAAgOQAAgOAKgKQAKgKAOAAQAMAAAKAKg");
	this.shape_1.setTransform(1.3,3.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

	// Layer 2
	this.Back = new lib.ChatterB();
	this.Back.parent = this;
	this.Back.setTransform(1.4,3.5,1,1,0,0,0,5.1,8);

	this.timeline.addTween(cjs.Tween.get(this.Back).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-4.7,-5.5,12.2,18);


(lib.NameGlow = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		/* import flash.filters.GlowFilter;
		
		//f = 1;
		
		//Col = 0x0000FF;
		
		//if(f == 1 || // mk1 system (uses by web)
		//   (_parent.SF & 4) == 4) // new system, by chat flash
			Col = 0x00FF00;
		
		TextGlow = new Array();
		var tg:GlowFilter = 
		new GlowFilter(Col, //color, 
			0.7,	//alpha, 
			2,		//blurX, 
			2,		//blurY, 
			6,		//strength, 
			3,		//quality, 
			false,	//inner, 
			false);	//knockout);
		TextGlow.push(tg);
		
		tk = 0;
		
		//if(f != 1 && // mk1 system (uses by web)
		//   (_parent.SF & 4) != 4) // new system, by chat flash
			onEnterFrame = PowerTick;
		//else
		//	main.filters = TextGlow;
			
		function PowerTick()
		{
		//	if(f == 1 || // mk1 system (uses by web)
		//   (_parent.SF & 4) == 4) // new system, by chat flash
		//		return;
			
			tk++;
			if(tk & (0xe << 0))
				BigN.filters = TextGlow;
			else
				BigN.filters = null;
		}
		
		*/
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1));

	// Layer 1
	this.BigN = new lib.BigN();
	this.BigN.parent = this;
	this.BigN.setTransform(8.3,7.6,1,1,0,0,0,6.8,6.8);

	this.timeline.addTween(cjs.Tween.get(this.BigN).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(1.5,0.8,13.7,13.6);


(lib.Hands = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.cry1 = new lib.cry2();
	this.cry1.parent = this;
	this.cry1.setTransform(6.7,9.7,1,1,0,0,0,1.5,0.5);

	this.cry2 = new lib.Cry_();
	this.cry2.parent = this;
	this.cry2.setTransform(12.5,9.6,1,1,0,0,0,1.5,0.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.cry2},{t:this.cry1}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(5.2,9.1,8.9,1.2);


(lib.coin = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.Shine2("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(12.5,16.6,0.62,0.62,0,0,0,-0.1,2.4);

	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("ACjAYIAAguAihgXIgBAp");
	this.shape.setTransform(16.3,10.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#000000").ss(1,1,1).p("AihAZQABAeAuAWQAwAXBCAAQBDAAAwgXQAugWABgeACigWQgBAeguAWQgwAWhDAAQhCAAgwgWQgvgXAAgdIAAgBQABgfAugWQAwgXBCAAQBDAAAwAXQAvAWAAAgg");
	this.shape_1.setTransform(16.4,10);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.rf(["#FFEFCC","#E8BD17"],[0,1],0.1,1.5,0,0.1,1.5,9.8).s().p("AhxA2QgwgXAAgfIAAAAQABgeAvgXQAvgWBCAAQBDAAAvAWQAwAXAAAeIAAAAQgBAfgvAXQgvAWhDAAQhCAAgvgWg");
	this.shape_2.setTransform(16.4,7.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.lf(["#E8BD17","#FFEFCC","#E8BD17"],[0.016,0.471,1],-16.3,0,16.3,0).s().p("AhxAnQgugWgCgdIgBgFIABgrQAAAfAwAXQAvAUBCAAQBEAAAvgUQAvgXAAgfIAAAwQgBAdguAWQgvAWhEABQhCgBgvgWg");
	this.shape_3.setTransform(16.3,13.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape},{t:this.instance}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-5.6,-1,39.3,34);


(lib.Bkg = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.Shad = new lib.smShad();
	this.Shad.parent = this;
	this.Shad.setTransform(9.5,9.5,1,1,0,0,0,9.5,9.5);

	this.timeline.addTween(cjs.Tween.get(this.Shad).wait(1));

	// Layer 2
	this.Back = new lib.smBack();
	this.Back.parent = this;
	this.Back.setTransform(9.5,9.5,1,1,0,0,0,9.5,9.5);

	this.timeline.addTween(cjs.Tween.get(this.Back).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,19,19.1);


(lib.BigCry = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.Hands();
	this.instance.parent = this;
	this.instance.setTransform(8.8,12,1,1,0,0,0,9.6,10.3);

	this.instance_1 = new lib.Face();
	this.instance_1.parent = this;
	this.instance_1.setTransform(10.3,9.1,1,1,0,0,0,11.2,7);

	this.instance_2 = new lib.Bkg();
	this.instance_2.parent = this;
	this.instance_2.setTransform(9.4,9.4,1,1,0,0,0,9.5,9.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_2},{t:this.instance_1},{t:this.instance}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-0.1,-0.1,19,19);


(lib.coins = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.coin("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(10.1,8.8,0.6,0.603,0,0,0,16.2,10);

	this.instance_1 = new lib.coin("synched",0);
	this.instance_1.parent = this;
	this.instance_1.setTransform(18,13.4,0.6,0.603,0,0,0,16.4,10);

	this.instance_2 = new lib.coin("synched",0);
	this.instance_2.parent = this;
	this.instance_2.setTransform(8.9,17.3,0.6,0.603,0,0,0,16.4,10.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_2},{t:this.instance_1},{t:this.instance}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-4.3,1.8,33,29.3);


(lib.XatDays = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.coins();
	this.instance.parent = this;
	this.instance.setTransform(33.5,16.1,0.775,0.764,0,0,0,10,9.3);

	this.instance_1 = new lib.coins();
	this.instance_1.parent = this;
	this.instance_1.setTransform(37.2,26.2,0.775,0.764,0,0,0,10.1,9.5);

	this.instance_2 = new lib.coins();
	this.instance_2.parent = this;
	this.instance_2.setTransform(18.5,18.3,0.775,0.764,0,0,0,10,9.3);

	this.instance_3 = new lib.coins();
	this.instance_3.parent = this;
	this.instance_3.setTransform(27.6,25.9,0.775,0.764,0,0,0,10,9.3);

	this.instance_4 = new lib.coins();
	this.instance_4.parent = this;
	this.instance_4.setTransform(11.1,25.1,0.775,0.764,0,0,0,10,9.3);

	this.instance_5 = new lib.star();
	this.instance_5.parent = this;
	this.instance_5.setTransform(7.4,21.6,1.207,1.191,0,0,0,5.9,13);

	this.instance_6 = new lib.star();
	this.instance_6.parent = this;
	this.instance_6.setTransform(38.2,18.6,1.207,1.191,0,0,0,6,13);

	this.instance_7 = new lib.star();
	this.instance_7.parent = this;
	this.instance_7.setTransform(17.7,15.6,1.207,1.191,0,0,0,6,13);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_7},{t:this.instance_6},{t:this.instance_5},{t:this.instance_4},{t:this.instance_3},{t:this.instance_2},{t:this.instance_1},{t:this.instance}]}).wait(1));

	// Layer 2
	this.instance_8 = new lib.purple();
	this.instance_8.parent = this;
	this.instance_8.setTransform(34.2,9,1.557,1.561,20.5,0,0,1.3,3.5);

	this.instance_9 = new lib.NameGlow();
	this.instance_9.parent = this;
	this.instance_9.setTransform(6.5,15.8,1.61,1.607,-20.3,0,0,8.2,7.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_9},{t:this.instance_8}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-7.4,-5.4,61.4,48);


(lib.main = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 7
	this.instance = new lib.XatDays();
	this.instance.parent = this;
	this.instance.setTransform(24.8,33.3,1,1,0,0,0,26.9,21.3);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(24).to({y:-19},24).to({y:33.3},26).wait(41));

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("AiqB4IB+iYIDXhX");
	this.shape.setTransform(7.8,-28.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#101010").s().p("ABKAiIgCAAIgjgDIgEgBIAMg1IADAAIABAAIAGAAIARgBIAVgDQADAAACAQQAEAFABAJIgBACIABAIQAAAKgCAHIgBAEIgCACIgYgCgAglAVIgXgGIgDgBIAPgnQAPABAUAAIANAAIgKAxIgbgEgAhXgjIAMAEIgbAGg");
	this.shape_1.setTransform(-28.4,-12.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAaAaIAKgyIATgBIAcACIgMA2IgtgFgAhSgNIASgLIAagGIAJACIAHACIAMABIgPAoQgQgFgpgXg");
	this.shape_2.setTransform(-32.2,-12.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFE1C4").s().p("AARArIgHgDQgOgFgSAAQgFAAgJgGIgCAAIABgKIgBgMIABAAQAAgHgCgDQAAAAAAgBQAAgBgBAAQAAgBAAAAQAAgBgBAAQAAgGAEgDIAAAAIAMgGQATgJAGAAIAOgDQAHAAARAJIABAAIABACIACABIgCADIgBACIAAAAIgCAAIgKgCQgEAAgIADIAAACQAAABASAIIAAABIACABIACACIACAAIAAABQAAABgDADIgEAEIAAgBIgHgBQgFAAgEACIAMAGIABACIAAABIABABIAAACIgCABIgCABIAAABIgCAAIgKAAQAAAAAAAAQAAABAAAAQgBABAAAAQAAABAAABQAAAEAKAGIAAABIABABIABACIAAABIgDACIAAABIgFgCgAgjgZQASgTAFAAQAEAAAGAFQgGABgDACIgZAOIABgDg");
	this.shape_3.setTransform(-13.6,-13.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("ABwCoQgGgDgQACQgGABgEgCQgFgCgDgEIgCAGIgBABQgCAHgEAAIgbgEIgfgEIgJgBIgjgBQgTgBgPgEIgXgEQgPgEgugWIACgNQApAZAQAFIACABIAYAGIAbAEIAtAFIABABIAjADIACAAIAZACIABgCIABgEQACgHAAgKIgBgIIABgDQAAgLgEgEQgDgQgDAAIgVADIgRABIgGgBIgBABIgDgBIgZgCIgTABIgOABQgTAAgQgCIgMgBIgGgCIgJgCIgMgEIAAgHQAQAGAKACIABABQASAEAdAAIAhgCIAeADIAWgDIAWgCQADAAAEAHIACgCIABgBIAHgIIABgBIAAAAIACgBIAAgBQAOgPAFAAQARABACAIIAKAAIAcAJIAAACIABAAQADADAAAEIgBAEQAAABAAAAQAAABgBAAQAAAAAAABQgBAAgBAAIgBABIgDAAIAAACIABACQAEAGAAAFQAAACgDAFQgFAFgDAAIAAAAIAAABQAAAAABABQAAAAABAAQAAABAAAAQAAAAAAABIAAAEIgBAFIgBACIAAABIAAACIgEAAIgCAAIAAABIgDgBIgBAAIADACIAAABIAEADIABAGIAAACIgBAEQgCADgEAAIgBgBIgBABIAAAAIgBABIgUgJgABJCRIgBAKIACAAQAJAGAFAAQASAAARAFIAGADIAFACIABgBIACgCIAAgBIgBgCIgBgBIAAgBQgJgGAAgEQAAgBAAgBQAAAAAAgBQAAAAAAgBQAAAAAAAAIAKAAIACAAIAAgBIADgBIABgBIAAgCIAAgBIgBgBIAAgCIgNgGQAEgCAFAAIAHABIAAABIAEgEQADgDAAgCIAAgCIgCAAIgCgCIgCgBIAAgBQgSgIAAgBIAAgCQAIgDAEAAIALACIABAAIABAAIABgCIABgDIgBgBIgCgCIAAAAQgSgJgHAAIgOADQgIAAgTAJIgMAGIAAAAQgDADAAAGQAAAAAAABQAAAAABABQAAAAAAABQAAABAAAAQACAEAAAIIgBAAIABAMgABLBjIgBADIAZgOQAEgCAFgBQgGgFgDAAQgFAAgTATgAhbiwQBNAJBNgGIAGAnQhSgBhOgpgAAeiSQAYANAGgUQgHgKgHAAQgIAAgIARg");
	this.shape_4.setTransform(-24.8,-25.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(115));

	// Layer 6
	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f().s("#000000").ss(1,1,1).p("AAAgbIAAA3");
	this.shape_5.setTransform(24,-37.4);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f().s("#000000").ss(1,1,1).p("AAAAnIAAhN");
	this.shape_6.setTransform(24.1,-36.3);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f().s("#000000").ss(1,1,1).p("AAAAyIAAhj");
	this.shape_7.setTransform(24.1,-35.2);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f().s("#000000").ss(1,1,1).p("AAAA9IAAh5");
	this.shape_8.setTransform(24.1,-34);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f().s("#000000").ss(1,1,1).p("AAABIIAAiP");
	this.shape_9.setTransform(24.1,-32.9);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f().s("#000000").ss(1,1,1).p("AAABTIAAil");
	this.shape_10.setTransform(24.1,-31.8);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f().s("#000000").ss(1,1,1).p("AAABeIAAi6");
	this.shape_11.setTransform(24.1,-30.7);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f().s("#000000").ss(1,1,1).p("AAABpIAAjR");
	this.shape_12.setTransform(24.1,-29.6);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f().s("#000000").ss(1,1,1).p("AAABzIAAjl");
	this.shape_13.setTransform(24.1,-28.5);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f().s("#000000").ss(1,1,1).p("AAAB+IAAj7");
	this.shape_14.setTransform(24.1,-27.4);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f().s("#000000").ss(1,1,1).p("AAACJIAAkR");
	this.shape_15.setTransform(24.1,-26.2);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f().s("#000000").ss(1,1,1).p("AAACUIAAkn");
	this.shape_16.setTransform(24.1,-25.1);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f().s("#000000").ss(1,1,1).p("AAACfIAAk9");
	this.shape_17.setTransform(24.1,-24);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f().s("#000000").ss(1,1,1).p("AAACqIAAlT");
	this.shape_18.setTransform(24.1,-22.9);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f().s("#000000").ss(1,1,1).p("AAAC1IAAlo");
	this.shape_19.setTransform(24.1,-21.8);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f().s("#000000").ss(1,1,1).p("AAAC/IAAl9");
	this.shape_20.setTransform(24.1,-20.7);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f().s("#000000").ss(1,1,1).p("AAADKIAAmT");
	this.shape_21.setTransform(24.1,-19.6);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f().s("#000000").ss(1,1,1).p("AAADVIAAmp");
	this.shape_22.setTransform(24.1,-18.4);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f().s("#000000").ss(1,1,1).p("AAADgIAAm/");
	this.shape_23.setTransform(24.1,-17.3);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f().s("#000000").ss(1,1,1).p("AAADrIAAnV");
	this.shape_24.setTransform(24.1,-16.2);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f().s("#000000").ss(1,1,1).p("AAAD2IAAnr");
	this.shape_25.setTransform(24.1,-15.1);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f().s("#000000").ss(1,1,1).p("AAAEBIAAoB");
	this.shape_26.setTransform(24.1,-14);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f().s("#000000").ss(1,1,1).p("AAAELIAAoV");
	this.shape_27.setTransform(24.1,-12.9);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f().s("#000000").ss(1,1,1).p("AAAEWIAAor");
	this.shape_28.setTransform(24.1,-11.8);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f().s("#000000").ss(1,1,1).p("AAAkgIAAJB");
	this.shape_29.setTransform(24,-10.7);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f().s("#000000").ss(1,1,1).p("AAAAmIAAhL");
	this.shape_30.setTransform(24.1,-36.3);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f().s("#000000").ss(1,1,1).p("AAAAxIAAhg");
	this.shape_31.setTransform(24.1,-35.3);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f().s("#000000").ss(1,1,1).p("AAAA6IAAh0");
	this.shape_32.setTransform(24.1,-34.3);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f().s("#000000").ss(1,1,1).p("AAABEIAAiI");
	this.shape_33.setTransform(24.1,-33.3);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f().s("#000000").ss(1,1,1).p("AAABOIAAib");
	this.shape_34.setTransform(24.1,-32.2);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f().s("#000000").ss(1,1,1).p("AAABZIAAix");
	this.shape_35.setTransform(24.1,-31.2);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f().s("#000000").ss(1,1,1).p("AAABjIAAjE");
	this.shape_36.setTransform(24.1,-30.2);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f().s("#000000").ss(1,1,1).p("AAABtIAAjZ");
	this.shape_37.setTransform(24.1,-29.2);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f().s("#000000").ss(1,1,1).p("AAAB3IAAjt");
	this.shape_38.setTransform(24.1,-28.1);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f().s("#000000").ss(1,1,1).p("AAACBIAAkB");
	this.shape_39.setTransform(24.1,-27.1);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f().s("#000000").ss(1,1,1).p("AAACLIAAkV");
	this.shape_40.setTransform(24.1,-26.1);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f().s("#000000").ss(1,1,1).p("AAACVIAAkp");
	this.shape_41.setTransform(24.1,-25.1);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f().s("#000000").ss(1,1,1).p("AAACpIAAlR");
	this.shape_42.setTransform(24.1,-23);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f().s("#000000").ss(1,1,1).p("AAACzIAAll");
	this.shape_43.setTransform(24.1,-22);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f().s("#000000").ss(1,1,1).p("AAAC9IAAl5");
	this.shape_44.setTransform(24.1,-20.9);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f().s("#000000").ss(1,1,1).p("AAADHIAAmN");
	this.shape_45.setTransform(24.1,-19.9);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f().s("#000000").ss(1,1,1).p("AAADRIAAmh");
	this.shape_46.setTransform(24.1,-18.9);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f().s("#000000").ss(1,1,1).p("AAADbIAAm1");
	this.shape_47.setTransform(24.1,-17.8);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f().s("#000000").ss(1,1,1).p("AAADlIAAnJ");
	this.shape_48.setTransform(24.1,-16.8);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f().s("#000000").ss(1,1,1).p("AAADvIAAnd");
	this.shape_49.setTransform(24.1,-15.8);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f().s("#000000").ss(1,1,1).p("AAAD5IAAnx");
	this.shape_50.setTransform(24.1,-14.7);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f().s("#000000").ss(1,1,1).p("AAAEDIAAoF");
	this.shape_51.setTransform(24.1,-13.7);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f().s("#000000").ss(1,1,1).p("AAAENIAAoZ");
	this.shape_52.setTransform(24.1,-12.7);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f().s("#000000").ss(1,1,1).p("AAAEXIAAot");
	this.shape_53.setTransform(24.1,-11.7);

	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.f().s("#000000").ss(1,1,1).p("AAAEaIAAoz");
	this.shape_54.setTransform(24.1,-11.4);

	this.shape_55 = new cjs.Shape();
	this.shape_55.graphics.f().s("#000000").ss(1,1,1).p("AAAESIAAoj");
	this.shape_55.setTransform(24.1,-12.2);

	this.shape_56 = new cjs.Shape();
	this.shape_56.graphics.f().s("#000000").ss(1,1,1).p("AAAD8IAAn3");
	this.shape_56.setTransform(24.1,-14.5);

	this.shape_57 = new cjs.Shape();
	this.shape_57.graphics.f().s("#000000").ss(1,1,1).p("AAAD0IAAnn");
	this.shape_57.setTransform(24.1,-15.2);

	this.shape_58 = new cjs.Shape();
	this.shape_58.graphics.f().s("#000000").ss(1,1,1).p("AAADtIAAnZ");
	this.shape_58.setTransform(24.1,-16);

	this.shape_59 = new cjs.Shape();
	this.shape_59.graphics.f().s("#000000").ss(1,1,1).p("AAADmIAAnL");
	this.shape_59.setTransform(24.1,-16.7);

	this.shape_60 = new cjs.Shape();
	this.shape_60.graphics.f().s("#000000").ss(1,1,1).p("AAADeIAAm7");
	this.shape_60.setTransform(24.1,-17.5);

	this.shape_61 = new cjs.Shape();
	this.shape_61.graphics.f().s("#000000").ss(1,1,1).p("AAADWIAAms");
	this.shape_61.setTransform(24.1,-18.3);

	this.shape_62 = new cjs.Shape();
	this.shape_62.graphics.f().s("#000000").ss(1,1,1).p("AAADPIAAmd");
	this.shape_62.setTransform(24.1,-19);

	this.shape_63 = new cjs.Shape();
	this.shape_63.graphics.f().s("#000000").ss(1,1,1).p("AAADIIAAmP");
	this.shape_63.setTransform(24.1,-19.8);

	this.shape_64 = new cjs.Shape();
	this.shape_64.graphics.f().s("#000000").ss(1,1,1).p("AAADAIAAl/");
	this.shape_64.setTransform(24.1,-20.6);

	this.shape_65 = new cjs.Shape();
	this.shape_65.graphics.f().s("#000000").ss(1,1,1).p("AAAC5IAAlx");
	this.shape_65.setTransform(24.1,-21.3);

	this.shape_66 = new cjs.Shape();
	this.shape_66.graphics.f().s("#000000").ss(1,1,1).p("AAACxIAAlh");
	this.shape_66.setTransform(24.1,-22.1);

	this.shape_67 = new cjs.Shape();
	this.shape_67.graphics.f().s("#000000").ss(1,1,1).p("AAACjIAAlF");
	this.shape_67.setTransform(24.1,-23.6);

	this.shape_68 = new cjs.Shape();
	this.shape_68.graphics.f().s("#000000").ss(1,1,1).p("AAACbIAAk1");
	this.shape_68.setTransform(24.1,-24.4);

	this.shape_69 = new cjs.Shape();
	this.shape_69.graphics.f().s("#000000").ss(1,1,1).p("AAACMIAAkX");
	this.shape_69.setTransform(24.1,-25.9);

	this.shape_70 = new cjs.Shape();
	this.shape_70.graphics.f().s("#000000").ss(1,1,1).p("AAACFIAAkJ");
	this.shape_70.setTransform(24.1,-26.7);

	this.shape_71 = new cjs.Shape();
	this.shape_71.graphics.f().s("#000000").ss(1,1,1).p("AAAB9IAAj5");
	this.shape_71.setTransform(24.1,-27.5);

	this.shape_72 = new cjs.Shape();
	this.shape_72.graphics.f().s("#000000").ss(1,1,1).p("AAAB2IAAjr");
	this.shape_72.setTransform(24.1,-28.2);

	this.shape_73 = new cjs.Shape();
	this.shape_73.graphics.f().s("#000000").ss(1,1,1).p("AAABvIAAjd");
	this.shape_73.setTransform(24.1,-29);

	this.shape_74 = new cjs.Shape();
	this.shape_74.graphics.f().s("#000000").ss(1,1,1).p("AAABnIAAjN");
	this.shape_74.setTransform(24.1,-29.7);

	this.shape_75 = new cjs.Shape();
	this.shape_75.graphics.f().s("#000000").ss(1,1,1).p("AAABgIAAi/");
	this.shape_75.setTransform(24.1,-30.5);

	this.shape_76 = new cjs.Shape();
	this.shape_76.graphics.f().s("#000000").ss(1,1,1).p("AAABYIAAiv");
	this.shape_76.setTransform(24.1,-31.3);

	this.shape_77 = new cjs.Shape();
	this.shape_77.graphics.f().s("#000000").ss(1,1,1).p("AAABQIAAig");
	this.shape_77.setTransform(24.1,-32);

	this.shape_78 = new cjs.Shape();
	this.shape_78.graphics.f().s("#000000").ss(1,1,1).p("AAABJIAAiR");
	this.shape_78.setTransform(24.1,-32.8);

	this.shape_79 = new cjs.Shape();
	this.shape_79.graphics.f().s("#000000").ss(1,1,1).p("AAABCIAAiD");
	this.shape_79.setTransform(24.1,-33.6);

	this.shape_80 = new cjs.Shape();
	this.shape_80.graphics.f().s("#000000").ss(1,1,1).p("AAAA6IAAhz");
	this.shape_80.setTransform(24.1,-34.3);

	this.shape_81 = new cjs.Shape();
	this.shape_81.graphics.f().s("#000000").ss(1,1,1).p("AAAAzIAAhl");
	this.shape_81.setTransform(24.1,-35.1);

	this.shape_82 = new cjs.Shape();
	this.shape_82.graphics.f().s("#000000").ss(1,1,1).p("AAAArIAAhV");
	this.shape_82.setTransform(24.1,-35.9);

	this.shape_83 = new cjs.Shape();
	this.shape_83.graphics.f().s("#000000").ss(1,1,1).p("AAAAkIAAhH");
	this.shape_83.setTransform(24.1,-36.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5}]}).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_7}]},1).to({state:[{t:this.shape_8}]},1).to({state:[{t:this.shape_9}]},1).to({state:[{t:this.shape_10}]},1).to({state:[{t:this.shape_11}]},1).to({state:[{t:this.shape_12}]},1).to({state:[{t:this.shape_13}]},1).to({state:[{t:this.shape_14}]},1).to({state:[{t:this.shape_15}]},1).to({state:[{t:this.shape_16,p:{y:-25.1}}]},1).to({state:[{t:this.shape_17}]},1).to({state:[{t:this.shape_18}]},1).to({state:[{t:this.shape_19}]},1).to({state:[{t:this.shape_20}]},1).to({state:[{t:this.shape_21}]},1).to({state:[{t:this.shape_22}]},1).to({state:[{t:this.shape_23}]},1).to({state:[{t:this.shape_24}]},1).to({state:[{t:this.shape_25}]},1).to({state:[{t:this.shape_26}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_28}]},1).to({state:[{t:this.shape_29}]},1).to({state:[{t:this.shape_28}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_26}]},1).to({state:[{t:this.shape_25}]},1).to({state:[{t:this.shape_24}]},1).to({state:[{t:this.shape_23}]},1).to({state:[{t:this.shape_22}]},1).to({state:[{t:this.shape_21}]},1).to({state:[{t:this.shape_20}]},1).to({state:[{t:this.shape_19}]},1).to({state:[{t:this.shape_18}]},1).to({state:[{t:this.shape_17}]},1).to({state:[{t:this.shape_16,p:{y:-25.1}}]},1).to({state:[{t:this.shape_15}]},1).to({state:[{t:this.shape_14}]},1).to({state:[{t:this.shape_13}]},1).to({state:[{t:this.shape_12}]},1).to({state:[{t:this.shape_11}]},1).to({state:[{t:this.shape_10}]},1).to({state:[{t:this.shape_9}]},1).to({state:[{t:this.shape_8}]},1).to({state:[{t:this.shape_7}]},1).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_30}]},1).to({state:[{t:this.shape_31}]},1).to({state:[{t:this.shape_32}]},1).to({state:[{t:this.shape_33}]},1).to({state:[{t:this.shape_34}]},1).to({state:[{t:this.shape_35}]},1).to({state:[{t:this.shape_36}]},1).to({state:[{t:this.shape_37}]},1).to({state:[{t:this.shape_38}]},1).to({state:[{t:this.shape_39}]},1).to({state:[{t:this.shape_40}]},1).to({state:[{t:this.shape_41}]},1).to({state:[{t:this.shape_17}]},1).to({state:[{t:this.shape_42}]},1).to({state:[{t:this.shape_43}]},1).to({state:[{t:this.shape_44}]},1).to({state:[{t:this.shape_45}]},1).to({state:[{t:this.shape_46}]},1).to({state:[{t:this.shape_47}]},1).to({state:[{t:this.shape_48}]},1).to({state:[{t:this.shape_49}]},1).to({state:[{t:this.shape_50}]},1).to({state:[{t:this.shape_51}]},1).to({state:[{t:this.shape_52}]},1).to({state:[{t:this.shape_53}]},1).to({state:[{t:this.shape_29}]},1).to({state:[{t:this.shape_54}]},1).to({state:[{t:this.shape_55}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_51}]},1).to({state:[{t:this.shape_56}]},1).to({state:[{t:this.shape_57}]},1).to({state:[{t:this.shape_58}]},1).to({state:[{t:this.shape_59}]},1).to({state:[{t:this.shape_60}]},1).to({state:[{t:this.shape_61}]},1).to({state:[{t:this.shape_62}]},1).to({state:[{t:this.shape_63}]},1).to({state:[{t:this.shape_64}]},1).to({state:[{t:this.shape_65}]},1).to({state:[{t:this.shape_66}]},1).to({state:[{t:this.shape_18}]},1).to({state:[{t:this.shape_67}]},1).to({state:[{t:this.shape_68}]},1).to({state:[{t:this.shape_16,p:{y:-25.2}}]},1).to({state:[{t:this.shape_69}]},1).to({state:[{t:this.shape_70}]},1).to({state:[{t:this.shape_71}]},1).to({state:[{t:this.shape_72}]},1).to({state:[{t:this.shape_73}]},1).to({state:[{t:this.shape_74}]},1).to({state:[{t:this.shape_75}]},1).to({state:[{t:this.shape_76}]},1).to({state:[{t:this.shape_77}]},1).to({state:[{t:this.shape_78}]},1).to({state:[{t:this.shape_79}]},1).to({state:[{t:this.shape_80}]},1).to({state:[{t:this.shape_81}]},1).to({state:[{t:this.shape_82}]},1).to({state:[{t:this.shape_83}]},1).to({state:[{t:this.shape_5}]},1).wait(6));

	// Layer 1
	this.instance_1 = new lib.Hook();
	this.instance_1.parent = this;
	this.instance_1.setTransform(24.1,-29.1,1,1,0,0,0,3.8,9);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({y:21},24).to({y:-31.9},24).to({y:21},26).to({y:-29.1},35).wait(6));

	// Layer 3
	this.shape_84 = new cjs.Shape();
	this.shape_84.graphics.f().s("#330000").ss(3.4,1,1).p("AizB+QCRjzDWgI");
	this.shape_84.setTransform(7.1,-29);

	this.shape_85 = new cjs.Shape();
	this.shape_85.graphics.f("#999999").s().p("AgJAiIgNgHIgJgKIAEABQgLgEgBgKIgBgDIgBgFIACgBIgBAAIgBgBIAAggIAAABIACgCIAEABQAHADAEAAQAEAAADgDQAXAUAeAAIACABIAEAMQAAAAAAABQAAAAgBAAQAAABgBAAQgBAAgBABQgFAAgCACIgBAAIADACIABACQABAEgHADIgHADIACAIQgEASgFAAQgNAAgKgGgAAQgCIgBACIACAAIACABQABAAAAAAQABgBAAAAQAAAAAAAAQAAAAAAAAIAKAAQgCgCgGgBIgFgBQgBAAAAAAQAAAAgBABQAAAAAAAAQAAAAAAABg");
	this.shape_85.setTransform(-22.7,-34.3);

	this.shape_86 = new cjs.Shape();
	this.shape_86.graphics.f("#101010").s().p("AgoCNIgWgCIgBAAIgeAAIgBAAIgFgQQBOADBIgLIAAAJQAAAPgTAAIgEgBQgRACgeABIgVAAgABIBtIApgRIAMAWQAAAAAAAAQgBABAAAAQAAAAgBABQAAAAgBAAIgDAAIACABQgJAGgdAGQgCAAgJgUgAhtBLIgBgRIAAgWIAhgBIABAAQA+AFA8gHIgBASIACATQg0AGg2AAIgygBgAA1BEIAAABIgBAAIAAgFIgBgKIAAgFIAAgHIABgJIAegLIANAiIgpANIgBgBgAhMgLIADgRIAIgZIAAAAQA4ANA3gDIABAJQACAHAAAOIAAAKgAA2gNIgCgfIAQgCIABALIAAAJIACAQIgRAHIAAgKgAh8gaIAHgbIAEgSQAVAOAWACIgCACQgEAKgCAKIgDAVgAhjhtIAEgHIAKgSIAFgDIADgCQBCAeBAgNIABACQAEAHABAGIADAWIgPADQgCgKgCgFIgBABIABAPQhGABhIgdg");
	this.shape_86.setTransform(-27.2,-14.2);

	this.shape_87 = new cjs.Shape();
	this.shape_87.graphics.f("#FFFFFF").s().p("AhZCaIgBgBQgGgRgBgGIgBgVIgBgEQBPAEBMgIIACAeQADAFAAAKQg7AJg7AAIgggBgABNCBIgJgUQgCgDgCgGIAogNIAAAAIATAkIgpARIgFgLgAhDBCIgBgQQABgTABgOIB8AJIgCAUIAAARQgoAFglAAIgugCgAhkAtQAAgIgCAAQgCAAAAAIIAAACIgSgKIACgLIAGgXIArAOQgCAOAAASIABAPIAEACIggABgABAAZIARgHIACALIABACIAIAVIgeAMIACgngAg4gWIANgfQgLANgGAPQgWgCgWgNIAAgBQAEgSALgTQBHAcBHAAIADAgIAAAGIgTAAQgtAAgwgKgAA9gWIgEgdIAPgDIABACIADAYIACANIgQACIgBgJgAhDhtIAAAAIAFgDIADgEIAEgHIADgEIAAAAIADgEIAFgEQAGgIAGgFIAHgEIAGgCIAAABIgFAEIAAAAIgDAEIAAAHIABACIAEAKIAKAHQAGAEABACIABABIAAACIABACIACABIAKAAQAIAAAHgCQALgCALgFIAAACIAAACIAAABIABACIAIAIIABACIADADIABAAIADAFQgUAEgUAAQgsAAgugWgAAnhoIAAgBIAAAAgAAhh9IgBgBIABgGIACABIAAAAIAFAGIABACIACACIgKAEIAAgIg");
	this.shape_87.setTransform(-28.2,-17.3);

	this.shape_88 = new cjs.Shape();
	this.shape_88.graphics.f("#663300").s().p("AhiHVQgJgFgOgOQgUgRgCgDQgGgJAAgMIACgVIANADQAlAEAvgJIAFAEIALAKQABACAHAEQAIACALAGQAUAMAAAOQgBANgEAFIAAAAQgCAIgGAGQgJAMgXAAQgnAAgbgPgAA3GiQgWgGgVAAIgFAAIgEABIAAAAIgBAAIAAAAIgOgGIgHgCIAAAAIgCgBIgDgCIAAAAIAAgCIAEgSIABgDIAFgBIAAghQANAEAUABQAXADAOAAIAGABIAQAEIAIAEQAGADAHAAIAKgCIAQgBQAPAAAGAMQAEAIAAAHQAAAOgGAGQgOAPgtAAQgKAAgUgGgAgvk8QgFgZgYgaQgKgMgCgOQAAgRgBgIQgIAHgDAAIgBgBIgBAAQABgNAKgLQAMgNAWgIIgCgKIABgEQABgEAEAAQADAAACAIIAIgKQAFgGADAAIACAAQgBAGgGAJQAEgFAMgEQAOgFALAAQAQAAAUAGQATAFADAGIAGAFQAEAGABAEQAAAHgOALIgDADIAAAAIgCABIAAABQACACADAFIAFAMIAAABIgBgBIgKgGIgGgDIgBAAIgBAAIgCAAQgKAAgHAHIgGAFQgCACgDAAIgCAAIAAgCIACgHQgGAEgEAAQgBAAAAAAQgBAAAAgBQgBAAAAAAQAAgBAAgBIABgEIgDAJIAAABIAAAGQAHATAAAHIgBAFIgCACQgCADgCAAQgFAAgHgDIgDgBIgCACIAAgBIAAgCIAAgBIABgBIAAAAIABgHQABgKgKAAQgJAAgGANQgDAJAAAHQAAAFAEAIQAIALALAAIABAAIABAAIAAAAIABABIgFACQgJgBgGgIIgBgCIgBABIABABIgCAPQgCAHgCACIAAABgAAfmsIACgBIAFgJIgHAKg");
	this.shape_88.setTransform(-25,-1.5);

	this.shape_89 = new cjs.Shape();
	this.shape_89.graphics.f("#996600").s().p("AhqCuQgQgKAAgOQAbhKAHgbIAJgkQAEgfABgeIABgKIAAgpIACgSQADgiAAgXIACgBIAAgFIAAgBIAMABIAPACIAHAAIASABIATAAQAbAAASgCIANgDIAHgBQAAAFADANQAJAOAJAdQAPAuAEAkIAAAHIADANIABASQAJBSAAAUQACAsgQACQgGADgMgBQguAAgHgPIgGABQgDi9gMhNIgBgBQgBAAgBAFIgBASQAFAfAABBQAAASAHCRQAFAcgVgBIgIAAIgGACQgiACgfAEIgBAAQgUAAgPgKg");
	this.shape_89.setTransform(-29.9,18.4);

	this.shape_90 = new cjs.Shape();
	this.shape_90.graphics.f("#FFE1C4").s().p("ABTEMIABgGQAHgFAFgNQgCATgHAGgABHEEQAAgCAFgKQAEgKAAgKQAAgCgFgGQgFgHgDgBIgBABIgCgCIAAgTIgCgDQgFAOgCAgIgCAAQgBgMgLgWIgMgYIATgGQALgEAEgDQAKAIAJAVIACAFIgBAAIgBACIAHAOIADAJIABAIQABAHgHALQgHANgJAAIAAABIAAgDgABCD8QAIgRAAgFIgBgCIgCAAIgHAMQgEAHABAEIgBAAQgBAAAAAAQAAAAAAAAQAAAAAAgBQAAgBAAgBQAFgKABgIIAAAAQABgFgBgHIACACIACAAIAAgBIAGAJQAAAHgEALIgDAGIgCAAgAhFhkIgEgFQgNgIgDgFQgEgEgCgCIABAAQAGAAAFgTIABAAIAAgBIAAAAIAAgBIAAgBQACgCACgHIACgPIABAAQAGAIAJABIAFgCIABAAIgCABIABAHIABADQAAAKALAEIgDgBIAJAKIAAAAIgBAAIgBABIACAEIgDASIAAADQgLADgOAAIgEAAgAg5ikIgBAAQgLAAgIgLQgEgIAAgFQAAgHADgJQAGgNAJAAQAKAAgBAKIgBAHIAAAAIgBABIAAABIAAACIAAAgIAAAAgAhCi7QAAAKAFAAIADgCIgDgDQAAgBgBAAQAAgBAAAAQgBgBAAAAQAAAAAAgBIABgEQABgBAAgEIgBgGQgCgFgEAAQgDAAgDAFIgCAGIABAHQABAEADABIgCgIQAAgGAFgHQAEACABAEIAAADIgBAAIgCAIgAghjEIACgCIABgFQAAgHgHgTIgCgGIABgBIAEgJIgBAEQAAABAAABQAAAAABAAQAAABABAAQAAAAABAAQAEAAAGgEIgCAHIAAACIACAAQADAAACgCIAGgFQAHgHAIAAIACAAIABAAIABAAIAGADIAKAGIABABIAAgBIgFgMQgDgFgCgCIAAgBIAGAIQADAGACAGIAAAGQAAAEgCAGIgCAHIAKAJQAJAJABAIQAAAGgEADQgDACgJAAIgBAAIAAgBIABAAQgBgBAAAAQAAAAgBAAQAAAAgBAAQgBgBgBAAIAAAAIADAAQABAAABgBQAAAAABAAQAAAAABgBQAAAAAAAAIgCgCQgFAAgDACIgBACQAAABABAAQAAABAAAAQABABABAAQAAAAABAAIABABIAAAAIgCABIAAAAQgcAAgZgUgAALjtQgHAAgEAIQgEAHgBAEQAAACAFACQAGADAIAAQAEAAAFgNQAAgDgDgFQgDgFgFAAIgBAAgAAAkMIgEAJIgCABIAGgKg");
	this.shape_90.setTransform(-21.1,-18.5);

	this.shape_91 = new cjs.Shape();
	this.shape_91.graphics.f("#000000").s().p("Ag5HHQgVgEgLgGQgHgDgHgIIgLgMQgYgRgDgEQgDgDAAgXIABgNQAAgHgDgCIgDgCIgEgEIgDgCIgBACQgEgJgHgHIAIgWQAehWAHgvIAGg5IAAgNIABAAIgBgCIACgPIAAgHIABgGIAAgCIAAAAIACgJIAAgFIACgQIABgQIABgQQAAgNACgIIABgCIAAgBIAAAAIgCgBIAAgBQgEgEgEgPQgEgQgCgQIgBgPIgBgPIAAgUIAAgMIABgBIgBgCIABgEIgBgFIAAgBQAAgJACAAQACAAAAAJIAAAVIAAAWIABARIABADIABAVQABAGAGASIABAAIAEAQIABAAIAfAAIABAAIAVACIAVAAQAfgBARgCIADABQAUAAAAgPIAAgJQAAgJgDgGIgCgeIgBgTIABgSIAAgSIACgUIAAgKQABgOgCgHIgBgJIAAgFIgDghIgCgPIACgBQACAFACAKIAEAdIABAJIACAfIAAAKIgCAmIgBAJIAAAHIgBAFIACAKIAAAFIABAAIAAgBIABABQACAGACADIAJAUIAFALQAJAUABAAQAegGAIgGIgCgBIAEAAQABAAAAAAQABgBAAAAQAAAAAAgBQABAAAAAAIgMgWIgTgjIAAgBIgMgiIgIgWIgBgCIgCgKIgDgQIAAgJIAAgLIgCgMIgDgYIgBgDIgEgWQAAgGgEgHIgBgCIgDgFIgBAAIgDgDIgBgCIgIgHIgBgDIAAgBIAAgCIAAgBQgLAEgLADQgFABgIAAIgMAAIgCgBIgBgCIAAgCIgBgBQgBgCgGgEIgKgHIgEgKIgBgCIAAgGIADgFIAAAAIAFgDIAAAAIgEAMQAFgHAEgIIgFACIgGACIgHADQgGAGgGAHIgFAEIgDAEIAAABIgDADIgEAIIgDADIgFADIAAABIgDACIgGADIgKASIgDAHQgLAUgEARIAAABIgDASIgHAbIgGAXIgCALIgGgDIACgIIALgyIAEgUQALglAVgaIAUgPIgBgGQAAgDANgNQAMgMAJgCQACgCAFAAIAEAAIAAgBIADACIAAAAIAAABIAAAAIgBAAQgFAUgFgBIgBAAQABADAEADQADAGANAIIAFAEQAPABAMgDIAAgEIACgRIgCgEIABgBIABAAIAAAAIANAHQAMAGANAAQAFAAAEgTIgCgHIAHgEQAHgCgBgFIgBgBIgDgEIABAAQACgCAFgBQABAAABAAQABAAAAgBQABAAAAgBQAAAAAAgBIgEgLIgCgBIAAAAIABgBIAAAAIAAgBIAAAAQgBAAgBAAQgBgBAAAAQgBAAAAgBQAAAAAAgBIABgCQACgCAGAAIACACQAAAAgBAAQAAAAgBABQAAAAgBAAQgBAAgBAAIgCAAIAAABQABAAAAAAQABAAABABQAAAAABAAQAAAAAAAAIgBABIAAABIABAAQAJAAAEgDQADgCAAgHQAAgHgKgKIgKgJIACgGQACgGAAgFIAAgFQgBgHgDgFIgHgIIADgBQALALAAATQAAABgCAGIgDAFQAUAQAAALQgCAQgLAAIgFgBIACADIACAIIgBAEQgCABgGACQAEALgOAGIACAFIgEAMQgFALgHAAQgHAAgKgEQgHgBgEgDIAHAKQAEAIACAGIAHAFIAJAIIAEALIACAKIAAAAIAAACIABADIABAFQADANABAUIAAABQAHAxACAKQAFAUAYAxIAVAwQAAACgCADQAKAGAKAXQAJARACANIAAABQADAFAAASQAAAcgQAAQgFgBgBgHIAAgBQgEACgEAAQgFAAAAgHIAAgCQgFgDgFAAIAAgEIACgKIgHABIgCgBQABgJgKgUQgJgUgCgOIgMACIgBgEIgCgEIAAAAIgBgBIgSglIgBAKIADAhIAAAAIgBAEIgDADIAAACIgBgBIgCACIgBAAIABABQAAABAAAAQAAABABABQAAAAAAABQAAAAABABQAWAtARBhQAVBygIA9QgBAIgLACIAKAEQAPAFADgBIAGgBQAGgCAOAAQASgBAIAPQAGAKAAAKQAAAPgGAHQgPAUgyAAQgNAAgOgEIgMgFQgRgDgSgBIAEAEQAEAHgBANQAAAHgBAGIgBABIgJAPQgGAHgKAFIgDABIgDACIgFABIgMACIgFABQgPAAgSgFgAiJF7QABALAFAJQACAEAVARQANAOAJAFQAbAPAoAAQAVAAAKgMQAGgHACgHIAAgBQAEgEACgNQAAgOgXgMQgJgGgIgCQgGgEgCgCIgLgKIgEgEQgwAJglgEIgMgEIgDAWgAAUGvIABgDIAAAAIgBADgAAZF9QAVAAAVAHQAVAGAKAAQAsAAAOgPQAHgHAAgNQAAgHgFgIQgGgMgPAAIgQABIgKACQgGAAgGgDIgIgEIgRgEIgFgBQgOAAgYgDQgVgBgMgEIAAAgIgEABIgBAEIgFASIAAACIAAAAIAEABIACABIAAAAIAGADIAPAFIAAABIABAAIAAgBIADgBIAGAAgAgTFtIADAEIABgIIACgHIABgEIgMADIgDAAIgHABIABABIACABIAIAFIADADIgBAAIACABgAhmgLIAAAFIgCABQAAAVgCAiIgCASIgBApIgBAKQgBAegDAhIgKAkQgHAbgbBKQAAAOAQAKQAPAKAVAAIAFABIgFgBQAfgEAigCIAIgCIAJAAQAUABgFgcQgHiRAAgUQAAhBgFgfIABgSQABgFABAAIABABQAMBNADC/IAEgBQAIAPAtAAQAMABAGgDQAQgCgBgsQgBgUgIhUIgCgSIgDgNIAAgHQgEgkgPguQgJgdgJgOQgDgLAAgFIgGABIgOADQgPACgcAAIgVAAIgSgBIgHAAIgPgCIgMgBIAAABgACIA+IgBAGIADAAQAHgFACgTQgFANgGAFgAB/AUQAFAGAAACQAAAKgFAKQgEAKgBACQAAABABABQAAAAAAAAQAAABAAAAQAAgBAAAAQAIAAAHgNQAHgMAAgGIgBgJIgEgIIgGgOIABAAIACACIgBgDIgCgEQgJgWgKgHQgFADgKAEIgTAFIALAXQAMAWABAMIACAAQACghAEgLIADADIAAARIACABIAAABIAAgBQAEAAAFAIgAB9AcIABACQgBAEgHARIABABIADgGQAFgMAAgGIgHgJIAAABIgCAAIgBgCQABAHgBAFIAAAAQgCAIgFAKQAAABABABQAAAAAAABQAAAAAAAAQAAAAAAgBIABABQAAgEAEgIIAHgLgAAngPIAAgBIAAAAgAANk5IABAAIAAAJIAKgFIgCgCIgBgCIgFgGIAAAAIgCgBIgBAHgAhXh4IgEgCIgBgPQAAgSACgOIADgVQACgKAEgKIACgCQAGgPALgNIgNAeIAAAAIgIAZIgCARQgBANgBATIABAQgAAUklIAAAAIAAABgAA1lkIgCgCIABgDQAAAAAAAAQAAAAAAgBQABAAAAAAQAAAAABAAIAFABQAGABACACIgKAAQAAABAAAAQAAABAAAAQAAAAgBAAQAAAAgBAAIgCAAgAgPmDIACgIIABAAIAAgDQgBgEgDgCQgGAHAAAGIACAIQgCgBgCgFIAAgGIABgGQADgGAEAAQADABACAFIACAGQAAAEgCABIgBAEQAAAAABABQAAAAAAABQAAAAABABQAAAAABAAIADAEIgDACQgFAAgBgKgAAymeQgFgCAAgDQAAgEAFgGQAGgJAHABQAFgBAEAGQADAFgBADQgFANgEAAQgHgBgIgCgAA1mrIgEAIIADABIAKABQAFgIgDgEIgDgFQgFACgDAFg");
	this.shape_91.setTransform(-26.3,1.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_91},{t:this.shape_90},{t:this.shape_89},{t:this.shape_88},{t:this.shape_87},{t:this.shape_86},{t:this.shape_85},{t:this.shape_84}]}).wait(115));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-43.2,-50,95,104.6);


// stage content:



(lib.bigthief = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF0000").s().p("AgUChIAAgtIAoAAIAAAtgAgJBUIgLiJIAAhrIApAAIAABrIgLCJg");
	this.shape.setTransform(228.7,46.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FF0000").s().p("AhwB5QgkgwAAhIQAAg/AfgwQAng7BOAAQBQAAAmA3QAfAqAABEQAABGgjAvQgpA5hJAAQhIAAgogxgAhLhfQgeAhAABCQAAA2AaAkQAaAlA3AAQA4AAAYgqQAZgpAAg0QAAg5gdgiQgcgjgxAAQguAAgeAjg");
	this.shape_1.setTransform(205,46.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FF0000").s().p("ABJChIiZkCIAAECIgnAAIAAlBIAxAAICWEDIAAkDIAoAAIAAFBg");
	this.shape_2.setTransform(173,46.3);

	this.instance = new lib.cross();
	this.instance.parent = this;
	this.instance.setTransform(101.6,42.8,5.133,5.132,0,0,0,7.5,6.8);

	this.text = new cjs.Text("Password:", "20px 'Helvetica'");
	this.text.textAlign = "center";
	this.text.lineHeight = 26;
	this.text.lineWidth = 100;
	this.text.parent = this;
	this.text.setTransform(58.6,56.4);

	this.text_1 = new cjs.Text("Name:", "20px 'Helvetica'");
	this.text_1.textAlign = "center";
	this.text_1.lineHeight = 26;
	this.text_1.lineWidth = 100;
	this.text_1.parent = this;
	this.text_1.setTransform(41.6,33.9);

	this.text_2 = new cjs.Text("Email:", "20px 'Helvetica'");
	this.text_2.textAlign = "center";
	this.text_2.lineHeight = 26;
	this.text_2.lineWidth = 100;
	this.text_2.parent = this;
	this.text_2.setTransform(39.6,11.4);

	this.instance_1 = new lib.BigCry();
	this.instance_1.parent = this;
	this.instance_1.setTransform(38.9,140.9,3.421,3.419,0,0,0,9.3,10.8);

	this.instance_2 = new lib.Cry();
	this.instance_2.parent = this;
	this.instance_2.setTransform(196.1,134.5,1,1,0,0,0,-8.3,-58.6);

	this.main = new lib.main();
	this.main.parent = this;
	this.main.setTransform(217.1,151.8,1,1,0,0,0,94.7,14.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f().s("#000000").ss(1,1,1).p("ACWiGIkrAAIAAigIErAAgAiVCHIErAAIAACgIkrAAgACWBLIkrAAIAAieIErAAg");
	this.shape_3.setTransform(125.1,45.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_3},{t:this.main},{t:this.instance_2},{t:this.instance_1},{t:this.text_2},{t:this.text_1},{t:this.text},{t:this.instance},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(112.6,107.9,260.5,184);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;