(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 100,
	height: 100,
	fps: 12,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: []
};



lib.ssMetadata = [];


// symbols:



(lib.star = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFCC00").s().p("AgeAXIhAggIBIgNIAMhIIAhBAIBHgJIgxAyIAfBBIhBgfIgyAyg");
	this.shape.setTransform(9.5,9.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,19,19);


(lib.Shine2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.rf(["#FFFFFF","rgba(255,255,255,0)"],[0,1],-0.2,0,0,-0.2,0,21.9).s().p("AgODyIAAjJQAAgFgFAAIgSgXQgDgDgBAAIjFAAIAAgTIDFAAQACAAACgDIAUgXQADgDAAgCIAAjJIAXAAIAADJIAAAAQAAADADACIAUAYIAEACIDLAAIAAATIjLAAQgFAAAAAFIgSAVQgEAAAAAFIAADJg");
	this.shape.setTransform(0.3,0);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Layer 1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.rf(["#FFFFFF","rgba(255,255,255,0)"],[0,1],0.1,-2.3,0,0.1,-2.3,16.9).s().p("AgREJIAAjwIgbgcIj2AAIAAglID2AAIAbgeIAAjCIAmAAIAADCIAaAeID0AAIAAAlIj0AAIABAAIgbAcIAADwg");
	this.shape_1.setTransform(-0.1,2.3);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-29.3,-24.2,58.4,53.2);


(lib.coin = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.Shine2("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(12.5,16.6,0.62,0.62,0,0,0,-0.1,2.4);

	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("ACjgWIAAAuAiiASIABgp");
	this.shape.setTransform(16.3,10.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#000000").ss(1,1,1).p("ACiAZQgBAeguAWQgwAXhDAAQhCAAgwgXQgugWgBgeAihgWIAAgBQABgfAugWQAwgXBCAAQBDAAAwAXQAvAWAAAgIAAAAQgBAeguAWQgwAWhDAAQhCAAgwgWQgvgXAAgdg");
	this.shape_1.setTransform(16.4,10);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.rf(["#FFEFCC","#E8BD17"],[0,1],0.1,1.5,0,0.1,1.5,9.8).s().p("AhxA2QgwgXAAgfIAAAAQABgeAvgXQAvgWBCAAQBDAAAvAWQAwAXAAAeIAAAAQgBAfgvAXQgvAWhDAAQhCAAgvgWg");
	this.shape_2.setTransform(16.4,7.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.lf(["#E8BD17","#FFEFCC","#E8BD17"],[0.016,0.471,1],-16.3,0,16.3,0).s().p("AhxAnQgugWgCgdIgBgFIABgrQAAAfAwAXQAvAUBCAAQBEAAAvgUQAvgXAAgfIAAAwQgBAdguAWQgvAWhEABQhCgBgvgWg");
	this.shape_3.setTransform(16.3,13.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape},{t:this.instance}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-5.6,-1,39.3,34);


(lib.coins = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.coin("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(10.1,8.8,0.6,0.603,0,0,0,16.2,10);

	this.instance_1 = new lib.coin("synched",0);
	this.instance_1.parent = this;
	this.instance_1.setTransform(18,13.4,0.6,0.603,0,0,0,16.4,10);

	this.instance_2 = new lib.coin("synched",0);
	this.instance_2.parent = this;
	this.instance_2.setTransform(8.9,17.3,0.6,0.603,0,0,0,16.4,10.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_2},{t:this.instance_1},{t:this.instance}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-4.3,1.8,33,29.3);


// stage content:
(lib.thief = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.coins();
	this.instance.parent = this;
	this.instance.setTransform(77.1,78.1,0.775,0.764,0,0,0,10,9.3);

	this.instance_1 = new lib.coins();
	this.instance_1.parent = this;
	this.instance_1.setTransform(80.8,88.2,0.775,0.764,0,0,0,10.1,9.5);

	this.instance_2 = new lib.coins();
	this.instance_2.parent = this;
	this.instance_2.setTransform(62.1,80.3,0.775,0.764,0,0,0,10,9.3);

	this.instance_3 = new lib.coins();
	this.instance_3.parent = this;
	this.instance_3.setTransform(71.2,87.9,0.775,0.764,0,0,0,10,9.3);

	this.instance_4 = new lib.coins();
	this.instance_4.parent = this;
	this.instance_4.setTransform(54.7,87.1,0.775,0.764,0,0,0,10,9.3);

	this.instance_5 = new lib.star();
	this.instance_5.parent = this;
	this.instance_5.setTransform(51,83.6,1.207,1.191,0,0,0,5.9,13);

	this.instance_6 = new lib.star();
	this.instance_6.parent = this;
	this.instance_6.setTransform(81.8,80.6,1.207,1.191,0,0,0,6,13);

	this.instance_7 = new lib.star();
	this.instance_7.parent = this;
	this.instance_7.setTransform(61.3,77.6,1.207,1.191,0,0,0,6,13);

	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFCC00").ss(2,1,1).p("AABgyQgBAJgBAIQgCAGgHAEQgJAFgEADQgQALADAWQADAVANAIQALAGAMgFQAOgFAKgNQAKgOAAgQIgPAP");
	this.shape.setTransform(70.4,58.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#000000").ss(1,1,1).p("AiqAVIB+iYIDWhXIAAGeQACALgCAM");
	this.shape_1.setTransform(53.5,31.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#330000").ss(3.4,1,1).p("AiyB8QCQjvDVgI");
	this.shape_2.setTransform(53,20.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#996600").s().p("AhqCuQgQgLAAgNQAbhJAHgbIAJgmQAEgfABgdIABgLIAAgnIACgTQADghAAgYIACgBIAAgFIAAgBIAMACIAPABIAHAAIASABIATAAQAbAAASgCIANgCIAHgDQAAAGADAOQAJAOAJAcQAPAuAEAkIAAAGIADAPIABARQAJBRAAAVQACAsgQABQgGADgMABQguAAgHgPIgGAAQgDi9gMhOIgBAAQgBAAgBAFIgBASQAFAfAABAQAAATAHCRQAFAcgVAAIgIgBIgGACQgiACgfAEIgBABQgUgCgPgJg");
	this.shape_3.setTransform(15.9,68.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AhaCaIgBgBQgFgRgBgGIgCgVIgBgEQBPAEBNgIIACAeQACAFAAAKQg7AJg7AAIgggBgABNCBIgJgUQgDgDgBgGIAhgLIAAAAIAHgCIAAAAIASAkIgoARIgFgLgAgNBJIAKgzIAAgBIARgCIAcADIgLA4IgsgFgAhlA3IAaALIgaABgAhDA9IgGgCQgLgFgRgKIgDgCIgRgKIABgGIAGgXIAYAIIgOAJIAagGIAGACIADABIADABIADAAIANACIgQAqIgBgBgAg4gWIAMgfQgKANgHAPQgWgCgVgNIAAgBQAEgSAKgTQBIAcBGAAIADAgIAAAGIgTAAQgtAAgvgKgAA8gWIgDgdIAPgDIAAACIAEAYIABANIgQACIgBgJgAhDhtIAAAAIAEgDIAEgEIADgHIAEgEIAAAAIADgEIAEgEQAHgIAGgFIAHgEIAFgCIABABIgFAEIgBAAIgDAEIAAAHIABACIAFAKIAJAHQAGAEACACIABABIAAACIABACIABABIAKAAQAJAAAHgCQALgCAKgFIABACIAAACIgBABIACACIAHAIIACACIACADIABAAIAEAFQgVAEgUAAQgsAAgtgWgAAnhoIAAgBIAAAAgAAgh9IAAgBIABgGIABABIAAAAIAGAGIABACIABACIgKAEIAAgIg");
	this.shape_4.setTransform(17.6,32.7);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#101010").s().p("AgoCMIgWgBIgBgBIgeAAIgBAAIgFgOQBOADBIgMIAAAKQAAAOgTgBIgEAAQgRACgeAAIgVAAgABIBtIApgRIAMAVQAAABAAAAQgBABAAAAQAAAAgBABQAAAAgBABIgDAAIACABQgJAFgdAFQgCAAgJgTgAhtBKIgBgRIAAgVIAaAAIAMADIAWAFQAPADAUABIAhACIALAAIAQADIACASQg0AFg2AAIgygCgAA1BDIAAADIgBgBIAAgFIgBgJIAAgBIAJABIAbADIABAAIgiAMIgBgDgABdA0IAAAAIACAEIgHACQADgBACgFgAA+AyIgCAAIgJAAIgGgBIgUgCIgDAAIALg2IADABIABgBIAGABIAGAAIAFgBIAGAAIAFgBIAGAAIAHgBIADgBQADAAACAOQAFAEAAALIgBACIABAIIAAAAIgBAPIgBADIgBADIgCADIgYgDgAgxAmIgGgBIgRgFIgDgBIAPgoQAPABAUABIAGAAIAHgBIAAABIgKAxIgbgEgAhjgSIgZgIIAHgaIAEgSQAVANAWABIgCAEQgEAJgCAKIgCAPIgTgHIAAAHIAMAEIgbAGgAAFgOIgeABQgdABgSgEIgCgBIgBAAIACgKIAIgZIAAgBQA4ANA3gDIABAKQACAFAAAPIAAAAIgLABIghgCgAA0grIAQgCIABALIAAAIIABALIgKABIgGABQAAgKgCgUgAhjhtIAEgHIAKgSIAFgDIADgDQBCAfBAgNIABABQAEAIABAHIADAVIgPAEQgCgLgCgEIgBABIABAPQhGAAhIgdg");
	this.shape_5.setTransform(18.5,35.8);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#999999").s().p("AgJAiIgMgHIgKgKIAEABQgLgEgBgKIAAgDIgCgFIACgBIgBAAIgBgBIAAggIAAABIADgCIADABQAGADAFAAQAEAAADgDQAWAUAfAAIACABIAEAMQAAAAAAABQgBAAAAABQgBAAAAAAQgBABgBAAQgFAAgCACIAAAAIACACIABACQAAAEgGADIgGADIACAIQgFASgFAAQgNAAgKgGgAAQgCIgBACIABAAIADABQABAAAAAAQABgBAAAAQAAAAAAAAQAAAAAAAAIAKAAQgCgCgGgBIgGgBQAAAAAAAAQgBAAAAABQAAAAAAAAQAAAAAAABg");
	this.shape_6.setTransform(23.1,15.7);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("Ag6HIQgWgFgLgGQgGgDgIgIIgLgMQgXgRgDgEQgEgDAAgXIABgOQAAgFgCgEIgDgCIgFgDIgCgCIgBADQgFgKgHgHIAIgVQAfhXAGgvIAGg5IAAgNIABAAIgBgBIACgQIAAgIIABgFIABgCIAAgBIABgIIABgFIABgRIABgPIABgPQAAgPACgHIABgCIAAgBIAAAAIgCgBIAAgCQgEgDgEgPQgEgQgCgPIgBgRIAAgPIAAgUIAAgLIAAgBIAAgCIAAgCIgUgKIABgHIgGgDIACgJIALgwIAFgVQAKglAVgbIAUgOIgBgGQAAgEANgMQAMgMAJgBQACgDAFAAIAEABIAAgBIADABIAAABIABAAIAAABIgBAAQgFASgGAAIgBAAQABADAEAEQADAFANAIIAFAFQAQAAALgEIAAgDIACgRIgBgEIAAgCIABAAIABAAIAMAIQAMAGANAAQAFAAAFgSIgCgIIAGgDQAHgEgBgDIgBgCIgCgEIAAAAQACgCAFAAQABgBABAAQABAAAAgBQABAAAAgBQAAAAAAAAIgEgNIgCAAIAAgBIACAAIAAgBIAAAAIgBAAQgEgBAAgCIABgDQACgCAGAAIACACQAAABAAAAQgBABAAAAQgBAAgBAAQAAAAgBABIgDAAIAAAAQABAAABAAQAAAAABABQAAAAABAAQAAAAAAABIgBAAIAAABIABAAQAJAAAEgCQADgDAAgGQAAgIgKgJQghgBgggHQgvgKgwgZQAvAGAtAAIAAAAIAcAAIAWgBIAKgBIAAAAIgCgFIgGgIIACgBQALAKAAAUIAAAAIADASQAMAMAAAJQgCAQgLAAIgFgCIACAFIACAIIgBADQgCACgGABQAEALgOAFIACAHIgEAKQgFAMgHAAQgHAAgKgEQgGgBgFgCIAHAJQAFAJABAEIAIAGIAIAJIAEAKIACAKIAAAAIABACIABAEIABAEQACAMABAWIAAAAIAHAuIAFgBQADAAAEAHIACgCIABgCIAHgIIABgBIAAAAIABgBIAAAAQAPgPAEAAQASABACAIIAKgBIAPAFIANAFIAAACIABAAQADADAAAEIgBAEQAAAAAAABQAAAAgBABQAAAAgBAAQAAABgBAAIgBABIgDAAIgBABIACADQAEAFAAAGQAAACgEAFQgEAFgDAAIgBAAIABAAQAAABABAAQAAABAAAAQABAAAAABQAAAAAAABIAAADIgBAGIgCACIAAAAIAAACIgDABIgCAAIAAAAIgEgBIAAAAIADACIAAACIADADIACAGIgBACIAAADQgCADgFABIAAgBIgBABIgBAAIAAABIgUgJQgGgDgRACQgFABgFgDIgDgBIAIAQIAWAvQAAAEgDADQAKAFAKAWQAJATADANIAAAAQACAFAAARQABAcgRAAQgFABAAgIIAAAAQgEABgFAAQgFAAAAgHIAAgCQgFgDgFAAIAAgDIACgLIgGABIgCAAQAAgKgJgUQgJgUgDgNIgLABIgCgEIgBgEIAAAAIgBAAIgTgmIgBALIADAfIAAACIAAADIgEADIAAACIgBgBIgCACIAAAAIAAABQAAABAAAAQAAABABABQAAAAAAABQABAAAAAAQAWAuARBhQAVBygIA+QgBAGgKAEIAKADIARAFIAGgCQAGgDAOAAQASAAAJAQQAFAJAAAKQAAAPgFAHQgQAUgyAAQgNAAgOgEIgLgEQgSgEgSgBIAEAFQAEAFAAAOQAAAHgCAGIAAABIgJAOQgHAIgKAFIgCABIgEACIgFABIgMABIgFACQgPgBgRgDgAiKF6QAAAMAGAKQACACAUASQANANAJAGQAbAPAoAAQAVAAALgNQAFgFADgIIAAAAQAEgGABgMQAAgPgWgLQgJgGgIgCQgHgEgCgCIgKgLIgFgDQgvAJgmgFIgMgDIgCAVgAATGvIABgCIgBAAIAAACgAAXF+QAVAAAVAFQAVAHAKAAQAtAAAOgQQAGgFAAgOQAAgHgEgIQgHgNgPAAIgPACIgKACQgHAAgGgDIgIgEIgRgEIgFgCQgOABgXgDQgWgBgLgFIAAAiIgFABIgBACIgFASIABADIAAAAIADACIACABIAAAAIAHACIAOAGIAAAAIABAAIAAAAIAEgBIAFAAgAgVFuIADACIACgHIABgGIACgFIgNADIgDAAIgHABIACABIABABIAIAFIAEAEIgBgBIABACgAhngLIAAAFIgCABQAAAWgDAhIgCATIgBAnIAAALQgCAdgDAhIgKAmQgHAbgbBJQAAANAQALQAPAJAVACIAGAAIgGgBQAfgEAigCIAJgCIAIABQAUAAgFgcQgHiRAAgVQAAhAgFgfIACgSQAAgFABAAIABAAQANBOADC/IAEAAQAHAPAtAAQAMgBAGgDQAQgBgBgsQAAgVgJhTIgBgRIgDgPIgBgGQgEgkgPguQgJgcgIgOQgEgMAAgGIgGADIgOACQgPACgbAAIgVAAIgSgBIgIAAIgPgBIgLgCIAAABgACGA+IgBAGIADABQAIgGABgTQgEAMgHAGgAB9ATQAFAHAAABQAAAKgEALQgFAKAAACQAAABAAABQAAAAAAABQAAAAAAAAQAAAAAAgBQAIAAAIgNQAGgLAAgHIgBgIIgDgJIgHgOIABAAIADACIgCgDIgCgEQgJgWgKgIQgFAEgKAEIgTAGIAMAWQALAWABALIACAAQACgfAEgMIADACIAAARIACADIABAAIAAgBQADABAFAGgAB7AcIABACQAAAEgIASIABAAIADgGQAFgLAAgIIgGgJIgBABIgBAAIgCgCQABAIgBAFIAAAAQgBAIgFAKQAAABAAABQAAAAAAABQAAAAAAAAQAAAAAAAAIACAAQgBgFAEgGIAHgNgAh5h3IAAAVIABARIABAFIABAUQABAHAGAQIABACIAFAOIABAAIAeAAIABABIAWABIAVAAQAeAAARgCIAEAAQATABAAgOIAAgKQAAgKgCgFIgCgdIgCgSIgQgDIgLAAIghgCQgUgBgPgDIgWgFIgMgDIgagLgAAlgQIABAAIgBAAgAArhVQACAFADADIAJAVIAEAKQAJATACAAQAdgFAJgFIgCgBIADAAQABgBAAAAQABgBAAAAQAAAAABgBQAAAAAAgBIgMgVIgSgkIAAAAIgCgEIAAAAQgCAFgDABIAAAAIgBAAIgbgDIgJgBIAAABIABAJIAAAFIABABIAAgDIABADgABWh+IgBAKIACAAQAJAHAFAAQASAAAQAEIAHAEIAFABIAAAAIADgCIAAgBIgBgDIgBAAIAAgCQgKgFAAgEQAAgBAAgBQAAgBAAAAQABgBAAAAQAAAAAAAAIAKAAIACAAIAAgBIACgBIACgCIAAgBIgBgBIAAgBIgBgCIgMgGQAEgCAFAAIAHABIAAABIAEgFQADgCAAgCIAAgCIgCAAIgCgCIgCgCIAAgBQgSgHAAgBIAAgDQAIgCAEAAIAKACIACAAIAAAAIABgCIACgEIgCAAIgBgCIgBAAIgMgGQgIgDgEgBIgOADQgIABgTAIIgMAGIAAABQgEADAAAFQABABAAABQAAAAAAABQABAAAAABQAAAAAAABQACADAAAJIgBAAIABALgAgolWIgGACIgGAEQgHAGgGAHIgEAEIgEAEIAAAAIgDAFIgEAGIgDAFIgFACIAAAAIgDADIgFADIgKASIgEAHQgLATgDATIAAABIgEASIgHAaIgGAXIgBAGIASAKIADACQARALALAEIAGACIABABIADABIARAFIAGABIAbAEIAsAFIADAAIAUACIAGABIAJAAIACAAIAYADIACgDIABgDIABgDIABgPIAAAAIgBgIIABgCQAAgLgFgEQgCgQgDAAIgDABIgHABIgGAAIgFABIgGAAIgFABIgGAAIgGgBIgBABIgDgBIgagCIgTABIgHABIgGAAQgUgBgPgBIgMgCIgEAAIgCgBIgDgBIgGgBIgMgEIAAgHIATAHIACgPQACgKAEgJIACgEQAGgPALgNIgMAfIAAABIgIAZIgCAKIABAAIACABQASAEAdgBIAggBIAfACIALgBIAAAAQAAgPgCgFIgBgKIAAgGIgDgfIgBgPIABgBQACAEACALIAEAdIABAJQACAUAAAKIAGgBIAKgBIgBgLIAAgIIgBgLIgBgOIgEgYIgBgCIgDgVQgBgHgEgIIgBgBIgDgEIgBgBIgCgDIgCgCIgHgIIgCgBIAAgCIAAgBIAAgDQgKAGgLABQgGACgIAAIgMAAIgCgBIAAgCIAAgBIgCgBQgBgDgGgEIgJgHIgFgKIgBgBIAAgIIADgDIAAAAIAGgFIAAABIgEAMQAFgHADgHIgFAAgABYirIgBADIAZgOQADgCAGgBQgGgFgEAAQgFAAgSATgAAMk6IAAABIAAAIIAKgDIgBgDIgCgCIgFgGIAAABIgBgBIgBAFgAAzmqIgEAHIADACIAKABQAFgJgCgEIgEgEQgFABgDAGgAASkkIABAAIAAAAgAAzllIgCgCIABgBQAAgBAAAAQAAAAABgBQAAAAAAAAQAAAAABAAIAFABQAGABACABIgKABQAAABAAAAQAAABAAAAQAAAAAAAAQgBABAAAAIgDgCgAgQmDIACgJIABABIgBgDQgBgEgDgCQgFAHgBAGIADAHQgDAAgBgEIgBgHIACgGQADgFADAAQADAAACAEIACAGQAAAEgCACIAAAEQAAAAAAABQAAAAAAABQABAAAAABQABAAAAABIADADIgDABQgFAAAAgJg");
	this.shape_7.setTransform(19.6,51.5);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFE1C4").s().p("ABJEMIABgGQAGgFAFgNQgCATgHAGgAA8EEQAAgCAFgKQAFgKAAgKQAAgCgGgGQgFgHgDgBIAAABIgCgCIgBgTIgCgDQgFAOgCAgIgBAAQgCgMgLgWIgMgYIATgGQALgEAFgDQAJAIAKAVIACAFIgBAAIgCACIAHAOIAEAJIABAIQAAAHgHALQgHANgIAAIgBABIAAgDgAA3D8QAIgRAAgFIAAgCIgCAAIgHAMQgEAHAAAEIgBAAQAAAAAAAAQgBAAAAAAQAAAAAAgBQAAgBAAgBQAFgKACgIIgBAAQABgFgBgHIACACIACAAIAAgBIAHAJQAAAHgFALIgDAGIgCAAgABSBhIgHgDQgQgFgTAAQgFAAgJgGIgBAAIAAgKIAAgMIAAAAQAAgIgCgEQAAAAAAgBQAAgBAAAAQAAgBgBAAQAAgBAAAAQAAgGAEgDIAAAAIALgGQAUgJAIAAIAOgDQAEAAAIADIAMAGIAAAAIACACIABABIgBADIgBACIgBAAIgBAAIgKgCQgFAAgHADIAAACQAAABARAIIABABIABABIACACIACAAIAAACQAAACgCADIgFAEIAAgBIgHgBQgFAAgEACIANAGIAAACIABABIAAABIAAACIgBABIgCABIgBABIgBAAIgKAAQgBAAAAAAQAAABAAAAQAAABAAAAQAAABAAABQAAAEAJAGIABABIAAABIACACIAAABIgDACIgBABIgEgCgAAbAbQATgTAFAAQADAAAHAFQgGABgEACIgYAOIAAgDgAhQhkIgEgFQgNgIgDgFQgEgEgBgCIAAAAQAGAAAFgTIABAAIAAgBIAAAAIAAgBIAAgBQACgCACgHIADgPIAAAAQAHAIAIABIAFgCIABAAIgCABIABAHIABADQABAKALAEIgEgBIAJAKIAAAAIgBAAIgBABIACAEIgCASIAAADQgMADgOAAIgEAAgAhEikIAAAAQgMAAgHgLQgFgIAAgFQAAgHAEgJQAFgNAJAAQAKAAgBAKIgBAHIAAAAIgBABIAAABIAAACIAAAgIAAAAgAhNi7QAAAKAGAAIACgCIgCgDQgBgBAAAAQgBgBAAAAQAAgBgBAAQAAAAAAgBIABgEQACgBAAgEIgCgGQgCgFgDAAQgEAAgDAFIgBAGIAAAHQACAEACABIgCgIQAAgGAFgHQAEACABAEIAAADIgBAAIgCAIgAgrjEIABgCIABgFIgBgKQAgAGAfABQAKAJAAAIQAAAGgEADQgDACgJAAIgBAAIAAgBIABAAQAAAAgBgBQAAAAgBAAQAAAAgBAAQgBgBgBAAIAAAAIADAAQABAAABgBQABAAAAAAQABAAAAgBQABAAAAAAIgCgCQgGAAgCACIgBACQAAADAEAAIAAABIAAAAIgBABIAAAAQgdAAgYgUgAgujzIABgCIAAACgAgFj3IACAAIABAAIABAAIAEADIgUABQAGgEAGAAgAAMj1IgCgFQgDgFgDgCIAAgBIAGAIIADAFIgBAAgAgJkMIgFAJIgDABIAIgKg");
	this.shape_8.setTransform(25.7,31.5);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#663300").s().p("AhiHVQgKgFgNgOQgUgRgCgDQgGgJAAgMIADgVIAMADQAlAEAvgJIAFAEIALAKQABACAHAEQAIACALAGQAUAMAAAOQgBANgEAFIAAAAQgDAIgFAGQgIAMgYAAQgoAAgagPgAA2GiQgVgGgVAAIgFAAIgEABIAAAAIgBAAIAAAAIgNgGIgHgCIgBAAIgBgBIgEgCIAAAAIgBgCIAFgSIABgDIAFgBIAAghQANAEAUABQAXADAOAAIAGABIAQAEIAIAEQAHADAGAAIAKgCIAQgBQAOAAAHAMQAEAIAAAHQAAAOgGAGQgOAPgtAAQgJAAgWgGgAgvk8QgFgZgYgaQgKgMgCgOQAAgRgBgIQAvAZAwAKIABAKIgBAFIgBACQgDADgCAAQgFAAgGgDIgEgBIgCACIAAgBIAAgCIAAgBIAAgBIABAAIAAgHQABgKgJAAQgJAAgFANQgFAJAAAHQAAAFAGAIQAHALAMAAIAAAAIABAAIAAAAIAAABIgEACQgJgBgGgIIgBgCIAAABIABABIgDAPQgCAHgCACIgBABgAhlmcIAAAAQAAgNALgLQALgNAWgIIgCgKIABgEQACgEADAAQADAAADAIIAHgKQAFgGADAAIACAAQgBAGgGAJQAEgFANgEQAOgFALAAQAPAAAUAGQATAFADAGIAGAFQAEAGAAAEQAAAHgNALIgDADIAAAAIgCABIAAABQACACAEAFIACAFIgJABIgHgDIgBAAIgBAAIgBAAQgGAAgHAEIgcAAIABgCIgBACQgtAAgugFQgIAHgCAAIgCgBgAAfmsIADgBIAEgJIgHAKg");
	this.shape_9.setTransform(20.7,48.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape},{t:this.instance_7},{t:this.instance_6},{t:this.instance_5},{t:this.instance_4},{t:this.instance_3},{t:this.instance_2},{t:this.instance_1},{t:this.instance}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(52.5,50,95,104.6);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;