<?php


$array = [
     'quizq1' => 'Ai primit mesaj de la o persoana care pretinde ca este voluntar. Această persoană spune că logarea Dumneavoastră este blocată și ca să vă rezolve problema trebuie sa îi furnizați parola și e-mail-ul, dacă nu le ve-ți furniza logarea Dumneavoastră va rămâne blocată. Ce vei face?',
     'quizq1a1' => 'Nu le furniza nici o informație!',
     'quizq1a2' => 'Nu dorești să-ți pierzi logarea '. XAT_NAME .', deci le furnizezi informațiile cerute.',
     'quizq1a3' => 'Întreabă-i dacă intr-adevăr ei sunt voluntari, să-ți demonstreze!',
     'quizq1info' => 'Corect! Echipa '. XAT_NAME .' și voluntarii niciodată nu o să întrebe informații personale în privat. Raportati utilizatorul adaugand dovezi cu poze la conversatie si numarul contului (ID) apoi deschideti un ticket sub raporteaza scam (Report Scam).',
     'quizq1image' => '<br img src="https://util.'. DOMAIN .'/wiki/images/f/f9/Securityimage1.png" class="img-fluid"/>',
     'quizq2' => 'Ești pe Chat-ul de Trade încercând să cumperi days-uri. Și persoana respectiva îți spune să transferi '. XAT_NAME .'s-ii întâi. Ce vei face?',
     'quizq2a1' => 'Refuzati și îi sugerezi să folosească Aplicația Comerț (Safe Trade în engleză) care este cea mai sigură metodă și recomandată.',
     'quizq2a2' => 'Faci întâi transferul de '. XAT_NAME .'s.',
     'quizq2a3' => 'Cereti zilele intai.',
     'quizq2info' => 'Perfect! De fiecare dată când cumperi și vinzi '. XAT_NAME .'s, days sau powers trebuie să folosești aplicația cea mai sigură Safe Trade. Prin aceasta aplicatie puteti vedea in timp real ce vindeti sau cumparati. Niciodată să nu folosiți trade prin Transfer deoarece nu poate fi anulată după finalizare.',
     'quizq2image' => '<br img src="https://util.'. DOMAIN .'/wiki/images/c/c0/Securityimage2.png" class="img-fluid"/>',
     'quizq3' => 'E-mail-ul tău oferă 2-factori de protecție. Ar trebui sa actiati aceasta optiune?',
     'quizq3a1' => 'Da. Aceasta o să aibe o protecție majoră asupra adresei de e-mail.',
     'quizq3a2' => 'Nu. Parola mea este destul de complexă.',
     'quizq3a3' => 'Niciodata. Această protecție este nefolositoare.',
     'quizq3info' => 'Corect! Corect! 2-factor2 de autentificare în adresa de e-mail vor adăuga un alt rând de securizare (prin telefon) pentru siguranța că nimeni nu va mai avea acces e-mail-ul Dumneavoastră chiar dacă parola este spartă.<br><br>Va rugam sa contactati furnizorul dvs pentru mai multe informatii despre activarea acestuia. Pentru deținatorii de Gmail urmariți link-ul <a href="https://www.google.com/landing/2step/" target="_blank">sau pagina</a>.',
     'quizq3image' => '<br img src="https://util.'. DOMAIN .'/wiki/images/7/71/Securityimage3.png" class="img-fluid"/>',
     'quizq4' => 'Vi se aduce la cunostiinta o imbunatatire a paginii de login. Userul va trimite un link pentru a testa https://xaatt.com/login. Ce vei face?',
     'quizq4a1' => 'Nu dai click pe acel link pentru că nu este un https://'. DOMAIN .' domeniu.',
     'quizq4a2' => 'Dai click și vezi ce sa schimbat.',
     'quizq4info' => 'Corect! Mereu să verifici că bara de adresă <a href="https://'. DOMAIN .'" target="_blank">https://'. DOMAIN .'</a> a domeniului înainte de a te loga sau de a vizita un chat, să nu introduci nici o informație fară să verifici în prealabil.',
     'quizq4image' => '<br img src="https://util.'. DOMAIN .'/wiki/images/7/7d/Securityimage4.png" class="img-fluid"/>',
     'quizq5' => 'Un user se ofera sa va dubleze puterile dar inainte trebuie sa ii oferiti puterile dvs inainte. Ce vei face?',
     'quizq5a1' => 'Puterile nu pot sa fie dublate. Nu ii oferiti puterile.',
     'quizq5a2' => 'Acceptati oferta. Puteri duble inseamna profit dublu.',
     'quizq5a3' => 'Cere probe doveditoare că ei pot dubla puterile tale.',
     'quizq5info' => 'Foarte bine! '. XAT_NAME .'s, zilele si puterile nu pot sa fie dublate. Hotii deseori utilizeaza o astfel de tactica pentru a va atrage atentia si a va fura lucrurile. Raportati utilizatorul adaugand dovezi cu poze la conversatie si numarul contului (ID) apoi deschideti un ticket sub raporteaza scam (Report Scam).',
     'quizq5image' => '<br img src="https://util.'. DOMAIN .'/wiki/images/3/35/Securityimage5.png" class="img-fluid"/>',
     'quizq6' => 'Vei primi un e-mail de la info@'. DOMAIN .' spunând că puterile tale trebuiesc verificate manual de un angajat de '. XAT_NAME .'. Intrucțiunile spun că trebuie să faci comerț cu o anumita persoană. Dacă vei refuza să faci comerțul, logarea ta va fi blocată 3 luni. Ce vei face?',
     'quizq6a1' => 'Ignorati mesajul si raportati mailul ca spam.',
     'quizq6a2' => 'Acceptati fara intrebari. Nu ma blocati, va rog!',
     'quizq6a3' => 'Răspunzi la acel e-mail cerând mai multe informații.',
     'quizq6info' => 'Perfect! Tu nu vei primi niciodata un astfel de e-mail de la '. XAT_NAME .'. Toate notificarile privind contul dvs de '. XAT_NAME .' sunt oferite prin sistemul de suport la <a href="https://'. DOMAIN .'/ticket" target="_blank">'. DOMAIN .'/ticket</a> si nu nicaieri altundeva.',
     'quizq6image' => '<br img src="https://util.'. DOMAIN .'/wiki/images/3/3b/Securityimage6.png" class="img-fluid"/>',
     'quizq7' => 'Toată lumea știe că parolele sunt greu de reținut. Ca sa va asigurati ca va este mai usor , decideti sa folositi aceeasi parola pentru e-mail si contul de '. XAT_NAME .'. Este aceasta o siguranță?',
     'quizq7a1' => 'Nu!',
     'quizq7a2' => 'Desigur ca da. Asa va asigurati ca nu o sa uitati parola.',
     'quizq7info' => 'Aveți dreptate! Siguranța este pe primul loc. Întotdeauna utilizați parole diferite la conturile dvs online.',
     'quizq7image' => '<br img src="https://util.'. DOMAIN .'/wiki/images/2/2b/Securityimage7.png" class="img-fluid"/>',
     'quizq8' => 'Ai invățat că se pot genera '. XAT_NAME .'s gratis dar trebuie să instalezi un program. Ce vei face?',
     'quizq8a1' => 'Știi bine că nu se pot genera gratis '. XAT_NAME .'s, deci ignori.',
     'quizq8a2' => 'Ceri mai multe informații.',
     'quizq8a3' => 'Cereti dovada cum ca '. XAT_NAME .'s pot fi generati.',
     'quizq8info' => 'Ai perfectă dreptate! '. XAT_NAME .'s nu pot fi generați gratis! Fii foarte atent nu descărca nici un program aceaste programe pot fi periculoase si dăunatoare (infectate cu viruși).',
     'quizq8image' => '<br img src="https://util.'. DOMAIN .'/wiki/images/5/5c/Securityimage8.png" class="img-fluid"/>',
     'quizq9' => 'Ai primit un mesaj spunând că logarea ta va fi blocată în 24h dacă nu achiți 10000 '. XAT_NAME .'s. Ce vei face?',
     'quizq9a1' => 'Nu trimiți '. XAT_NAME .'s și ignori utilizatorul.',
     'quizq9a2' => 'Blocată? Nici gând! Voi plăti suma cerută.',
     'quizq9a3' => 'Ceri explicații.',
     'quizq9info' => 'Corect! Angajații '. XAT_NAME .' și voluntarii nu vor cere niciodată '. XAT_NAME .'s. Raportati utilizatorul adaugand dovezi cu poze la conversatie si numarul contului (ID) apoi deschideti un ticket sub raporteaza scam (Report Scam).',
     'quizq9image' => '<br img src="https://util.'. DOMAIN .'/wiki/images/b/b4/Securityimage9.png" class="img-fluid"/>',
     'quizq10' => 'Vi se oferă o sumă destul de mare de '. XAT_NAME .'s pentru powers Dumneavoastră gen 50000 '. XAT_NAME .'s. Pe durata Trade, sunt mai multe incercari eșuate din cauza greșelilor a parolei și diverse erori. Ce vei face?',
     'quizq10a1' => 'Cu stima și respect pentru user îi scrii ca vei reseta trade.',
     'quizq10a2' => 'Ignori problema și continui trade.',
     'quizq10a3' => 'Ignori userul.',
     'quizq10info' => 'Corect! Hotii vor incerca sa va fure '. XAT_NAME .'s, zilele si puterile, prin schimbarea cantitatii de '. XAT_NAME .'s, zile sau puteri in aplicatia.<br><br>Intotdeauna aveti grija si verificati de doua ori dupa fiecare tranzactie esuata. Este mai sigur sa va asigurati inainte de a confirma tranzactia.',
     'quizq10image' => '<br img src="https://util.'. DOMAIN .'/wiki/images/a/a2/Securityimage10.png" class="img-fluid"/>',
     'quizq11' => 'Primești mesaj pe forum un mesaj privat de la o persoană care pretinde că este un angajat '. XAT_NAME .'. În mesajul respectiv ești întrebat de detaliile tale de logare (parolă și e-mail), întrucât dacă nu le vei furniza riști ca logarea ta să fie blocată de '. XAT_NAME .'. Ce vei face?',
     'quizq11a1' => 'Ignori utilizatorul și ii faci reclamație la un angajat din echipa de forum.',
     'quizq11a2' => 'Raspunzi la mesaj dând informațiile cerute de angajat.',
     'quizq11a3' => 'Cereti mai multe informatii.',
     'quizq11info' => 'Corect! Personalul '. XAT_NAME .'ului si voluntarii nu va vor contacta niciodata prin in privat in legatura cu problemele legate de '. XAT_NAME .' inclusiv in legatura cu blocarea unui cont. Toate problemele sunt rezolvate prin suport <a href="https://'. DOMAIN .'/ticket" target="_blank">'. DOMAIN .'/ticket</a> iar dvs trebuie sa raportati mesajele inapropiate si daunatoare.',
     'quizq11image' => '<br img src="https://util.'. DOMAIN .'/wiki/images/7/7a/Securityimage11.png" class="img-fluid"/>',
     'quizq12' => 'Ți sa spus pe un anumit chat de la un angajat '. XAT_NAME .' să dezactivați 2-factori de autentificare a protecției adresei de e-mail. Ce vei face?',
     'quizq12a1' => 'Refuzati si ignori persoana.',
     'quizq12a2' => 'Dezactivezi 2-factori de autentificare.',
     'quizq12info' => 'Da, ai drepatete! Angajații '. XAT_NAME .' și voluntarii nu o să îți ceară niciodată să dezactivezi 2-factor de autentificare a protecției în nici un caz. Nu ezitati sa raportati utilizatorii care incearca sa va faca sa dezactivati protectia contului dvs.',
     'quizq12image' => '<br img src="https://util.'. DOMAIN .'/wiki/images/4/45/Securityimage12.png" class="img-fluid"/>',
     'quizq13' => 'Cineva va spune despre o pagina pe un site care are un generator gratuit de '. XAT_NAME .'s .Dar ca sa obtineti '. XAT_NAME .'s trebuie sa va logati cu adresamail si parola. Ce faci tu?',
     'quizq13a1' => 'Ignori site-ul pentru că tu știi că '. XAT_NAME .'s nu pot fi generați gratis.',
     'quizq13a2' => 'Mergeți mai departe și vă logați!',
     'quizq13a3' => 'Cereti dovada cum ca '. XAT_NAME .'s pot fi generati.',
     'quizq13info' => 'Ai perfectă dreptate! '. XAT_NAME .'s nu pot fi generați gratis! Este recomandat sa va logati cu parola doar pe site-ul oficial <a href="https://'. DOMAIN .'" target="_blank">https://'. DOMAIN .'</a> paginii. Always check the address to make sure it is <a href="https://'. DOMAIN .'" target="_blank">'. DOMAIN .'</a>.',
     'quizq13image' => '<br img src="https://util.'. DOMAIN .'/wiki/images/5/57/Securityimage13.png" class="img-fluid"/>',
     'quizq14' => 'Tu ai negociat o afacere ca să cumperi puteri de la un user de pe Trade. Utilizatorul va spune ca o sa va dea jumatate din puteri acum iar cealalta jumatate mai tarziu. Ce vei face?',
     'quizq14a1' => 'Refuzati oferta, utilizatorul trebuie sa puna tot ce a oferit intr-o singura tranzactie.',
     'quizq14a2' => 'Acceptati oferta. Nu pare nimic in neregula.',
     'quizq14a3' => 'Cereti dovada ca userul are si cealalta jumatate de puteri.',
     'quizq14info' => 'Corect! Escrocii vor încerca să te păcălească oferindu-ți o sumă înainte si apoi promițându-ți că îți vor da restul pe viitor. Niciodata sa nu crezi acesti utilizatori si accepta numai plata completa in trade. Utilizatorul este puțin probabil să se întoarcă după aceea.',
     'quizq14image' => '<br img src="https://util.'. DOMAIN .'/wiki/images/5/59/Securityimage14.png" class="img-fluid"/>',
     'quizq15' => 'Ți sa spus de un program gratis de făcut avatare (gif-uri). O anumită persoană de pe chat îți trimite link-ul să îl descarci dar este un site anonim. Ce vei face?',
     'quizq15a1' => 'Niciodata nu descarcati, programul poate contine virusi.',
     'quizq15a2' => 'Il descarcati.',
     'quizq15info' => 'Corect! Hotii va vor tenta sa va dea virusii lor, sub pretextul ca vor sa va ajute. Aveti grija sa nu descarcati fisiere/programe necunoscute. Cateva indicii pentru a descoperi o pagina virusata:<br><br ol><li>Caută numele programului de descărcat pe Google (programul dacă există se va găsi și pe google).</li><li>Verificati surse alternative pentru a descarca.</li><li>Scanati cu un anivirus fisierele.</li></ol>',
     'quizq15image' => '<br img src="https://util.'. DOMAIN .'/wiki/images/1/19/Securityimage15.png" class="img-fluid"/>',
     'quizq16' => 'O anumită persoană pe care ai întâlnit-o pe chat îți cere numele tău, adresa și e-mail-ul. Ce vei face?',
     'quizq16a1' => 'Schimbi subiectul spunând că nu dorești să vorbești despre informații personale.',
     'quizq16a2' => 'Ei par a fi destul cool, asa ca dai raspuns la intrebarile lor cu informatii tale reale.',
     'quizq16a3' => 'Ignori userul.',
     'quizq16info' => 'Foarte bine! Nu ar trebui sa va oferiti nimanui informatiile personale online. Niciodată să nu divulgi adresa de e-mail sau parola!',
     'quizq16image' => '<br img src="https://util.'. DOMAIN .'/wiki/images/d/d9/Securityimage16.png" class="img-fluid"/>',
     'quizq17' => 'Ai primit o notificare pe chat că logarea ta are probleme și ca să rezolvi problema trebuie să închizi protecția de pe pagina unde te loghezi. Ce vei face?',
     'quizq17a1' => 'Niciodată să nu îți închizi protecția când cineva o va cere.',
     'quizq17a2' => 'Ai încredere în străin. Te loghezi și îți dezactivezi protecția.',
     'quizq17a3' => 'Îi întrebi să îți explice de ce trebuie să îți dezactivezi protecția.',
     'quizq17info' => 'Corect! Protectia contului dvs nu trebuie dezactivata sub nici o circumstanta. Angajatii '. XAT_NAME .'ului sau voluntarii nu va vor cere niciodata sa va dezactivati protectia.',
     'quizq17image' => '<br img src="https://util.'. DOMAIN .'/wiki/images/a/ab/Securityimage17.png" class="img-fluid"/>',
     'quizq18' => 'Un prieten va cere imprumut puterea namecolor pentru scurt timp, pentru ca vor sa ii testeze efectele. Ce vei face?',
     'quizq18a1' => 'Nu-l da deoparte. Există o șansă că nu o veți primi înapoi.',
     'quizq18a2' => 'Da e bine îl dai. Poți avea powers-ul când dorești înapoi.',
     'quizq18a3' => 'Cei mai buni prieteni pentru totdeauna. Faci trade fara sa te gandești o secunda!',
     'quizq18info' => 'Perfect! '. XAT_NAME .'s tăi, days și powers sunt responsabilitatea ta. '. XAT_NAME .'s tăi, days și powers sunt responsabilitatea ta. Dacă ai finalizat o afacere, trade nu poate fi anulată. Fii foarte atent de fiecare dată. <a href="//util.'. DOMAIN .'/wiki/index.php?title=Special:MyLanguage/Trading" target="_blank">Citește mai multe aici.</a>',
     'quizq18image' => '<br img src="https://util.'. DOMAIN .'/wiki/images/1/17/Securityimage18.png" class="img-fluid"/>',
     'quizq19' => 'Vei primi un e-mail de la info@'. DOMAIN .', care va arata ca tocmai ati cumparat cu succes 100000 de '. XAT_NAME .'s. De asemenea trebuie sa confirmi plata apasand click pe un link. Linkul va redirectioneaza catre o pagina in care trebuie sa platiti 100$ pentru a primi in cele din urma '. XAT_NAME .'s. Ce vei face?',
     'quizq19a1' => 'Aceasta este o oferta ciudata. Daca am cumparat cu succes '. XAT_NAME .'s, de ce trebuie sa platesc mai mult? Blocati e-mailul deoarece este o inselatorie (scam).',
     'quizq19a2' => 'E-mailul vine de la info@'. DOMAIN .', dar 100$ sunt o multime de bani. Raspunde-ti si cereti mai multe informatii.',
     'quizq19a3' => 'Nu am intentionat sa cumpar '. XAT_NAME .'s, dar 100000 '. XAT_NAME .'s pentru 100 de dolari este o afacere buna. Du-te!',
     'quizq19info' => 'Corect! '. XAT_NAME .' NICIODATA nu va va cere sa cumparati '. XAT_NAME .'s intr-un mail, singurul loc sigur unde puteti cumpara '. XAT_NAME .'s cu bani reali este <a href="https://'. DOMAIN .'/buy">https://'. DOMAIN .'/buy</a>. Unii escroci (scammers) sunt capabili sa falsifice adresele de e-mail '. XAT_NAME .', deci nu ar trebui sa procedati niciodata chiar daca se afiseaza info@'. DOMAIN .'. Cu toate acestea, daca acordul pare a fi prea bun pentru a fi adevarat, aceasta este, de obicei si este foarte probabil sa fi scamat.',
     'quizq19image' => '<br img src="https://util.'. DOMAIN .'/wiki/images/f/fe/Securityimage19.png" class="img-fluid"/>',
     'start' => 'incepe chestionarul',
     'desc' => 'Pentru a obține <a href="//util.'. DOMAIN .'/wiki/index.php?title=Special:MyLanguage/Tickle" target="_blank">Tickle</a> power gratis, ai nevoie să completati quiz-ul de mai jos și să răspundeți corect la fiecare din întrebari.',
     'wronganswer' => 'Acest răspuns este greșit. Mai încearcă odată.',
     'next' => 'următorul',
     'continuein' => 'Continua în',
     'gratz' => 'Felicitari, ati completat acest quiz! Acum aveti mai multe cunostinte despre siguranta pe '. XAT_NAME .'.',
     'tickle' => 'Ati primit puterea Tickle.',
     'redirect' => 'Va rugam sa asteptati pana o sa fiti trimis pe pagina de login.'
	 ]
?>