<?php
$array = [
     'groups' => 'Gruplar',
     'store' => 'Stok',
     'buyxats' => 'xats days satin al',
     'powers' => 'Gücler',
     'xavi' => 'xaviler',
     'xatgroup' => ''.XAT_NAME.' grup',
     'shortname' => 'Kisa isim',
     'promotion' => 'Tanitim',
     'auctions' => 'Acik artirmalar',
     'community' => 'Topluluk',
     'more' => 'Daha fazla',
     'twitter' => 'Twitter',
     'wiki' => 'Wiki',
     'support' => 'Destek',
     'contact' => 'Iletisim',
     'help' => 'Yardım',
     'trade' => 'Trade',
     'widgets' => 'Widgets',
     'login' => 'Login',
     'language' => 'Dil',
     'privacy' => 'Mahremiyet',
     'terms' => 'Sartlar',
     'safety' => 'Güvenlik',
     'failed' => 'başarısız',
     'evalid' => 'gecersiz e-posta',
     'recaperr' => 'reCAPTCHA dogru girilmedi. Lütfen tekrar dene. (reCAPTCHA dedi',
     'notbot' => 've bot olmadigini dogrulamak icin',
     'numinbox' => 'Lütfen bu numarayi kutuya gir',
     'cancel' => 'Iptal',
     'submit' => 'Gönder',
     'wrongnum' => 'Yanlis numara girildi!',
     'ayaherr' => 'Insan oldugunu kanitlaman gerekiyor'
	 ]
?>