<?php
$array = [
     'quizq1' => 'Volunteer oldugunu iddia eden bir kisiden mesaj alacaksin. Bu kisi hesabinin bloke edildigini ve bu sorunu cözmek icin senden sifreni ve e-posta adresini isteyecektir, aksi halde blokenin kalici oldugunu söyler. Ne yapman gerekiyor?',
     'quizq1a1' => 'Onlara herhangi bir bilgi verme.',
     'quizq1a2' => ''.XAT_NAME.' hesabini kaybetmek istemiyorsun, böylelikle onlara bilgi veriyorsun.',
     'quizq1a3' => 'Onlara gercek volunteer olduklarini kanitlamalari icin bir delil talebinde bulun.',
     'quizq1info' => 'Dogru! '.XAT_NAME.' yetkilileri ve volunteersler asla özel sohbetde kisisel bilgi paylasimi talebinde bulunmazlar. ID ve mesajlarini iceren bir ekran görüntüsü al, sonra Report scam üzerinden onlari rapor etmek icin bir ticket olustur.',
     'quizq1image' => '<br img src="https://util.'.DOMAIN.'/wiki/images/f/f9/Securityimage1.png" class="img-fluid"/>',
     'quizq2' => 'Trade sitesindesin ve days almaya calisiyorsun. Sizden önce xatsi transfer etmenizi isteyen bir kullanici ile irtibat kuracaksiniz. Ne yapmam gerekiyor?',
     'quizq2a1' => 'Reddet ve tavsiye edilen Güvenli Trade uygulamasini kullanmayi öner.',
     'quizq2a2' => 'Önce xatsini transfer et.',
     'quizq2a3' => 'Onun yerine önce days atmasini talep et.',
     'quizq2info' => 'Bu dogru! xats, days veya powers alip satarken Güvenli Trade uygulamasini kullanman gerekmektedir. Bu uygulama sayesinde dogru zamanda hangi miktarin konuldugunu görebilirsin. Transfer özelliğini kullanarak asla islem yapma, cünkü islemler tamamlandiktan sonra geri alinamaz.',
     'quizq2image' => '<br img src="https://util.'.DOMAIN.'/wiki/images/c/c0/Securityimage2.png" class="img-fluid"/>',
     'quizq3' => 'E-posta saglayicin 2 faktörlü kimlik dogrulama korumasi sunar. Bu opsiyonu etkinlestirmen gerekiyor mu?',
     'quizq3a1' => 'Evet. Bu, e-posta güvenligini büyük oranda artiracaktir.',
     'quizq3a2' => 'Hayir. Benim sifrem yeteri kadar saglam.',
     'quizq3a3' => 'Asla. Bu koruma kullanisli degil.',
     'quizq3info' => 'Dogru! E-posta adresindeki 2 faktörlü kimlik dogrulama sifren kirilsa bile, baska his kimsenin e-postana erisemeyeceginden emin olmak icin (telefona) ek bir güvenlik katmani saglayacaktir.<br><br>Lütfen e-posta hesabin icin kimlik dogrulamayi nasil etkilestirecegin ile ilgili talimatlar almak icin e-posta saglayicinla irtibata gec. Gmail hesaplari icin, lütfen <a href="https://www.google.com/landing/2step/" target="_blank">bu sayfaya</a> bak.',
     'quizq3image' => '<br img src="https://util.'.DOMAIN.'/wiki/images/7/71/Securityimage3.png" class="img-fluid"/>',
     'quizq4' => ''.XAT_NAME.' login sayfasindaki bir güncelleme ile ilgili sana bilgi verilecektir. Kullanici test etmen icin sana bu baglantiyi gönderir https://xaatt.com/login. Ne yapmam gerekir?',
     'quizq4a1' => 'https://'.DOMAIN.' domain olmadigi takdirde o baglantiya tiklama.',
     'quizq4a2' => 'Ona tikla ve neyin degistigini gör.',
     'quizq4info' => 'Dogru! Giris yapmadan, sohbete katilmadan veya herhangi bir '.XAT_NAME.' bilgini vermeden önce, her zaman dogru adres cubugunda yani <a href="https://'.DOMAIN.'" target="_blank">https://'.DOMAIN.'</a> da oldugundan emin ol.',
     'quizq4image' => '<br img src="https://util.'.DOMAIN.'/wiki/images/7/7d/Securityimage4.png" class="img-fluid"/>',
     'quizq5' => 'Bir kullanici sana powerslerini ikiye katlayacagini söylüyor fakat önce powerslerini ona atmani talep ediyor. Ne yapman gerekiyor?',
     'quizq5a1' => 'Powersler cogaltilamaz. Powerslerini transfer etme.',
     'quizq5a2' => 'Teklifini kabul et. Duble powers demek duble kar demek.',
     'quizq5a3' => 'Ürünlerini iki katina cikaracagiyla ilgili kanit talep et.',
     'quizq5info' => 'Aferin! xats, days ve powers cogaltilamaz. Dolandiricilar genellikle bu yolu secerler dikkatini cekmek ve ürünlerine sahip olmak icin. ID ve mesajlarini iceren bir ekran görüntüsü al, sonra Report scam üzerinden onlari rapor etmek icin bir ticket olustur.',
     'quizq5image' => '<br img src="https://util.'.DOMAIN.'/wiki/images/3/35/Securityimage5.png" class="img-fluid"/>',
     'quizq6' => 'Powerslerinin bir '.XAT_NAME.' calisani tarafindan manuel olarak gözden gecirilmesi gerektigini söyleyen info@'.DOMAIN.' adresinden bir e-posta alirsin. Talimat olarak sohbet’de powerslerini belirli bir kisiyle takas etmen gerektigini söylüyor. Bunu yapmayi reddedersen, hesabin 3 ayligina bloke edilir. Ne yapman gerekiyor?',
     'quizq6a1' => 'Yoksay ve e-postayi spam olarak rapor et.',
     'quizq6a2' => 'Baska sorgulama yapmadan kabul et. Lütfen, bloke edilmesin!',
     'quizq6a3' => 'E-postaya daha fazla bilgi almak icin cevap ver.',
     'quizq6info' => 'Bu dogru! Asla buna benzer bir e-posta '.XAT_NAME.' tarafindan almazsin. '.XAT_NAME.' hesabin ile ilgili tüm bildirimler <a href="https://'.DOMAIN.'/ticket" target="_blank">'.DOMAIN.'/ticket</a> destek sisteminde ele alinir ve baska hicbir yerde degil.',
     'quizq6image' => '<br img src="https://util.'.DOMAIN.'/wiki/images/3/3b/Securityimage6.png" class="img-fluid"/>',
     'quizq7' => 'Herkes sifrelerin hatirlanmasinin zor oldugunu bilir. Yani böylelikle hayatini kolaylastirmak icin '.XAT_NAME.' hesabinla e-posta adresinin sifresini ayni yapmaya karar veriyorsun. Bu güvenli mi?',
     'quizq7a1' => 'Hayir!',
     'quizq7a2' => 'Kesinlikle evet. Böylelikle asla sifreni unutma sorunu ile karsi karsiya kalmazsin.',
     'quizq7info' => 'Dogru anladin! Zorluklar ödüllendirebilinir. Korumani artirmak icin cevrimici olan her hesabin icin farkli sifre kullan.',
     'quizq7image' => '<br img src="https://util.'.DOMAIN.'/wiki/images/2/2b/Securityimage7.png" class="img-fluid"/>',
     'quizq8' => 'Indirilmesi gerekerek elde edilen ücretsiz bir xats jeneratörü programi ile ilgili bilgi edinceksin. Ne yapman gerekir?',
     'quizq8a1' => 'xats üretilmedigini biliyorsun, yani bunu yoksay.',
     'quizq8a2' => 'Daha fazla bilgi edinmek icin sor.',
     'quizq8a3' => 'eger xats üretilebiliyorsa kanit iste.',
     'quizq8info' => 'Haklisin! Ücretsiz olarak xats üretilemez! Herhangi bilinmedik bir program indirmek konusunda dikkatli olun, kötü amacli olabilirler ve zararli yazilimlar icerebilirler (virüsler).',
     'quizq8image' => '<br img src="https://util.'.DOMAIN.'/wiki/images/5/5c/Securityimage8.png" class="img-fluid"/>',
     'quizq9' => 'Eger 24 saat icerisinde 10000 xats satin almazsan hesabinin bloke edilecegini söyleyen bir mesaj aldin. Ne yapman gerekir?',
     'quizq9a1' => 'xats yollama ve kullaniciyi yoksay.',
     'quizq9a2' => 'Bloke mi? Mümkün degil! En iyisi ödeyeyim.',
     'quizq9a3' => 'Bir aciklama talebinde bulun.',
     'quizq9info' => 'Dogru! '.XAT_NAME.' yetkilileri ve volunteersler asla xats talebinde bulunmaz. ID ve mesajlarini iceren bir ekran görüntüsü al, sonra Report scam üzerinden onlari rapor etmek icin bir ticket olustur.',
     'quizq9image' => '<br img src="https://util.'.DOMAIN.'/wiki/images/b/b4/Securityimage9.png" class="img-fluid"/>',
     'quizq10' => 'Powerslerin icin 50000 xats gibi pahali miktarda xats teklif edilir. Ticaret sirasinda, birden fazla basarisizlik denemesi var, yanlis sifre ve diger hatalardan dolayi. Ne yapman gerekir?',
     'quizq10a1' => 'Saygili bir sekilde kullaniciya ticareti yeniden baslatmak istedigini söyle.',
     'quizq10a2' => 'Sorunu yoksay ve ticarete devam et.',
     'quizq10a3' => 'Kullaniciyi yoksay.',
     'quizq10info' => 'Dogru! Dolandiricilar, uygulamada xats, days ve ya powers miktarini degistirerek senin xatsini, daysini ve ya powersini calmaya calisacaktir.<br><br>Her hatali girisimden sonra iki kez kontrol et her powersi ve her zaman icin dikkatli ol ticaret esnasinda. Onaylamadan önce ticaret detaylarini tekrar kontrol etmek icin ekstra bir dönüs yap.',
     'quizq10image' => '<br img src="https://util.'.DOMAIN.'/wiki/images/a/a2/Securityimage10.png" class="img-fluid"/>',
     'quizq11' => 'Forumdan '.XAT_NAME.' yetkilisini oldugunu iddia eden bir kisiden özel mesaj aldin. Mesajda hesap detaylarin soruluyor (sifreler ve e-postalarin gibi), aksi halde '.XAT_NAME.' tarafindan hesabinin bloke edilecegini söylüyor. Ne yapman gerekir?',
     'quizq11a1' => 'Kullaniciyi yoksay ve forum yetkililerine rapor et.',
     'quizq11a2' => 'Mesaja istenen bilgilerle geri dönüs yap.',
     'quizq11a3' => 'Bloke ile ilgili daha fazla bilgi icin sor.',
     'quizq11info' => 'Dogru! '.XAT_NAME.' yetkilileri ve volunteersler asla seni bloke edilme gibi sorunlarla ilgili özelden irtibat saglamazlar. Tüm hesap sorunlari <a href="https://'.DOMAIN.'/ticket" target="_blank">'.DOMAIN.'/ticket</a> destek sisteminde islem görür ve sen uygunsuz ve kötü niyetli özel mesajlari rapor etmelisin.',
     'quizq11image' => '<br img src="https://util.'.DOMAIN.'/wiki/images/7/7a/Securityimage11.png" class="img-fluid"/>',
     'quizq12' => 'Sohbetde '.XAT_NAME.' yetkilisi tarafindan e-postanin 2 faktör dogrulama korumasini devre disi birakman söyleniyor. Ne yapman gerekiyor?',
     'quizq12a1' => 'Onlari reddet ve yoksay.',
     'quizq12a2' => '2 faktör dogrulamayi devre disi birak.',
     'quizq12info' => 'Evet, haklisin! Hicbir kosulda '.XAT_NAME.' yetkilileri ve volunteersler 2 faktör dogrulama korumasini devre disi birakmani talep etmezler. Hesap güvenligini devre disi birakmani talep eden kullanicilari rapor etmekten cekinme.',
     'quizq12image' => '<br img src="https://util.'.DOMAIN.'/wiki/images/4/45/Securityimage12.png" class="img-fluid"/>',
     'quizq13' => 'Bir web sitesi sayfasinda ücretsiz xats üreticisi olduguyla ilgili söylenti duyuyorsun. Ancak ücretsiz xats üretmek icin sifre ve e-postani yazman gerekiyor. Ne yapman gerekir?',
     'quizq13a1' => 'Bildigin üzere ücretsiz xats üretimi yoktur o yüzden yoksay.',
     'quizq13a2' => 'Devam et ve giris yap.',
     'quizq13a3' => 'Eger xats üretilebiliyorsa kanit iste.',
     'quizq13info' => 'Haklisin! Ücretsiz olarak xats üretilemez. Yani, sadece <a href="https://'.DOMAIN.'" target="_blank">https://'.DOMAIN.'</a> resmi sayfasina sifreni yaz. Sürekli olarak <a href="https://'.DOMAIN.'" target="_blank">'.DOMAIN.'</a> sayfasinda olduguna emin olmak icin adres cubugunu kontrol et.',
     'quizq13image' => '<br img src="https://util.'.DOMAIN.'/wiki/images/5/57/Securityimage13.png" class="img-fluid"/>',
     'quizq14' => 'Trade chat’de bir kullanicidan powers satin almak icin anlasma yaptin Kullanici önce powerslerin yarisini daha sonra diger yarisini verecegini söylüyor. Ne yapman gerekiyor?',
     'quizq14a1' => 'Teklifi reddet - simdi tüm ürünleri eklemesini iste.',
     'quizq14a2' => 'Teklifi kabul et. Hic bir aksilik olmaz.',
     'quizq14a3' => 'Bahsi gecen powerslerin var olduguna dair kanit talep et.',
     'quizq14info' => 'Dogru! Dolandiricilar, önceden bir miktar teklif ederek ve daha sonra geri kalanini ödemeye söz vererek alim satimlari sahnelemeye calisabilirler. Bu tür kullanicilara asla güvenme ve sadece anlasilan miktarin tamamini talep ederek ticaret yap. Kullanicinin sonra tekrar dönüs yapmasi cok düsük bir ihtimal.',
     'quizq14image' => '<br img src="https://util.'.DOMAIN.'/wiki/images/5/59/Securityimage14.png" class="img-fluid"/>',
     'quizq15' => 'Ücretsiz animasyonlu avatar (gifs) yapan bir program ile ilgili duyum aliyorsunuz. Bir kullanici sana sohbet’de programi indirmen icin bir baglanti yolluyor bilinmedik bir web sitesinin. Ne yapman gerekir?',
     'quizq15a1' => 'Virüs icerebilecegi icin asla bilinmedik dosyalari indirmeyin.',
     'quizq15a2' => 'Körü körüne indir.',
     'quizq15info' => 'Dogru! Dolandiricilar, sana yardimci olan arkadas pozu vererek seni virüs indirmeye tesvik edebilir. Bilinmeyen dosyalari indirmemeye özen gösterin. Tehlikeli seyleri indirmekten seni korumak icin bir kac ipucu:<br><br ol><li>Dosya ismi icin Google’de arama yapin (program güvenirligi ve hatta mevcut olduguna dair).</li><li>Indirmek icin baska alternatif kaynaklar ara.</li><li>Dosya üzerinde bi virüs taramasi baslat.</li></ol>',
     'quizq15image' => '<br img src="https://util.'.DOMAIN.'/wiki/images/1/19/Securityimage15.png" class="img-fluid"/>',
     'quizq16' => 'Sohbet’de tanistigin bir kisi sana kisisel bilgilerin ile ilgili sorular soruyor, ismin, sokak adresin ve e-postan gibi. Ne yapman gerekir?',
     'quizq16a1' => 'Kisisel bilgilerin hakkinda sohbet etmek istemedigini söyleyerek konuyu degistir.',
     'quizq16a2' => 'Havali durduklari icin gercek bilgilerinle ilgili sorulari cevapliyorsun.',
     'quizq16a3' => 'Kullaniciyi yoksay.',
     'quizq16info' => 'Aferin! Sanal hic kimseyle kisisel bilgilerini paylasma. Asla sifreni ve e-postani paylasma!',
     'quizq16image' => '<br img src="https://util.'.DOMAIN.'/wiki/images/d/d9/Securityimage16.png" class="img-fluid"/>',
     'quizq17' => 'Bir sohbet sayfasinda hesabinla ilgili bir sorun olustugu söyleniyor, ve bu sorunu gidermek icin, giris sayfasinda hesap korumasini devre disi birakman talep ediliyor. Ne yapman gerekir?',
     'quizq17a1' => 'Asla soruldugu zaman hesap korumani devre disi birakma.',
     'quizq17a2' => 'Herhangi bir yabanciya güveneceksin. Ve koruma devre disi sekildeyken giris yapacaksin.',
     'quizq17a3' => 'Isteklerini yerine getirmeden önce daha fazla bilgi icin sorun.',
     'quizq17info' => 'Dogru! '.XAT_NAME.' hesap korumalarini hic bir kosulda devre disi birakma. '.XAT_NAME.' yetkilileri ve volunteersler asla senden korumalarini devre disi birakmani talep etmezler.',
     'quizq17image' => '<br img src="https://util.'.DOMAIN.'/wiki/images/a/ab/Securityimage17.png" class="img-fluid"/>',
     'quizq18' => 'Bir arkadasin efektlerini test etmek icin bir süreligine namecolor gücünü ödünc alabilirmi diye sorar. Ne yapman gerekir?',
     'quizq18a1' => 'Hic kimseye verme. Geri alamayacagin ihtimali var.',
     'quizq18a2' => 'Vermekte bir sorun görmüyorum. Nasilsa istedigim zaman geri alirim.',
     'quizq18a3' => 'Sonsuza kadar kankayiz. Trade tikla, ve saniye düsünme!',
     'quizq18info' => 'Bu dogru! xats’larin, days’lerin ve powers’lerin tamamen senin sorumlulugun altindadir. xat’da borc verme yöntemi mevcut degildir, yani kendi rizanla vermis olarak degerlendirilir. Eger bir ticaret veya transfer islemini tamamlarsan, geri alinamaz. Her zaman icin cok dikkatli ol. <a href="//util.'.DOMAIN.'/wiki/index.php?title=Special:MyLanguage/Trading" target="_blank">Buradan daha fazla bilgi edin.</a>',
     'quizq18image' => '<br img src="https://util.'.DOMAIN.'/wiki/images/1/17/Securityimage18.png" class="img-fluid"/>',
     'quizq19' => 'Az önce info@'.DOMAIN.' tarafindan 100000 xats satin aldigina dair bir e-posta aldin. Ayrica bir baglantiyi tiklayarak ödemeyi onaylaman gerektigini belirtiyor. Baglanti xatslari almak icin 100$ dolar ödeme yapman gerektigini belirten bir sayfaya yönlendirir. Ne yapman gerekir?',
     'quizq19a1' => 'Bu garip bir teklif. Eger zaten xatslari satin aldiysam, neden daha fazla ödeme yapmam gerekiyor? E-postayi spam oldugundan dolayi bloke ederim.',
     'quizq19a2' => 'E-posta info@'.DOMAIN.'dan geliyor ama 100$ dolar cok para. Cevapla ve daha fazla bilgi talebinde bulun.',
     'quizq19a3' => 'xats almayi planlamiyordum, ama 100000 xats 100$a karli bir alisveris. Yap bunu!',
     'quizq19info' => 'Dogru! '.XAT_NAME.' sana ASLA bir e-posta ile satin al talebinde bulunmaz, ve tek güvenilir yer gercek paraya xats satin alabilecegin yer <a href="https://'.DOMAIN.'/buy">https://'.DOMAIN.'/buy</a> dir. Bazi dolandiricilar '.XAT_NAME.' e-posta adresini taklit edebiliyor, yani info.'.DOMAIN.' gösterse bile asla devam etmemelisin. Bununla birlikte, eger anlasma gercek olamayacak kadar mükemmel duruyorsa genellikle böyledir ve muhtemelen bir dolandiricilikla karsi karsiyasin.',
     'quizq19image' => '<br img src="https://util.'.DOMAIN.'/wiki/images/f/fe/Securityimage19.png" class="img-fluid"/>',
     'start' => 'Quizi baslat',
     'desc' => 'Ücretsiz olarak <a href="//util.'.DOMAIN.'/wiki/index.php?title=Special:MyLanguage/Tickle" target="_blank">Tickle</a> gücünü almak icin, asagida bulunan quizi ve her soruyu tek tek dogru cevaplaman gerekiyor.',
     'wronganswer' => 'Yanlis cevap. Lütfen tekrar dene.',
     'next' => 'sonraki',
     'continuein' => 'Devam et',
     'gratz' => 'Tebrikler, quizi tamamladiniz! Artik '.XAT_NAME.' güvenligi ile ilgili daha fazla bilgiye sahipsin.',
     'tickle' => 'Tickle gücüne sahipsin.',
     'redirect' => 'Lütfen giris sayfasina yönlendirilirken beklemede kal.'
	 ]
?>