<?php
$array = [
     'buyshort' => 'Legyen neked is rövidebb felhasználóneved.',
     'notavailable' => 'Bocsánat. Rövid név nem áll rendelkezésre',
     'terms' => 'El kell fogadnia a feltételeket',
     'nametaken' => 'Sajnos név már foglalt',
     'costchanged' => 'Költség megváltozott',
     'notfound' => 'nem található',
     'wrongpassword' => 'Hibás jelszó',
     'noxats' => 'Nincs elég xats',
     'namechanged' => 'Név változott',
     'xatname' => ''.XAT_NAME.' felhasználónév:',
     'password' => 'Jelszó:',
     'desiredname' => 'Kívánt rövidebb felhasználónév:',
     'noteil' => 'Megjegyzés: az "i" mindig kisbetűs "L" mindig a nagybetűs',
     'iagree' => 'Elolvastam és elfogadom a szabályokat és <a href="http://'.DOMAIN.'/terms.html">feltételeket</a>',
     'getcost' => 'Ár lekérése',
     'once' => 'Csak egyszer kattintson.',
     'letters' => 'Neve tartalmazza rossz betű',
     'short' => 'Név túl rövid',
     'long' => 'Név túl hosszú',
     'notallowed' => 'Név nem megengedett. Kérjük, próbálkozzon egy másik.',
     'firstletter' => 'Első betű nem lehet több.',
     'youcan' => 'Vásárolj egy 4-9 karakteres felhasználónevet a xatsaid segítségével.',
     'rules' => 'Szabályzat:',
     'rulesname' => '<li> Meg kell <a href="http://'.DOMAIN.'/terms.html">felelned a felhasználási feltételeknek</a> </li><li> A rövidebb név ára változhat, ezért kattints az Ár lekérése gombra,hogy megkapd a jelenlegit. </li> Ha vásárolsz egy rövidebb felhasználónevet, és nem használod 90 napig, az újra eladásra kerül. Egy Felhasználó csak egy rövidebb felhasználónevet vásárolhat. <li> A jelenlegi felhasználóneved törlésre kerül, amikor rövidebb felhasználónevet vásárolsz. </li><li> Ha egy olyan felhasználónevet választasz, ami sértő mások számára( bármilyen nyelven), az törlésre kerülhet, és a xats nem kerül visszatérítésre.</li> Megjegyzés: egy rövidebb felhasználónévvel magasabb helyet foglalhatsz el a felhasználók listájában. <li></li>',
     'buypow' => 'Powerek vásárlása',
     'maxbuy' => 'Maximum lehet kapni',
     'notyet' => 'Nem lehet vásárolni többé ez a hatalom még, próbálja újra perc',
     'allgone' => 'Bocsánat. Nincs hatásköre maradt.',
     'nodays' => 'Nincs elég nap',
     'nothing' => 'Semmi vásárolni!',
     'relogin' => 'Biztonsági ellenőrzés sikertelen. Kattintson <a href="http://'.DOMAIN.'/login">ide, hogy újra be kell '.XAT_NAME.' csevegés</a>',
     'alreadyhave' => 'Már van ezeket a hatásköröket:',
     'completeta' => 'Vásárlásra. Köszönöm.',
     'canpowers' => 'A xatsaid segítségével powereket és más előnyöket, tulajdonságokat vásárolhatsz a '.XAT_NAME.'hoz.',
     'readwell' => 'Leírás <font color="#FF0000">(Kérjük, olvasd el figyelmesen a vásárlás előtt!)</font>',
     'canplay' => 'Ezzel a powerrel tudsz játékokat inditani és irányitani.',
     'chkforall' => 'Ellenőrizze, hogy a hatáskörök szükséges minden hatáskört',
     'unavailable' => 'ideiglenesen nem lesz elérhető, ha elfogyott',
     'remaining' => 'még!',
     'willdrop' => 'Ár csökken!',
     'sold' => 'eladott',
     'trytrading' => 'Nem elérhető próbáld a <a href="http://'.DOMAIN.'/web_gear/chat/chats.php?type=trade">kereskedelmet</a>',
     'atauction' => 'Vásárlás aukción <a href="\"http://'.DOMAIN.'/web_gear/chat/Auction4.php\"">aukción</a>',
     'powrules' => '<li> Meg kell <a href="http://'.DOMAIN.'/terms.html">felelned a feltételeknek</a> </li><li> A powerek csak akkor müködnek, ha vannak Dayseid ( napjaid ) .<strong> </strong>Mindig jön ki egy új power.</li><li>A power lehet limitált, ezért vedd meg a tiédet most, nehogy lemaradj róla. </li> A powerek ára változhat, mint felfelé, mint lefelé, ez az igénytől függ. <li>Más felhasználók láthatják a bekapcsolt powereidet. A powereket be és kikapcsolhatod.( Kivonhatod őket a használatból .) </li><li> A powerekkel kereskedhetsz. </li> Powereid megmaradnak, amig nem adod őket el más felhasználóknak.Minden powernek megvan a saját jelképe. Csak az használhatja ezt a jelképet, aki rendelkezik az adott powerrel. <li>Kérjük, hogy olvasd el a power leírását vásárlás előtt. ( Vidd rá az egeret ,hogy megkapd a felugró leírást. </li>',
     'power' => 'Power',
     'smilie' => 'Jelkép',
     'cost' => 'Ár',
     'quantity' => 'Mennyiség',
     'orcheck' => 'vagy jelöld be',
     'games' => 'Játékok',
     'powers' => 'Powerek',
     'allpowers' => 'AllPowers',
     'alldesc' => 'Ahhoz, hogy megvehesd az allpowerst ,szükséged van minden <b>rendelkezésre álló</b> powerre ( ami kis rakétával van jelölve ). Limitált és Epic powerek nem szükségesek.',
     'everypower' => 'EveryPower',
     'everydesc' => 'Ahhoz, hogy mekapd és használni tudd a Ruby bábut, szükséged van az ÖSSZES létező powerre , beleértve a limitáltakat, chat powereket, és epic powereket. Everypowerrel NEM lehet kereskedni.',
     'epicdesc' => '<b>Az Epic Powerek</b> ritkák, mivel elég drágák is. Mester kereskedőknek egy ú.n díj, akik sikeresen kereskednek nap mint nap, a saját kis profitjukból meg tudnak élni a '.XAT_NAME.'on.',
     'needlogin' => '( <a href="http://'.DOMAIN.'/Login">Jelentkezz be </a> hogy ezen változtass',
     'markallp' => 'Mark All Powers',
     'buyxavis' => 'Xavik vásárlása',
     'check' => 'jelöld be a vásárláshoz',
     'hat' => 'kalap',
     'hair' => 'haj',
     'xavirules' => '<li> Meg kell <a href="http://'.DOMAIN.'/terms.html">felelned a feltételeknek.</a> </li> <li>Xavik csak akkor fognak müködni, ha vannak dayseid és van xavi powered<strong> </strong>Xavikkal NEM tudsz kereskedni.</li>',
     'type' => 'Fajta',
     'buygroup' => 'Chat vásárlás',
     'gtxnotavail' => 'Bocsánat. Csoportos átutalás nem áll rendelkezésre',
     'groupnoexist' => 'Ez a csoport nem létezik',
     'notdormant' => 'csoport nem alvó',
     'txgroupdone' => 'Transzfer befejeződött. Kérjük, <a href="http://'.DOMAIN.'/$RoomName">látogasson el a csoport</a> , kap egy új jelszót küldött e-mail, és beállítja az összes fel.',
     'youcangroup' => 'Használd a xatsaidat ahhoz, hogy egy chatet vásárolj.',
     'groupname' => 'Chat neve:',
     'costxats' => 'Költség xats',
     'language' => 'Nyelv',
     'editgrp' => 'Szerkesztése csoport változtatni',
     'rulesgroup' => '<li>Ha a chat neve másokra sértő lehet (lást <a href="http://'.DOMAIN.'/terms.html">szerződési feltételek</a>) ta chat törlésre kerülhet bármilyen figyelmeztetés vagy visszatérítés nélkül. </li>
 <li>Ne aggódj! A chatednek 3 hónapig inaktívnak kell lenni, hogy újra eladásra kerüljön!</li>',
     'promo' => 'Elősegítése Chat Group',
     'langnotset' => 'Group nyelv nincs beállítva. Kérjük, módosítsa csoport állítani a nyelvet.',
     'tinypiconly' => 'Kép kell tinypic.com png, jpg vagy nem animált GIF',
     'promona' => 'Sajnáljuk, promóció nem elérhető',
     'promoblocked' => 'Sajnáljuk, promóció blokkolva',
     'delisted' => 'Chat törölték. Kérjük, re-lista. (Edit Chat, extrák)',
     'membersonly' => 'Chat csak tagoknak. Kérjük, változtassa meg. (Edit Chat, extrák)',
     'notzero' => 'Nem lehet nulla!',
     'adssoon' => '<p> Köszönöm. Reklámok fog futni hamarosan </p>',
     'promosoon' => '<p> Köszönöm. Promotion hamarosan megkezdődik </p>',
     'emailauth' => '<p> Köszönöm. Akkor e-mailben, ha a hirdetés nem engedélyezték. </p>',
     'canpromo' => 'Használhatja a xats, hogy a chat-csoportot támogatott itt.',
     'promonow' => 'Promotálni most!',
     'orads' => 'Vagy hirdesd a chated bannerrel a '.XAT_NAME.'on',
     'imageerror' => 'Hibaellenőrzés képet. Töltsd újra?',
     'noanim' => 'Animáció nem engedélyezett most, sajnálom',
     'imageinval' => 'Invalid kép (2)',
     'imagetype' => 'Invalid image Típus: $ type',
     'imagebig' => 'A kép túl nagy (max $ t bytes)',
     'imagesize' => 'Kép kell 728 x 90',
     'days' => 'days',
     'rulespromo' => '<li> A chat tulajdonosának többnek kell lenni mint 14 év.</li> A chatnek meg kell felelnie az Általános Szerződési Feltételeknek. <li>A chatnek moderálva kell lennie a promoció alatt.CHAT RÁDIÓ: Ha a chatben olyan rádió van , ami tartalmaz trágár szavakat, akkor tartalmaznia kell a chatnek ezt a kiírást:FIGYELEM: A rádió 18+-os (a promóció nyelvén), vagy a dj-nek ki kell takarnia ezeket a szavakat. <a href="http://'.DOMAIN.'/terms.html"></a> Ha egy felhasználó nem megfelelően viselkedik, vagy trágárul beszél, azonnal bannolva kell, hogy legyen. </li><li> Trágár felhasználókat azonnal tiltani kell, és nem csak kickelni. </li> Nem szabad bármilyen sértő tartalmú képet, vagy szoftverre utaló linket posztolni. A promóció ideje alatt nem szabad rangot árulni. Pl. Moderátori jogot eladni. EZ TILOS. <li>A promóció ideje alatt nem lehet politikai vagy vallási nézetekről beszélni. </li><li> A promóció ideje alatt kell, hogy legyen egy moderátor vagy admin </li>látható admin<li> A chatnek a megfelelő nyelven kell lennie.</li><li></li><li> Több chaten is lehetsz egyidőben. </li><li></li> A promóció költsége változhat. Kattintson az Ár lekérése gombra, hogy megkapja az aktuálisat.A chatnek mindenki számára elérhető kell , hogy legyen. ( Pl. nem lehet csak tagok számára )Ne tilts ok nélkül senkit. ( pl. új felhasználókat) <li> A hirdetés csak azok számára lesznek elérhetők, akik a chat nyelvét beszélik. <em></em> A hirdetések váltakoznak. </li> Ne használd a pr parancsot, használd a p-t helyette, mivel a chatnek mindenki számára nyitottnak kell lennie. Ne használd a pr parancsot, mivel ezzel elveszitheted a teljes promóciód. <li></li>',
     'promohours' => 'Promotálni kívánt óra száma',
     'minhalf' => 'Minimum fél óra.(0.5)',
     'adimage' => 'Kép URL-je',
     'advertise' => 'Hirdetés',
     'aphase' => 'Aukció fázis',
     'needmore' => 'Be kell, hogy ajánlatot több mint',
     'notpart' => 'nem része az árverés!',
     'ended' => 'Aukció véget ért.',
     'idblocked' => 'ID blokkolva van.',
     'choose' => 'Kérjük, válasszon ki egy átviteli módot',
     'notenough' => 'Nincs elég xats / hatásköröket',
     'alreadybid' => 'Már van egy ajánlatot',
     'biddone' => 'Benyújtott ajánlatot.',
     'during1' => '1. fázisban az árverés akkor javaslom azonosítókat szeretne vásárolni.',
     'p1ends' => '1. fázis véget ér:',
     'during2' => '2. fázis során az árverés akkor ajánlatot bármely azonosítók a listában.',
     'previous' => 'Korábbi aukciós eredmények.',
     'bids' => 'Aktuális ajánlatok:',
     'idfor' => 'Eladó ID',
     'timeleft' => 'hátralévő idő',
     'prevbid' => 'előző ajánlat',
     'congrats' => 'Gratulálok a győztes az árverés.',
     'auclogin' => 'Ahhoz, hogy az új azonosítót, lépjen be a nevét',
     'rereg' => 'FONTOS: Ha azt szeretné, hogy újra nyilvántartásba a régi ID kérjük, használja ezt a linket',
     'aucreg' => 'FONTOS: regisztrálni az új azonosítót használja ezt a linket',
     'bid' => 'Ajánlat',
     'topbid' => 'Eddigi legjobb ajánlat tőle',
     'prevhere' => 'Az előző aukción eredményei <a href="?old=1">itt</a> .',
     'canauction' => 'xatsaid segítségével licitálhatsz az aukciókon',
     'auctionrules' => '<li> Meg kell <a href="http://'.DOMAIN.'/terms.html">felelnie a feltételeket</a> </li> '.XAT_NAME.' fenntartja magának a jogot, hogy törölje, és visszatéríti aukciós értesítés nélkül '.XAT_NAME.' reserves the right to cancel and refund any auction without notice</li> A '.XAT_NAME.' nevét és user id jelenik meg, ha magas ajánlattevő / nyertes (ez a nyilvános árverésen) <li>Your '.XAT_NAME.' name and user id will be shown if you are high bidder / winner (this is a public auction) Ajánlatok kötelező érvényűek. Ha nem túllicitálni kell majd fizetnie. <li> Ha első ajánlattevőnek be kell tartani ahhoz, xats és hatásköröket a számláján, hogy fedezze az ajánlatot. </li> Meg kell elég xats és vagy nem korlátozott hatáskörrel a venni annak érdekében, hogy ajánlatot. If you are top bidder you must keep enough xats and powers in your account to cover the bid. <li> Ha <strong>nyersz, kell igényelni az azonosító számított 12 órán belül</strong> az aukció vége </li> Ha nem sikerül a teljes és aukciós akkor lehet If you fail to complete and auction you can bebírságot vagy törölt fined or deleted </li> <span class="style1">NEW</span> Ha ajánlatot véletlenül elveszíti 20%-a az ajánlatot, de értesítenie kell '.XAT_NAME.' azonnal </li> <span class="style1">NEW</span> Ha nem tölti ki az aukción, és mozgassa a xats el fogja veszíteni 100%-os ajánlatát </li> '.XAT_NAME.' fenntartja magának a jogot, hogy blokkolja azonosítók az aukcióból. '.XAT_NAME.' reserves the right to block IDs from the auction.</li> is, nézd meg a <li>wiki<a href="http://util.'.DOMAIN.'/wiki/index.php/Auction"> , mielőtt ajánlatot </a> before bidding A név aukció a nevet kap az azonosító. A régi neve elvész.For name auctions the name will be assigned to your ID. Your old name will be lost.',
     'minbid' => 'A minimális ajánlatot ezen az árverésen is:',
     'desired' => 'Kívánt ID',
     'digits' => 'számjegy',
     'enterbif' => 'Adja meg a licit',
     'buyxats' => 'xatsok és Daysek vásárlása',
     'intro' => 'A '.XAT_NAME.'nál vásárolhat powereket és több hasonló dolgot, amely jobbá teszi a chatelést. Vásárlás során Days-eket is kap vásárol, amelyek szükségesek ahhoz, hogy a powerek müködjenek. Döntsd el, hogy mennyiért szeretnél xatsot és dayset vásárolni. Kérlek győződj meg arról, hogy a bankszámlatulajdonos engedélyezte a vásárlást számodra. A vásárlások feltételeit a <a href="http://'.DOMAIN.'/terms.html">szerződési feltételekben tekintheti meg.</a> Amennyiben telefonnal vásárolsz, győzödj meg arról, hogy az előfizetés fizetőjének engedélye meg van.',
     'aboutto' => 'Ennek a '.XAT_NAME.' felhasználókat fogsz xatsot és days-et vásárolni:',
     'notyou' => 'Ha nem a te ID-d , AKKOR NE FOLYTASD.',
     'cash' => 'Bank / PayByCash',
     'credcard' => 'Hitelkártya',
     'includes' => 'days',
     'over70' => 'Több mint 70 nem bankkártyás fizetési <br> mód világszerte.<br>',
     'ugc' => 'Ultimate Game Card',
     'prepaid' => 'Előfizetős kártya - USA Kanada Törökország Brazília Fülöp Izrael Portugália Malajzia Szingapúr Tajvan',
     'calculated' => 'A kártya érététől függően lesz<br> kiszámítva, hogy mennyi xatsot <br>és dayst kapsz.',
     'multiugc' => 'Ha több, mint egy gamecard akkor lehet, hogy <br> minél több xats segítségével PayByCash gombbal',
     'pin' => 'Pin kód',
     'nogc33k' => '<b>UGC nem használható <br> a 33000 xats-os opcióhoz.</b>',
     'max10' => '*: Legfeljebb 10 éves előfizetés --- **: Az EU-s áfa levonásra kerül a xats összegéből. --- USD = USA dollár',
     'reserve' => 'PayPalos, hitelkártyás és telefonos fizetések esetén<a href="http://util.'.DOMAIN.'/wiki/index.php/xatsReserve">kereskedelmi limit</a> fogja korlátozni fiókját.',
     'days2xats' => 'Days( napok ) xatssá való alakítása',
     'min10' => 'Minimum 10 nap',
     'nodx' => 'Nincs elég DX hatáskörök',
     'sorryyou' => 'Sajnálom, hogy kell lennie egy regisztrált felhasználó',
     'candx' => 'Itt tudod átalakítani a dayseidet xatssá.',
     'daysto' => 'Átalakítandó napok száma:',
     'dxrules' => '<li> Meg kell <a href="http://'.DOMAIN.'/terms.html">felelned a feltételeknek.</a> </li><li> Szükséged lesz a DX Power használatára minden egyes konvertáláskor.<strong> </strong>1DX Powerrel maximum 180 Days-et( napot ) alakíthatsz át. </li><li> Daysenként 13.5 xats-ot kapsz. </li>',
     'convert' => 'Átalakítás',
     'notconf' => 'regisztráció nem erősítette',
     'pleasewait' => 'Kérjük, várjon',
     'promonote' => 'Megjegyzés: ha nem tartja magát e szabályok a promóció véget sem vetett, nem visszatérítés xats és a csoport is törölték, és blokkolja a további támogatása.',
     'held' => 'Fiók tartott. Nem lehet vásárolni.',
     'pinbad' => 'PIN-kód túl rövid, vagy rossz betűk',
     'paypal' => 'Paypal',
     'oneonly' => 'PayPal kifizetéseket kell egy '.XAT_NAME.' id csak.',
     'careful' => '(Ellenőrizze alaposan!)',
     'otherids' => 'Más azonosítók ajánlatot',
     'notavail' => 'Bocsánat. Nem érhető el',
     'imgneedauth' => 'Hirdetés képeket kell authoized <font color="#FF0000">(költség 50 xats)</font> See Lásd wikiwiki before proceeding. előtt.',
     'authorize' => 'Engedélyez',
     'winner' => 'Győztes',
     'soldcol' => 'Eladva és teljesítve',
     'p2ends' => '2. fázis véget ér:',
     'forgotpass' => 'Ha elfelejtetted a jelszavad, add meg az e-mail címet a visszaállításhoz',
     'wait' => 'Kérjük, várjon ..',
     'buy' => 'Vesz',
     'norequests' => 'No beérkezett eddig',
     'pinacc' => 'PIN elfogadott. Akkor e-mailben röviden a regisztrált e-mail felhasználói',
     'refreshok' => 'Frissítse sucessful. <br> Kérjük, zárja be az összes chat ablak.',
     'refreshRfail' => 'efresh sikerült .. Kérjük, <a href="\"http://'.DOMAIN.'/login\"">jelentkezz be</a> újra.',
     'refreshfail' => 'Frissítés sikertelen .. Kérjük, <a href="\"http://'.DOMAIN.'/login\"">jelentkezz be</a> újra.'
	 ]
?>
