<?php
$array = [
     'groups' => 'Chatek',
     'store' => 'Tárolás',
     'buyxats' => 'xats és Days vásárlás',
     'powers' => 'Powerek',
     'xavi' => 'xavis',
     'xatgroup' => ''.XAT_NAME.' chat',
     'shortname' => 'Rövid név',
     'promotion' => 'Promotálás',
     'auctions' => 'Aukciók',
     'community' => 'Közösség',
     'more' => 'Több',
     'twitter' => 'Twitter',
     'wiki' => 'Wiki',
     'support' => 'Ügyfélszolgálat',
     'contact' => 'Kapcsolatfelvétel',
     'help' => 'Segítség',
     'trade' => 'Kereskedelem',
     'widgets' => 'Kütyü',
     'login' => 'Bejelentkezés',
     'language' => 'Nyelv',
     'privacy' => 'Anonimitás',
     'terms' => 'Felhasználási Feltételek',
     'safety' => 'Biztonság',
     'failed' => 'sikertelen',
     'evalid' => 'e-mail nem érvényes',
     'recaperr' => 'A reCAPTCHA nem helyesen adta. Kérjük, próbálja újra. (ReCAPTCHA szerint',
     'notbot' => 'és hogy ellenőrizze, ha nem egy bot',
     'numinbox' => 'Kérlek add meg a képen látható számokat:',
     'cancel' => 'Mégsem',
     'submit' => 'Elküldés',
     'wrongnum' => 'Rossz beírt szám!',
     'ayaherr' => 'Be kell bizonyítani, hogy az emberi.'
	 ]
?>