<?php
$array = [
     'creategroup' => 'Gruppe erstellen',
     'badpass' => 'Fehler beim Raum Passwort.',
     'modrules' => 'geändert werden, um Regeln anzupassen',
     'access' => 'Zugriff zu der bestehenden Gruppen hier',
     'yourname' => 'Ihr Name:',
     'desc' => 'Gruppen Beschreibung:',
     'let2050' => '(20-50 Zeichen)',
     'grt6' => 'Mindestens 6 Zeichen lang, Groß-und Kleinschreibung - NICHT TEILEN (Passwort ist für die Bearbeitung der Gruppe)',
     'noshare' => 'TEILEN SIE NICHT',
     'passonly' => '(Passwort ist nur für die Bearbeitung der Gruppe)',
     'tags' => 'Schlagwörter:',
     'sepcom' => '(Durch Kommas trennen)',
     'taginfo' => 'Tags sind Schlüsselwörter, die Ihre Gruppe in einzelnen Wörtern beschreibt. Damit kann Ihre Chat Gruppe einfacher gefunden werden z.B. für eine Renn Gruppe: Rennen, Auto, Rennwagen. Wenn die Chat Gruppe nicht Englisch ist, fügen Sie noch die Sprache dazu.',
     'mustvalid' => 'DIES MUSS EINE GÜLTIGE E-MAIL ADRESSE SEIN, UM DIE GRUPPE ZU AKTIVIEREN.',
     'grpres' => 'Gruppenname ist reserviert',
     'grpexist' => 'Gruppe existiert bereits',
     'urlinfo' => 'Optional - Adresse der Webseite, welche die Gruppe unterstütztanzeigt',
     'grpac1' => '<p>Vielen Dank, Ihr Gruppen Antrag wurde bearbeitet.<br>
Eine Bestätigungs-E-Mail wurde abgeschickt. Sie müssen den Link in der E-Mail anklicken um die Chat Gruppe zu aktivieren.</p>
<p><strong>Wenn SIe keine E-Mail erhalten, überprüfen Sie bitte ihren Spam Ordner.</strong></p>
<p><strong>(es kann bis zu 30 Minuten dauern, bis Sie die E-Mail erhalten)</strong></p>
<p>Wenn Sie immernoch keine E-Mail empfangen haben, müssen Sie es erneut mit einem anderen E-Mail Provider welcher funktioniert versuchen. Versuch ein<a href="http://gmail.com">Gmail</a> Konto. Wenn dein E-Mail Provider die E-Mail nicht an Sie weitergibt, können Sie ihren Chat nicht eröffnen.</p>',
     'grpac2' => 'Bitte aktivieren SIe die '.XAT_NAME.' Chat-Gruppe:%s',
     'grpac3' => 'Hallo %s,

Klick den folgenden Link um deine %s Gruppe zu aktivieren und Hauptbesitzer zu werden:

%s',
     'grpinfo' => 'Chat-Gruppen sind offene Chat Räume für bestimmte Zwecke. Dies könnte zum diskutieren zu einem bestimmten Thema (z.B. Musik, Anime, Computerspiele) ein, für eine bestimmte Altersgruppe oder die Art der Person (z.B. 20 Jahre alt, Studenten) oder für ein bestimmtes Land Sprache. Sie finden <a href="http://'.DOMAIN.'/groups.">hier bereits die vorhandenen Gruppen</a>',
     'az' => 'nur A-Z, a-z, 0-9, _ erlaubt. z.B.: EmoPlace',
     'grpwarn' => '<p>Ihre Gruppe kann ohne Vorwarnung entfernt oder geändert werden, wenn:</p>
<p>Sie keine gültige E-Mail Adresse angegeben haben<br>
 der Gruppenname unangemessen ist (siehe <a href="http://www.'.DOMAIN.'/terms.html" target="_blank">Nutzungsbedingungen</a>)<br>
 die Gruppe wird nicht benutzt oder wird nicht moderiert</p>',
     'iam14' => 'Ich bin 14 Jahre oder älter und stimme den <a href="http://www.'.DOMAIN.'/terms.html" target="_blank">Nutzungsbedingungen</a> zu',
     'sendfbk' => 'Senden Sie einen Kommentare an den Gruppen Besitzer',
     'contact' => 'Sie können hier den Chat Besitzer von der %s Gruppe kontaktieren. Besitzer sind nicht verpflichtet zu antworten, aber wenn Sie keine E-Mail Adresse angeben, ist dies auch nicht möglich.',
     'grpmess1' => ''.XAT_NAME.' Gruppe: %s - Nachricht',
     'grpmes2' => 'Hello %s Ein Besucher Ihrer Chat Gruppe %s hat den Nachricht Button geklickt und Ihnen folgende Nachricht gesendet. (SIE SOLLTEN NICHT AUF LINKS KLICKEN).',
     'noemail' => 'Der Benutzer hat seine E-Mail-Adresse nicht angegeben',
     'thxsent' => 'Vielen Dank. Ihre Nachricht wurde gesendet',
     'optemail' => 'Optional, aber Sie werden keine Antwort erhalten, wenn Sie keine E-Mail Adresse eingeben.',
     'message' => 'Nachricht',
     'send' => 'Senden',
     'grpmess2' => 'Hello %s Ein Besucher Ihrer Chat Gruppe %s hat den Nachricht Button geklickt und Ihnen folgende Nachricht gesendet. (SIE SOLLTEN NICHT AUF LINKS KLICKEN).',
     'reportgrp' => 'Einen unangemessenen Chat melden',
     'plzsel' => 'Bitte auswählen ..',
     'badlang' => 'Beleidigende Sprache',
     'scamming' => 'Betrügereien, Phishing oder Häcker',
     'badimg' => 'Unangebrachte Bilder oder Videos',
     'bully' => 'Belästigung, Cybermobbing, Betrüger',
     'unwanted' => 'Unerwünschter Kontakt',
     'otherissue' => 'Sonstige Verstöße der Nutzungsbedingungen (bitte angeben)',
     'readcare' => 'Wichtig: Bitte lesen Sie sorgfältig, bevor Sie ein unangemessen melden',
     'mustsel' => 'Sie müssen eine entsprechende Kategorie wählen',
     'bademail' => 'E-Mail ist nicht gültig',
     'mustchars' => 'muss mindestens 8 Zeichen beinhalten',
     'complaint' => 'Beschwerde:',
     'bedetailed' => '(Bitte so detailliert wie möglich um uns so gut zu unterstützen wie möglich)',
     'nonotify' => 'Sie werden wahrscheinlich nicht über die Ergebnis der Meldung oder jeder Maßnahme informiert.',
     'repimg' => 'Bilder melden',
     'canreport' => 'Sie können etwas als unangebracht melden wenn es gegen unsere <a href="http://'.DOMAIN.'/terms.html">Nutzungsbedingungen verstößt.</a>.
Wenn Sie glauben, dass etwas anderes unangebracht ist, benutzen Sie bitte die Box unten, um uns zu sagen, warum. Wie auch immer,
'.XAT_NAME.' wird nicht bei streitigkeiten zwischen Benutzern helfen. Bitte melden Sie nicht ohne einen guten Grund,
wenn Sie dies kontinuierlich tun, könnten Sie von der Nutzung unseres Dienstes gesperrt werden.',
     'addinfo' => 'Zusätzliche Informationen: <br> (Bitte so detailliert wie möglich, um uns so gut wie möglich zu Unterstützen)',
     'reportpro' => 'Melden Sie einen unangemessenes xatspace (Profil)',
     'repuser' => 'Benutzer melden',
     'grpknown' => 'Gruppe (falls bekannt)',
     'postcom' => 'Einen Kommentar hinzufügen',
     'todelete' => 'Sie müssen ein Eigentüme sein, um einen Kommentar zu löschen',
     'topost' => 'Sie müssen Mitglied sein, um einen Kommentar schreiben zu können',
     'confdel' => 'Löschen des Kommentars bestätigen',
     'typecom' => 'Geben Sie hier Ihren Kommentar ein. Sie können einfache HTML Codes und Bilder hinzufügen. (Grenzwert 5000 bytes)',
     'delcom' => 'Kommentar löschen',
     'savcom' => 'Kommentar speichern',
     'activategrp' => 'Chat-Gruppe aktivieren',
     'expired' => 'Ihre Gruppe Anwendung ist abgelaufen. Sie könnten es erneut versuchen.',
     'already' => 'Diese Gruppe wurde bereits aktiviert.',
     'taken' => 'Leider wurde diese Gruppe bereits übernommen. Sie können es mit einem anderen Gruppen Namen erneut versuchen.',
     'activated' => 'Ihre Gruppe wurde nun aktiviert! Überprüfe deine E-Mails für weitere Details. Ihre Gruppe-Adresse lautet:',
     'grpok1' => 'Gruppen aktivierung für %s ist abgeschlossen',
     'grpok2' => 'Hello %s,

Ihre Chat Gruppe $name wurde aktiviert.
Der Link für deine Gruppe lautet: %s

Um Ihre %s Chat Gruppe zu bearbeiten, müssen Sie den Edit Buuton unten rechts in ihrer Gruppe anklicken und Ihr Chat Passwort eingeben. Um Ihren Besitzer Status wiederherzustellen, klicken Sie den Chat Box bearbeiten Button.

Um Ihre Gruppe in eine peronalisierte CHat Box einzufügen, klicken Sie Ihren Chat ändern -gt Gruppen, schreib %s in die Box und klicken Sie den Erhalten Button.

Wenn Ihre Gruppe die Nutzungsbedingungen %s nicht einhält oder inaktiv ist, kann diese dann geändert oder gelöscht werden. Einzelpersonen sind verantwortlich für das, was sie in der Chat Box schreiben aber Ihre Gruppen Moderatoren sollten alles machen was sie können, damit die Benutzer die Nutzungsbedingungen einhalten.

Genießen Sie Ihren Chat und viel Glück!

xat',
     'seachchat' => 'Im Chat suchen',
     'searchinfo' => 'Private Chats, Private Nachrichten, Nur Mitglieder, nicht gelistete Chats und nicht speichern Chats können nicht durchsucht werden. <a href="http://util.'.DOMAIN.'/wiki/index.php/Search">Mehr Informationen</a>',
     'moreinfo' => 'Mehr Informationen.',
     'nores' => 'Leider keine Ergebnisse',
     'moreresults' => 'Mehr Ergebnisse',
     'minsago' => 'Minuten zuvor auf',
     'hoursago' => 'Stunden zuvor auf',
     'searchingfor' => 'Suche nach:',
     'results' => 'Ergebnisse',
     'search' => 'Suchen',
     'mustbe' => 'muss mindestens',
     'letters' => 'Zeichen',
     'unfair' => 'Unfair verbannt',
     'noctrl' => 'Werbung: Unangemessen oder außer Kontrolle',
     'addcom' => 'Kommentar hinzufügen',
     'dispcom' => 'Kommentar anzeigen',
     'delete' => 'löschen',
     'news' => 'Neuigkeiten',
     'events' => 'Ereignisse',
     'inapp' => 'unangemessen',
     'comments' => 'Kommentare',
     'grid' => 'Raster',
     'player' => 'Spieler
 : doodle',
     'translate' => 'übersetzen',
     'games' => 'Spiele',
     'apps' => 'Apps',
     'embed' => 'Einbetten',
     'chglang' => 'Sprache wechseln',
     'sellang' => 'Wählen Sie die Sprache aus:',
     'eventsfor' => 'Chat Ereignisse für',
     'oldres' => 'Ältere Ergebnisse',
     'duration' => 'Dauer',
     'text' => 'Text',
     'canevents' => 'Sie können nach Chat Ereignissen suchen (siehe <a href="http://util.'.DOMAIN.'/wiki/index.php/Events">Wiki</a> )',
     'all' => 'Alle',
     'time' => 'Zeit',
     'emailsent' => 'E-Mail gesendet',
     'needlogin' => 'Bitte <a href="http://'.DOMAIN.'/login">loggen Sie sich ein</a> , um diese Seite zu nutzen.',
     'needevents' => 'Entschuldigung, Sie benötigen die Event Power um diese Seite zu nutzen.',
     'nodays' => 'Entschuldigung, ihre Abonnenten Tage sind abgelaufen',
     'continue' => 'Weiter',
     'name' => 'Name',
     'grassmod' => 'Moderator melden',
     'feelunfair' => 'Wenn Sie glauben, das Sie ein Moderator unfair behandelt, können Sie diesen an den Chat Besitzer melden. Eigentümer sind nicht verpflichtet, die E-Mails zu beantworten, aber sie wird sicherlich nicht beantwortet, wenn Sie eine falsche E-Mail Adresse eingeben.',
     'modrpt1' => ''.XAT_NAME.' Gruppe: %s - Moderator melden',
     'modrpt2' => 'Hallo %s, 

Sie erhalten diese Meldung, da jemand einen Moderator in Ihrem Chat gemeldet hat',
     'modrpt3' => '\n\nKlick hier: %s, um ein Protokoll der Ereignisse zu sehen.',
     'transcript' => 'Chatprotokoll',
     'youneed' => '<p>Sie müssen sicherstellen, dass Ihre Moderatoren einen guten Job machen und fair zu den Besuchern sind. Es braucht nur einen schlechten Moderatorm um Ihren Chat zu ruinieren. Wenn Ihre Moderatoren gut sind, gewinnt Ihr Chat immer mehr an Beliebtheit</p> <p>Bitte sehen Sie sich die Beschwerde an und wenn Sie über den Moderator unglücklich sind, sprechen Sie mit ihm darüber oder stufen ihn herab.</p>',
     'banby' => 'wurde verboten von',
     'clkunmod' => 'Klicken, um den Moderator herabzustufen',
     'unfriendly' => '<p>Hinweis: Deine Gruppe kann von den Listen entfernt werden, wenn Ihre Moderatoren nicht freundlich sind. z.B. wird Ihr Chat dann nicht in der Beliebtheitsliste angezeigt</p>',
     'transno' => 'Chatverlauf nicht vorhanden. Diese wurde möglicherweise gelöscht. Chatverläufe werden für eine Woche gespeichert.',
     'unmod' => 'Moderator herunterstufen',
     'yesunmod' => 'Ja - UnModerate',
     'sureunmod' => 'Sind Sie sicher, dass Sie diesen Benutzer herabstufen wollen:',
     'chatconf' => 'Bitte bestätigen Sie, das Sie diesen Benutzer Gast machen wollen',
     'tounmod' => 'Klicken Sie oben auf den Link um Un-Mod',
     'istrans' => 'Unten ist eine Mitschrift von den Nachrichten im Vorfeld des Verbots',
     'chatid' => 'Chat ID:',
     'seeall' => 'Sie können alle Bilder der Gruppe hier sehen und diese einfach an den Bild-Hoster melden.'	 
	 ]
?>