<?php
$array = [
     'groups' => 'Gruppen',
     'store' => 'Laden',
     'buyxats' => 'Kauf xats und Abo-Tage',
     'powers' => 'Powers',
     'xavi' => 'xavis',
     'xatgroup' => ''.XAT_NAME.' Gruppen',
     'shortname' => 'Kurzname',
     'promotion' => 'Werbung',
     'auctions' => 'Auktionen',
     'community' => 'Community',
     'more' => 'Mehr',
     'twitter' => 'Twitter',
     'wiki' => 'Wiki',
     'support' => 'Support',
     'contact' => 'Kontakt',
     'help' => 'Hilfe',
     'trade' => 'Handel',
     'widgets' => 'Widgets',
     'login' => 'Einloggen',
     'language' => 'Sprache',
     'privacy' => 'Datenschutz',
     'terms' => 'Nutzungsbedingungen',
     'safety' => 'Sicherheit',
     'failed' => 'fehlgeschlagen',
     'evalid' => 'E-Mail ist nicht gültig',
     'recaperr' => 'Die reCAPTCHA wurde nicht korrekt eingegeben. Bitte versuchen Sie es erneut.(reCAPTCHA meldete',
     'notbot' => 'und um zu überprüfen, das Sie kein Bot sind',
     'numinbox' => 'Bitte geben Sie diese Nummer in die Box ein',
     'cancel' => 'Abbrechen',
     'submit' => 'Senden',
     'wrongnum' => 'Falsche Nummer eingegeben!',
     'ayaherr' => 'Sie müssen beweisen, dass Sie ein mensch sind.'
	 ]
?>