<?php
$array = [
     'quizq1' => 'Du erhältst eine Nachricht von einer Person, die vorgibt, Volunteer zu sein. Diese Person sagt, dass dein Account gesperrt ist und um das Problem zu beheben, musst du dein Passwort und deine E-Mail Adresse geben, andernfalls wird die Sperre beibehalten. Was machst du?',
     'quizq1a1' => 'Du gibst keinerlei Information.',
     'quizq1a2' => 'Du willst dein '.XAT_NAME.' Account nicht verlieren, daher gibst du Ihnen deine Information.',
     'quizq1a3' => 'Du fragst nach Beweisen, dass es sich um einen echten Volunteer handelt.',
     'quizq1info' => 'Korrekt! '.XAT_NAME.' Mitarbeiter und Volunteer werden die nie nach persönlichen Informationen im Private Chat fragen. Melde diesen Benutzer indem du Screenshots von deren ID und Nachricht aufnimmst und öffne ein Ticket unter der Report Scam Hilfe-Thema.',
     'quizq1image' => '<br img src="https://util.'.DOMAIN.'/wiki/images/f/f9/Securityimage1.png" class="img-fluid"/>',
     'quizq2' => 'Du bist in einem Handels-Chat um Days zu kaufen. Eine Person kontaktiert dich, welche dich fragt, ob du die xats per Transfer schicken kannst. Was machst du?',
     'quizq2a1' => 'Lehne ab und schlage vor die Safe-Trade App zu benutzen, welche die empfohlene Methode ist.',
     'quizq2a2' => 'Überreiche deine xats als erstes.',
     'quizq2a3' => 'Frage erst nach Ihren Days stattdessen.',
     'quizq2info' => 'Das ist richtig! Beim Kauf und Verkauf von xats, Days und Powers solltest du immer die Safe-Trade App benutzen. Durch diese Applikation kannst du in Echtzeit sehen, was verhandelt wird. Handele nie über die Transfer Funktion, da Geschäfte nicht rückgängig gemacht werden können, wenn sie abgeschlossen wurden.',
     'quizq2image' => '<br img src="https://util.'.DOMAIN.'/wiki/images/c/c0/Securityimage2.png" class="img-fluid"/>',
     'quizq3' => 'Dein E-Mail Anbieter bietet die Zwei-Faktor-Authentifizierung Sicherung an. Solltest du diese Option aktivieren?',
     'quizq3a1' => 'Ja. Dies wird den Schutz meiner E-Mail Adresse erheblich erhöhen.',
     'quizq3a2' => 'Nein. Mein Passwort ist stark genug.',
     'quizq3a3' => 'Niemals. Dieser Schutz ist nicht nützlich.',
     'quizq3info' => 'Korrekt! Zwei-Faktor-Authentifizierung fügt deiner E-Mail Adresse eine weitere Schutzschicht hinzu (mit dem Handy), um sicherzustellen, dass niemand außer dir auf deine E-Mail zugreifen kann - sogar wenn dein Password gehackt wird.<br><br>Bitte kontaktiere deinen E-Mail Anbieter für Anleitungen, wie du die Authentifikation bei deiner E-Mail aktivierst. Für Gmail Accounts, siehe <a href="https://www.google.com/landing/2step/" target="_blank">diese Seite</a>.',
     'quizq3image' => '<br img src="https://util.'.DOMAIN.'/wiki/images/7/71/Securityimage3.png" class="img-fluid"/>',
     'quizq4' => 'Dir wurde über ein Update auf der '.XAT_NAME.' Login Seite erzählt. Der Benutzer sendet dir ein Link um es zu testen, welches https://xaatt.com/login ist. Was machst du?',
     'quizq4a1' => 'Klicke nicht auf den Link, da dieser kein https://'.DOMAIN.' Domain ist.',
     'quizq4a2' => 'Klicke es an, um zu sehen was sich geändert hat.',
     'quizq4info' => 'Korrekt! Überprüfe immer die Addressleiste, um sicher zu gehen, dass du dich auf einem <a href="https://'.DOMAIN.'" target="_blank">https://'.DOMAIN.'</a> Domain befindest, bevor dich einloggst, einen Chat besuchst oder jegliche '.XAT_NAME.' Informationen eingibst.',
     'quizq4image' => '<br img src="https://util.'.DOMAIN.'/wiki/images/7/7d/Securityimage4.png" class="img-fluid"/>',
     'quizq5' => 'Ein Benutzer bietet dir an deine Powers zu verdoppeln, aber dazu musst du erst deine Powers senden. Was machst du?',
     'quizq5a1' => 'Powers können nicht dupliziert werden. Du übergibst nicht deine Powers.',
     'quizq5a2' => 'Akzeptiere das Angebot. Doppelte Powers heißt doppelter Profit.',
     'quizq5a3' => 'Frage nach Beweisen, ob sie deine Powers verdoppeln können.',
     'quizq5info' => 'Gut gemacht! xats, Days und Powers können nicht dupliziert werden. Betrüger benutzen oft diese Herangehensweise, um leicht deine Aufmerksamkeit und deine Powers zu gewinnen. Melde diesen Benutzer indem du Screenshots von deren ID und Nachricht aufnimmst und öffne ein Ticket unter der Report Scam Hilfe-Thema.',
     'quizq5image' => '<br img src="https://util.'.DOMAIN.'/wiki/images/3/35/Securityimage5.png" class="img-fluid"/>',
     'quizq6' => 'Du erhältst eine E-Mail von info@'.DOMAIN.', worin steht, dass deine Powers persönlich von einem '.XAT_NAME.' Mitarbeiter überprüft werden müssen. Die Anweisungen sagen, dass du die Powers zu einer bestimmten Person in einem Chat übergeben sollst. Wenn du ablehnst, wird dein Account für 3 Monate gesperrt. Was machst du?',
     'quizq6a1' => 'Ignoriere die E-Mail und melde es als Spam.',
     'quizq6a2' => 'Akzeptiere ohne jegliches Infragestellen. Keine Sperre, bitte!',
     'quizq6a3' => 'Antworte auf die E-Mail und frage nach mehr Information.',
     'quizq6info' => 'Das ist richtig! Du wirst nie eine E-Mail dieser Art von '.XAT_NAME.' erhalten. Jede Benachrichtigung bezüglich deines '.XAT_NAME.' Accounts läuft über das Support System auf <a href="https://'.DOMAIN.'/ticket" target="_blank">'.DOMAIN.'/ticket</a> und nirgendwo anders.',
     'quizq6image' => '<br img src="https://util.'.DOMAIN.'/wiki/images/3/3b/Securityimage6.png" class="img-fluid"/>',
     'quizq7' => 'Jeder weiß, dass Passwörter schwer zu merken sind. Um dein Leben somit leichter zu gestalten, entscheidest du dich dazu das selbe Passwort für deine E-Mail Adresse und deinen '.XAT_NAME.' Account zu benutzen. Ist dies sicher?',
     'quizq7a1' => 'Nein!',
     'quizq7a2' => 'Garantiert ja. Damit du nie das Problem hast, dein Passwort vergessen zu haben.',
     'quizq7info' => 'Du hast recht! Schwierigkeit kann sich belohnen. Benutze immer unterschiedliche Passwörter für jedes deiner Online Accounts, um den Schutz zu erhöhen.',
     'quizq7image' => '<br img src="https://util.'.DOMAIN.'/wiki/images/2/2b/Securityimage7.png" class="img-fluid"/>',
     'quizq8' => 'Du erfährst über einen Generator für kostenlose xats, dass heruntergeladen werden muss. Was machst du?',
     'quizq8a1' => 'Du weißt, dass xats nicht generiert werden können, daher ignorierst du dies.',
     'quizq8a2' => 'Frage nach mehr Information.',
     'quizq8a3' => 'Frage nach Beweisen, dass xats generiert werden können.',
     'quizq8info' => 'Du hast Recht! xats können nicht kostenlos erzeugt werden! Sei vorsichtig, dass du keine unbekannten Programme herunterlädst, da diese schädliche Software (Virus) enthalten können.',
     'quizq8image' => '<br img src="https://util.'.DOMAIN.'/wiki/images/5/5c/Securityimage8.png" class="img-fluid"/>',
     'quizq9' => 'Du erhältst eine Nachricht, dass dein Account in 24 Stunden gesperrt wird, außer du bezahlst 10000 xats. Was machst du?',
     'quizq9a1' => 'Du schickst keine xats und ignorierst diesen Benutzer.',
     'quizq9a2' => 'Sperre? Auf keinen Fall! Ich bezahle die Geldstrafe.',
     'quizq9a3' => 'Frage nach einer Erklärung.',
     'quizq9info' => 'Korrekt! '.XAT_NAME.' Mitarbeiter und Volunteer werden nie nach xats fragen. Melde diesen Benutzer indem du Screenshots von deren ID und Nachricht aufnimmst und öffne ein Ticket unter der Report Scam Hilfe-Thema.',
     'quizq9image' => '<br img src="https://util.'.DOMAIN.'/wiki/images/b/b4/Securityimage9.png" class="img-fluid"/>',
     'quizq10' => 'Dir wird ein teures Angebot von 50000 xats für deine Powers unterbracht. Während dem Handel gibt es mehrmals Fehlversuche mit Fehlern wie Falsches Passwort. Was machst du?',
     'quizq10a1' => 'Sage dem Benutzer respektvoll, dass du den Handel neu starten willst.',
     'quizq10a2' => 'Ignoriere die Probleme und führe mit dem Handel fort.',
     'quizq10a3' => 'Ignoriere den Benutzer.',
     'quizq10info' => 'Korrekt! Betrüger versuchen deine xats, Days oder Powers zu stehlen, indem sie die Anzahl der xats, Days oder Powers in der App ändern.<br><br>Sei immer vorsichtig und überprüfe nach Fehlversuchen mehrmals, ob sich alle Powers noch in der App befinden. Überprüfe die Eingaben in der Trade App ein zusätzliches mal, bevor du den Handel bestätigst.',
     'quizq10image' => '<br img src="https://util.'.DOMAIN.'/wiki/images/a/a2/Securityimage10.png" class="img-fluid"/>',
     'quizq11' => 'Du erhältst von einer Person im Forum eine Private Nachricht, die behauptet ein '.XAT_NAME.' Mitarbeiter zu sein. Laut der Nachricht sollst du deine Account Daten (Password und E-Mail) übermitteln, andernfalls wird dein Account von '.XAT_NAME.' gesperrt. Was machst du?',
     'quizq11a1' => 'Ignoriere den Benutzer und melde es den Forum Mitarbeitern.',
     'quizq11a2' => 'Antworte der Nachricht mit deinen Account Details.',
     'quizq11a3' => 'Frage nach mehr Information zu der Sperre.',
     'quizq11info' => 'Korrekt! '.XAT_NAME.' Mitarbeiter und Volunteer werden dich nie privat zu Problemen mit deinem '.XAT_NAME.' Account, wie z. B. einer Sperre, kontaktieren. Alle Probleme mit Accounts werden im Support System auf <a href="https://'.DOMAIN.'/ticket" target="_blank">'.DOMAIN.'/ticket</a> behandelt und du solltest unangemessene und schädliche Privat-Nachrichten melden.',
     'quizq11image' => '<br img src="https://util.'.DOMAIN.'/wiki/images/7/7a/Securityimage11.png" class="img-fluid"/>',
     'quizq12' => 'Dir wird durch einen '.XAT_NAME.' Mitarbeiter auf einem Chat gesagt, dass du die Zwei-Faktor-Authentifizierung von deiner E-Mail deaktivieren solltest. Was machst du?',
     'quizq12a1' => 'Lehne ab und ignoriere es.',
     'quizq12a2' => 'Schalte die Zwei-Faktor-Authentifizierung aus.',
     'quizq12info' => 'Ja, du hast recht! '.XAT_NAME.' Mitarbeiter und Volunteer werden dich unter keinen Umständen danach fragen die Zwei-Faktor-Authentifizierung zu deaktivieren. Zögere nicht Benutzer zu melden, welche dich dazu bringen wollen, deinen Account Schutz zu deaktivieren.',
     'quizq12image' => '<br img src="https://util.'.DOMAIN.'/wiki/images/4/45/Securityimage12.png" class="img-fluid"/>',
     'quizq13' => 'Dir wird von einem Generator auf einer Webseite erzählt, die kostenlose xats erzeugt. Aber um kostenlose xats zu erzeugen, musst du dein Passwort und deine E-Mail Adresse eingeben. Was machst du?',
     'quizq13a1' => 'Ignoriere diese Webseite, das du weißt, dass man xats nicht kostenlos generieren kann.',
     'quizq13a2' => 'Fahre fort und logge dich ein.',
     'quizq13a3' => 'Frage nach Beweisen, dass xats generiert werden können.',
     'quizq13info' => 'Du hast Recht! xats können nicht kostenlos erzeugt werden: Außerdem, gebe dein '.XAT_NAME.' Passwort nur auf offiziellen <a href="https://'.DOMAIN.'" target="_blank">https://'.DOMAIN.'</a> Seiten ein. Überprüfe immer die Adressleiste, um sicher zu stellen, dass du auf <a href="https://'.DOMAIN.'" target="_blank">'.DOMAIN.'</a> bist.',
     'quizq13image' => '<br img src="https://util.'.DOMAIN.'/wiki/images/5/57/Securityimage13.png" class="img-fluid"/>',
     'quizq14' => 'Du hast ein Geschäft ausgehandelt, um die Powers von einem Benutzer im Trade Chat zu kaufen. Der Benutzer gibt an, dass er die Hälfte der Powers jetzt und den Rest später übergeben will. Was machst du?',
     'quizq14a1' => 'Lehne das Angebot ab - sie sollten alle Artikel jetzt hinzufügen.',
     'quizq14a2' => 'Akzeptiere das Angebot. Nichts kann falsch laufen.',
     'quizq14a3' => 'Frage nach Beweisen, dass sie die verbleibenden Powers haben.',
     'quizq14info' => 'Korrekt! Betrüger können versuchen Geschäfte zu entzerren, indem sie einen Betrag im Voraus anbieten und versprechen, dass restliche in der Zukunft zu bezahlen. Glaube nie solchen Benutzern und akzeptiere nur den vereinbarten Betrag in einem einzigen Trade. Der Benutzer wird dir wohl kaum den Rest im Nachhinein geben.',
     'quizq14image' => '<br img src="https://util.'.DOMAIN.'/wiki/images/5/59/Securityimage14.png" class="img-fluid"/>',
     'quizq15' => 'Dir wird von einem kostenlosen Programm erzählt welches animierte Avatare (gifs) erstellt. Eine Person schickt dir auf einem Chat den Download Link für das Programm, welches sich auf einer unbekannten Webseite befindet. Was machst du?',
     'quizq15a1' => 'Lade niemals unbekannte Dateien herunter, da diese Viren enthalten können.',
     'quizq15a2' => 'Lade es unbedacht herunter.',
     'quizq15info' => 'Korrekt! Betrüger locken die dazu ihre Viren herunterzuladen, indem sie vorgeben ein hilfsbereiter Freund zu sein. Sei vorsichtig keine unbekannten Dateien herunterzuladen. Ein paar Tipps um zu vermeiden, dass schädliche Sachen heruntergeladen werden.<br><br ol><li>Suche den Dateinamen auf Google (Programm Glaubwürdigkeit und ob es überhaupt existiert).</li><li>Suche nach alternativen Quellen zum Download.</li><li>Führe ein Virenscan über die Datei durch.</li></ol>',
     'quizq15image' => '<br img src="https://util.'.DOMAIN.'/wiki/images/1/19/Securityimage15.png" class="img-fluid"/>',
     'quizq16' => 'Eine Person, welche du auf einem Chat getroffen hast, fragt dich nach private Informationen wie deinem Namen, deiner Straße oder deiner E-Mail Adresse. Was machst du?',
     'quizq16a1' => 'Ändere das Thema, indem du sagst, dass du nicht über deine private Informationen reden willst.',
     'quizq16a2' => 'Sie scheinen cool genug zu sein, beantworte daher die die Fragen zu deinen privaten Informationen.',
     'quizq16a3' => 'Ignoriere den Benutzer.',
     'quizq16info' => 'Gut gemacht! Du solltest deine persönlichen Informationen mit keinem online teilen. Teile niemals deine E-Mail Adresse oder dein Passwort mit.',
     'quizq16image' => '<br img src="https://util.'.DOMAIN.'/wiki/images/d/d9/Securityimage16.png" class="img-fluid"/>',
     'quizq17' => 'Dir wird auf einem Chat über ein Problem mit deinem '.XAT_NAME.' Account mitgeteilt und um es zu beheben, solltest du den Account Schutz auf der '.XAT_NAME.' Login Seite ausschalten. Was machst du?',
     'quizq17a1' => 'Schalte niemals den Account Schutz aus, wenn du danach gefragt wirst.',
     'quizq17a2' => 'Du vertraust jedem Fremden. Du loggst dich ein und schaltest den Schutz aus.',
     'quizq17a3' => 'Frage nach weiteren Informationen, bevor du ihre Anfrage in Erwägung ziehst.',
     'quizq17info' => 'Korrekt! Dein '.XAT_NAME.' Account Schutz sollte unter keinen Umständen ausgeschaltet werden. '.XAT_NAME.' Mitarbeiter und Volunteer werden dich nie bitten deinen Schutz auszuschalten.',
     'quizq17image' => '<br img src="https://util.'.DOMAIN.'/wiki/images/a/ab/Securityimage17.png" class="img-fluid"/>',
     'quizq18' => 'Einer deiner Freunde fragt dich, ob sie dein Namecolor Power für eine bestimmte Zeit ausleihen können, da sie die Effekte testen wollen. Was machst du?',
     'quizq18a1' => 'Du gibst es nicht. Es gibt immer eine Chance, dass du es nicht wieder erhältst.',
     'quizq18a2' => 'Man kann es ruhig ausleihen. Du kannst deine Powers jederzeit zurück erhalten.',
     'quizq18a3' => 'Beste Freunde für immer. Du öffnest die Trade App ohne Bedenken!',
     'quizq18info' => 'Das ist richtig! Deine xats, Days und Powers sind deine alleinige Verantwortung. Ausleihen existiert auf '.XAT_NAME.' nicht und wird so gesehen, dass du es weggabst. Wenn du ein Handel oder Transfer abschließt, kannst es nicht rückgängig gemacht werden. Sei stets vorsichtig. <a href="//util.'.DOMAIN.'/wiki/index.php?title=Special:MyLanguage/Trading" target="_blank">Lese mehr dazu hier.</a>',
     'quizq18image' => '<br img src="https://util.'.DOMAIN.'/wiki/images/1/17/Securityimage18.png" class="img-fluid"/>',
     'quizq19' => 'Du erhältst eine Nachricht von info@'.DOMAIN.', welches dir mitteilt, dass du erfolgreich 100000 xats erworben hast. Es gibt auch an, dass du die Bezahlung bestätigen musst, indem du auf einen Link klickst. Der Link leitet dich auf eine Seite, wo du 100$ bezahlen sollst, damit du letztendlich deine xats erhältst. Was machst du?',
     'quizq19a1' => 'Dies ist ein merkwürdiges Angebot. Wenn ich erfolgreich xats erworben habe, wieso muss ich noch mehr bezahlen? Du blockst die E-mail, da es ein Betrug ist.',
     'quizq19a2' => 'The E-mail kommt von info@'.DOMAIN.' aber 100$ sind eine Menge Geld. Du antwortest und fragst nach mehr Information.',
     'quizq19a3' => 'Du hattest nicht geplant xats zu kaufen, aber 100000 xats für 100$ ist ein guter Deal. Nicht wie ran!',
     'quizq19info' => 'Korrekt! '.XAT_NAME.' wird dich NIE in einer E-Mail fragen, ob du xats kaufen willst, und der einzige sichere Ort, wo du xats für echtes Geld kaufen kannst, ist auf <a href="https://'.DOMAIN.'/buy">https://'.DOMAIN.'/buy</a>. Manche Betrüger können '.XAT_NAME.' E-Mail Adressen fälschen, daher solltest du nie fortfahren, auch wenn info@'.DOMAIN.' angezeigt ist. Nichtsdestotrotz, wenn der Deal als zu gut erscheint, um wahr zu sein, dann ist es normalerweise auch so, und du wirst sehr wahrscheinlich betrogen.',
     'quizq19image' => '<br img src="https://util.'.DOMAIN.'/wiki/images/f/fe/Securityimage19.png" class="img-fluid"/>',
     'start' => 'Quiz starten',
     'desc' => 'Um das <a href="//util.'.DOMAIN.'/wiki/index.php?title=Special:MyLanguage/Tickle" target="_blank">Tickle</a> Power kostenlos zu erhalten, musste du das Quiz unten abschließen und jedes der Fragen richtig beantworten.',
     'wronganswer' => 'Dies ist inkorrekt. Bitte versuche es nochmal.',
     'next' => 'weiter',
     'continuein' => 'Fortsetzung in',
     'gratz' => 'Glückwunsch, du hast das Quiz komplett abgeschlossen! Du solltest dich nun über Sicherheit auf '.XAT_NAME.' auskennen.',
     'tickle' => 'Sie haben das Tickle Power erhalten.',
     'redirect' => 'Bitte warte während du zur Login Seite weitergeleitet wirst.'
	 ]
?>