<?php
$array = [
     'groups' => 'مجموعات',
     'store' => 'المتجر',
     'buyxats' => 'و ايام xats اشتري',
     'powers' => 'القوي',
     'xavi' => 'xavis',
     'xatgroup' => ''.XAT_NAME.' مجموعات',
     'shortname' => 'اسم صغير',
     'promotion' => 'الترقيه',
     'auctions' => 'مزاد',
     'community' => 'المجتمع',
     'more' => 'مزيد',
     'twitter' => 'Twitter',
     'wiki' => 'Wiki',
     'support' => 'الدعم',
     'contact' => 'الأتصال',
     'help' => 'مساعده',
     'trade' => 'تجاره',
     'widgets' => 'الحاجيات',
     'login' => 'دخول',
     'language' => 'اللغه',
     'privacy' => 'الخصوصية',
     'terms' => 'الشروط',
     'safety' => 'الأمان',
     'failed' => 'فشل',
     'evalid' => 'البريد الالكتروني غير صالح',
     'recaperr' => 'لم دخلت اختبار reCAPTCHA بشكل صحيح. يرجى المحاولة مرة أخرى. (قال اختبار reCAPTCHA',
     'notbot' => 'وللتحقق من أنك لست بوت',
     'numinbox' => 'من فضلك ادخل الأرقام التي بالمريع',
     'cancel' => 'إلغاء',
     'submit' => 'عرض',
     'wrongnum' => '!تم ادخال رقم خطأ',
     'ayaherr' => 'تحتاج إلى إثبات أنك الإنسان.'
	 ]
?>