<?php
$array = [
     'creategroup' => 'Crea chat',
     'badpass' => 'Password della chat sbagliata.',
     'modrules' => 'modificato per rispettare le regole',
     'access' => 'access the existing groups here',
     'yourname' => 'Il tuo nome:',
     'desc' => 'Descrizione chat:',
     'let2050' => '(20-50 lettere)',
     'grt6' => 'Almeno 6 lettere, maiuscole e minuscole - NON CONDIVIDERLA (la password serve soltanto per la modifica della chat)',
     'noshare' => 'NON CONDIVIDERLA',
     'passonly' => '(la password serve soltanto per la modifica della chat)',
     'tags' => 'Parole chiave:',
     'sepcom' => '(separate da virgole)',
     'taginfo' => 'Le parole chiave servono a descrivere la tua chat in modo che gli altri utenti possano trovarla facilmente. Per esempio: una chat basata sulle corse d’auto può essere descritta come: auto,corse,competizioni. Se la lingua della chat non è l’Inglese, specificare la lingua, per esempio: Italiano.',
     'mustvalid' => 'QUESTO INDIRIZZO MAIL DEVE ESSERE VALIDO PER POTER ATTIVARE LA TUA CHAT.',
     'grpres' => 'Il nome della chat è riservato',
     'grpexist' => 'Il nome della chat esiste già',
     'urlinfo' => 'Facoltativo - Link del sito web che pubblicizzerà questa chat',
     'grpac1' => '<p>Grazie. La tua richiesta di creazione della chat è stata elaborata.<br />
È stata inviata una mail di conferma. Clicca sul link che troverai all’interno di essa per attivare la tua chat.</p>
<p><strong>NOTA BENE: se non ricevi nessuna mail, controlla la cartella di spam.</strong></p>
<p><strong>(la ricezione della mail può richiedere fino a 30 minuti)</strong></p>
<p>Se non riesci a trovare la mail puoi compilare nuovamente la pagina di richiesta di creazione della chat usando un provider email che funzioni. Prova usando un account <a href="https://gmail.com">Gmail</a>. Se il provider di email non consegna le nostre email, non sarai in grado di attivare la tua chat.</p>',
     'grpac2' => 'Attiva la tua chat:%s',
     'grpac3' => 'Ciao %s,

Clicca sul link qui sotto per attivare la chat %s e diventare il proprietario:

%s

(NOTA BENE: il nome della chat non sarà riservato e la chat non sarà attivata fino a che non verrà fatto click sul link)

Sarà inviata un’altra email per la conferma dell’attivazione della chat.',
     'grpinfo' => 'Le chat sono stanze condivise, con uno scopo specifico. Potrebbero parlare di argomenti specifici (ad esempio: musica, anime, videogiochi), potrebbero essere adatti ad un gruppo specifico di età o tipo di persone (ad esempio: 20enni, studenti) o per un paese/lingua specifica. Puoi <a href="//'.DOMAIN.'/groups">entrare nelle chat esistenti da qui</a>',
     'az' => 'solo A-Za-z0-9_ ad esempio: La_Stanza',
     'grpwarn' => '<p>La tua chat potrebbe essere rimossa senza avviso o modificata se:</p>
<p>Non fornisci un indirizzo mail valido<br>
 Il nome della chat scelto risulti inappropriato (vedi i <a href="//'.DOMAIN.'/terms" target="_blank">Termini di Servizio</a>)<br>
 La tua chat non sarà usata o non sarà moderata a dovere</p>',
     'iam14' => 'Ho più di 14 anni ed accetto i <a href="//'.DOMAIN.'/terms" target="_blank">Termini di Servizio</a>',
     'sendfbk' => 'Invia un messaggio al proprietario della chat',
     'contact' => 'Se desideri contattare il proprietario della chat %s, puoi farlo da qui. I proprietari non sono obbligati a rispondere ai messaggi che ricevono ma sicuramente non lo faranno se non fornirai un indirizzo mail valido.',
     'grpmess1' => 'Chat: %s - Messaggio',
     'grpmes2' => 'Salve %s,
Un utente della chat %s ti ha inviato il seguente messaggio (SI CONSIGLIA DI NON CLICCARE SU NESSUN LINK):',
     'noemail' => 'L’utente non ha fornito un indirizzo mail',
     'thxsent' => 'Grazie. Il tuo messaggio è stato inviato correttamente.',
     'optemail' => 'Facoltativo - non riceverai risposta se l’email non sarà valida',
     'message' => 'Messaggio',
     'send' => 'Invia messaggio',
     'grpmess2' => 'Salve %s,
Un utente della chat %s ti ha inviato il seguente messaggio (SI CONSIGLIA DI NON CLICCARE SU NESSUN LINK):',
     'reportgrp' => 'Segnala una chat inappropriata',
     'plzsel' => 'Scegli...',
     'badlang' => 'Linguaggio offensivo',
     'scamming' => 'Truffe, phishing o hacking',
     'badimg' => 'Immagini o video inappropriati',
     'bully' => 'Molestie, cyberbullismo, impostore',
     'unwanted' => 'Contatto indesiderato',
     'otherissue' => 'Altre violazioni dei Termini di Servizio (specificare)',
     'readcare' => 'Importante: Si prega di leggere attentamente quanto segue prima di inviare la segnalazione',
     'mustsel' => 'Devi selezionare il reclamo pertinente',
     'bademail' => 'L’indirizzo email non è valido',
     'mustchars' => 'Deve contenere almeno 8 lettere',
     'complaint' => 'Reclamo:',
     'bedetailed' => '(si prega di essere il più dettagliati possibile per aiutarci ulteriormente con il reclamo)',
     'nonotify' => 'Potresti non essere avvisato del risultato del reclamo o di qualsiasi altra azione intrapresa.',
     'repimg' => 'Segnala immagini',
     'canreport' => 'È possibile segnalare qualcosa di inappropriato o qualcosa che violi i nostri Termini di Servizio. Se ritieni che qualcosa non sia appropriato utilizza il form qui sotto per spiegarci il motivo. Tuttavia, '.XAT_NAME.' non aiuterà a risolvere dispute tra utenti. Si prega di non inviare una segnalazione se non per una giusta causa. Se lo si farà ripetutamente, si potrà venir bloccati dall’uso del nostro servizio.',
     'addinfo' => 'Informazioni aggiuntive:<br>
(si prega di essere il più dettagliati possibile per aiutarci ulteriormente con il reclamo)',
     'reportpro' => 'Segnala un profilo '.XAT_NAME.'.me inappropriato',
     'repuser' => 'Utente segnalato',
     'grpknown' => 'Chat (se conosciuta)',
     'postcom' => 'Scrivi un messaggio',
     'todelete' => 'Devi essere un proprietario per poter cancellare un messaggio',
     'topost' => 'Devi essere un membro per poter lasciare un messaggio',
     'confdel' => 'Conferma eliminazione del messaggio',
     'typecom' => 'Scrivi il tuo messaggio qui. Puoi usare l’HTML semplice ed aggiungere immagini (con limite di byte).',
     'delcom' => 'Elimina messaggio',
     'savcom' => 'Salva messaggio',
     'activategrp' => 'Attiva una nuova chat',
     'expired' => 'L’attivazione della chat è scaduta. Prova nuovamente.',
     'already' => 'La chat è già stata attivata.',
     'taken' => 'Questo nome per la chat è già stato usato. Provane un altro.',
     'activated' => 'La tua chat è stata arrivata con successo! Leggi l’email per i dettagli. Il link della tua chat è:',
     'grpok1' => 'L’attivazione della chat %s è completata.',
     'grpok2' => 'Salve %s,

La tua chat chiamata %s è stata attivata.
Il link della tua chat è: %s

Per modificare la tua chat (%s) clicca sulla scritta "Modifica" presente in basso a destra e scrivi la password. Per diventare nuovamente il proprietario della chat, clicca sul bottone "Modifica Chat".

Se la chat non rispetta i Termini di Servizio %s oppure risulta inattiva potrebbe venir modificata o cancellata. Gli utenti sono responsabili di ciò che scrivono all’interno della chat ed i moderatori devono fare quello che possono per fare in modo che gli utenti rispettino i Termini di Servizio.

Buona chiacchierata e buona fortuna!

'.XAT_NAME.'',
     'seachchat' => 'Cerca',
     'searchinfo' => 'Le chat private, i messaggi privati, le chat impostate per soli membri, le chat non in lista e le chat impostate a non conservare i messaggi NON appariranno nei risultati. <a href="//util.'.DOMAIN.'/wiki/index.php?title=Special:MyLanguage/Search">Più informazioni</a>',
     'moreinfo' => 'Più informazioni.',
     'nores' => 'Nessun risultato',
     'moreresults' => 'Più risultati',
     'minsago' => 'minuti fa su',
     'hoursago' => 'ore fa su',
     'searchingfor' => 'Cerca:',
     'results' => 'Risultati',
     'search' => 'Cerca',
     'mustbe' => 'Deve contenere almeno',
     'letters' => 'lettere',
     'unfair' => 'Ban ingiusto',
     'noctrl' => 'Promozione: inappropriata o fuori controllo',
     'addcom' => 'Aggiungi messaggio',
     'dispcom' => 'Visualizza messaggio',
     'delete' => 'cancella',
     'news' => 'Novità',
     'events' => 'Eventi',
     'inapp' => 'Inappropriato',
     'comments' => 'Messaggi',
     'grid' => 'griglia',
     'player' => 'player',
     'doodle' => 'disegno',
     'translate' => 'traduttore',
     'games' => 'giochi',
     'apps' => 'app',
     'embed' => 'Incorpora',
     'chglang' => 'Cambia lingua',
     'sellang' => 'Seleziona lingua:',
     'eventsfor' => 'Eventi della chat per',
     'oldres' => 'Vecchi risultati',
     'duration' => 'Durata',
     'text' => 'Testo',
     'canevents' => 'Puoi cercare gli eventi della chat (vedi la <a href="//util.'.DOMAIN.'/wiki/index.php?title=Special:MyLanguage/Events">wiki</a>)',
     'all' => 'Tutti',
     'time' => 'Tempo',
     'emailsent' => 'Email inviata',
     'needlogin' => 'Si prega di effettuare il <a href="//'.DOMAIN.'/login">login</a> per poter usare questa pagina.',
     'needevents' => 'Devi possedere il potere Events per poter usare questa pagina.',
     'nodays' => 'Non possiedi i days da abbonato.',
     'continue' => 'Continua',
     'name' => 'Nome',
     'grassmod' => 'Segnala moderatore',
     'feelunfair' => 'Se vieni bannato ingiustamente oppure vieni trattato male da un moderatore, puoi segnalarlo al proprietario della chat. I proprietari non sono obbligati a rispondere ai messaggi che ricevono ma sicuramente non lo faranno se non fornirai un indirizzo mail valido.',
     'modrpt1' => 'Chat: %s - Segnalazione moderatore',
     'modrpt2' => 'Salve %s,
hai ricevuto una segnalazione riguardante un moderatore della tua chat',
     'modrpt3' => 'Clicca qui: %s per vedere cosa è successo.',
     'transcript' => 'Trascrizione chat',
     'youneed' => '<p>Devi assicurarti che i tuoi moderatori stiano facendo un buon lavoro e si stiano comportando bene con gli utenti della tua chat. Basta un solo moderatore scorretto per rovinarla. Se i tuoi moderatori fanno un buon lavoro, la chat potrebbe diventare sempre più popolare.</p><p>Si prega di controllare la segnalazione di ban ingiusto e, se ti trovi in disaccordo, parla con il moderatore oppure degradalo.</p>',
     'banby' => 'è stato bannato da',
     'clkunmod' => 'Clicca per degradare',
     'unfriendly' => '<p>NOTA BENE: la tua chat potrebbe essere rimossa dalla lista se i tuoi moderatori si comportano in modo scorretto. La chat potrebbe non comprarire nella lista presente nel sito e, quindi, ne risentirebbe la popolarità.</p>',
     'transno' => 'La trascrizione non esiste. Potrebbe essere stata cancellata. Le trascrizioni vengono conservate per una settimana',
     'unmod' => 'Degrada moderatore',
     'yesunmod' => 'Sì, degrada',
     'sureunmod' => 'Sei sicuro di voler degradarlo?',
     'chatconf' => 'Conferma il degrado ad ospite attraverso la chat',
     'tounmod' => 'Clicca il link qui sopra per degradarlo',
     'istrans' => 'Di seguito è riportata una trascrizione dei messaggi che hanno portato al ban',
     'chatid' => 'ID Chat:',
     'seeall' => 'Qui puoi vedere tutte le immagini di una chat e segnalarle facilmente, in caso fossero inappropriate, al sito.'
	 ]
?>