<?php
$array = [
     'quizq1' => 'คุณได้รับข้อความจากบุคคลที่อ้างว่าเป็นอาสาสมัคร. คนผู้นี้กล่าวว่า บัญชีของคุณถูกบล็อก และเพื่อแก้ไขปัญหานี้ คุณจะต้องให้รหัสผ่านของคุณและที่อยู่อีเมล มิฉะนั้นบัญชีของคุณจะยังคงถูกบล๊อก. คุณจะทำอย่างไร ?',
     'quizq1a1' => 'อย่าให้ข้อมูลใดๆ กับพวกเขา.',
     'quizq1a2' => 'คุณไม่ต้องการที่จะสูญเสียบัญชี '.XAT_NAME.' กรุณากรอกข้อมูล.',
     'quizq1a3' => 'ขอหลักฐานว่า พวกเขาเป็นอาสาสมัครจริง',
     'quizq1info' => 'ถูกต้อง! เจ้าหน้าที่ และ อาสาสมัคร '.XAT_NAME.' จะไม่ขอข้อมูลส่วนบุคคลในการสนทนาส่วนตัว. รายงานผู้ใช้ โดยการบันทึกภาพหน้าจอ ไอดี และข้อความของเขา แล้วทำการเปิดตั๋วในหัวข้อรายงานหลอกลวง.',
     'quizq1image' => '<br img src="https://util.'.DOMAIN.'/wiki/images/f/f9/Securityimage1.png" class="img-fluid"/>',
     'quizq2' => 'คุณอยู่ในห้องแชทการซื้อขาย พยายามที่จะซื้อวัน. คุณได้รับการติดต่อจากคนที่ขอให้คุณโอน xats คุณเป็นอันดับแรก. คุณจะทำอย่างไร ?',
     'quizq2a1' => 'ปฏิเสธ และแนะนำการใช้แอป Safe Trade เป็นการซื้อขายที่ปลอดภัยซึ่งเป็นวิธีแนะนำ.',
     'quizq2a2' => 'ก่อนโอน xats ของคุณ.',
     'quizq2a3' => 'ถามพวกเขาสำหรับการแลกเปลี่ยนวัน.',
     'quizq2info' => 'ถูกต้อง! ในขณะที่ทำการซื้อและขาย xats,day หรือ power คุณควรใช้แอปซื้อขายที่ปลอดภัย Safe Trade. คุณสามาดูการแลกเปลี่ยนในขณะที่คุณกำลังทำแบบ real time ได้. ในขณะที่ทำการซื้อขายอย่าโอนเงินผ่านช่องทางอื่น.',
     'quizq2image' => '<br img src="https://util.'.DOMAIN.'/wiki/images/c/c0/Securityimage2.png" class="img-fluid"/>',
     'quizq3' => 'Your email provider offers 2-factor authentication protection. คุณควรเปิดใช้งานตัวเลือกนี้?',
     'quizq3a1' => 'Yes. นอกจากนี้จะเพิ่มการรักษาความปลอดภัยของที่อยู่อีเมล.',
     'quizq3a2' => 'No. รหัสผ่านง่ายเกินไปกรุณาเปลี่ยนอีกครั้ง.',
     'quizq3a3' => 'ไม่เลย การป้องกันแบบนี้ไม่ได้มีประโยชน์ใดๆ',
     'quizq3info' => 'ถูกต้อง! 2-factor authentication on your email address will add an additional layer of security (by phone) to ensure that no one else but you can access your email - even if your password gets hacked.<br><br>กรุณาติดต่อผู้ให้บริการอีเมลของคุณสำหรับขั้นตอนในการเปิดใช้การยืนยันตัวตนสำหรับบัญชีอีเมลของคุณ สำหรับบัญชี Gmail กรุณาดูที่<a href="https://www.google.com/landing/2step/" target="_blank">เพจนี้</a>',
     'quizq3image' => '<br img src="https://util.'.DOMAIN.'/wiki/images/7/71/Securityimage3.png" class="img-fluid"/>',
     'quizq4' => 'คุณจะถูกบอกว่ามีการอัพเดทบนหน้าล็อคอินใหม่ของ '.XAT_NAME.' ผู้ใช้คนนั้นจะส่งลิ้งค์ใหม่ให้คุณสำหรับทดสอบโดยเป็น https://xaatt.com/login คุณจะทำอย่างไร?',
     'quizq4a1' => 'อย่าคลิกบนลิ้งค์นั้นเด็ดขาดเพราะไม่ได้เป็นลิ้งค์ของโดเมน https://'.DOMAIN.'',
     'quizq4a2' => 'คลิกเพื่อดูว่ามีอะไรที่เปลี่ยนแปลงไป',
     'quizq4info' => 'ถูกต้อง! ตรวจสอบแอดเดรสบาร์ให้มั่นใจเสมอว่าคุณอยู่บนโดเมน <a href="https://'.DOMAIN.'" target="_blank">https://'.DOMAIN.'</a> ก่อนทำการล็อคอิน, เข้าไปในแชทหรือใส่ข้อมูล '.XAT_NAME.' ใดๆ ของคุณ',
     'quizq4image' => '<br img src="https://util.'.DOMAIN.'/wiki/images/7/7d/Securityimage4.png" class="img-fluid"/>',
     'quizq5' => 'มีผู้ช้เสนอที่จะเพิ่มพาวเวอร์ของคุณให้เป็นสองเท่าแต่คุณต้องเทรดพาวเวอร์ของคุณให้เขาไปก่อน คุณจะทำอย่างไร?',
     'quizq5a1' => 'พาวเวอร์ไม่สามารถทำให้เป็นสองเท่าได้ คุณจะไม่ส่งพาวเวอร์ของคุณไป',
     'quizq5a2' => 'ยอมรับข้อเสนอ เพราะเพิ่มเป็นสองเท่าก็เท่ากับกำไรเท่าตัว',
     'quizq5a3' => 'ขอดูหลักฐานว่าพวกเขาสามารถทำให้พาวเวอร์ของคุณเพิ่มเป็นสองเท่าได้',
     'quizq5info' => 'ทำได้เยี่ยม! จำนวน '.XAT_NAME.', วันและพาวเวอร์ต่างๆ ไม่สามารถทำซ้ำได้ มิจฉาชีพมักจะใช้วิธีการนี้เพื่อทำให้คุณสนใจเพื่อจ้องจะขโมยของของคุณ รายงานผู้ใช้ โดยการบันทึกภาพหน้าจอ ไอดี และข้อความของเขา แล้วทำการเปิดตั๋วในหัวข้อรายงานหลอกลวง.',
     'quizq5image' => '<br img src="https://util.'.DOMAIN.'/wiki/images/3/35/Securityimage5.png" class="img-fluid"/>',
     'quizq6' => 'คุณได้รับอีเมลจาก info@'.DOMAIN.' ว่าพาวเวอร์ของคุณจะต้องถูกตรวจสอบจากเจ้าหน้าที่ของ '.XAT_NAME.' มีขั้นตอนบอกว่าคุณต้องเทรดพาวเวอร์ไปยังใครบางคนที่กำหนดให้ ถ้าหากคุณไม่ทำตาม บัญชีของคุณจะถูกบล็อคเป็นเวลา 3 เดือน คุณจะทำอย่างไร?',
     'quizq6a1' => 'ไม่ใส่ใจและรายงานว่าอีเมลเป็นสแปม',
     'quizq6a2' => 'ยอมรับโดยไม่มีข้อโต้แย้ง ได้โปรดอย่าบล็อค!',
     'quizq6a3' => 'ตอบอีเมลกลับไปเพื่อขอข้อมูลเพิ่มเติม',
     'quizq6info' => 'ถูกต้อง! คุณจะไม่มีทางได้รับอีเมลแบบนั้นจาก '.XAT_NAME.' การแจ้งใดๆ เกี่ยวกับบัญชี '.XAT_NAME.' ของคุณจะถูกดำเนินการบนระบบสนับสนุนทาง <a href="https://'.DOMAIN.'/ticket" target="_blank">'.DOMAIN.'/ticket</a> เท่านั้น',
     'quizq6image' => '<br img src="https://util.'.DOMAIN.'/wiki/images/3/3b/Securityimage6.png" class="img-fluid"/>',
     'quizq7' => 'ทุกคนรู้ว่ารหัสผ่านนั้นจำยาก ดังนั้นเพื่อทำให้ชีวิตคุณง่ายขึ้น คุณจึงตัดสินใจที่จะให้รหัสผ่านที่เหมือนกันสำหรับอีเมลและบัญชี '.XAT_NAME.' ของคุณ ปลอยภัยไหม?',
     'quizq7a1' => 'ไม่เลย!',
     'quizq7a2' => 'แน่นอน แล้วคุณก็จะไม่มีปัญหาเกี่ยวกับการลืมรหัสผ่านของคุณ',
     'quizq7info' => 'คุณทำถูกต้องแล้ว! ความยากลำบากจะเป็นผลดี Always use different passwords for each of your online accounts to increase your protection.',
     'quizq7image' => '<br img src="https://util.'.DOMAIN.'/wiki/images/2/2b/Securityimage7.png" class="img-fluid"/>',
     'quizq8' => 'You learn about a free xats generator program that needs to be downloaded. What do you do?',
     'quizq8a1' => 'You know that xats cannot be generated, so you ignore this.',
     'quizq8a2' => 'Ask for more information.',
     'quizq8a3' => 'Ask for proof if xats can be generated.',
     'quizq8info' => 'You are right! xats cannot be generated for free! Be careful not to download any unknown program as they can be malicious and may contain harmful software (viruses).',
     'quizq8image' => '<br img src="https://util.'.DOMAIN.'/wiki/images/5/5c/Securityimage8.png" class="img-fluid"/>',
     'quizq9' => 'You received a message saying that your account is getting blocked within 24 hours unless you pay 10000 xats. What do you do?',
     'quizq9a1' => 'Do not send xats and ignore the user.',
     'quizq9a2' => 'Block? No way! I pay the fine.',
     'quizq9a3' => 'Ask for an explanation.',
     'quizq9info' => 'Correct! '.XAT_NAME.' staff and volunteers will never ask for xats. Report the user by taking screenshots of their ID and message, then open a ticket under the Report Scam topic.',
     'quizq9image' => '<br img src="https://util.'.DOMAIN.'/wiki/images/b/b4/Securityimage9.png" class="img-fluid"/>',
     'quizq10' => 'You’re offered an expensive amount of xats for your powers such as 50000 xats. During the trade, there are multiple failed attempts due to wrong password and other errors. What do you do?',
     'quizq10a1' => 'Respectfully tell the user that you will restart the trade.',
     'quizq10a2' => 'Ignore the issue and continue to trade.',
     'quizq10a3' => 'Ignore the user.',
     'quizq10info' => 'Correct! Scammers will try to steal your xats, days or powers by changing the quantity of xats, days or powers on the app.<br><br>Always be careful and double check all the powers of the trade after each failed attempt. Take an extra turn to recheck the trade details before clicking confirm.',
     'quizq10image' => '<br img src="https://util.'.DOMAIN.'/wiki/images/a/a2/Securityimage10.png" class="img-fluid"/>',
     'quizq11' => 'You receive a forum private message from a person claiming to be a '.XAT_NAME.' employee. The message asks for your account details (passwords and email), otherwise your account will get blocked by '.XAT_NAME.'. What do you do?',
     'quizq11a1' => 'Ignore the user and report them to the forum staff.',
     'quizq11a2' => 'Answer the message by providing the requested information.',
     'quizq11a3' => 'Ask for more information about the block.',
     'quizq11info' => 'Correct! '.XAT_NAME.' staff and volunteers will never contact you privately about '.XAT_NAME.' account issues such as blocking. All account issues are handled on the support system at <a href="https://'.DOMAIN.'/ticket" target="_blank">'.DOMAIN.'/ticket</a> and you should report inappropriate and malicious private messages.',
     'quizq11image' => '<br img src="https://util.'.DOMAIN.'/wiki/images/7/7a/Securityimage11.png" class="img-fluid"/>',
     'quizq12' => 'You’re told on a chat by a '.XAT_NAME.' employee to disable the 2-factor authentication protection from your email address. What do you do?',
     'quizq12a1' => 'Deny them and ignore.',
     'quizq12a2' => 'Disable the 2-factor authentication.',
     'quizq12info' => 'Yes, you’re right! '.XAT_NAME.' staff and volunteers will never ask you to disable the 2-factor authentication protection under any circumstances. Do not hesitate to report users who try to disable your account protections.',
     'quizq12image' => '<br img src="https://util.'.DOMAIN.'/wiki/images/4/45/Securityimage12.png" class="img-fluid"/>',
     'quizq13' => 'You’re told about a free xats generator page on a website. But to generate free xats you must enter your password and email address. What do you do?',
     'quizq13a1' => 'Ignore the website as you know that xats cannot be generated for free.',
     'quizq13a2' => 'Proceed and log in.',
     'quizq13a3' => 'Ask for proof if xats can be generated.',
     'quizq13info' => 'You are right! xats cannot be generated for free. Also, only enter with your '.XAT_NAME.' password on official <a href="https://'.DOMAIN.'" target="_blank">https://'.DOMAIN.'</a> pages. Always check the address bar to make sure you are at <a href="https://'.DOMAIN.'" target="_blank">'.DOMAIN.'</a>.',
     'quizq13image' => '<br img src="https://util.'.DOMAIN.'/wiki/images/5/57/Securityimage13.png" class="img-fluid"/>',
     'quizq14' => 'You’ve negotiated a deal to buy powers from a user on Trade chat. The user states they will trade half of the powers now and the rest later. What do you do?',
     'quizq14a1' => 'Refuse the offer - they should add all of the items now.',
     'quizq14a2' => 'Accept the offer. Nothing can go wrong.',
     'quizq14a3' => 'Ask for proof they have the remaining powers.',
     'quizq14info' => 'Correct! Scammers may try to stagger trades by offering an amount upfront and promising to pay the rest in the future. Never believe these users and only accept the agreed amount in one full trade. The user is unlikely to return afterwards.',
     'quizq14image' => '<br img src="https://util.'.DOMAIN.'/wiki/images/5/59/Securityimage14.png" class="img-fluid"/>',
     'quizq15' => 'You’re told about a free program that makes animated avatars (gifs). A person on a chat sends you a download link for the program that is on an unknown website. What do you do?',
     'quizq15a1' => 'Never download unknown files as they may contain viruses.',
     'quizq15a2' => 'Blindly download it.',
     'quizq15info' => 'Correct! Scammers will tempt you to download their viruses by posing as a helpful friend. Be careful not to download unknown files. A few tips to avoid downloading malicious things are:<br><br ol><li>Search for the file name on Google (program credibility and if it even exists).</li><li>Check alternative sources for download.</li><li>Run a virus scan over the file.</li></ol>',
     'quizq15image' => '<br img src="https://util.'.DOMAIN.'/wiki/images/1/19/Securityimage15.png" class="img-fluid"/>',
     'quizq16' => 'A person you met on a chat asks for your personal information such as your name, street address and email address. คุณทำอะไร ?',
     'quizq16a1' => 'Change the subject by saying you do not want to talk about your personal information.',
     'quizq16a2' => 'They seem to be cool enough so you answer their questions with your real information.',
     'quizq16a3' => 'Ignore the user.',
     'quizq16info' => 'Well done! You should not be sharing your personal information with anybody online. Never share your email address or password!',
     'quizq16image' => '<br img src="https://util.'.DOMAIN.'/wiki/images/d/d9/Securityimage16.png" class="img-fluid"/>',
     'quizq17' => 'You are notified on a chat that your '.XAT_NAME.' account has a problem and to fix it you must turn off the account protection on the '.XAT_NAME.' login page. คุณทำอะไร ?',
     'quizq17a1' => 'Never turn off your '.XAT_NAME.' account protections when asked.',
     'quizq17a2' => 'You will trust any stranger. You do log in to turn off protections.',
     'quizq17a3' => 'Ask them for further information before considering their request.',
     'quizq17info' => 'Correct! Your '.XAT_NAME.' account protections are not to be turned off under any circumstances. '.XAT_NAME.' employees and volunteers will never ask for you to turn off the protections.',
     'quizq17image' => '<br img src="https://util.'.DOMAIN.'/wiki/images/a/ab/Securityimage17.png" class="img-fluid"/>',
     'quizq18' => 'A friend of yours asks if they can borrow your namecolor power for some time, as they want to test its effects. What do you do?',
     'quizq18a1' => 'Do not give it away. There’s a chance that you won’t get it back.',
     'quizq18a2' => 'It is ok to give it away. You can get your powers back any time.',
     'quizq18a3' => 'Best friends forever. You click trade, no second thoughts!',
     'quizq18info' => 'That’s right! Your xats, days and powers are your sole responsibility. Lending does not exist on '.XAT_NAME.', and it will be viewed that you gave your items away. If you complete a trade or a transfer, it cannot be undone. Be very careful at all times. <a href="//util.'.DOMAIN.'/wiki/index.php?title=Special:MyLanguage/Trading" target="_blank">Read more here.</a>',
     'quizq18image' => '<br img src="https://util.'.DOMAIN.'/wiki/images/1/17/Securityimage18.png" class="img-fluid"/>',
     'quizq19' => 'You receive an email from info@'.DOMAIN.' stating you have just successfully purchased 100000 xats. It also states you need to confirm the payment by clicking on a link. The link redirects you to a page where you need to pay $100 to finally receive the xats. What do you do?',
     'quizq19a1' => 'This is a strange offer. If I purchased the xats successfully, why do I need to pay more? You block the email as this is a scam.',
     'quizq19a2' => 'The email comes from info@'.DOMAIN.' but $100 is a lot of money. Reply and ask for more information.',
     'quizq19a3' => 'I wasn’t planning to buy xats, but 100000 xats for $100 is a good deal. Go for it!',
     'quizq19info' => 'Correct! '.XAT_NAME.' will NEVER ask you to buy xats in an email, and the only safe place where you can buy xats for real money is <a href="https://'.DOMAIN.'/buy">https://'.DOMAIN.'/buy</a>. Some scammers are able to fake '.XAT_NAME.' email addresses, so you should never proceed, even if it shows info@'.DOMAIN.'. Nonetheless, if the deal looks too good to be true, it usually is, and you are very likely being scammed.',
     'quizq19image' => '<br img src="https://util.'.DOMAIN.'/wiki/images/f/fe/Securityimage19.png" class="img-fluid"/>',
     'start' => 'start quiz',
     'desc' => 'To get <a href="//util.'.DOMAIN.'/wiki/index.php?title=Special:MyLanguage/Tickle" target="_blank">Tickle</a> power for free, you need to complete the quiz below and answer each of the questions correctly.',
     'wronganswer' => 'This is incorrect. Please try again.',
     'next' => 'ถัดไป',
     'continuein' => 'ต่อไปใน',
     'gratz' => 'ขอแสดงความยินดี คุณเสร็จแบบทดสอบ คุณควรจะมีความรู้เกี่ยวกับความปลอดภัยบน '.XAT_NAME.'.',
     'tickle' => 'You have received the Tickle power.',
     'redirect' => 'กรุณารอสักครู่ขณะที่คุณกำลังเปลี่ยนไปยังหน้าเข้าสู่ระบบล็อกอิน.'
	 ]
?>