(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


// symbols:
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.xring = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.rf(["rgba(249,201,49,0)","#F9C931","#F9C931","rgba(249,201,49,0)"],[0.396,0.494,0.635,0.729],0,0,0,0,0,16.1).s().p("AhxByIAAjjIBCAAIgCBnIAxACIAzANIgEh2IBDAAIAADjg");
	this.shape.setTransform(11.4,11.4);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.xring, new cjs.Rectangle(0,0,22.8,22.8), null);


(lib.wheels = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(0.1,1,1).p("ABTgNIAAANQgCAJgIADQgIADgIgEQgJgEgBgGIAAgOgAhSgNIAAAOQAAAFAHAFQAHAFAKgDQAJgEACgJIAAgNg");

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AhLALQgGgFgBgFIAAgOIAjAAIAAANQgCAJgJAEIgHABQgFAAgFgDgAA5ALQgKgEAAgGIAAgOIAkAAIAAANQgCAJgIADIgHACQgFAAgEgDg");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.wheels, new cjs.Rectangle(-9.3,-2.4,18.6,4.9), null);


(lib.Tween3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(0.2,1,1).p("AgEgLQAGgDAFADQAFADABAIQABADgDAFQgCAEgFACQgFABgFgDQgFgDgBgFQgBgFACgEQADgFAEgBgAgGAMIAGgLIgEgMAAAABIANgB");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-2.3,-2.4,4.7,4.8);


(lib.Tween2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 5
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["#00CC00","#006600"],[0,1],-18.9,0,19,0).s().p("AA6CiIguAeQgwiiiYiqIC1CsQgxhPhJhRICVCOQg2hmhfhrIC6CyQgbhZgvhiICmESIALAKIgEACIAiA2IgfAKIABABIhXA6IgPgrg");
	this.shape.setTransform(5.6,89.3);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Layer 6
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.lf(["#FF0000","rgba(255,255,255,0.51)"],[0,1],-6.9,0,7,0).s().p("AgwAyQgVgVAAgdQAAgcAVgVQAUgVAcAAQAdAAAUAVQAVAVAAAcQAAAdgVAVQgUAVgdAAQgcAAgUgVg");
	this.shape_1.setTransform(-16.9,49.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.lf(["#FF0000","rgba(255,255,255,0.51)"],[0,1],-6.9,0,7,0).s().p("AgwAyQgVgVAAgdQAAgcAVgVQAUgVAcAAQAdAAAUAVQAVAVAAAcQAAAdgVAVQgUAVgdAAQgcAAgUgVg");
	this.shape_2.setTransform(-36.4,32.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.lf(["#FF0000","rgba(255,255,255,0.51)"],[0,1],-6.9,0,7,0).s().p("AgwAyQgVgVAAgdQAAgcAVgVQAUgVAcAAQAdAAAUAVQAVAVAAAcQAAAdgVAVQgUAVgdAAQgcAAgUgVg");
	this.shape_3.setTransform(-6.4,-16.9);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.lf(["#FF0000","rgba(255,255,255,0.51)"],[0,1],-6.9,0,7,0).s().p("AgwAyQgVgVAAgdQAAgcAVgVQAUgVAcAAQAdAAAUAVQAVAVAAAcQAAAdgVAVQgUAVgdAAQgcAAgUgVg");
	this.shape_4.setTransform(-34.1,1.4);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.lf(["#FF0000","rgba(255,255,255,0.51)"],[0,1],-6.9,0,7,0).s().p("AgwAyQgVgVAAgdQAAgcAVgVQAUgVAcAAQAdAAAUAVQAVAVAAAcQAAAdgVAVQgUAVgdAAQgcAAgUgVg");
	this.shape_5.setTransform(-4.5,17.9);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.lf(["#FF0000","rgba(255,255,255,0.51)"],[0,1],-6.9,0,7,0).s().p("AgwAyQgVgVAAgdQAAgcAVgVQAUgVAcAAQAdAAAUAVQAVAVAAAcQAAAdgVAVQgUAVgdAAQgcAAgUgVg");
	this.shape_6.setTransform(23.4,13.2);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.lf(["#FF0000","rgba(255,255,255,0.51)"],[0,1],-6.9,0,7,0).s().p("AgwAyQgVgVAAgdQAAgcAVgVQAUgVAcAAQAdAAAUAVQAVAVAAAcQAAAdgVAVQgUAVgdAAQgcAAgUgVg");
	this.shape_7.setTransform(17.6,-7.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1}]}).wait(1));

	// Layer 3
	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("rgba(255,0,0,0.988)").s().p("AiYF+QgVgVAAgdQAAgdAVgVQAUgVAdAAQAdAAAUAVQAVAVAAAdQAAAdgVAVQgUAVgdAAQgdAAgUgVgAlbDRQgVgVAAgeQAAgdAVgVQAUgVAdAAQAdAAAUAVQAVAVAAAdQAAAegVAVQgUAVgdAAQgdAAgUgVgAgcBCQgVgVAAgdQAAgcAVgVQAUgVAcAAQAdAAAUAVQAVAVAAAcQAAAdgVAVQgUAVgdAAQgcAAgUgVgAD6AUQgVgUAAgeQAAgdAVgVQAUgVAdAAQAdAAAUAVQAVAVAAAdQAAAegVAUQgUAVgdAAQgdAAgUgVgAlEhiQgVgVAAgdQAAgdAVgVQAUgVAdAAQAdAAAUAVQAVAVAAAdQAAAdgVAVQgUAVgdAAQgdAAgUgVgADAi2QgVgVAAgeQAAgdAVgVQAUgVAdAAQAdAAAUAVQAVAVAAAdQAAAegVAVQgUAVgdAAQgdAAgUgVgAgvkZQgUgVAAgdQAAgdAUgVQAVgVAbAAQAdAAAVAVQAUAVAAAdQAAAdgUAVQgVAVgdAAQgbAAgVgVg");
	this.shape_8.setTransform(-6.5,16.3);

	this.timeline.addTween(cjs.Tween.get(this.shape_8).wait(1));

	// Layer 7
	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.lf(["#009900","#90D290"],[0,1],-42.5,0,42.6,0).s().p("AjkGSQiGhHgvi2Qgui1BXioQBXipCpg5QCpg4CYBYQCaBYAuC1QAvC1hXCpQhHCJiDhnQgTgPgPgKIgBAAQgCioAWimQgLA/hFC/Qimhph4hbQCUCeBxCyIAAAFIAAACIAAAJQgBBghAAfQgZAMggAAQg/AAhagvg");
	this.shape_9.setTransform(-5,18.6);

	this.timeline.addTween(cjs.Tween.get(this.shape_9).wait(1));

	// Layer 9
	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.lf(["#663300","rgba(149,114,79,0.98)"],[0,1],-26.8,0,26.8,0).s().p("AgGhRIAAgDIAAgFQhxixiUigQB3BcCnBpQBEjAALg/QgVCoACCnIAAABQAeEeCfD2QhwgFgtBqQgIkbhtkbgAgGhgIAAADIAAAEIgBgYg");
	this.shape_10.setTransform(0.3,57);

	this.timeline.addTween(cjs.Tween.get(this.shape_10).wait(1));

	// Layer 1
	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#663333").s().p("AgGhRIAAgDIAAgFQhxixiUigQB3BcCnBpQBEjAALg/QgVCoACCnIAAABQAeEeCfD2QhwgFgtBqQgIkbhtkbgAgGhgIAAADIAAAEIgBgYg");
	this.shape_11.setTransform(0.3,57);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#00CC00").s().p("AjkGSQiGhHgvi2Qgui1BXioQBXipCpg5QCpg4CYBYQCaBYAuC1QAvC1hXCpQhHCJiDhnQgTgPgPgKIgBAAQgCioAWimQgLA/hFC/Qimhph4hbQCUCeBxCyIAAAFIAAACIAAAJQgBBghAAfQgZAMggAAQg/AAhagvg");
	this.shape_12.setTransform(-5,18.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_12},{t:this.shape_11}]}).wait(1));

	// Layer 8
	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.lf(["#00FF00","rgba(255,255,255,0.18)"],[0,1],-49.4,0,49.4,0).s().p("AkIG5QichOg2jIQg2jGBli5QBli5DEg/QDEg+CxBhQCyBhA2DHQA2DHhlC5QhTCXiYhyQgVgRgSgKIgCgBQhig7gCBXIABAVIABAOIAAAJIAAADIAAAJQgBBphKAjQgdANgmAAQhJAAhng0g");
	this.shape_13.setTransform(-5.9,17.1);

	this.timeline.addTween(cjs.Tween.get(this.shape_13).wait(1));

	// Layer 4
	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#00FF00").s().p("AkIG5QichOg2jIQg2jGBli5QBli5DEg/QDEg+CxBhQCyBhA2DHQA2DHhlC5QhTCXiYhyQgVgRgSgKIgCgBQhig7gCBXIABAVIABAOIAAAJIAAADIAAAJQgBBphKAjQgdANgmAAQhJAAhng0g");
	this.shape_14.setTransform(-5.9,17.1);

	this.timeline.addTween(cjs.Tween.get(this.shape_14).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-55.2,-32.2,98.8,142);


(lib.Tween1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgLA4QgHg4AHg3QALgQAMAQQAGA7gGA0QgEAIgGAAQgFAAgIgIg");
	this.shape.setTransform(-0.4,0);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1.9,-6.4,3.1,12.8);


(lib.treeobj2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["#009900","#C1FFAD","#33FF00"],[0.051,0.549,0.914],-14.7,-2,14.5,2.7).s().p("AAOBrQgIAGgGgBQARgRgLgbQgHALgGgCQAQghgLgbQgagugvAMQgOgCgJAGQADgJAOgGQgSgJgQAOQABgKANgFQgRgJgbANQBHg1ApAdIAKAKIAIAMIgBgLIgDgIQgGgRgOgNQAJADAAgGQgGgOgTgDQAMAAABgEQgEgLgUgCQAJABABgGQgCgIgWgBQB0gJgNBhIgBAIIgBACIAEgCIAJgDQBUghAcBdIghgTIAAALIgegTIgBAJQgjgXgYAOQBWAJANA3QAHAagQAXQgCgYgLgPQABAMgJAHQgDgdgSgIQACAKgFAJQgPgyglgIQBKBXhZAsQAJgNAEgSg");
	this.shape.setTransform(14.6,13.8);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.treeobj2, new cjs.Rectangle(0,0,29.2,27.7), null);


(lib.treeobj1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["rgba(255,255,255,0.31)","rgba(193,255,173,0.231)","rgba(255,255,255,0.29)"],[0.051,0.549,1],-17.6,0,17.7,0).s().p("AgWABQgrADgdA7QgEgMAEgMQgWAGgIAjQgKgKADgOQgQAPgIAfQgOggANggQAahCBoAGQgagWgtAWIAAgLIgnASIADgPIgrASQA3h4BmBMQgEiLCPAkQgbgCgEAJQABAHAKACQgYgCgGANQAAAGAOABQgXAAgJAQQgBAIAKgCQgdAXgJAhQA9hIBcBlQgcgUgWAHQAPAJgBAMQgRgVgWAIQAOAKACAMQgJgKgQAAQg3gYgmA1QgTAfAOArQgIACgIgPQgRAgARAZQgIgBgIgJQACAXAGATQhfhJBnheg");
	this.shape.setTransform(17.7,16.7);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.treeobj1, new cjs.Rectangle(0,0,35.3,33.5), null);


(lib.Symbol2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(2.1,1,1).p("ADDhkQBQAugHBHQgIBHhoAIQhpAHhPAfQhQAfhQguQhQgtAAhBQAAg/BQguQBQguBvAAQBxAABPAug");

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("ABsAiQgCgNACgPQAAgYAEgGQAJgRAnADQAAAAAAAAQAAABABAAQAAAAAAABQABAAAAAAQACABAAAMQAAAKgIAFQgIAFAAAJQAAAKAIANQAHAOABAIIgGAFQgGAFgMAAQgaAAgGgbgAifgLIgEgUQAAgsAqAYQAVAMAhAdQgGAMgEAEQgGAHgQAAQgvAAgNgYg");
	this.shape_1.setTransform(1.2,-0.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#999999").s().p("Ai8B3QhQgtAAhBQAAg/BQguQBQguBvAAQBxAABPAuQBQAugHBHQgIBHhoAIQhpAHhPAfQggANggAAQgwAAgwgcgAB7gcQgEAGAAAYQgCAQADANQAFAaAaAAQAMAAAGgFIAGgFQgBgIgHgNQgIgNAAgLQAAgJAIgFQAIgFAAgKQAAgLgCgBQAAAAAAgBQgBAAAAAAQAAgBAAAAQgBAAAAgBIgJAAQgfAAgIAOgAiUgOQAOAXAuAAQAQAAAGgGQAEgEAGgNQghgcgVgNQgqgYAAAsIAAAAIAEAVg");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol2, new cjs.Rectangle(-27.9,-15.7,55.8,31.5), null);


(lib.snowboard = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFCC00").s().p("AgCACIgGgCIAHgBIABgHIACAGIAHgBIgFAEIADAHIgGgEIgEAFg");
	this.shape.setTransform(-0.1,0);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Layer 1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#000000").ss(0.3,1,1).p("AAMAuIgXAAIAAhRQALgUAMAUg");

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.lf(["#009900","#FFFF00","#FF0000","#0000FF"],[0,0.173,0.486,1],-1.8,3.2,2,-3.3).s().p("AgKAuIAAhRQAKgUALAUIAABRg");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.snowboard, new cjs.Rectangle(-2.2,-5.6,4.3,11.2), null);


(lib.shape122 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(2,1,1).p("AgxgUIBjAp");
	this.shape.setTransform(7.7,15.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#999999").ss(1,1,1).p("AgegoIAAA4AAfApQgDg6gmgN");
	this.shape_1.setTransform(9.8,10.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#FFFFFF").ss(1,1,1).p("AgMgDIgngPAALAEIApAO");
	this.shape_2.setTransform(7.6,12.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f().s("#000000").ss(1,1,1).p("AhYgcQAKgpAhgDAA1AmIAjggAA2BJIAjggAA1AIIAjggAhYAaIBqAsAgZg/IAAA6");
	this.shape_3.setTransform(11.3,13.6);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.rf(["#FFFFFF","#000000"],[0,1],-0.5,-0.4,0,-0.5,-0.4,1.5).s().p("AgIALQgEgFABgGQgBgFAEgEQADgFAFAAQAFAAAEAFQADAEAAAFQAAAGgDAFQgEAEgFAAQgFAAgDgEg");
	this.shape_4.setTransform(11.8,23);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.rf(["#FFFFFF","#000000"],[0,1],-0.5,-0.4,0,-0.5,-0.4,1.5).s().p("AgIALQgDgFgBgGQABgFADgEQAEgFAEAAQAFAAAEAFQADAEABAFQgBAGgDAFQgEAEgFAAQgEAAgEgEg");
	this.shape_5.setTransform(7.2,21);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.rf(["#FFFFFF","#000000"],[0,1],-0.5,-0.4,0,-0.5,-0.4,1.5).s().p("AgIALQgEgFAAgGQAAgFAEgFQAEgEAEAAQAFAAAEAEQAEAFgBAFQABAGgEAFQgEAEgFAAQgEAAgEgEg");
	this.shape_6.setTransform(3,19.6);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#999999").s().p("AALAaIAAg5QAnAOACA5gAgzAEQAKgpAhgDIAAA3IgEAEg");
	this.shape_7.setTransform(7.6,10.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	// Layer 1
	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f().s("#999999").ss(1,1,1).p("AhphIIAACmICQAuIBDhBIAAiIIg/A6QhGiShOBNgAArgDIgECPABqg9QhmiWhtCL");
	this.shape_8.setTransform(11.1,12.5);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#999999").s().p("AgdgqIA+g6IAACIIhBBBg");
	this.shape_9.setTransform(18.4,16.4);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#CCCCCC").s().p("AhpBeIAAimIAAgBIACgBQAagYAZAAIAAAAIABAAQAvABArBWIABABIAAABIADAGIgDgGIAAgBIgBgBQgrhWgvgBIgBAAIAAAAQgZAAgaAYIgCABIAAABQBtiLBmCWIg/A6IgECPg");
	this.shape_10.setTransform(11.1,12.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_10},{t:this.shape_9},{t:this.shape_8}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-0.5,-2.5,23.2,30);


(lib.obj5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["#C26000","#482A00"],[0.22,1],-4.4,-1.7,4.4,-1.7).s().p("AgZB4QgHgPgEgQQgMgqAJgtQAHgiAUgmQAMgaATgaIAZAUQgOAWgKAWQgOAfgFAeQgGAmAHAlQAEAXAKAWg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.obj5, new cjs.Rectangle(-4.4,-12.3,8.9,24.7), null);


(lib.obj4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF0000").s().p("AAbAqQAlgpg4glQg2AkAGAfQACAMAMAEQABAMgIAKQgDgNgMgIQgUgVALgaIABgCQASgmAogPQAJgTAQAFQgJAEABALQAbAQAOAcQAGAQgNAcQgHAHgEAFQgDAFgBAEQgCAJgDAFQgNgLAHgRg");
	this.shape.setTransform(6.2,7);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.obj4, new cjs.Rectangle(0,0,12.4,14), null);


(lib.obj3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#B927FF").s().p("AgBCFQgPgCgQgQQgNgRAEgWQACgPgKgrQALAIADAOQAJgKgCgNQgLgDgDgNQgGgeA3gkQA3AmglAoQgGAQAMALQADgEADgJQAAgEAEgFQgCAeAFAeQACASgCAHQgCAGgGAKQgHALgWADgAgCiCQBIgNgMBpQgNgcgcgRQgBgKAKgEQgRgGgIATQgoAQgSAmQgLhUBCgQg");
	this.shape.setTransform(6,13.2);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.obj3, new cjs.Rectangle(0,0,12,26.5), null);


(lib.obj2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#66CCFF").s().p("AgyAnQgPgjAFgqIB5AAIABAAQADAtgPAgQgygdgyAdg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.obj2, new cjs.Rectangle(-6.2,-3.8,12.5,7.7), null);


(lib.obj1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(0.2,1,1).p("AA5ABQgBgBgBgBQgRgmgngPQgJgTgQAFQAKAEgBALQgbAQgNAcQgHAQANAcQAHAHAEAFQADAFABAEQACAJADAFQAMgLgDgOQgngsA3gkQA0AjgFAXQgDASgLAFQgCANAIAKQADgNAMgIQATgVgKgag");
	this.shape.setTransform(6,7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FF0000").s().p("AgkA4QgBgEgDgFQgEgFgHgHQgNgcAHgQQANgcAbgQQABgLgKgEQAQgFAJATQAnAPARAmIACACQAKAagTAVQgMAIgDANQgIgKACgNQALgFADgSQAFgXg0gjQg3AkAnAsQADAOgMALQgDgFgCgJg");
	this.shape_1.setTransform(6,7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.obj1, new cjs.Rectangle(-1,-1,14.1,16), null);


(lib.oarobj = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#D72828").s().p("AhaCcQgNgIADgXQADgYALgSQALgTAQgKQAQgJANAIIACABIABABQALAIAAAQQgBAQgJAUQgJAUgVAOQgNAKgKAAQgGAAgFgDgAAhgyIgCgCQgOgHABgTQAAgTALgSQAKgTATgOQATgPANAIQAOAIgDAZQgCAZgMASQgNASgOAIQgIAFgIAAQgGAAgFgCg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.oarobj, new cjs.Rectangle(-10.2,-15.9,20.4,31.8), null);


(lib.mountain = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AOKOfQAZFPkTiiIFQxgIEfUfQk7n3g6CLgAwML1IjziKIF1wFIDgOyILB8iMAIkAgVQjYlliTD8QjXqgkYIlQhSn8k5HtQAIEPixAAQhMAAhtgyg");
	this.shape.setTransform(287.7,36);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Layer 1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.lf(["#FFFFFF","#DDDDDD","#C4C4C4","#B3B3B3","#999999"],[0,0.235,0.655,0.875,1],0,-158.9,0,159).s().p("A41a9MAOigoJIDhOyILA8iMAJ5AlWIFRxgIFeY/IAAJEg");
	this.shape_1.setTransform(263,79.5);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

}).prototype = getMCSymbolPrototype(lib.mountain, new cjs.Rectangle(104,-93,318,345), null);


(lib.mbox = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(255,255,255,0)").s().p("AvbKnIAA1NIe3AAIAAVNg");
	this.shape.setTransform(98.8,67.9);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.mbox, new cjs.Rectangle(0,0,197.6,135.8), null);


(lib.grass2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#006600").ss(3.1,1,1).p("EAgyAAYQG6iQhdjrQFXB7AZCyQDEgogEhlQECC+Ezo1IEEJ+QCXh+haiZQE8BuAUCpIBzAAQgOmeD7lZQgVF8FSF7IAJAYIAAJgMiZVAAAIAAp4IE3qPQgkEYETD5IA9kBQApDbDMAVQBzB+ANgNQAVgWASgPQB/hrgJmRQDhHsgfhUIBSCnQEAi+CEC+QCVl/hcmAIEQJIIB2iYQhZC5EMB6IBRirQDVBkgEBjQDpkEBzEEQg0mNEtkyQAgE5GeDjIAkAsAx2hfIBVkQQDdC/AQC/ICdiyID3CgICBj6QFFChgGCgQCHhmCEBmQE2ivg9iwQElAfAgDBQFwiAAIjdQFgDuAEBfICMCPQhTiWDIhBQAABWDsBVIA+As");
	this.shape.setTransform(206.8,-17.9);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#009900").s().p("EhMqAK8IAAp4IE3qPQgkEYETD4IA9kAQApDbDMAVQBzB+ANgOQAVgVASgQQB/hqgJmRQDhHsgfhUIBSCnQEAi+CEC+QCWl/hdmAIERJIIB1iYQhYC5ELB5IBRiqQDWBkgFBjQDpkEBzEEQg0mNEtkyQAhE6GdDhIAlAtIglgtIBVkQQDdDAARC/ICciyID3CgICBj6QFFChgGCgQCHhmCEBmQE3ivg+ixQElAgAgDBQFwiAAHjdQFiDuADBfICMCPQhTiWDIhBQAABWDsBVQG6iRhdjqQFXB7AYCyQDFgogEhlQECC+Ezo1IEDJ+QCYh+haiZQE8BtAUCqIBzAAQgOmeD7lZQgVF8FSF7IAJAYIAAJggEAhwABEIg+gsg");
	this.shape_1.setTransform(206.8,-17.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.grass2, new cjs.Rectangle(-285.5,-89.5,984.5,143.1), null);


(lib.Symbol1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AAgAfIgBgDIACgCIAFgBIADADQAAADgFACgAg3AdIgBgDQADgDAGABIAAAAIABADQAAABAAABQAAAAAAABQAAAAgBAAQAAgBAAAAQgCACgCAAgAAJAZQABgEAGgBIACACQAAAEgEABQgBAAgBAAQAAAAgBgBQAAAAgBAAQAAAAgBgBgAhzAYIAAgDQACgDAGABIABAAIAAADQAAABAAABQAAAAAAABQAAAAAAAAQAAgBAAAAQgCACgDAAgABdATIAAgDIACgCIAFAAIACACQAAADgEACgAgbANIgBgDQACgEADAAIALAFQgBAFgGAAQgEAAgEgDgAA9AKQgCgCAAgDQAEgCAFABIABADIgBADQAAAAAAAAQAAAAgBAAQAAABgBAAQgBAAAAAAgAhMAEIAAgDQAAAAAAgBQABAAAAAAQAAAAABAAQAAgBAAAAQACgBAKACIABAAIAAACQAAABAAAAQAAABAAAAQgBABAAAAQAAABgBAAIgGAAQgEAAgDgCgAiIAEQgCgCAAgCQADgDAGABIABADIgBACQAAAAAAAAQAAABgBAAQAAAAgBAAQgBAAAAAAgACDgCQAAAAAAAAQgBgBAAAAQAAgBAAAAQAAgBAAgBQAAgBAAAAQAAgBAAAAQABgBAAAAQABAAAAAAIAFAAQACACAAADQgBACgEABIgDgBgAAfgKQAEgCAFABIAAAAIABADQAAABAAABQAAAAAAABQAAAAgBAAQAAgBAAAAIgEACQgFgBAAgFgABbgSQACgDAGABIABAAIAAADQAAABAAABQAAAAAAABQAAAAAAAAQAAgBAAAAQAAAAgBABQAAAAgBAAQAAABgBAAQAAAAgBAAQgFgBAAgEgAgwgPQAAABAAAAQAAAAAAAAQAAgBAAAAQAAgBAAgBQAAgGAQACIABADQAAAFgKAAQgFAAgCgCgAhagPQAAAAAAAAQAAgBgBAAQAAgBAAAAQAAgBAAgBQAAgGAMADIABACIgIAGgABDgSQgCgCAAgDQADgCAFAAIABAAIAAADQAAABAAABQAAABAAAAQAAAAAAAAQAAAAAAgBIAAACIgEAAgAAQgZQgCgCAAgEQAFgBAEACIAAACIAAADQAAAAAAAAQAAAAAAAAQAAABgBAAQgBAAgBAAg");
	this.shape.setTransform(13.9,3.3);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol1, new cjs.Rectangle(0,0,27.8,6.6), null);


(lib.obj4_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.lf(["#C26000","#482A00"],[0.22,1],-3.7,-1.2,3.7,-1.2).s().p("AgZCQQAIgTAFgTQAKglABgnQAAgugPgyQgIgcgMgcIAZgVQAPAhAMAgQAUA5ABAyQABAvgOAqQgEANgGANg");

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

}).prototype = getMCSymbolPrototype(lib.obj4_1, new cjs.Rectangle(-3.7,-14.3,7.5,28.8), null);


(lib.obj3_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.lf(["#009900","#C1FFAD","#33FF00"],[0.051,0.549,0.914],-17.6,0,17.7,0).s().p("AgWABQgrADgdA7QgEgMAEgMQgWAGgIAjQgKgKAEgOQgRAPgIAfQgOggANggQAahCBoAGQgagWgtAWIAAgLIgnASIADgPIgqASQA2h4BmBMQgDiLCOAkQgbgCgEAJQABAHAKACQgYgCgGANQAAAGAOABQgXAAgJAQQgBAIAKgCQgdAXgJAhQA9hIBcBlQgcgUgXAHQAQAJgBAMQgRgVgWAIQAOAKACAMQgJgKgQAAQg3gYgmA1QgTAfAOArQgIACgIgPQgRAgARAZQgIgBgIgJQACAXAGATQhfhJBnheg");

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

}).prototype = getMCSymbolPrototype(lib.obj3_1, new cjs.Rectangle(-17.6,-16.7,35.3,33.5), null);


(lib.obj2_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#B927FF").s().p("AgGCFQgVgDgHgLQgGgKgCgGQgCgHACgSQAFgegCgeQAEAFAAAEQADAJACAEQANgLgDgOQgogqA4gmQA0AkgFAYQgEARgLAFQgBANAIAKQADgOALgIQgKArACAPQAEAWgNARQgQAQgOACgAAAhUQgIgTgQAGQAJAEgBAKQgbARgNAcQgMhpBHANQBAAQgKBUQgSgmgngQg");
	this.shape_1.setTransform(5.8,13.2);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

}).prototype = getMCSymbolPrototype(lib.obj2_1, new cjs.Rectangle(0,0,11.7,26.5), null);


(lib.driverobj = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#666666").s().p("AiMBqQgghVAkh5QCGgJCQAIQAcBmgcBpg");
	this.shape.setTransform(0.1,-0.1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.driverobj, new cjs.Rectangle(-15.5,-10.7,31.2,21.2), null);


(lib.dots = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("EgyJglLIAABGEAyKAlMIAAhk");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.dots, new cjs.Rectangle(-321.9,-238.9,644,478), null);


(lib.cloud1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#CCCCCC").s().p("AG+HAIAAgDIgZAAIAAgDIgSAAIAAgDIgRAAIAAgCIgKAAIAAgDIgLAAIAAgCIgLAAIAAgEIgLAAIAAgCIgGAAIAAgDIgIAAIAAgDIgKAAIAAgDIgIAAIAAgCIgHAAIAAgEIgHAAIAAgDIgGAAIAAgCIgEAAIAAgDIgHAAIAAgDIgHAAIAAgDIgDAAIAAgDIgIAAIAAgDIgDAAIAAgCIgEAAIAAgDIgHAAIAAgDIgEAAIAAgCIgDAAIAAgDIgHAAIAAgDIgEAAIAAgDIgDAAIAAgDIgEAAIAAgEIgDAAIAAgCIgHAAIAAACIgEAAIAAAEIgHAAIAAADIgEAAIAAADIgHAAIAAADIgGAAIAAADIgIAAIAAACIgHAAIAAADIgLAAIAAADIgHAAIAAACIgHAAIAAADIgOAAIAAADIgLAAIAAADIgOAAIAAADIgVAAIAAADIgZAAIAAACIg8AAIAAgCIgfAAIAAgDIgOAAIAAgDIgOAAIAAgDIgPAAIAAgDIgKAAIAAgDIgHAAIAAgCIgLAAIAAgDIgGAAIAAgDIgDAAIAAADIgEAAIAAADIgEAAIAAACIgEAAIAAADIgHAAIAAADIgDAAIAAADIgFAAIAAADIgGAAIAAADIgDAAIAAACIgEAAIAAADIgIAAIAAAEIgDAAIAAACIgGAAIAAADIgIAAIAAADIgHAAIAAADIgHAAIAAACIgHAAIAAAEIgLAAIAAACIgHAAIAAADIgOAAIAAACIgLAAIAAADIgVAAIAAADIhHAAIAAgDIgSAAIAAgDIgRAAIAAgCIgKAAIAAgDIgLAAIAAgCIgHAAIAAgEIgLAAIAAgCIgHAAIAAgDIgIAAIAAgDIgHAAIAAgDIgDAAIAAgCIgIAAIAAgEIgGAAIAAgDIgEAAIAAgCIgHAAIAAgDIgEAAIAAgDIgDAAIAAgDIgEAAIAAgDIgGAAIAAgDIgEAAIAAgCIgDAAIAAgDIgEAAIAAgDIgEAAIAAgCIgDAAIAAgDIgDAAIAAgDIgEAAIAAgGIgEAAIAAgEIgEAAIAAgCIgDAAIAAgDIgEAAIAAgFIgDAAIAAgDIgEAAIAAgGIgDAAIAAgGIgDAAIAAgDIgEAAIAAgGIgEAAIAAgHIgEAAIAAgEIgDAAIAAAEIgHAAIAAADIgLAAIAAACIgKAAIAAACIgHAAIAAAEIgPAAIAAACIgJAAIAAADIgPAAIAAADIgSAAIAAADIgYAAIAAADIgkAAIAAADIgxAAIAAgDIgkAAIAAgDIgZAAIAAgDIgPAAIAAgDIgNAAIAAgDIgOAAIAAgCIgLAAIAAgEIgKAAIAAgCIgHAAIAAgCIgLAAIAAgDIgIAAIAAgEIgGAAIAAgCIgIAAIAAgDIgHAAIAAgDIgHAAIAAgDIgHAAIAAgCIgDAAIAAgEIgIAAIAAgCIgHAAIAAgDIgDAAIAAgDIgDAAIAAgDIgIAAIAAgDIgDAAIAAgDIgEAAIAAgDIgHAAIAAgCIgDAAIAAgDIgEAAIAAgDIgDAAIAAgCIgEAAIAAgDIgEAAIAAgEIgDAAIAAgCIgEAAIAAgDIgEAAIAAgDIgDAAIAAgDIgEAAIAAgCIgDAAIAAgDIgEAAIAAgGIgDAAIAAgDIgEAAIAAgFIgEAAIAAgEIgDAAIAAgFIgDAAIAAgDIgEAAIAAgIIgDAAIAAgGIgEAAIAAgGIgDAAIAAgFIgEAAIAAgMIgDAAIAAgHIgDAAIAAgPIgEAAIAAg8IAEAAIAAgLIADAAIAAgLIADAAIAAgJIAEAAIAAgGIADAAIAAgFIAEAAIAAgGIADAAIAAgGIAEAAIAAgDIADAAIAAgGIADAAIAAgDIAEAAIAAgFIAEAAIAAgDIADAAIAAgCIAEAAIAAgHIADAAIAAgCIAEAAIAAgDIADAAIAAgDIAEAAIAAgCIAEAAIAAgDIADAAIAAgDIAEAAIAAgDIAEAAIAAgDIADAAIAAgCIAEAAIAAgDIADAAIAAgCIAEAAIAAgEIAHAAIAAgCIADAAIAAgCIAEAAIAAgEIAHAAIAAgDIADAAIAAgCIAEAAIAAgDIAHAAIAAgDIAHAAIAAgCIADAAIAAgEIAIAAIAAgDIAHAAIAAgCIAHAAIAAgDIAHAAIAAgDIAHAAIAAgDIALAAIAAgCIAHAAIAAgDIAKAAIAAgDIAKAAIAAgDIALAAIAAgEIASAAIAAgDIAOAAIAAgBIATAAIAAgEIAfAAIAAgCIBHAAIAAACIAgAAIAAAEIADAAIAAgPIADAAIAAgLIAEAAIAAgJIAEAAIAAgIIAEAAIAAgGIADAAIAAgGIADAAIAAgGIADAAIAAgFIAEAAIAAgEIAEAAIAAgEIAEAAIAAgEIADAAIAAgCIAEAAIAAgDIAEAAIAAgDIAEAAIAAgDIADAAIAAgCIADAAIAAgEIADAAIAAgCIAEAAIAAgDIAEAAIAAgDIAHAAIAAgDIADAAIAAgCIAIAAIAAgEIADAAIAAgDIAHAAIAAgCIAHAAIAAgEIAHAAIAAgCIALAAIAAgCIAKAAIAAgDIAOAAIAAgEIAWAAIAAgCIAnAAIAAACIARAAIAAAEIAPAAIAAADIAKAAIAAACIAEAAIAAgFIAEAAIAAgGIADAAIAAgJIAEAAIAAgGIADAAIAAgFIADAAIAAgGIAFAAIAAgJIADAAIAAgGIADAAIAAgCIAEAAIAAgFIADAAIAAgGIAEAAIAAgCIAEAAIAAgGIADAAIAAgGIADAAIAAgDIAEAAIAAgCIADAAIAAgGIAEAAIAAgDIAEAAIAAgHIADAAIAAgBIADAAIAAgDIAEAAIAAgEIAEAAIAAgFIADAAIAAgDIAEAAIAAgDIAEAAIAAgDIADAAIAAgCIAEAAIAAgEIAEAAIAAgCIADAAIAAgDIADAAIAAgDIAEAAIAAgCIADAAIAAgEIAEAAIAAgDIADAAIAAgCIADAAIAAgDIAEAAIAAgDIADAAIAAgDIAEAAIAAgCIAEAAIAAgEIAHAAIAAgCIADAAIAAgDIAEAAIAAgEIADAAIAAgCIAIAAIAAgCIADAAIAAgEIAEAAIAAgCIAGAAIAAgDIAFAAIAAgDIAGAAIAAgDIAEAAIAAgDIAIAAIAAgDIADAAIAAgCIAHAAIAAgDIAHAAIAAgDIAHAAIAAgDIAIAAIAAgCIADAAIAAgDIAGAAIAAgEIAIAAIAAgCIAKAAIAAgCIAIAAIAAgEIAGAAIAAgDIAMAAIAAgCIAHAAIAAgEIAKAAIAAgCIAKAAIAAgDIALAAIAAgDIAOAAIAAgDIAKAAIAAgCIASAAIAAgEIASAAIAAgCIAYAAIAAgDIB5AAIAAADIAbAAIAAACIATAAIAAAEIARAAIAAACIAPAAIAAADIAOAAIAAADIAKAAIAAADIALAAIAAACIAKAAIAAAEIAIAAIAAACIALAAIAAADIAHAAIAAAEIAHAAIAAACIAHAAIAAACIAKAAIAAAEIAHAAIAAADIADAAIAAACIAIAAIAAADIAGAAIAAADIAIAAIAAADIAEAAIAAACIAGAAIAAADIADAAIAAADIAIAAIAAADIAEAAIAAADIAHAAIAAADIADAAIAAACIAIAAIAAAEIADAAIAAACIADAAIAAACIAEAAIAAAEIAHAAIAAADIAEAAIAAACIADAAIAAAEIADAAIAAACIAFAAIAAADIAGAAIAAADIAEAAIAAADIADAAIAAACIAFAAIAAADIADAAIAAAEIADAAIAAACIADAAIAAADIAEAAIAAADIAEAAIAAACIADAAIAAAGIAEAAIAAADIADAAIAAADIAFAAIAAADIADAAIAAADIADAAIAAACIAEAAIAAAHIADAAIAAABIAEAAIAAADIAEAAIAAAEIADAAIAAAFIADAAIAAAEIAEAAIAAAFIAEAAIAAADIADAAIAAAFIAEAAIAAAEIADAAIAAAFIADAAIAAAGIAEAAIAAAEIADAAIAAAGIAEAAIAAAEIADAAIAAAFIAEAAIAAAJIAEAAIAAAGIADAAIAAAFIADAAIAAAGIAEAAIAAAJIADAAIAAAIIAEAAIAAAJIAEAAIAAAIIAEAAIAAALIADAAIAAALIAEAAIAAARIAEAAIAAAPIAGAAIAAADIAPAAIAAACIAOAAIAAAEIAOAAIAAACIAKAAIAAADIALAAIAAADIAHAAIAAADIALAAIAAADIAKAAIAAACIAIAAIAAADIAKAAIAAADIAHAAIAAADIAHAAIAAAEIAHAAIAAACIADAAIAAACIAIAAIAAAEIAHAAIAAABIADAAIAAADIAHAAIAAAEIAEAAIAAADIAHAAIAAADIAEAAIAAADIAEAAIAAACIAHAAIAAADIADAAIAAADIAEAAIAAADIAHAAIAAACIADAAIAAADIAEAAIAAAEIADAAIAAACIAEAAIAAAGIADAAIAAACIAEAAIAAADIADAAIAAAEIAVAAIAAgEIBEAAIAAAEIARAAIAAACIALAAIAAACIAKAAIAAAEIALAAIAAACIAIAAIAAADIAHAAIAAACIAHAAIAAADIAHAAIAAADIAEAAIAAADIAHAAIAAADIADAAIAAACIAHAAIAAADIAEAAIAAADIADAAIAAACIAEAAIAAAEIAHAAIAAADIADAAIAAAFIAEAAIAAADIADAAIAAACIAEAAIAAADIAEAAIAAAEIADAAIAAACIAEAAIAAAGIADAAIAAADIADAAIAAAGIAEAAIAAACIAEAAIAAAGIADAAIAAAFIAEAAIAAAHIAEAAIAAAFIAEAAIAAAIIADAAIAAAJIADAAIAAAPIADAAIAAA8IgDAAIAAANIgDAAIAAAJIgDAAIAAAIIgEAAIAAAGIgEAAIAAAFIgEAAIAAAGIgDAAIAAAFIgEAAIAAAEIgEAAIAAAFIgDAAIAAADIgDAAIAAAGIgEAAIAAADIgDAAIAAACIgEAAIAAADIgEAAIAAADIgDAAIAAADIgEAAIAAAGIgHAAIAAADIgDAAIAAACIgEAAIAAADIgDAAIAAADIgEAAIAAACIgHAAIAAADIgDAAIAAADIgEAAIAAADIgHAAIAAADIgHAAIAAADIgHAAIAAADIgHAAIAAACIgIAAIAAAEIgHAAIAAACIgKAAIAAADIgPAAIAAADIgRAAIAAADIg5AAIAAACIgDAAIAAAEIgEAAIAAAFIgEAAIAAAGIgDAAIAAACIgDAAIAAADIgEAAIAAADIgDAAIAAADIgEAAIAAADIgEAAIAAADIgDAAIAAADIgEAAIAAADIgDAAIAAACIgEAAIAAADIgDAAIAAACIgEAAIAAAEIgDAAIAAADIgEAAIAAADIgDAAIAAADIgHAAIAAADIgEAAIAAACIgDAAIAAADIgEAAIAAADIgIAAIAAACIgDAAIAAADIgHAAIAAADIgEAAIAAADIgHAAIAAADIgDAAIAAADIgIAAIAAACIgHAAIAAADIgGAAIAAAEIgHAAIAAACIgHAAIAAADIgHAAIAAADIgLAAIAAADIgHAAIAAACIgLAAIAAAEIgKAAIAAACIgLAAIAAADIgOAAIAAACIgPAAIAAADIgSAAIAAADIgUAAIAAADg");
	this.shape.setTransform(1.6,14.1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Layer 1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#CCCCCC").ss(7.1,1,1).p("AAHpcIgYAAIAAAEIgSAAIAAAEIgSAAIAAAEIgLAAIAAAEIgOAAIAAAEIgLAAIAAAEIgLAAIAAADIgLAAIAAAEIgHAAIAAAEIgLAAIAAAEIgHAAIAAAEIgHAAIAAAEIgLAAIAAAEIgHAAIAAADIgHAAIAAAEIgEAAIAAAEIgHAAIAAAEIgHAAIAAAEIgHAAIAAADIgIAAIAAAFIgDAAIAAADIgHAAIAAAEIgEAAIAAAEIgHAAIAAAEIgEAAIAAAEIgHAAIAAADIgEAAIAAAEIgDAAIAAAEIgHAAIAAAEIgEAAIAAAEIgEAAIAAAEIgDAAIAAAEIgHAAIAAAEIgEAAIAAADIgEAAIAAAEIgDAAIAAAEIgEAAIAAAEIgDAAIAAAEIgEAAIAAAEIgEAAIAAAEIgDAAIAAADIgEAAIAAAEIgDAAIAAAEIgEAAIAAAEIgDAAIAAAEIgEAAIAAADIgEAAIAAAFIgDAAIAAAEIgEAAIAAADIgDAAIAAAIIgEAAIAAAEIgEAAIAAAEIgDAAIAAADIgEAAIAAAIIgDAAIAAAEIgEAAIAAAIIgEAAIAAAEIgDAAIAAADIgEAAIAAAIIgDAAIAAAIIgEAAIAAAEIgEAAIAAAHIgDAAIAAAIIgEAAIAAAEIgDAAIAAAHIgEAAIAAAMIgEAAIAAAIIgDAAIAAAIIgEAAIAAAHIgDAAIAAAMIgEAAIAAAIIgEAAIAAAHIgDAAIAAgEIgLAAIAAgDIgOAAIAAgEIgSAAIAAgEIgoAAIAAAEIgVAAIAAAEIgPAAIAAADIgLAAIAAAEIgKAAIAAAEIgIAAIAAAEIgHAAIAAAEIgHAAIAAAEIgDAAIAAAEIgIAAIAAAEIgDAAIAAADIgHAAIAAAEIgEAAIAAAEIgEAAIAAAEIgDAAIAAAEIgEAAIAAAEIgDAAIAAAEIgEAAIAAADIgEAAIAAAEIgDAAIAAAEIgEAAIAAAEIgDAAIAAAHIgEAAIAAAFIgEAAIAAAHIgDAAIAAAIIgEAAIAAAHIgDAAIAAAIIgEAAIAAAMIgEAAIAAALIgDAAIAAAQIgEAAIAAATIgDAAIAAgEIghAAIAAgEIhIAAIAAAEIggAAIAAAEIgSAAIAAAEIgOAAIAAAEIgSAAIAAADIgLAAIAAAFIgLAAIAAAEIgLAAIAAADIgHAAIAAAEIgLAAIAAAEIgHAAIAAAEIgHAAIAAAEIgHAAIAAADIgHAAIAAAEIgIAAIAAAEIgDAAIAAAEIgHAAIAAAEIgIAAIAAAEIgDAAIAAAEIgEAAIAAADIgHAAIAAAEIgEAAIAAAEIgDAAIAAAEIgHAAIAAAEIgEAAIAAAEIgDAAIAAAEIgEAAIAAACIgEAAIAAAEIgDAAIAAAEIgEAAIAAAEIgDAAIAAAEIgEAAIAAADIgEAAIAAAFIgDAAIAAAEIgEAAIAAADIgDAAIAAAIIgEAAIAAAEIgEAAIAAAEIgDAAIAAAHIgEAAIAAAEIgDAAIAAAIIgEAAIAAAEIgEAAIAAAHIgDAAIAAAIIgEAAIAAAIIgDAAIAAAIIgEAAIAAALIgEAAIAAAQIgDAAIAAAPIgEAAIAABRIAEAAIAAATIADAAIAAAMIAEAAIAAAPIAEAAIAAAIIADAAIAAAHIAEAAIAAAIIADAAIAAAMIAEAAIAAAEIAEAAIAAAHIADAAIAAAEIAEAAIAAAIIADAAIAAAEIAEAAIAAAIIAEAAIAAADIADAAIAAAEIAEAAIAAAEIADAAIAAAEIAEAAIAAAEIAEAAIAAADIADAAIAAAEIAEAAIAAAFIADAAIAAADIAEAAIAAAEIAEAAIAAAEIADAAIAAAEIAHAAIAAAEIAEAAIAAADIADAAIAAAEIAIAAIAAAEIADAAIAAAEIAEAAIAAAEIAHAAIAAAEIAHAAIAAAEIAEAAIAAADIAHAAIAAAEIAHAAIAAAEIAHAAIAAAEIAIAAIAAAEIAHAAIAAAEIAHAAIAAAEIALAAIAAADIAHAAIAAAEIALAAIAAAEIALAAIAAAEIAOAAIAAAEIAOAAIAAADIAPAAIAAAEIAZAAIAAAFIAkAAIAAADIAyAAIAAgDIAkAAIAAgFIAZAAIAAgEIASAAIAAgDIAPAAIAAgEIAKAAIAAgEIAPAAIAAgEIAHAAIAAgEIALAAIAAgDIAKAAIAAgEIAIAAIAAgEIADAAIAAAEIAEAAIAAALIADAAIAAAIIAEAAIAAAEIAEAAIAAAHIADAAIAAAIIAEAAIAAAEIADAAIAAAIIAEAAIAAAEIAEAAIAAADIADAAIAAAEIAEAAIAAAIIADAAIAAAEIAEAAIAAAEIAEAAIAAAEIADAAIAAADIAEAAIAAAEIADAAIAAAEIAEAAIAAAEIAHAAIAAAEIAEAAIAAAEIADAAIAAAEIAEAAIAAADIAHAAIAAAEIAEAAIAAAEIAHAAIAAAEIAHAAIAAAEIAEAAIAAADIAHAAIAAAEIAHAAIAAAFIAHAAIAAADIALAAIAAAEIAHAAIAAAEIALAAIAAAEIALAAIAAAEIASAAIAAADIASAAIAAAEIBIAAIAAgEIAVAAIAAgDIALAAIAAgEIAOAAIAAgEIAIAAIAAgEIAKAAIAAgEIAIAAIAAgDIAHAAIAAgFIAHAAIAAgEIAHAAIAAgDIAHAAIAAgEIAEAAIAAgEIAHAAIAAgEIAEAAIAAgEIADAAIAAgDIAHAAIAAgEIAEAAIAAgEIAEAAIAAgEIAHAAIAAgEIADAAIAAgEIAEAAIAAgEIAEAAIAAgDIADAAIAAADIAHAAIAAAEIALAAIAAAEIAHAAIAAAEIALAAIAAAEIAPAAIAAAEIAOAAIAAAEIAOAAIAAADIAgAAIAAAEIA9AAIAAgEIAZAAIAAgDIAWAAIAAgEIAOAAIAAgEIALAAIAAgEIAPAAIAAgEIAHAAIAAgEIAHAAIAAgEIALAAIAAgDIAHAAIAAgEIAHAAIAAgEIAHAAIAAgEIAHAAIAAgEIAEAAIAAgEIAHAAIAAgEIAEAAIAAgDIAHAAIAAADIAEAAIAAAEIADAAIAAAEIAEAAIAAAEIADAAIAAAEIAIAAIAAAEIADAAIAAAEIAEAAIAAADIAHAAIAAAEIAEAAIAAAEIADAAIAAAEIAHAAIAAAEIAEAAIAAAEIAHAAIAAAEIAHAAIAAADIAEAAIAAAEIAHAAIAAAEIAHAAIAAAEIAHAAIAAAEIAIAAIAAADIAKAAIAAAEIAIAAIAAAFIAHAAIAAADIALAAIAAAEIAKAAIAAAEIALAAIAAAEIALAAIAAAEIASAAIAAADIASAAIAAAEIAZAAIAAAEIBsAAIAAgEIAVAAIAAgEIASAAIAAgDIAPAAIAAgEIAOAAIAAgEIALAAIAAgEIALAAIAAgEIALAAIAAgDIAHAAIAAgFIALAAIAAgEIAHAAIAAgDIAHAAIAAgEIAHAAIAAgEIAHAAIAAgEIAHAAIAAgEIAIAAIAAgDIADAAIAAgEIAHAAIAAgEIAEAAIAAgEIAHAAIAAgEIAEAAIAAgEIAHAAIAAgEIAEAAIAAgDIADAAIAAgEIAEAAIAAgEIAHAAIAAgEIAEAAIAAgEIADAAIAAgEIAEAAIAAgEIADAAIAAgDIAEAAIAAgEIAEAAIAAgEIADAAIAAgEIAEAAIAAgEIADAAIAAgDIAEAAIAAgFIAEAAIAAgEIADAAIAAgDIAEAAIAAgEIADAAIAAgEIAEAAIAAgIIAEAAIAAgHIADAAIAAgEIAEAAIAAgEIA5AAIAAgEIASAAIAAgEIAPAAIAAgEIAKAAIAAgDIAIAAIAAgEIAHAAIAAgEIAHAAIAAgEIAHAAIAAgEIAHAAIAAgEIAHAAIAAgEIAEAAIAAgDIAEAAIAAgEIAHAAIAAgEIADAAIAAgEIAEAAIAAgEIAEAAIAAgDIADAAIAAgFIAHAAIAAgHIAEAAIAAgEIAEAAIAAgEIADAAIAAgEIAEAAIAAgEIADAAIAAgDIAEAAIAAgIIAEAAIAAgEIADAAIAAgIIAEAAIAAgEIADAAIAAgHIAEAAIAAgIIAEAAIAAgIIADAAIAAgIIAEAAIAAgLIADAAIAAgMIAEAAIAAgTIAEAAIAAhRIgEAAIAAgTIgEAAIAAgLIgDAAIAAgMIgEAAIAAgIIgDAAIAAgIIgEAAIAAgHIgEAAIAAgIIgDAAIAAgEIgEAAIAAgIIgDAAIAAgDIgEAAIAAgIIgEAAIAAgEIgDAAIAAgEIgEAAIAAgEIgDAAIAAgEIgEAAIAAgDIgEAAIAAgIIgDAAIAAgEIgHAAIAAgEIgEAAIAAgDIgEAAIAAgEIgDAAIAAgFIgHAAIAAgDIgEAAIAAgEIgHAAIAAgEIgEAAIAAgEIgHAAIAAgEIgHAAIAAgCIgHAAIAAgEIgHAAIAAgEIgLAAIAAgEIgLAAIAAgEIgLAAIAAgEIgSAAIAAgEIhEAAIAAAEIgWAAIAAgEIgDAAIAAgDIgEAAIAAgEIgDAAIAAgIIgEAAIAAgEIgEAAIAAgEIgDAAIAAgEIgEAAIAAgDIgHAAIAAgEIgEAAIAAgEIgDAAIAAgEIgHAAIAAgEIgEAAIAAgDIgEAAIAAgEIgHAAIAAgFIgDAAIAAgDIgIAAIAAgEIgDAAIAAgEIgHAAIAAgEIgIAAIAAgEIgDAAIAAgDIgHAAIAAgEIgHAAIAAgEIgIAAIAAgEIgKAAIAAgEIgIAAIAAgEIgKAAIAAgEIgLAAIAAgDIgHAAIAAgEIgLAAIAAgEIgLAAIAAgEIgOAAIAAgEIgPAAIAAgEIgOAAIAAgEIgHAAIAAgTIgEAAIAAgXIgDAAIAAgPIgEAAIAAgQIgEAAIAAgLIgDAAIAAgMIgEAAIAAgMIgDAAIAAgLIgEAAIAAgIIgEAAIAAgIIgDAAIAAgHIgEAAIAAgMIgDAAIAAgHIgEAAIAAgFIgEAAIAAgHIgDAAIAAgIIgEAAIAAgHIgDAAIAAgIIgEAAIAAgEIgEAAIAAgIIgDAAIAAgEIgEAAIAAgHIgDAAIAAgEIgEAAIAAgIIgEAAIAAgEIgDAAIAAgEIgEAAIAAgDIgDAAIAAgIIgEAAIAAgEIgEAAIAAgEIgDAAIAAgDIgEAAIAAgEIgDAAIAAgFIgEAAIAAgHIgEAAIAAgEIgDAAIAAgEIgEAAIAAgEIgDAAIAAgDIgEAAIAAgEIgDAAIAAgEIgEAAIAAgEIgEAAIAAgEIgDAAIAAgEIgHAAIAAgEIgEAAIAAgDIgEAAIAAgEIgDAAIAAgEIgEAAIAAgEIgHAAIAAgEIgEAAIAAgEIgDAAIAAgEIgEAAIAAgEIgHAAIAAgDIgEAAIAAgEIgHAAIAAgEIgDAAIAAgEIgIAAIAAgEIgDAAIAAgDIgHAAIAAgFIgEAAIAAgDIgHAAIAAgEIgHAAIAAgEIgIAAIAAgEIgDAAIAAgEIgHAAIAAgDIgLAAIAAgEIgHAAIAAgEIgHAAIAAgEIgIAAIAAgEIgKAAIAAgEIgIAAIAAgEIgKAAIAAgDIgLAAIAAgEIgLAAIAAgEIgOAAIAAgEIgPAAIAAgEIgSAAIAAgEIgSAAIAAgEIgcAAIAAgEIh7AAg");

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AHFJhIAAgEIgZAAIAAgEIgSAAIAAgDIgTAAIAAgEIgKAAIAAgEIgLAAIAAgEIgLAAIAAgEIgLAAIAAgDIgHAAIAAgFIgHAAIAAgEIgLAAIAAgDIgHAAIAAgEIgHAAIAAgEIgHAAIAAgEIgIAAIAAgEIgDAAIAAgDIgHAAIAAgEIgIAAIAAgEIgDAAIAAgEIgHAAIAAgEIgDAAIAAgEIgFAAIAAgEIgHAAIAAgDIgDAAIAAgEIgDAAIAAgEIgIAAIAAgEIgEAAIAAgEIgDAAIAAgEIgDAAIAAgEIgEAAIAAgDIgIAAIAAADIgDAAIAAAEIgHAAIAAAEIgEAAIAAAEIgHAAIAAAEIgHAAIAAAEIgIAAIAAAEIgGAAIAAADIgMAAIAAAEIgGAAIAAAEIgHAAIAAAEIgPAAIAAAEIgLAAIAAAEIgPAAIAAAEIgVAAIAAADIgZAAIAAAEIg9AAIAAgEIgfAAIAAgDIgPAAIAAgEIgOAAIAAgEIgPAAIAAgEIgKAAIAAgEIgIAAIAAgEIgKAAIAAgEIgIAAIAAgDIgDAAIAAADIgEAAIAAAEIgDAAIAAAEIgEAAIAAAEIgHAAIAAAEIgEAAIAAAEIgDAAIAAAEIgIAAIAAADIgDAAIAAAEIgEAAIAAAEIgHAAIAAAEIgEAAIAAAEIgHAAIAAADIgHAAIAAAEIgHAAIAAAFIgHAAIAAADIgIAAIAAAEIgKAAIAAAEIgIAAIAAAEIgOAAIAAAEIgLAAIAAADIgVAAIAAAEIhIAAIAAgEIgSAAIAAgDIgSAAIAAgEIgKAAIAAgEIgLAAIAAgEIgHAAIAAgEIgLAAIAAgDIgHAAIAAgFIgIAAIAAgEIgHAAIAAgDIgDAAIAAgEIgIAAIAAgEIgHAAIAAgEIgDAAIAAgEIgIAAIAAgDIgDAAIAAgEIgEAAIAAgEIgDAAIAAgEIgIAAIAAgEIgDAAIAAgEIgEAAIAAgEIgDAAIAAgDIgEAAIAAgEIgEAAIAAgEIgDAAIAAgEIgEAAIAAgIIgDAAIAAgEIgEAAIAAgDIgEAAIAAgEIgDAAIAAgIIgEAAIAAgEIgDAAIAAgIIgEAAIAAgHIgEAAIAAgEIgDAAIAAgIIgEAAIAAgLIgDAAIAAgEIgEAAIAAAEIgHAAIAAAEIgLAAIAAADIgLAAIAAAEIgHAAIAAAEIgOAAIAAAEIgLAAIAAAEIgPAAIAAADIgSAAIAAAEIgZAAIAAAFIgkAAIAAADIgyAAIAAgDIgkAAIAAgFIgZAAIAAgEIgPAAIAAgDIgOAAIAAgEIgOAAIAAgEIgLAAIAAgEIgLAAIAAgEIgHAAIAAgDIgLAAIAAgEIgHAAIAAgEIgHAAIAAgEIgIAAIAAgEIgHAAIAAgEIgGAAIAAgEIgIAAIAAgDIgEAAIAAgEIgGAAIAAgEIgIAAIAAgEIgEAAIAAgEIgDAAIAAgEIgIAAIAAgEIgDAAIAAgDIgEAAIAAgEIgGAAIAAgEIgEAAIAAgEIgEAAIAAgEIgEAAIAAgDIgDAAIAAgFIgDAAIAAgEIgEAAIAAgDIgEAAIAAgEIgEAAIAAgEIgDAAIAAgEIgDAAIAAgEIgEAAIAAgDIgEAAIAAgIIgEAAIAAgEIgDAAIAAgIIgDAAIAAgEIgEAAIAAgHIgDAAIAAgEIgFAAIAAgMIgDAAIAAgIIgDAAIAAgHIgEAAIAAgIIgDAAIAAgPIgFAAIAAgMIgDAAIAAgTIgDAAIAAhRIADAAIAAgPIADAAIAAgQIAFAAIAAgLIADAAIAAgIIAEAAIAAgIIADAAIAAgIIADAAIAAgHIAFAAIAAgEIADAAIAAgIIAEAAIAAgEIADAAIAAgHIADAAIAAgEIAEAAIAAgEIAEAAIAAgIIAEAAIAAgDIADAAIAAgEIADAAIAAgFIAEAAIAAgDIAEAAIAAgEIAEAAIAAgEIADAAIAAgEIADAAIAAgEIAEAAIAAgCIAEAAIAAgEIAEAAIAAgEIADAAIAAgEIAHAAIAAgEIADAAIAAgEIAFAAIAAgEIAGAAIAAgDIAEAAIAAgEIADAAIAAgEIAIAAIAAgEIAHAAIAAgEIADAAIAAgEIAIAAIAAgEIAHAAIAAgDIAIAAIAAgEIAGAAIAAgEIAHAAIAAgEIALAAIAAgEIAHAAIAAgDIALAAIAAgEIALAAIAAgFIALAAIAAgDIASAAIAAgEIAOAAIAAgEIASAAIAAgEIAgAAIAAgEIBIAAIAAAEIAhAAIAAAEIADAAIAAgTIAEAAIAAgQIAEAAIAAgLIADAAIAAgMIAEAAIAAgIIADAAIAAgHIAEAAIAAgIIAEAAIAAgHIADAAIAAgFIAEAAIAAgHIADAAIAAgEIAEAAIAAgEIAEAAIAAgEIADAAIAAgDIAEAAIAAgEIADAAIAAgEIAEAAIAAgEIAEAAIAAgEIADAAIAAgEIAEAAIAAgEIAHAAIAAgDIAEAAIAAgEIAHAAIAAgEIADAAIAAgEIAIAAIAAgEIAHAAIAAgEIAHAAIAAgEIALAAIAAgEIALAAIAAgDIAOAAIAAgEIAWAAIAAgEIAnAAIAAAEIASAAIAAAEIAPAAIAAADIAKAAIAAAEIADAAIAAgHIAFAAIAAgIIADAAIAAgMIAEAAIAAgHIADAAIAAgIIADAAIAAgIIAFAAIAAgMIADAAIAAgHIAEAAIAAgEIADAAIAAgIIADAAIAAgHIAEAAIAAgEIAEAAIAAgIIAEAAIAAgIIADAAIAAgDIADAAIAAgEIAEAAIAAgIIAEAAIAAgEIAEAAIAAgIIADAAIAAgDIADAAIAAgEIAEAAIAAgEIAEAAIAAgIIAEAAIAAgDIADAAIAAgEIADAAIAAgFIAEAAIAAgDIAEAAIAAgEIAEAAIAAgEIADAAIAAgEIADAAIAAgEIAEAAIAAgDIADAAIAAgEIAFAAIAAgEIADAAIAAgEIADAAIAAgEIAEAAIAAgEIADAAIAAgEIAFAAIAAgDIADAAIAAgEIAHAAIAAgEIADAAIAAgEIAFAAIAAgEIADAAIAAgEIAHAAIAAgEIADAAIAAgEIAEAAIAAgDIAHAAIAAgEIAEAAIAAgEIAHAAIAAgEIAEAAIAAgEIAHAAIAAgDIADAAIAAgFIAIAAIAAgDIAHAAIAAgEIAHAAIAAgEIAHAAIAAgEIAEAAIAAgEIAHAAIAAgDIAHAAIAAgEIALAAIAAgEIAHAAIAAgEIAHAAIAAgEIALAAIAAgEIAHAAIAAgEIALAAIAAgDIALAAIAAgEIALAAIAAgEIAOAAIAAgEIALAAIAAgEIASAAIAAgEIASAAIAAgEIAYAAIAAgEIB7AAIAAAEIAcAAIAAAEIASAAIAAAEIASAAIAAAEIAPAAIAAAEIAOAAIAAAEIAKAAIAAAEIAMAAIAAADIAKAAIAAAEIAIAAIAAAEIAKAAIAAAEIAIAAIAAAEIAGAAIAAAEIAHAAIAAAEIALAAIAAADIAHAAIAAAEIAEAAIAAAEIAHAAIAAAEIAHAAIAAAEIAIAAIAAADIADAAIAAAFIAHAAIAAADIAEAAIAAAEIAHAAIAAAEIAEAAIAAAEIAHAAIAAAEIADAAIAAADIAIAAIAAAEIADAAIAAAEIAEAAIAAAEIADAAIAAAEIAIAAIAAAEIADAAIAAAEIAEAAIAAAEIAEAAIAAADIADAAIAAAEIAHAAIAAAEIAEAAIAAAEIAEAAIAAAEIADAAIAAAEIAEAAIAAAEIADAAIAAADIAEAAIAAAEIADAAIAAAEIAEAAIAAAEIAEAAIAAAHIADAAIAAAFIAEAAIAAAEIADAAIAAADIAEAAIAAAEIAEAAIAAAEIADAAIAAAIIAEAAIAAADIADAAIAAAEIAEAAIAAAEIAEAAIAAAIIADAAIAAAEIAEAAIAAAHIAEAAIAAAEIADAAIAAAIIAEAAIAAAEIADAAIAAAIIAEAAIAAAHIAEAAIAAAIIADAAIAAAHIAEAAIAAAFIADAAIAAAHIAEAAIAAAMIADAAIAAAHIAEAAIAAAIIAEAAIAAAIIADAAIAAALIAEAAIAAAMIADAAIAAAMIAEAAIAAALIAEAAIAAAQIADAAIAAAPIAEAAIAAAXIADAAIAAATIAIAAIAAAEIAOAAIAAAEIAPAAIAAAEIAOAAIAAAEIALAAIAAAEIAKAAIAAAEIAIAAIAAADIALAAIAAAEIAKAAIAAAEIAHAAIAAAEIALAAIAAAEIAIAAIAAAEIAHAAIAAAEIAHAAIAAADIADAAIAAAEIAIAAIAAAEIAHAAIAAAEIADAAIAAAEIAIAAIAAADIADAAIAAAFIAHAAIAAAEIAEAAIAAADIAEAAIAAAEIAHAAIAAAEIADAAIAAAEIAEAAIAAAEIAHAAIAAADIAEAAIAAAEIADAAIAAAEIADAAIAAAEIAFAAIAAAIIADAAIAAAEIAEAAIAAADIADAAIAAAEIAVAAIAAgEIBFAAIAAAEIASAAIAAAEIAKAAIAAAEIALAAIAAAEIAMAAIAAAEIAGAAIAAAEIAHAAIAAACIAIAAIAAAEIAHAAIAAAEIADAAIAAAEIAIAAIAAAEIADAAIAAADIAHAAIAAAFIAEAAIAAAEIAEAAIAAADIADAAIAAAEIAHAAIAAAEIAEAAIAAAIIAEAAIAAADIADAAIAAAEIAEAAIAAAEIADAAIAAAEIAEAAIAAAEIAEAAIAAAIIADAAIAAADIAEAAIAAAIIADAAIAAAEIAEAAIAAAIIAEAAIAAAHIADAAIAAAIIAEAAIAAAIIADAAIAAAMIAEAAIAAALIAEAAIAAATIADAAIAABRIgDAAIAAATIgEAAIAAAMIgEAAIAAALIgDAAIAAAIIgEAAIAAAIIgDAAIAAAIIgEAAIAAAHIgEAAIAAAEIgDAAIAAAIIgEAAIAAAEIgDAAIAAAIIgEAAIAAADIgEAAIAAAEIgDAAIAAAEIgEAAIAAAEIgDAAIAAAEIgEAAIAAAHIgHAAIAAAFIgEAAIAAADIgDAAIAAAEIgEAAIAAAEIgEAAIAAAEIgHAAIAAAEIgDAAIAAADIgEAAIAAAEIgHAAIAAAEIgHAAIAAAEIgIAAIAAAEIgHAAIAAAEIgGAAIAAAEIgIAAIAAADIgKAAIAAAEIgPAAIAAAEIgSAAIAAAEIg5AAIAAAEIgEAAIAAAEIgDAAIAAAHIgFAAIAAAIIgDAAIAAAEIgDAAIAAAEIgEAAIAAADIgDAAIAAAEIgFAAIAAAFIgDAAIAAADIgDAAIAAAEIgEAAIAAAEIgDAAIAAAEIgFAAIAAAEIgDAAIAAADIgDAAIAAAEIgEAAIAAAEIgDAAIAAAEIgEAAIAAAEIgHAAIAAAEIgEAAIAAAEIgDAAIAAADIgEAAIAAAEIgHAAIAAAEIgEAAIAAAEIgHAAIAAAEIgEAAIAAAEIgHAAIAAAEIgDAAIAAADIgIAAIAAAEIgHAAIAAAEIgHAAIAAAEIgHAAIAAAEIgHAAIAAADIgIAAIAAAEIgKAAIAAAFIgHAAIAAADIgLAAIAAAEIgLAAIAAAEIgLAAIAAAEIgOAAIAAAEIgPAAIAAADIgSAAIAAAEIgVAAIAAAEg");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.cloud1, new cjs.Rectangle(-111.3,-64.4,222.7,128.8), null);


(lib.carobj1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#41BBFF").s().p("AhUAyQgNg1AWgZQgTgXAcgBIAEAMQgEAnAPAhQAyAKAygKQAOgggCgnIACgBIgCgBIAJgMQAWAHgRARQAXAbgNAwIgBAEIg0ADIgdABQgkAAgzgEgABCAIQgDAFAAAJQAAAIADAGQADAGADAAQAEAAADgGQADgGAAgIQAAgJgDgFQgDgGgEAAQgDAAgDAGgAhPAHQgDAGAAAIQAAAIADAGQACAGAEAAQAEAAADgGQADgGAAgIQAAgIgDgGQgDgGgEAAQgEAAgCAGg");
	this.shape.setTransform(0,0.2);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.carobj1, new cjs.Rectangle(-9,-5.1,18,10.8), null);


(lib.carobj = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#41BBFF").s().p("Ag9AoIAShPQArgYAxAYIANBPQgiAMgeAAQgfAAgcgMgAgkgXQAJAYABAZQAWAJAggIIAJgyQgRgEgSAAQgSAAgUAEg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.carobj, new cjs.Rectangle(-6.2,-5.2,12.5,10.4), null);


(lib.bucketobj = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#CC0000").s().p("AgnAsIgUhgQACAFAPADQASAEAYAAQAZAAARgEQAQgDABgFIgMBgQgWAJgWAAQgUAAgWgJg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.bucketobj, new cjs.Rectangle(-5.9,-5.3,11.9,10.6), null);


(lib.birdobj = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#027AFF").s().p("Ag9BIQgMgCgIgEIgBAAIgBgBIgBAAIgBAAIgBgBIAAAAIgBgBIAAAAIgBAAIAAAAIgBgBIgEgDIgHgFIgHgHIgGgJIgFgKQgDgHAAgEQgCgHAAgHIAAgNIAEgVQACgMAFgJIAHgJIAIgGIABAAIAAgBIAAAAIACAAIAAgBQAGgDAJABIALACIABAAIABABIABABIABAAIABAAIAAABIABAAIAAAAIABAAIAAABIALAIIAGAHQAEAEACAFIAKAUIAGAJIAPAOQAFAFADACIAJAGIABAAIABAAIAAABIACABIABAAIAAAAIABABIAAAAIABAAIABABIAAAAIABAAIAAAAIABABIABAAIAAAAIABABIABAAIAAAAIABABIABAAIAEgBIAJhOQAPA3BHAAIhgAeIgOAPIgSAPIgFADIgBABIgBAAIgBAAIAAABIgBAAIgBABIgBAAIAAAAIgBAAIAAABIgBAAIAAAAIgBAAIAAABIgBAAIgBAAIgHADQgLAEgOAAIgJgBgAg8gSIgEAAQgDABgCACQgDAEABAJIABAEQACAIAFAIQAEAGAFAGQAIAIAKAFIAHADQAJACAGgBIAFgEQADgDABgDQABgGgCgIIgCgEQgHgJgPgEQgQgEgHgJQgGgLgBAAIAAAAgAhXg1QgEAEAAAHIAAAAIAAADQABAEADAEQAFAFAHAAQAHAAAEgFQAFgFAAgGQAAgHgFgEQgEgFgHAAQgHAAgFAFg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.birdobj, new cjs.Rectangle(-12.4,-7.2,24.9,14.5), null);


(lib.ball = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(0.2,1,1).p("AAPg0QAOADAKALQAIAHAEAJQAFAKAAAMQAAASgLAOAgmgmQAQgQAWAAQAIAAAHACAABADQACADAAADIAAABQAZAEARASQgCAEgEADQgQAQgXAAQAAAAAAAAQgXAAgPgQQgEgEgDgEQgKgNAAgSQAAgWARgQAABADQASgRAggIAgVACQABgBABgBQAEgCAFAAQAEAAADACQACAAABAAQAAABABACAgEAVQgDABgDAAQgFAAgEgEQgBgBgBgBQgCgDAAgEQAAgDACgEQgTgNACgbAADAKQAAAEgDAEQgCACgCABQAIAOgEAUAgVAQQgJAKgPAFAgDAAQgBgdATgX");

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FF6600").s().p("AgUAXQAFgUgJgOIAEgDQAEgDAAgFQAYAEARASIgGAGQgQARgWAAIgBAAg");
	this.shape_1.setTransform(2,3.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#009900").s().p("AgQADIgGgGQAPgFAIgLIABACQAEAEAGAAIAFgBQAJAOgFAUQgVgBgQgQg");
	this.shape_2.setTransform(-2.2,3.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FF00FF").s().p("AgQAEQAAgWAQgQQgBAbASANQgDAEAAADQAAAEADADQgJAKgOAFQgKgNAAgSg");
	this.shape_3.setTransform(-3.8,-0.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgIAIIgCgCQgDgDAAgDQAAgDADgDIACgCQAEgDAEgBQAEAAADACIADACIABADQACADAAACIAAABQAAAEgDADIgFAEIgFABQgEAAgEgFg");
	this.shape_4.setTransform(-1,0.9);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#0000FF").s().p("AgYAFIAAgBQAAgDgCgCQASgSAfgIQAEALAAAMQAAASgKAOQgRgTgYgEg");
	this.shape_5.setTransform(2.8,0.5);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FEDA18").s().p("AgYAaIgCgCQgCgcAUgXQANADAKALQAIAIAEAHQgfAIgSASIgCgCg");
	this.shape_6.setTransform(2.4,-2.5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FF0000").s().p("AgagMQAQgQAWAAQAIAAAHACQgUAXACAcQgDgCgEAAQgFAAgEAEIgBACQgTgPABgag");
	this.shape_7.setTransform(-1.2,-2.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.ball, new cjs.Rectangle(-6.5,-6.5,13.1,13.1), null);


(lib.BACKground = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["rgba(255,255,255,0.569)","rgba(255,255,255,0.302)","rgba(204,204,204,0.302)"],[0.2,0.506,1],-338.5,6.5,338.6,6.5).s().p("Eg05ARpMAAAghOUA1egEGA0VAEGMAAAAhOg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Layer 1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.lf(["#66B900","#66CC00","#C2CC00","#FFCC00","#669900"],[0.051,0.106,0.243,0.565,1],-338.5,6.5,338.6,6.5).s().p("Eg05ARpMAAAghOUA1egEGA0VAEGMAAAAhOg");

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

}).prototype = getMCSymbolPrototype(lib.BACKground, new cjs.Rectangle(-338.5,-112.9,677.1,225.9), null);


(lib.aa = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 4
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["#ADADAD","#D1D1D1"],[0,1],-248.5,1.1,248.5,1.1).s().p("EAkZAb5QA75xhK6fQgDg8gQgfQgPgeggAAQ7Tgm7vAeIvJAJQgWgBgPASQgUAZgDAqQhyabBLadQgyAMgxAqQhU69BP6RQgUkPBIAPUAlhgAtAk9AAtQBnAHgOCHIABABQAubZgubmQhEg1hBgFg");
	this.shape.setTransform(0,-1.2);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Layer 1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.rf(["#ADADAD","#D1D1D1","#BDBDBD","#FFFFFF"],[0,0.427,0.635,1],0,0,0,0,0,296.7).s().p("EAh+AcnQCp4Vi67sUgiCgCNghBACNQj+b5DrYIQiYh0iIB0QhU68BP6RQgOjpA1gXMBK6AAAQBPAQgFB9IABABQAubagublQiYh0iIB0g");

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

}).prototype = getMCSymbolPrototype(lib.aa, new cjs.Rectangle(-248.5,-185.4,497,368.5), null);


(lib.xatlogoside = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.instance = new lib.xring();
	this.instance.parent = this;
	this.instance.setTransform(15.6,320.8,17.22,2.657,-23.6,0,0,12,12.3);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Layer 4
	this.shape = new cjs.Shape();
	this.shape.graphics.rf(["#02A9D2","#FFFFFF"],[0.565,0.816],-17.4,9,0,-17.4,9,123.1).s().p("AphJMQi2ichTksQAJhHgCgvQAHlpD3j1QEOkBFeAIQElgBDmC9QAxA5AMALQEkEAgIFfQgVFIkCEBQjsDolTADIgNAAQltAAj8j+g");
	this.shape.setTransform(5.4,321);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Layer 3
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AjYIUQiIiRAAjXQAAjdCFiPQCDiOC6AAQBXAABLAhQBNAhBABBIAAhqIDyAAIAAPAIjyAAIAAhmQhHBEhGAeQhIAdhTAAQi4AAiJiQgAglggQhKBOAAB8QAAB8BLBRQBKBQBvAAQBxAABLhPQBLhPAAiAQAAh+hLhNQhLhNhyAAQhxAAhIBPgAQpJ0Qg7gkgchEQgahEAAiIIABmxIh7AAIAAjQIB7AAIAAliIDxAAIAAFiICPAAIAADQIiPAAIAAHCQgBBKAYAbQAWAcAuAAQArAAA5gcIAAC+QhsAkhIAAQhSAAg6gkgAqMKAIjlk8IjkE8IkTAAIFtn6IlLnHIEYAAIC/EHIC9kHIETAAIlHHEIFyH9g");
	this.shape_1.setTransform(260.9,334.3);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

}).prototype = getMCSymbolPrototype(lib.xatlogoside, new cjs.Rectangle(-186.8,216.6,586.2,212.5), null);


(lib.v = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.Tween3("synched",0);
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({rotation:15},15).to({startPosition:0},10).to({rotation:0},14).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-2.3,-2.4,4.7,4.8);


(lib.Tween6 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.Symbol2();
	this.instance.parent = this;
	this.instance.setTransform(503.7,299.9,0.844,0.926,0,0,0,0,-0.1);

	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#00AD00").ss(2.1,1,1).p("AiDEeQgFgjgFgjQgqjzhmkAQBoCfBTCdQgsjOhWjYQB1CyBZCyQAFidgRimQA/DLAlDEQA1ifAhixQAGELghD0AiNDYQiCAahCBUQK9BzgahbQg9hjiYghQgGA2gKA0");
	this.shape.setTransform(490.9,267.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.lf(["rgba(0,102,0,0.278)","rgba(255,255,255,0.161)"],[0,0.855],-33.8,0,33.9,0).s().p("AlRFGQBChUCCgaQgqjzhmkAQBoCfBTCdQgsjOhWjYQB1CyBZCyQAFidgRimQA/DLAlDEQA1ifAhixQAGELghD0QgGA2gKA0QAKg0AGg2QCYAhA9BjQALAoiCAAQilAAmHhAgAiDEeIgKhGIAKBGg");
	this.shape_1.setTransform(490.9,267.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape},{t:this.instance}]}).wait(1));

	// Layer 2
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#009933").s().p("AlRFGQBChUCCgaQgqjzhmkAQBoCfBTCdQgsjOhWjYQB1CyBZCyQAFidgRimQA/DLAlDEQA1ifAhixQAGELghD0QCYAhA9BjQALAoiCAAQilAAmHhAg");
	this.shape_2.setTransform(490.9,267.5);

	this.timeline.addTween(cjs.Tween.get(this.shape_2).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(456.1,227.5,71.2,87.1);


(lib.trees = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Tree2
	this.instance = new lib.Tween2("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(238.4,-220.7,0.126,0.122,0,0,0,-6,105.4);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({regY:105.5,scaleX:0.36,scaleY:0.34,guide:{path:[238.4,-220.6,224.1,-200.2,237.8,-156.2]}},44).to({regX:-5.9,regY:105.3,scaleX:0.25,scaleY:0.25,guide:{path:[237.7,-156.1,237.7,-156.2,237.7,-156.2]},alpha:0},5).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(232.3,-237.5,12.3,17.3);


(lib.tree2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#006600").ss(0.4,1,1).p("ABGiEQABAGANABQgXAAgJAQQgBAIALgCQgeAXgIAhQA8hIBdBlQgdgUgWAHQAPAJgBAMQgQgVgXAIQAOAKACAMQgJgKgQAAQg3gYglA1QgUAfANArQgHACgIgPQgRAgARAZQgIgBgIgJQABAXAIATQhfhJBmheQgrADgdA7QgDgMADgMQgWAGgIAjQgKgKADgOQgQAPgHAfQgOggAMggQAbhCBnAGQgagWgtAWIAAgLIgnASIADgPIgrASQA3h4BmBMQgDiLCOAkQgagCgFAJQABAHAKACQgXgCgHANg");
	this.shape.setTransform(39.1,19);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Layer 4
	this.instance = new lib.treeobj1();
	this.instance.parent = this;
	this.instance.setTransform(39.1,19.1,1,1,0,0,0,17.7,16.8);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Layer 5
	this.col1 = new lib.obj3_1();
	this.col1.name = "col1";
	this.col1.parent = this;
	this.col1.setTransform(39.1,19.1);

	this.timeline.addTween(cjs.Tween.get(this.col1).wait(1));

	// Layer 2
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#663300").ss(0.4,1,1).p("AgQhDQATAEANgPQgLgggQghIgZAVQAMAcAIAbgAAlAdQABAvgOAqQgEANgGANIgnAAQAIgTAFgTQAKglABgnQAAgugPgzAAlAdQgUANgSgMAAQhOQAUA5ABAy");
	this.shape_1.setTransform(44.2,30.8);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

	// Layer 3
	this.instance_1 = new lib.obj4_1();
	this.instance_1.parent = this;
	this.instance_1.setTransform(44.2,30.8);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = getMCSymbolPrototype(lib.tree2, new cjs.Rectangle(20.4,1.3,37.3,44.9), null);


(lib.tree1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#006600").ss(0.4,1,1).p("ABTgKIAeATIAAgLIAhATQgchdhUAhQgFABgEACQgCACgCAAQABgBAAgBQABgEAAgEQANhhh0AJQAWABACAIQgBAGgJgBQAUACAEALQgBAEgMAAQATADAGAOQAAAGgJgDQAOANAGARQACAEABAEQABAGAAAFQgEgGgEgGQgFgFgFgFQgpgdhHA1QAbgNARAJQgNAFgBAKQAQgOASAJQgOAGgDAJQAJgGAOACQAvgMAaAuQALAbgQAhQAGACAHgLQALAbgRARQAGABAIgGQgEASgJANQBZgshKhXQAlAIAPAyQAFgJgCgKQASAIADAdQAJgHgBgMQALAPACAYQAQgXgHgaQgNg3hWgJQAYgOAjAXg");
	this.shape.setTransform(60,24.6);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Layer 5
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.lf(["rgba(255,255,255,0.31)","rgba(193,255,173,0.231)","rgba(255,255,255,0.29)"],[0.051,0.549,1],-14.5,0,14.6,0).s().p("AAOBrQgIAGgGgBQARgRgLgbQgHALgGgCQAQghgLgbQgagugvAMQgOgCgJAGQADgJAOgGQgSgJgQAOQABgKANgFQgRgJgbANQBHg1ApAdIAKAKIAIAMIgBgLIgDgIQgGgRgOgNQAJADAAgGQgGgOgTgDQAMAAABgEQgEgLgUgCQAJABABgGQgCgIgWgBQB0gJgNBhIgBAIIgBACIAEgCIAJgDQBUghAcBdIghgTIAAALIgegTIgBAJQgjgXgYAOQBWAJANA3QAHAagQAXQgCgYgLgPQABAMgJAHQgDgdgSgIQACAKgFAJQgPgyglgIQBKBXhZAsQAJgNAEgSg");
	this.shape_1.setTransform(60,24.6);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

	// Layer 4
	this.instance = new lib.treeobj2();
	this.instance.parent = this;
	this.instance.setTransform(60.1,24.6,1,1,0,0,0,14.6,13.8);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Layer 2
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#663300").ss(0.4,1,1).p("AgnACQAUARATgQQgFAmAHAlQAEAXAKAWIgpgDQgHgPgFgQQgLgqAJgtQAHgiATgmQAEAPAdgDQgOAfgGAeAAUg6QAKgWAOgWIgZgUQgTAagNAa");
	this.shape_2.setTransform(56.8,33);

	this.timeline.addTween(cjs.Tween.get(this.shape_2).wait(1));

	// Layer 3
	this.instance_1 = new lib.obj5();
	this.instance_1.parent = this;
	this.instance_1.setTransform(56.8,33);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = getMCSymbolPrototype(lib.tree1, new cjs.Rectangle(44.5,9.8,31.1,36.6), null);


(lib.Symbol1_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 4 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AiMBwQgghaAjh/QCHgMCRANQAbBpgcBvg");
	mask.setTransform(0.1,0.5);

	// Layer 2
	this.instance = new lib.Tween1("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(0.1,-12.8,1,0.78);

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).to({scaleY:0.84,y:12.4},9).wait(1));

	// Layer 3
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.lf(["rgba(153,153,153,0.271)","rgba(255,255,255,0.341)"],[0,1],-15.7,0.1,15.6,0.1).s().p("AiMBqQgghXAkh3QCIgJCOAIQAcBmgcBpg");
	this.shape_1.setTransform(0.1,-0.1);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(10));

	// Layer 1
	this.instance_1 = new lib.driverobj();
	this.instance_1.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(10));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-15.5,-10.7,31.2,21.2);


(lib.SeaTree = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 8
	this.instance = new lib.Symbol1();
	this.instance.parent = this;
	this.instance.setTransform(48.8,43,1,1,0,0,0,13.8,3.3);
	this.instance.alpha = 0.469;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Layer 5
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["#FAE696","#FFFFFF","#FCF3CD"],[0.051,0.522,0.761],71,-15,71,-38.9).s().p("AilgLQCvg+CcA+QgeAjgJAJIjdAKQgvgMgYgqg");
	this.shape.setTransform(49.2,42.8);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Tree2
	this.instance_1 = new lib.tree2();
	this.instance_1.parent = this;
	this.instance_1.setTransform(38.2,44,0.927,0.908,0,0,0,39.1,45.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

	// Tree1
	this.instance_2 = new lib.tree1();
	this.instance_2.parent = this;
	this.instance_2.setTransform(59.2,44.1,0.839,0.851,0,0,0,60,45.4);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(1));

}).prototype = getMCSymbolPrototype(lib.SeaTree, new cjs.Rectangle(21.6,4.9,50,42.2), null);


(lib.oar = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#666666").ss(1.3,1,1).p("AARgcIghA5");
	this.shape.setTransform(0.2,0.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#000000").ss(1,1,1).p("AAhgyQgBgBgBgBQgOgHABgTQAAgTALgSQAKgTATgOQATgPANAIQAOAIgDAZQgCAZgMASQgNASgOAIQgOAIgNgFgAASgZIAPgZIAqhNAgcA2IABABQALAIAAAQQgBAQgJAUQgJAUgVAOQgUAPgOgIQgNgIADgXQADgYALgSQALgTAQgKQAQgJANAIQABAAABABIgtBLAgOAfIgNAY");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

	// Layer 2
	this.instance = new lib.oarobj();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.oar, new cjs.Rectangle(-11.2,-16.9,22.4,33.8), null);


(lib.message2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AR0K0IAAuHIhqAAIDGngIC5HgIhhAAIAAOHgA0fK0IAAuHIhpAAIDGngIC5HgIhiAAIAAOHg");
	this.shape.setTransform(-4.4,-7.3);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Layer 2
	this.mbox = new lib.mbox();
	this.mbox.name = "mbox";
	this.mbox.parent = this;
	this.mbox.setTransform(-101.8,-68.8);

	this.timeline.addTween(cjs.Tween.get(this.mbox).wait(1));

	// Layer 4
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.lf(["rgba(80,80,80,0.478)","rgba(255,255,255,0.188)"],[0,1],-151.6,0,151.6,0).s().p("A3rNTIAA6lMAvXAAAIAAalg");
	this.shape_1.setTransform(-2.2,0);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

	// Layer 1
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("rgba(0,102,255,0.988)").s().p("A3rNTIAA6lMAvXAAAIAAalg");
	this.shape_2.setTransform(-2.2,0);

	this.timeline.addTween(cjs.Tween.get(this.shape_2).wait(1));

}).prototype = getMCSymbolPrototype(lib.message2, new cjs.Rectangle(-153.8,-85.1,303.3,170.1), null);


(lib.grass = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.instance = new lib.Tween6("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(-12,-26.5,0.37,0.339,0,0,0,491.8,275.9);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(12).to({_off:false},0).to({regX:491.5,regY:269.4,scaleX:1,scaleY:1,x:6.8,y:185.6},47).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.flip2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#333333").ss(0.4,1,1).p("AA3geQALhUhBgQQhGgNAMBpQgHARANAbQAHAGAEAGQACAegGAeQgBASABAHQACAGAHAKQAGALAWADIAHAAQAPgCAPgQQAOgRgEgWQgDgPALgrQATgUgKgaQgBgBgBgBg");
	this.shape.setTransform(6,13.2);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Layer 4
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.lf(["rgba(0,0,0,0.188)","rgba(185,185,185,0.329)","rgba(255,255,255,0.29)","rgba(230,230,230,0.329)","rgba(153,153,153,0.471)"],[0,0.243,0.518,0.733,1],-5.8,0,5.9,0).s().p("AAAgCQgIgTgQAGQAJAEgBAKQgbAQgNAcQgMhoBHANQBAAQgKBTQgSgmgngPg");
	this.shape_1.setTransform(5.9,5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.lf(["rgba(0,0,0,0.188)","rgba(185,185,185,0.329)","rgba(255,255,255,0.29)","rgba(230,230,230,0.329)","rgba(153,153,153,0.471)"],[0,0.243,0.518,0.733,1],-4.6,0,4.7,0).s().p("AgIBjQgWgDgGgKQgHgKgCgHQgBgGABgSQAGgegCgeQADAFABAEQACAIADAFQAMgKgDgOQgngsA3glQA0AjgFAYQgDATgLAEQgCANAIAJQADgMAMgIQgLAqADAPQAEAVgOARQgPAQgOACg");
	this.shape_2.setTransform(6.1,16.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1}]}).wait(1));

	// Layer 3
	this.instance = new lib.obj2_1();
	this.instance.parent = this;
	this.instance.setTransform(5.9,13.3,1,1,0,0,0,5.8,13.3);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Layer 1
	this.instance_1 = new lib.obj1();
	this.instance_1.parent = this;
	this.instance_1.setTransform(6,10.3,1,1,0,0,0,6,7);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = getMCSymbolPrototype(lib.flip2, new cjs.Rectangle(-1,-1,14.1,28.5), null);


(lib.flip1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(0.1,1,1).p("Ag5gBQASgmAogPQAIgTARAFQgKAEABALQAcAQANAcAgxAwQALAIADANQAJgKgCgMQgLgEgDgMQgGgfA3gkQA3AlglApQgGARAMALQADgFADgJQAAgEAEgF");
	this.shape.setTransform(6.3,10.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#333333").ss(0.1,1,1).p("AgwAdQgUgVALgZQAAgCABgBAA8gcQAGARgNAbQgHAHgEAF");
	this.shape_1.setTransform(6.2,12.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#333333").ss(0.4,1,1).p("Ag5geQgLhUBCgQQBIgNgMBpAApASQgCAeAFAeQACASgCAHQgCAGgGAKQgHALgWADIgIAAQgPgCgQgQQgNgRAEgWQACgPgKgr");
	this.shape_2.setTransform(6.3,13.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	// Layer 2
	this.instance = new lib.obj4();
	this.instance.parent = this;
	this.instance.setTransform(6.2,10.3,1,1,0,0,0,6.2,7);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Layer 4
	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.lf(["rgba(0,0,0,0.188)","rgba(185,185,185,0.329)","rgba(255,255,255,0.29)","rgba(230,230,230,0.329)","rgba(153,153,153,0.471)"],[0,0.243,0.518,0.733,1],-4.7,0,4.8,0).s().p("AABBjQgOgBgQgRQgOgRAEgVQADgPgLgqQAMAIADAMQAIgJgBgMQgMgDgCgNQgGgfA2glQA4AmglApQgHARANAKQADgFACgHQABgFADgEQgCAdAGAeQABASgBAGQgCAHgHAKQgHAKgWADg");
	this.shape_3.setTransform(6.1,16.6);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.lf(["rgba(0,0,0,0.188)","rgba(185,185,185,0.329)","rgba(255,255,255,0.29)","rgba(230,230,230,0.329)","rgba(153,153,153,0.471)"],[0,0.243,0.518,0.733,1],-5.9,0,6,0).s().p("AgCgwQBIgNgMBoQgNgcgcgQQgBgKAKgEQgRgGgIATQgoAPgSAmQgLhTBCgQg");
	this.shape_4.setTransform(6.3,5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_4},{t:this.shape_3}]}).wait(1));

	// Layer 3
	this.instance_1 = new lib.obj3();
	this.instance_1.parent = this;
	this.instance_1.setTransform(6.4,13.3,1,1,0,0,0,6,13.3);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = getMCSymbolPrototype(lib.flip1, new cjs.Rectangle(-1,-1,14.4,28.5), null);


(lib.carobj2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(0.1,1,1).p("AA+gmQADAtgPAgQgygdgyAdQgPgjAFgqQA5ABBAgBQAAABABgBg");
	this.shape.setTransform(0,-0.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Layer 2
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.lf(["rgba(153,153,153,0.278)","rgba(255,255,255,0.161)"],[0,0.855],-6.2,0,6.3,0).s().p("AgyAmQgPghAFgqIB5AAIABAAQADAsgPAfQgygcgyAcg");
	this.shape_1.setTransform(0,-0.5);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

	// Layer 1
	this.col0 = new lib.obj2();
	this.col0.name = "col0";
	this.col0.parent = this;
	this.col0.setTransform(0,-0.5);

	this.timeline.addTween(cjs.Tween.get(this.col0).wait(1));

}).prototype = getMCSymbolPrototype(lib.carobj2, new cjs.Rectangle(-7.2,-5.3,14.5,9.7), null);


(lib.Buckethand = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 4
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("AAggpIgWgOQAIgPAWgFQANADAGAKQAFAVgKAOIgWgOIgfAtIATAMIgZA8QgegOgZgZIAtgtIAQAM");
	this.shape.setTransform(4.4,2.9);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#0066FF").s().p("Ag8AkIAtgsIAQAMIATAMIgZA8QgegOgZgagAAggoIgWgPQAIgPAWgEQANACAGAKQAFAWgKANg");
	this.shape_1.setTransform(4.4,2.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

	// Layer 3
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#000000").ss(1,1,1).p("Ag5gUQAEgEAMgCQARgEAYAAQAZAAARAEQAKACAEADQAEACAAACQAAABAAAAQgBAFgRAEQgRAEgZAAQgYAAgRgEQgQgEgBgEQgBgBAAgBQAAgCACgBgAA8gQIgNBgQgsAUgpgUIgUhfAA4gVQgEhLg3AIQg3AIABA8");
	this.shape_2.setTransform(-0.2,2.3);

	this.timeline.addTween(cjs.Tween.get(this.shape_2).wait(1));

	// Layer 2
	this.instance = new lib.bucketobj();
	this.instance.parent = this;
	this.instance.setTransform(-0.1,5.9);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#CC0000").s().p("AgpAJQgQgDgBgFIgBgBQAAAAAAAAQABAAAAgBQAAAAAAgBQABAAAAAAQAEgEAMgDQARgDAYAAQAZAAARADQAKACAEAEQAEABAAACIAAABQgBAFgRADQgRAEgZABQgYgBgRgEg");
	this.shape_3.setTransform(-0.2,0.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_3},{t:this.instance}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Buckethand, new cjs.Rectangle(-7.1,-7.7,18.6,20), null);


(lib.bird = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FF9900").ss(0.3,1,1).p("AAdgMIgBAdIAJALAgVACIgPgEAgSgbIgDAdQAHgCADADAggAIIALgGAAcARIgPABAAXAcQAAgHAFgE");
	this.shape.setTransform(-2.5,8.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(9));

	// Layer 4
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFCC00").s().p("AgRAJIAZgFIgBAHQgFAGgFAAQgGAAgIgIgAgLgPQARgFAMAJQgHAIgDAGg");
	this.shape_1.setTransform(-7.2,-4.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFCC00").s().p("AgOgDIAVAIIgBAHQgEADgCAAQgIAAgGgSgAgQgEQAUgPANAJQgHAHgDAHg");
	this.shape_2.setTransform(-7.1,-4.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFCC00").s().p("AgRAJIAZgFIgBAHQgFAHgFAAQgGAAgIgJgAgLgPQARgFAMAJQgHAIgDAGg");
	this.shape_3.setTransform(-7.3,-4.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1}]}).to({state:[{t:this.shape_2}]},3).to({state:[{t:this.shape_3}]},3).to({state:[{t:this.shape_2}]},2).wait(1));

	// Layer 1
	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AgGAHIgCgFIAAgCIAAAAQAAgDACgDQADgDADAAQADAAADADQADADAAADQAAAEgDADQgDADgDAAQgDAAgDgDg");
	this.shape_4.setTransform(-3,-4.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AATA0IgHgDQgKgFgHgIQgFgGgEgGQgFgIgCgIIgBgFQgCgIAEgEQACgCADgBIAEAAQABgBAGAMQAGAJAQAEQAPAEAHAJIACAEQACAIgBAGQgBADgDADIgFAEIgGAAIgJgBgAgmgZQgDgEgBgFIACAFQADADAEAAQADAAADgDQADgDAAgEQAAgEgDgDQgDgDgDAAQgEAAgDADQgCADAAAEQAAgHAEgEQAFgFAHAAQAHAAAEAFQAFAEAAAHQAAAGgFAFQgEAFgHAAQgHAAgFgFg");
	this.shape_5.setTransform(0.4,-0.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4}]}).wait(9));

	// Layer 6
	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.lf(["rgba(58,58,58,0.478)","rgba(255,255,255,0.412)"],[0,1],-10.3,-6.5,10.6,6.8).s().p("Ag9BIQgMgCgIgEIgBAAIgBgBIgBAAIgBAAIgBgBIAAAAIgBgBIAAAAIgBAAIAAAAIgBgBIgEgDIgHgFIgHgHIgGgJIgFgKQgDgHAAgEQgCgHAAgHIAAgNIAEgVQABgMAGgJIAHgJIAIgGIABAAIAAgBIAAAAIACAAIAAgBQAGgDAJABIALACIABAAIABABIABABIABAAIABAAIAAABIABAAIAAAAIABAAIAAABIALAIIAGAHQAEAEACAFIAKAUIAGAJIAPAOQAFAFADACIAJAGIABAAIABAAIAAABIACABIABAAIAAAAIABABIAAAAIABAAIABABIAAAAIABAAIAAAAIABABIABAAIAAAAIABABIABAAIAAAAIABABIABAAIAEgBIAJhOQAPA3BHAAIhgAeIgOAPIgSAPIgFADIgBABIgBAAIgBAAIAAABIgBAAIgBABIgBAAIAAAAIgBAAIAAABIgBAAIAAAAIgBAAIAAABIgBAAIgBAAIgHADQgLAEgOAAIgJgBgAg8gSIgEAAQgDABgCACQgEAEACAJIABAEQACAIAFAIQAEAGAFAGQAIAIAKAFIAHADQAJACAGgBIAFgEQADgDABgDQABgGgCgIIgCgEQgHgJgPgEQgQgEgHgJQgGgLgBAAIAAAAgAhXg1QgEAEAAAHIAAAAIAAACQABAFADAEQAFAFAHAAQAHAAAEgFQAFgFAAgGQAAgHgFgEQgEgFgHAAQgHAAgFAFg");
	this.shape_6.setTransform(5.3,0);

	this.timeline.addTween(cjs.Tween.get(this.shape_6).wait(9));

	// Layer 5
	this.instance = new lib.birdobj();
	this.instance.parent = this;
	this.instance.setTransform(5.3,0);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(9));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-8.9,-7.2,26.7,19.6);


(lib.car2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.col0 = new lib.carobj();
	this.col0.name = "col0";
	this.col0.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.col0).wait(1));

}).prototype = getMCSymbolPrototype(lib.car2, new cjs.Rectangle(-6.2,-5.2,12.5,10.4), null);


(lib.message = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 5
	this.shape = new cjs.Shape();
	this.shape.graphics.rf(["#FFFFFF","#E7E7E7","#FFFFFF"],[0,0.459,1],0,0,0,0,0,9.6).s().p("AABB8IgBAAQglAAgaglQgHgIgEgJQgQgfAAgnQAAgdAJgZIABgBQAGgSALgNQAaglAlAAIABAAIABAAQAlABAaAkQALAPAGASIABABQAIAZAAAbQAAAmgOAeIgBACQgFAJgGAIQgaAjglACIgBAAg");
	this.shape.setTransform(-112.3,121.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FF0000").s().p("AhcEwQgQgMAAglQgWATgQgMQgQgNAAgkQAAgjAQgmQAOggAUgUQgXAOgbAAQghAAgWgRQgXgSAAgZQAAgYAXgSQgXgQAAgZQAAgaAXgRQAWgSAhAAQAYAAAUAKIACACIACACIAHAGIACABIAXARQgKAZAAAeQAAAmAQAfQAFAJAGAIQAaAlAnAAIAAAAIAAA0IAAAPQgCAfgNAfQgQAmgWASQgOAKgKAAQgIAAgHgFgAhwBYIAHgFIAdgXIgdAWIgHAGIAAAAgAA3EqQgXgRgQgmQgNgfgDgfIAAgQIAAgzQAlgBAagkQAHgIAEgJIAgAYIAKAHIgKgJIgfgYQAPgeAAglQAAgcgJgYIAZgUIAJgHIgJAGIgZATQgHgSgLgPQgagjglgBIAAghIAAgNQACghAOgfQAQgmAWgSQAXgSAQANQAPAMABAkQAWgTAQANQAQANAAAjQAAAjgQAnQgOAfgSAUQAVgOAbAAQAhAAAWASQAXARAAAZQAAAZgXASQAXAPAAAZQAAAagXASQgWARghABQgaAAgVgMQATASAMAfQARAmAAAjQAAAjgRANQgPAMgXgRQABAjgRAMQgGAGgIAAQgLAAgNgLgAhphUIgLgGIgCgDQgQgRgLgaIgBgBIgBgCQgQgmAAgjQAAgkAQgMQAPgMAYARQgBgjAQgMQAQgOAXATQAWARARAmQANAfACAhIAAANIAAAhIAAAAQgnAAgaAkQgKAOgHARgAAAiyIAAAAg");
	this.shape_1.setTransform(-112.1,122.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

	// Layer 9
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("ACRCmQAFA8gtgdIA3jIIAtDqQgzhagJAZgAilCHIgogYIA8i4IAkCpIBxlGIBUFlIACAGIABAGIAAAAQgig/gXAtQgjh5gsBiQgNhagzBYQACAwgdAAQgMAAgRgJg");
	this.shape_2.setTransform(376.9,-53);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.lf(["#FFFFFF","#DDDDDD","#C4C4C4","#B3B3B3","#999999"],[0,0.235,0.655,0.875,1],0,-42.6,0,14.3).s().p("Aj+CnIBZkTIAnAZQA7AegChGQAyhYAOBbQArhiAjB4QAYgtAiA/IAOA6QAsAcgEg7QAJgZAzBZIAKA0IAABog");
	this.shape_3.setTransform(372.9,-31);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_3},{t:this.shape_2}]}).wait(1));

	// Layer 8
	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("EAjaAEMIgRkcQgHjfDwAdIAAg5ICfCsIifBFIAAguQhzgGgDBIIgNESgEgkXAEMIgOkSQgEhIh8AGIAAAuIirhFICrisIAAA5QEEgdgIDfIgSEcg");
	this.shape_4.setTransform(134.2,-94);

	this.timeline.addTween(cjs.Tween.get(this.shape_4).wait(1));

	// SEAtree
	this.instance = new lib.SeaTree();
	this.instance.parent = this;
	this.instance.setTransform(-100.4,-45.5,1.149,1.577,0,0,0,51,25.4);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Layer 11
	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.lf(["rgba(167,167,167,0.333)","rgba(255,255,255,0.188)"],[0,1],-51.4,65.2,251.8,65.2).s().p("AlnHNQiVi/AAkOQAAkNCVi/QCVi+DSgBQDSABCWC+QCVC/AAENQAAEOiVC/QiWC/jSAAQjSAAiVi/g");
	this.shape_5.setTransform(-102.4,-65.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.lf(["rgba(255,255,255,0.188)","rgba(80,80,80,0.478)"],[0,1],-51.4,65.2,251.8,65.2).s().p("AlnHNQiVi/AAkOQAAkNCVi/QCVi+DSgBQDTABCVC+QCVC/AAENQAAEOiVC/QiVC/jTAAQjSAAiVi/g");
	this.shape_6.setTransform(373.2,-65.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_6},{t:this.shape_5}]}).wait(1));

	// Layer 7
	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#0099FF").s().p("AfkHNQiVi/AAkOQAAkNCVi/QCVi+DTgBQDSABCWC+QCVC/AAENQAAEOiVC/QiWC/jSAAQjTAAiVi/gEgqzAHNQiVi/AAkOQAAkNCVi/QCVi+DTgBQDTABCVC+QCVC/AAENQAAEOiVC/QiVC/jTAAQjTAAiVi/g");
	this.shape_7.setTransform(135.5,-65.2);

	this.timeline.addTween(cjs.Tween.get(this.shape_7).wait(1));

	// Layer 6
	this.instance_1 = new lib.bird();
	this.instance_1.parent = this;
	this.instance_1.setTransform(323.6,-277.8,3.396,4.199);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

	// Layer 2
	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.rf(["#FFFF00","#E0E000","#E2E200","#FFFF00"],[0,0.439,0.502,1],0,0,0,0,0,9.8).s().p("AABB5IgBAAQgmAAgbgkQgGgIgFgKQgQgdgBgmQAAgdAKgYIABgCQAGgQALgNQAbgkAmAAIACAAIAAAAQAmABAbAjQALAOAGASIABABQAJAYAAAbQgBAmgPAcIgBABIgKASQgbAjgmABIgBAAg");
	this.shape_8.setTransform(389.3,118.9);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AheEqQgPgMgCgkQgVASgRgMQgRgMAAgjQAAgiARgmQAOggAVgTIAIgFIAcgXQAFAJAHAJQAbAkAnAAIAAAAIAAAyIAAAPQgBAfgOAeQgRAlgXASQgNAKgLAAQgIAAgHgFgAA5EkQgXgRgSglQgNgegDgfIABgPIAAgyQAmgCAagiIALgSIAfAYIAMAGIgKgIIgggXQAPgdAAglQAAgbgJgYIAagTIAIgIIgKAGIgYATQgHgRgLgPQgagigmgCIAAggIgBgNQACgfAOgfQARgmAXgRQAWgRARAMQAQAMABAjQAVgSARAMQARANAAAiQAAAjgRAmQgNAegUATQAXgNAbAAQAhAAAYARQAWASAAAYQAAAXgWASQAWAQAAAZQAAAZgWARQgYARghAAQgbAAgVgMQATATANAeQAQAmAAAiQAAAigQANQgQALgXgQQAAAigQAMQgHAFgIAAQgLAAgNgKgAAACxIAAAAgAjeBTQgXgRAAgZQAAgYAXgRQgXgQAAgZQAAgYAXgSQAXgRAhAAQAZAAAUAJIADADIACABQADAEAFACIABABIAXASQgKAXAAAeQAAAmAQAdIgdAWQgEADgDADQgYAOgcAAQghAAgXgRgAhqhSIgMgGQAAgBAAAAQgBgBAAAAQAAgBgBAAQAAAAgBAAQgQgRgMgZIAAgBIgBgCQgRgmAAgjQAAgiARgNQAQgLAXARQgBgjARgLQARgNAXASQAXAQARAmQAOAfABAfIAAANIAAAgIAAAAQgnAAgbAkQgLANgGAQg");
	this.shape_9.setTransform(389.4,119.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_9},{t:this.shape_8}]}).wait(1));

	// Layer 3
	this.instance_2 = new lib.message2();
	this.instance_2.parent = this;
	this.instance_2.setTransform(138.9,-188);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(1));

	// Layer 4
	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.lf(["#33FF00","#33D300","#339900"],[0,0.357,1],-32,-6.7,32.3,10.5).s().p("AiYI7IACgDIhQAQIAEikIgLgCIALgmIAOtOQATEhA2DvICyqLQhFFvAMEyICNoIQg2EZgFD0ICup4QhxJPBiGyIiJgJQAKA7AOA5g");
	this.shape_10.setTransform(-94.7,89.1);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.lf(["#33FF00","#33D300","#339900"],[0,0.357,1],-20.9,0,21,0).s().p("AhVGoIh7AMQBimIhZoOICPIyQABjbgrj6IB1HOQARkSg1lHICRJCQA4jXAXkCIgHL1IAJAhIgJABIgBCUIhIgMIACACIjtAXQANg0AKg1g");
	this.shape_11.setTransform(370.8,89.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_11},{t:this.shape_10}]}).wait(1));

	// Layer 1
	this.instance_3 = new lib.aa();
	this.instance_3.parent = this;
	this.instance_3.setTransform(137,-56.7);
	this.instance_3.shadow = new cjs.Shadow("rgba(0,0,0,1)",1,1,5);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(1));

}).prototype = getMCSymbolPrototype(lib.message, new cjs.Rectangle(-153.3,-308.3,577.8,462), null);


(lib.car = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 29
	this.instance = new lib.xatlogoside();
	this.instance.parent = this;
	this.instance.setTransform(-267.9,-202.2,0.011,0.012,0,0,0,108.8,321.9);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#666666").ss(0.1,1,1).p("AgjgMIBHAAIAAAZIhHAAg");
	this.shape.setTransform(-267.8,-202.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AgjANIAAgZIBHAAIAAAZg");
	this.shape_1.setTransform(-267.8,-202.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

	// Layer 9
	this.instance_1 = new lib.carobj2();
	this.instance_1.parent = this;
	this.instance_1.setTransform(-267.9,-211.9,1,0.465,0,0,0,-0.1,-3.9);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

	// Layer 10
	this.instance_2 = new lib.wheels();
	this.instance_2.parent = this;
	this.instance_2.setTransform(-267.7,-200.3);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(1));

	// Layer 6
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.lf(["rgba(153,153,153,0.369)","rgba(255,255,255,0.38)"],[0,1],-8.9,-0.2,9,-0.2).s().p("AAbA1IgMAAIg5gCIgqgBQgNg1AWgZQgTgXAbgBIAFAMQgEAnAPAhIAJABQAjAGAigEIAWgDQAOgggCgnIAAgBIAIgMQAXAGgRARQAXAbgNAwIgBAEQgRADgkAAIgEAAgABCAIQgDAFAAAJQAAAIADAGQADAGADAAQAEAAADgGQADgGAAgIQAAgJgDgFQgDgGgEAAQgDAAgDAGgAhPAHQgDAGAAAIQAAAIADAGQACAGAEAAQAEAAADgGQADgGAAgIQAAgIgDgGQgDgGgEAAQgEAAgCAGg");
	this.shape_2.setTransform(-267.7,-208.1);

	this.timeline.addTween(cjs.Tween.get(this.shape_2).wait(1));

	// Layer 7
	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.lf(["rgba(51,51,51,0.369)","rgba(255,255,255,0.522)"],[0,1],-9.4,-0.2,9.5,-0.2).s().p("AhZAHQgHgHAFgGIAHAAIArADQApADAcgBIAGgBIAzgEIAHAAQAFAGgHAHg");
	this.shape_3.setTransform(-267.8,-202.4);

	this.timeline.addTween(cjs.Tween.get(this.shape_3).wait(1));

	// Layer 4
	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.lf(["rgba(255,255,255,0.569)","rgba(255,255,255,0.302)","rgba(204,204,204,0.302)"],[0,0.506,1],-6.2,0,6.3,0).s().p("AgpAvQgKgDgKgEIAShPQArgYAxAYIANBPQgRAGgRADQgQADgOAAQgUAAgTgFgAgkgXQAGASADARIABAOQAWAJAggIIAJgyQgRgEgSAAQgSAAgUAEg");
	this.shape_4.setTransform(-267.8,-216.2);

	this.timeline.addTween(cjs.Tween.get(this.shape_4).wait(1));

	// Layer 2
	this.instance_3 = new lib.car2();
	this.instance_3.parent = this;
	this.instance_3.setTransform(-267.7,-216.2);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f().s("#000000").ss(0.1,1,1).p("AgpAvQgKgDgKgEIAShPQArgYAxAYIANBPQgRAGgRADQgkAHghgJgAgkgXQAogIAhAIIgJAyQggAIgWgJQAAgHgBgHQgDgRgGgSg");
	this.shape_5.setTransform(-267.8,-216.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.lf(["rgba(153,153,153,0)","rgba(224,224,224,0.349)","rgba(255,255,255,0.388)","rgba(210,210,210,0.361)"],[0,0.475,0.525,0.573],-4.4,-1.1,4.3,1.2).s().p("AgaAZIgBgOQgCgRgHgSQAogIAhAIIgJAyQgPADgNAAQgOAAgMgEg");
	this.shape_6.setTransform(-267.8,-216.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_6},{t:this.shape_5},{t:this.instance_3}]}).wait(1));

	// Layer 5
	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f().s("#000000").ss(0.1,1,1).p("Ag+gtQgHAFgGAGQgSgXAbAAIAEAMIB7AAQADApgPAfQgLACgKABQgiAEgjgGQgFgBgFAAQgPgiAEgmgAhSA6IgHAAQgHgGAFgIIAHAAQAXACAUABQApACAcgBQAEAAADAAQAqgCAIgCQAAgBABgCQANgwgXgcQgFgGgHgFQgBABgBAAIAAAAIgBAAQAAAAABAAIAIgMQAXAFgRARAhLgiQgVAZAMA1AA+gtIAAAAAA+gtIAAAAABVAsIAHAAQAFAIgHAGIgHAAAAvA6IhdAA");
	this.shape_7.setTransform(-267.8,-207.6);

	this.timeline.addTween(cjs.Tween.get(this.shape_7).wait(1));

	// Layer 11
	this.col0 = new lib.carobj1();
	this.col0.name = "col0";
	this.col0.parent = this;
	this.col0.setTransform(-267.7,-208.3);

	this.timeline.addTween(cjs.Tween.get(this.col0).wait(1));

	// Pawn3
	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f().s("#FFFFFF").ss(0.4,1,1).p("AgCAEQABgFAEgC");
	this.shape_8.setTransform(-265.7,-216.5);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f().s("rgba(0,0,0,0.651)").ss(1,1,1,3,true).p("AABgEQABAAAAAAQAFAAADgEQAEgEAAgGQAAgGgEgEQgEgEgFAAQgFAAgEAEQgEAEAAAGQAAAGAEAEQABABACABQACACADAAQgHAAgGAJQgFALgBAOQgBAEAUgBQABAAABAAQASgBAAgDQAAgOgGgKQgGgHgGgCQgBAAAAAAg");
	this.shape_9.setTransform(-265.2,-214.3);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.rf(["rgba(0,0,0,0.412)","rgba(1,49,152,0)"],[0,1],-1,0.8,0,-1,0.8,4).s().p("AgTAPQABgOAFgJQAGgKAHAAIABAAIABAAQAGACAGAIQAGAJAAAOQAAADgSABIgCAAIgGAAQgOAAABgEg");
	this.shape_10.setTransform(-265.2,-212.8);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.rf(["rgba(0,0,0,0.424)","rgba(1,49,152,0)"],[0,1],-0.6,0.5,0,-0.6,0.5,2).s().p("AAAAOIgBAAIgFgCIgDgCQgDgEAAgGQAAgFADgEQAEgEAFAAQAFAAAEAEQAFAEAAAFQAAAGgFAEQgDAEgEAAIgCAAgAgIAAQABgEAEgCQgEACgBAEg");
	this.shape_11.setTransform(-265.1,-216.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8}]}).wait(1));

	// pawn4
	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#009900").s().p("AgTAeQABgOAFgLQAGgJAHAAIgFgCIgDgCQgEgEAAgGQAAgGAEgEQAEgEAFAAQAFAAAEAEQAEAEAAAGQAAAGgEAEQgDAEgFAAIgBAAIABAAQAGACAGAHQAGAKAAAOQAAADgSABIgCAAIgGAAQgOAAABgDg");
	this.shape_12.setTransform(-265.2,-214.3);

	this.timeline.addTween(cjs.Tween.get(this.shape_12).wait(1));

	// Pawn3
	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f().s("#FFFFFF").ss(0.4,1,1).p("AgCAEQABgFAEgC");
	this.shape_13.setTransform(-270.5,-216.5);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f().s("rgba(0,0,0,0.651)").ss(1,1,1,3,true).p("AABgEQAEAAAEgCQAAgBABgBQAEgEAAgGQAAgGgEgEQgEgEgFAAQgFAAgEAEQgEAEAAAGQAAAGAEAEQABABABABQADACADAAQgHAAgGAJQgEAJgCALQAAACAAADQAAAAAAABQADADAQgBQAUAAAAgEQAAgOgGgKQgHgIgGgBg");
	this.shape_14.setTransform(-270,-214.2);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.rf(["rgba(0,18,56,0.267)","rgba(1,49,152,0)"],[0.012,1],-0.6,0.5,0,-0.6,0.5,2).s().p("AAAAOQgEAAgDgCIgCgCQgDgEAAgGQAAgFADgEQAEgEAFAAQAGAAADAEQAEAEABAFQgBAGgEAEIgBACQgEACgEAAIAAAAgAgIAAQABgEAFgCQgFACgBAEg");
	this.shape_15.setTransform(-269.9,-216.1);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.rf(["rgba(0,0,0,0.412)","rgba(1,49,152,0)"],[0,1],-1,0.8,0,-1,0.8,4).s().p("AgTARIAAgCIAAgFQACgKAEgIQAGgKAHAAIABAAQAGAAAHAKQAGAJAAAOQAAADgUABIgGAAQgLAAgCgCg");
	this.shape_16.setTransform(-270,-212.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13}]}).wait(1));

	// pawn4
	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FF9900").s().p("AgTAfIAAgBIAAgFQACgLAEgJQAGgJAHAAQgDAAgDgCIgCgCQgEgEAAgGQAAgGAEgEQAEgEAFAAQAFAAAEAEQAEAEAAAGQAAAGgEAEIgBACQgEACgEAAQAGABAHAIQAGAKAAAOQAAAEgUAAIgGAAQgLAAgCgCg");
	this.shape_17.setTransform(-270,-214.2);

	this.timeline.addTween(cjs.Tween.get(this.shape_17).wait(1));

	// Layer 8
	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FF0000").s().p("ABCAPQgCgGAAgIQAAgIACgFQAEgGADAAQAEAAADAGQADAFAAAIQAAAIgDAGQgDAGgEAAQgDAAgEgGgAhQAOQgCgGAAgIQAAgIACgGQAEgGAEAAQAFAAADAGQAEAGgBAIQAAAIgDAGQgDAHgFAAQgEAAgEgHg");
	this.shape_18.setTransform(-267.8,-206);

	this.timeline.addTween(cjs.Tween.get(this.shape_18).wait(1));

	// Layer 1
	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#999999").s().p("AhZAJQgHgHAFgGIAHAAIArgDQAjgBAiABIApACIAQABIAHAAQAFAGgHAHg");
	this.shape_19.setTransform(-267.8,-202.6);

	this.timeline.addTween(cjs.Tween.get(this.shape_19).wait(1));

	// Radio
	this.instance_4 = new lib.shape122();
	this.instance_4.parent = this;
	this.instance_4.setTransform(-269.9,-205.5,0.134,0.128,0,0,0,9.7,13.7);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(1));

	// Layer 18
	this.instance_5 = new lib.oar();
	this.instance_5.parent = this;
	this.instance_5.setTransform(-263.8,-207.3,0.237,0.178,120);

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(1));

	// Layer 16
	this.instance_6 = new lib.Buckethand();
	this.instance_6.parent = this;
	this.instance_6.setTransform(-266.5,-206.6,0.191,0.2);

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(1));

	// Layer 17
	this.instance_7 = new lib.snowboard();
	this.instance_7.parent = this;
	this.instance_7.setTransform(-263.4,-207.2,0.711,0.618,-60);

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(1));

	// FlipFlop2
	this.instance_8 = new lib.flip2();
	this.instance_8.parent = this;
	this.instance_8.setTransform(-273.5,-204.5,0.152,0.159,0,54.2,50.2,11.4,26.1);
	this.instance_8.shadow = new cjs.Shadow("rgba(153,153,153,1)",0,0,1);

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(1));

	// Flipflop1
	this.instance_9 = new lib.flip1();
	this.instance_9.parent = this;
	this.instance_9.setTransform(-273.8,-205.7,0.093,0.09,0,17.2,13,6.1,28.3);
	this.instance_9.shadow = new cjs.Shadow("rgba(153,153,153,1)",0,0,1);

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(1));

	// Ball
	this.instance_10 = new lib.ball();
	this.instance_10.parent = this;
	this.instance_10.setTransform(-269.1,-208.4,0.451,0.495);

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(1));

	// Layer 13
	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.lf(["#000000","#666666"],[0,1],0,-6.2,0,6.3).s().p("AgoAkIgKgCQgPgiAEgmIB7ABQADAngPAgIgVADQgPACgOAAQgUAAgUgDg");
	this.shape_20.setTransform(-267.9,-208.3);

	this.timeline.addTween(cjs.Tween.get(this.shape_20).wait(1));

	// Layer 14
	this.instance_11 = new lib.v();
	this.instance_11.parent = this;
	this.instance_11.setTransform(-268.9,-213.7);

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(1));

}).prototype = getMCSymbolPrototype(lib.car, new cjs.Rectangle(-278.2,-222.4,20.8,24.1), null);


(lib.Anim = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_190 = function() {
		KissDone(this);
		stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(190).call(this.frame_190).wait(1));

	// Cloud2
	this.instance = new lib.cloud1();
	this.instance.parent = this;
	this.instance.setTransform(-518.4,-69.7,0.688,0.711);
	this.instance._off = true;
	this.instance.filters = [new cjs.BlurFilter(17, 17, 1)];
	this.instance.cache(-113,-66,227,133);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(60).to({_off:false},0).to({x:393.6,y:-83.4},76).to({_off:true},1).wait(54));

	// Cloud1
	this.instance_1 = new lib.cloud1();
	this.instance_1.parent = this;
	this.instance_1.setTransform(-452.8,-132.3);
	this.instance_1._off = true;
	this.instance_1.filters = [new cjs.BlurFilter(17, 17, 1)];
	this.instance_1.cache(-113,-66,227,133);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(19).to({_off:false},0).to({x:420.8,y:-190.3},53).to({_off:true},1).wait(118));

	// Car
	this.instance_2 = new lib.car();
	this.instance_2.parent = this;
	this.instance_2.setTransform(58,445.5,12.165,11.354,0,0,0,-267.8,-207.6);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({y:157.5},28).wait(4).to({x:68},13).to({x:58},15).wait(12).to({x:68,y:155.9},12).to({y:157.5},13).to({x:58},15).to({scaleX:12.16,x:58.1,y:157.6},7).to({scaleX:12.17,x:58,y:157.5},5).to({x:68,y:155.9},12).to({y:157.5},13).to({x:58},9).to({x:68,y:137.5},32).wait(1));

	// Grass
	this.instance_3 = new lib.grass();
	this.instance_3.parent = this;
	this.instance_3.setTransform(224.9,311.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).to({y:119.1},33).to({_off:true},85).wait(73));

	// Trees
	this.instance_4 = new lib.trees();
	this.instance_4.parent = this;
	this.instance_4.setTransform(-203.6,363.8,6.393,6.441,0,0,0,244,-224.8);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).to({y:59.8},33).wait(61).to({_off:true},1).wait(96));

	// Road
	this.instance_5 = new lib.Symbol1_1();
	this.instance_5.parent = this;
	this.instance_5.setTransform(-18.1,478.4,13.021,9.248,0,-0.6,0,0,10.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_5).to({y:270.4},33).wait(158));

	// Layer 7
	this.instance_6 = new lib.message();
	this.instance_6.parent = this;
	this.instance_6.setTransform(-19.3,78.3,0.061,0.047,0,0,0,121.8,148.8);
	this.instance_6.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(94).to({alpha:1},0).to({regX:121.7,regY:149,scaleX:0.7,scaleY:0.55,x:-26,y:140.8},33).to({regY:148.8,scaleX:1.08,scaleY:0.85,x:-35.7,y:183.1},21).to({y:185.1},11).wait(32));

	// Layer 6
	this.instance_7 = new lib.BACKground();
	this.instance_7.parent = this;
	this.instance_7.setTransform(-12.9,395.6);

	this.timeline.addTween(cjs.Tween.get(this.instance_7).to({y:187.6},33).wait(158));

	// Layer 2
	this.instance_8 = new lib.mountain();
	this.instance_8.parent = this;
	this.instance_8.setTransform(-194.6,299.7,0.587,0.446,0,0,0,262.9,251.9);
	this.instance_8._off = true;
	this.instance_8.filters = [new cjs.BlurFilter(9, 9, 1)];
	this.instance_8.cache(102,-95,322,349);

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(30).to({_off:false},0).to({guide:{path:[-194.6,299.7,-1.8,111.8,301.4,104.6,365.4,105.8,429.4,107]}},70).wait(91));

	// SEAtree
	this.instance_9 = new lib.SeaTree();
	this.instance_9.parent = this;
	this.instance_9.setTransform(124.4,226.6,3.518,3.775,0,0,0,46.6,47.1);
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(68).to({_off:false},0).to({guide:{path:[124.4,226.6,-69.2,110.2,-339.9,104.6,-402.6,105.6,-465.3,106.7]}},61).wait(62));

	// Layer 3
	this.instance_10 = new lib.grass2();
	this.instance_10.parent = this;
	this.instance_10.setTransform(-380.7,443.9,1,1.114,0,0,0,0,31.6);
	this.instance_10.filters = [new cjs.BlurFilter(10, 10, 3)];
	this.instance_10.cache(-287,-91,989,147);

	this.timeline.addTween(cjs.Tween.get(this.instance_10).to({x:-360.7,y:133.9},33).to({x:-189.5,y:137.9},79).to({x:-59.5},78).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-694.2,54.9,1047,489.9);


// stage content:
(lib.Holiday = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		mystage = this;
		mystage.TextCol = 0x000000; // <- Set text color here
		
		if(!mystage.doneInit)
		{
		
			mystage.LocalInit = function()
			{
			  // debug stuff - dont remove
			  if(HugKissDebug)
			  {
				mystage.Args = {WW:640, HH:480};
				mystage.Args.Message = "The message will go here#yt"
				mystage.Args.Vol = 100;
				//DebugGo(mystage);	
			  }
			  
			  // custom code
			}
			/*
		
			function Tick(e) // empty function if no custom code
			{
		
			}
			*/
		
			mystage.LocalGo = function() // empty function if no custom code
			{
			  //mystageInfo.RoundAvs = true; // uncomment if you want circular Avatars
			  
		
			}
		
			KissInit(mystage);
			
			// If hug has NO sound all this can be deleted:
		
			if(mystage.Args == undefined || mystage.Args.Vol > 0)
			{
				mystage.SoundLoaded = function(event) {  
					mystage.SoundsLoading = false; // start timeline
					mystage.visible = true;
					}
				
				mystage.visible = false;
				mystage.SoundsLoading = true; // stop updating (timeline)
				RegisterSounds(["Engine1wav.mp3"], mystage.SoundLoaded);
			}
		
		
		}
		
		
		/* import flash.display.MovieClip;
		sWidth = 640; // width of this design
		sHeight = 480; // height of this design
		include "kiss.as"
		
		var TextCol = 0xFFFFFF; // <- Set text color here
		var TextCol2 = 0xFFFFFF; // <- Set text border color (if used)
		var TextType = 0; // Set to 4 for outlined text
		
		////////// TEST ////////////
		Args = {WW:640, HH:480};
		Args.Message = "The message will go here"
		Go(Args);
		/////// END TEST ////////////
		*/
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1));

	// Animation
	this.AnimMc = new lib.Anim();
	this.AnimMc.name = "AnimMc";
	this.AnimMc.parent = this;
	this.AnimMc.setTransform(337.5,210.5);

	this.timeline.addTween(cjs.Tween.get(this.AnimMc).wait(1));

	// Dots
	this.instance = new lib.dots();
	this.instance.parent = this;
	this.instance.setTransform(320,239);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-22.7,240.5,1015,754.8);
// library properties:
lib.properties = {
	id: '8779CE15A37BE444A8D74EED2114E6F1',
	width: 640,
	height: 480,
	fps: 12,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['8779CE15A37BE444A8D74EED2114E6F1'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;