<?php
$array = [
	'buyshort' => 'Kup krótką nazwę użytkownika',
	'notavailable' => 'Przepraszamy. Skrócona nazwa nie jest dostępna',
	'terms' => 'Musisz wyrazić zgodne z warunkami',
	'nametaken' => 'Niestety Nazwa jest już zajęta',
	'costchanged' => 'Koszt zmieniony',
	'notfound' => 'nie znaleziono',
	'wrongpassword' => 'Złe hasło',
	'noxats' => 'Nie ma wystarczającej liczby xats',
	'namechanged' => 'Nazwa zmieniona',
	'xatname' => 'Login:',
	'password' => 'Hasło:',
	'desiredname' => 'Pożądana nazwa:',
	'noteil' => 'Uwaga: ’j’ zawsze będzie mała litera ’L’ zawsze będzie wielkimą literą.',
	'iagree' => 'Przeczytałem i zgadzam się z <a href="//'.DOMAIN.'/terms">zasadami</a> .',
	'getcost' => 'Uzyskaj cene',
	'once' => 'Tylko raz kliknąć!',
	'letters' => 'Nazwa zawiera błędne litery',
	'short' => 'Nazwa jest za krótka',
	'long' => 'Nazwa jest za długa',
	'notallowed' => 'Nazwa nie jest dozwolona. Proszę spróbować innej.',
	'firstletter' => 'Pierwszy list nie musi być liczbą.',
	'youcan' => 'Możesz użyć '.XAT_NAME.' aby kupić krótką nazwe użytkownika (4-9 liter).',
	'rules' => 'Regulamin:',
	'rulesname' => '<li>Musisz postępować <a href="//'.DOMAIN.'/terms">zgodnie z warunkami</a> </li><li>Koszty są różne krótkiej nazwy, naciśnij koszt aby dowiedzieć się więcej,</li><li>Jeśli krótka nazwa jest nieużywana przez 90 dni Może być sprzedana ponownie</li><li>Tylko jedna krótka nazwa jest dozwolone na osobę</li><li>Twoja obecna nazwa zostanie zastąpiona i utracona</li><li>Jeśli zdecydujemy się na krótką nazwę, która jest obraźliwa (w dowolnym języku) może być usunięta bez refundacji</li><li>'.XAT_NAME.' zastrzega sobie prawo do unieważnienia i zwrotu dowolnej nazwy bez powiadomienia</li><li>Uwaga: krótka nazwa wyżej na liście użytkowników na czacie </li>',
	'buypow' => 'Kup powers',
	'maxbuy' => 'Maksymalnie możesz kupić to',
	'notyet' => 'Nie możesz kupić więcej tej mocy musisz spróbować ponownie',
	'allgone' => 'Przepraszam. Nie ma więcej uprawnień.',
	'nodays' => 'Nie ma wystarczającej liczby dni',
	'nothing' => 'Nic nie kupione!',
	'relogin' => 'Kontrola bezpieczeństwa nie powiodła się. Kliknij <a href="//'.DOMAIN.'/login">tutaj, aby zalogować się ponownie</a>',
	'alreadyhave' => 'Masz już te uprawnienia:',
	'completeta' => 'Zakup zakończony. Dziękuję Ci.',
	'canpowers' => 'Można użyć xats, kupić specjalne moce i uprawnienia do '.XAT_NAME.'',
	'readwell' => 'Opis <font color="#FF0000">(Prosze przeczytać uważnie!)</font>',
	'canplay' => 'Z tych uprawnień możesz uruchomić gry kontrolne.',
	'chkforall' => 'Sprawdź wszystkie dostępne Powers',
	'unavailable' => 'będzie chwilowo niedostępny, gdy wyprzedane',
	'remaining' => 'Pozostało !',
	'willdrop' => 'CENA SPADNIE!',
	'sold' => 'sprzedany',
	'trytrading' => 'Niedostępne, zobacz na <a href="//'.DOMAIN.'/web_gear/chat/chats.php?type=trade">Trade</a>',
	'atauction' => 'Zakup na aukcji <a href="//'.DOMAIN.'/web_gear/chat/Auction.php">Aukcja</a>',
	'powrules' => '<li>Musisz <a href="//'.DOMAIN.'/terms">przestrzegać warunków</a></li><li><strong> Powers działa tylko jeśli jesteś subskrybentem (masz dni) </strong></li><li>Więcej powersów będzie dodane później</li><li>Powers może być wykupiony w sklepie (więc pospiesz się!)</li><li>Cena Powersa może się zmienić w zależnośći od zapotrzebowania</li><li>Inni użytkownicy mogą zobaczyć jakie powersy są włączone </li><li>Powersy mogą być indywidualnie włączane i wyłączane </li><li>Powersy znajdują się w obrocie z innymi użytkownikami</li><li>Powersy mogą być handlowane</li><li>Każda władza ma emotke. Tylko użytkownicy z powersem mogą korzystać z emotek.</li><li><strong>Proszę zapoznać się z opisem powers</strong></li>',
	'power' => 'Power',
	'smilie' => 'Smilie',
	'cost' => 'Cena',
	'quantity' => 'Ilość',
	'orcheck' => 'lub zaznacz',
	'games' => 'Gry',
	'powers' => 'Powers',
	'allpowers' => 'All Powers',
	'alldesc' => 'Aby zakwalifikować się do allpowers, trzeba każdego z każdej mocy Standard Power (oznaczone rakietą).',
	'everypower' => 'Every Power',
	'everydesc' => 'Aby zakwalifikować się do everypower trzeba mieć jedną z każdej mocy wraz ze wszystkimi uprawnieniami grupowymi i Epickie. Można użyć pionka Emerald. Nie można handlować everypower.',
	'epicdesc' => '<b>Epic Powers</b><br>są rzadkie. Znaczną część swojego odwołania pochodzi z ich rzadkości, ponieważ są one tak drogie. Są to nagrody dla handlowców, którzy dążyli do swojej fortuny i celem dla nich jest ta moc.',
	'needlogin' => '(<a href="//'.DOMAIN.'/login">Login</a> aby zmienić)',
	'markallp' => 'Zaznacz All Powers',
	'buyxavis' => 'Kup przedmioty Xavi',
	'check' => 'sprawdź zakup',
	'hat' => 'Hat',
	'hair' => 'Włosy',
	'xavirules' => '<li> Musisz <a href="//'.DOMAIN.'/terms">zgodzić się z warunkami</a> </li>  <li>Xavi tylko działa jeżeli posiadasz subskrybcje (masz dni) i masz power xavi<strong>  </strong> Xavi dodatki nie są handlowane z innymi użytkownikami.</li>',
	'type' => 'Typ',
	'buygroup' => 'Kup Czat Grupe',
	'gtxnotavail' => 'Przepraszam. Przeniesieniem grupy niedostępne',
	'groupnoexist' => 'Ta Grupa nie istnieje',
	'notdormant' => 'Grupa nie uśpiona',
	'txgroupdone' => 'Transfer kompletny. Proszę <a href="//'.DOMAIN.'/$RoomName">przejśc do grupy</a>, aby uzyskać nowe hasło przysane na Państwa email i ustawić to wszystko.',
	'youcangroup' => 'Możesz użyć xats aby przenieść grupe na siebie, która nie jest używana.',
	'groupname' => 'Nazwa Grupy:',
	'costxats' => 'Koszt xats',
	'language' => 'Język',
	'editgrp' => 'Edytuj swoją Grupe aby zmienić',
	'rulesgroup' => '<li>Musisz <a href="//'.DOMAIN.'/terms">zatwierdzić warunki</a> </li><li>Koszt transferu Grupy może się zmieniać, naciśnij ’Uzyskaj Cene’ aby się dowiedzieć</li><li>Jeżeli grupa zostaje niewykorzystana znów może być ponownie przeniesiona</li><li>Wiadomość e-mail grupy zostanie ustawiony na ten sam e-mail co użytkownika</li><li>Jeśli nazwa grupy jest nieodpowiednia, (zobacz <a href="//'.DOMAIN.'/terms">warunki</a>) grupa może zostać usunięta bez uprzedzenia</li><li>Nie martw się, twoja grupa musi być niczyja dłużej niż 3 miesiące wtedy zostanie przeniesiona</li>',
	'promo' => 'Reklamuj Grupe Czatu',
	'langnotset' => 'Grupa językowa nie jest ustawiona. Proszę edytować grupę, aby ustawić język',
	'tinypiconly' => 'Obraz musi byc tinypic.com jako png, jpg. Nie moze być to animowany gif.',
	'promona' => 'Niestety, promocja nie jest dostepna',
	'promoblocked' => 'Niestety, promowanie zablokowane',
	'delisted' => 'Chat zostaje wycofany. Prosze o dodanie do re-listy. (Edycja Czatu, dodatkowe funkcje)',
	'membersonly' => 'Czat jest tylko dla uzytkownikow. Prosze to zmienic. (Edycja Czatu, dodatkowe funkcje)',
	'notzero' => 'Nie można mieć czasu na zero!',
	'adssoon' => '<p> Dziękuję. Reklama będzie wyświetlana wkrótce</p>',
	'promosoon' => '<p> Dziękuję. Reklama rozpoczyna się wkrótce</p>',
	'emailauth' => '<p> Dziekujemy. Email zostanie wysłany, gdy reklama została zatwierdzona. </p>',
	'canpromo' => 'xaty moga byc wykorzystane, aby uzyskac promocje swojej grupy czatu tutaj.',
	'promonow' => 'Promuj teraz!',
	'orads' => 'zareklamuj swoj czat ze swoimi banerami reklamowymi na '.XAT_NAME.'',
	'imageerror' => 'Sprawdzanie błedów obrazu. Przesłać ponownie?',
	'noanim' => 'Nie dopuszcza sie animacji, przepraszamy',
	'imageinval' => 'Nieprawidlowy obraz (2)',
	'imagetype' => 'Rodzaj obrazu nieprawidlowy: $typ',
	'imagebig' => 'Obraz jest zbyt duży (maximum $t bajtów)',
	'imagesize' => 'Wymiary obrazu 728 x 90 px',
	'days' => 'dni',
	'rulespromo' => ' <li>Wszelkie kwestie rozmowy na czacie musza być odpowiednie od wieku 14 lat i wyżej</li><li>Czat musi być <a href="//'.DOMAIN.'/terms">zgodny z warunkami</a> </li><li>Rozmowa na czacie musi być zgodna z zasadami, Chat musi być moderowany gdy jest on promowany (nie używamy wulgaryzmow,itd)</li><li>CHAT RADIO: Jeśli czat radiowy jest czescia umowy musi zawierac, ostrzeżenie radio przeznaczone dla osob w wieku 18 + (w jezyku reklamy)lub nieco powyzej tla (scroller). DJ nie powinien przeklinać. </li><li>Jezeli użytkownik wprowadzi w bota komendę nieodpowiednia, powinna byc zakazana . </li><li>Nieodpowiedni goście powinni być zbanowani (kopnięci)) </li><li>Nie potrzeba żadnych niewłaściwych powiązań ani linków do plikow binarnych (naprzykład programy) </li><li>Chat w promocji nie może sprzedawać Rang np. sell moderator</li><li>Czaty nie powinny opierać się na opiniach religijnych lub politycznych</li><li>Powinien byc przynajmniej jeden wlasciciel lub moderator cały czas <em>widoczny</em> wokół czasu reklamowego czatu </li><li>Czat musi znajdować się w odpowiednim języku w kazdej chwili</li><li>Inne dyskusje moga być promowane w tym samym czasie</li><li>Koszty promocji moga sie rożnić, nacisnij ’Get cost’ żeby dowiedzieć się o kosztach promocji</li><li>Czat musi być otwarty dla wszystkich (nie tylko uzytkownicy lub Live-Mod itd. bezposredni sposob). Zakazuje sie kopać bez powodu np:nowych uzytkownikow(toons,null) </li><li>Chat komunikaty sa wyświetlane tylko dla uzytkowników, którzy znaja jezyk</li><li>Chat reklama obraca się teraz,aby uzyskać wiecej ekspozycji</li><li>Nie nalezy używać pr chyba że jest to konieczne<a href="//util.'.DOMAIN.'/wiki/index.php/Owners_Guide"> można stracić promowanie</a> (Czat musi być otwarty dla wszystkich). Mogą stracić reklamę za pomocą pr. </li><li> <font color="#FF0000">NOWE:</font> Banery ogłoszenia sprzedaży xats są niedozwolone</li>',
	'promohours' => 'Godziny promocji',
	'minhalf' => 'Minimum 0,5 do 12 godz',
	'adimage' => 'Ogłoszenie graficzne',
	'advertise' => 'Publikuj',
	'aphase' => 'Faza Aukcji',
	'needmore' => 'Musisz licytować więcej niż',
	'notpart' => 'nie jest częścią aukcji!',
	'ended' => 'Aukcja została zakończona.',
	'idblocked' => 'ID jest zablokowane.',
	'choose' => 'Wybierz metodę przesyłania',
	'notenough' => 'Nie ma wystarczającej liczby xats/powers',
	'alreadybid' => 'Masz już ofertę',
	'biddone' => 'Oferta złożona.',
	'during1' => 'Podczas fazy 1 aukcji można zaproponować identyfikatory jakie chcesz kupić.',
	'p1ends' => 'Faza 1 zakończona:',
	'during2' => 'Podczas fazy 2 aukcji można licytować na którykolwiek z identyfikatorów z listy.',
	'previous' => 'Wcześniejsze wyniki aukcji.',
	'bids' => 'Aktualne oferty:',
	'idfor' => 'ID na sprzedaż',
	'timeleft' => 'Pozostały czas',
	'prevbid' => 'poprzednia oferta',
	'congrats' => 'Gratulujemy wygranej Aukcji.',
	'auclogin' => 'Aby otrzymać nowy ID login z nazwą',
	'rereg' => 'UWAGA: Jeśli chcesz, aby ponownie zarejestrować swój stary identyfikator skorzystaj z tego linku',
	'aucreg' => 'WAŻNE: Aby zarejestrować nowy identyfikator skorzystaj z tego linku',
	'bid' => 'Oferta',
	'topbid' => 'Najlepsza oferta z',
	'prevhere' => 'Dotychczasowe wyniki aukcji są <a href="?old=1">tutaj</a>.',
	'canauction' => 'Można użyć swoich '.XAT_NAME.' i licytować w aukcji.',
	'auctionrules' => '<li>Musisz postępować <a href="//'.DOMAIN.'/terms">zgodnie z warunkami</a> </li><li>'.XAT_NAME.' zastrzega sobie prawo do unieważnienia i zwrotu żadnej aukcji bez wypowiedzenia</li><li>Twoja nazwa i identyfikator użytkownika zostanie wyświetlona, jeśli są wysokie oferty/zwycięzca (to jest aukcja publiczna)</li><li>Oferty są wiążące. Jeśli cię nie przebiją będzie zobowiązany do zapłaty.</li><li>Jeśli jesteś na top licytacji musisz zachować wystarczająco '.XAT_NAME.' i uprawnień na koncie, aby pokryć oferte.. </li><li>Musisz mieć wystarczająco dużo '.XAT_NAME.' i nie ograniczone uprawnienia na koncie w celu podbicia stawki.</li><li>Jeśli wygrasz, <strong>musisz zastrzec swój identyfikator w ciągu 12 godzin</strong>aukcji kończących </li><li>Jeśli nie uda ci się wypełnić aukcja może być<strong> grzywną lub usunięta </strong></li><li><span class="style1">NOWE</span> Jeśli licytujesz przez pomyłkę tracisz 20% stawki, ale musisz powiadomić '.XAT_NAME.' odrazu</li><li><span class="style1">NOWE</span> Jeśli nie uda ci się zakończyć aukcji i przeniesiesz XATS stracisz 100% stawki </li><li>'.XAT_NAME.' zastrzega sobie prawo do zablokowania ID z aukcji.</li><li>również sprawdź <a href="//util.'.DOMAIN.'/wiki/index.php?title=Auction">Wiki</a> przed licytacją</li><li>Na aukcji nazwa zostanie przypisana do ID. <strong>Twoja stare ID zostanie utracone.</strong></li>',
	'minbid' => 'Minimalna stawka w tej Aukcji jest:',
	'desired' => 'Wymagane ID',
	'digits' => 'cyfr',
	'enterbif' => 'Wprowadź stawkę',
	'buyxats' => 'Kup xaty i dni',
	'intro' => 'xaty pozwalają na zakup uprawnień i wiele innych rzeczy, na czacie. Dostaniesz równierz ’dni’. Dni są jak czas abonencki i są potrzebne, aby moce działały i inne funkcje czatu. Zdecyduj, ile '.XAT_NAME.' chcesz zakupić z poniższej listy oraz nacisnąć jeden z przycisków. Należy upewnić się, że masz uprawnienia posiadacza karty lub konta. Wszystkie zakupy podlegają naszym <a href="//'.DOMAIN.'/terms">warunkom regulaminu.</a> Dla opcji płatności telefonicznych należy upewnić się, że posiadasz pozwolenie płatników Bill i masz ponad 16 lat.',
	'aboutto' => 'Masz zamiar zamówić xaty dla użytkownika:',
	'notyou' => 'Jeśli to nie jest twoje ID nie PRZECHODŹ DALEJ!',
	'cash' => 'Bank  PayByCash',
	'credcard' => 'Kredytkarta',
	'includes' => 'dni',
	'over70' => '\u00dcber 70 nicht-Kreditkarten <br> M\u00f6glichkeiten, um weltweit zu zahlen<br>',
	'ugc' => 'Ultimate Game Card',
	'prepaid' => 'Prepaid-Karte - USA  Kanada  T\u00fcrkei  Brasilien  Philippinen  Israel  Portugal  Malaysia  Singapur  Taiwan',
	'calculated' => 'xats und Tage <br> werden berechnet <br> auf dem Wert von <br> der Karte',
	'multiugc' => 'Wenn Sie mehr als eine Gamecard haben, k\u00f6nnen Sie vielleicht <br> mehr xats erhalten durch das Benutzen des PayByCash Button',
	'pin' => 'Pin-Code',
	'nogc33k' => '<b>Sie k\u00f6nnen nicht die Gamecard <br>  f\u00fcr 33000 xats Option benutzen</b>',
	'max10' => '*: do maksymalnie 10 lat --- **: Dla europejskich Unijny VAT zostanie dodany do kwoty lub odejmowane zostanie od xatów --- USD = US-Dollar',
	'reserve' => 'PayPal, Płatności kartą kredytową i telefonów podlegają <a href="//util.'.DOMAIN.'/wiki/index.php/XatsReserve">Rezerwie Transferu</a> . Płatności PayPal powinny być na jednym ID tylko.',
	'days2xats' => 'Konwersja dni na xaty',
	'min10' => 'minimum 10 dni',
	'nodx' => 'Nie masz powersa DX',
	'sorryyou' => 'Niestety trzeba być zarejestrowanym użytkownikiem, aby używać',
	'candx' => 'Można konwertować niektóre dni na xaty tutaj..',
	'daysto' => 'Dni do konwersji:',
	'dxrules' => ' <li>Musisz postępować <a href="//'.DOMAIN.'/terms">zgodnie z warunkami</a> </li><li><strong>Trzeba będzie użyć jedną moc DX na konwersję</strong></li><li>Można konwertować do 180 dni na jednej mocy DX</li><li>Dostaniesz 13,5 XATS za 1 dzień</li>',
	'convert' => 'Konwertuj',
	'notconf' => 'Nie potwierdzona rejestracja',
	'pleasewait' => 'Proszę czekać',
	'promonote' => 'Zauważ, że jeśli nie bedziesz przestrzegał tych zasad, reklama zostanie rozwiązana bez powiadomienia i bez zwrotu xats. Ponadto, grupa zostanie usunięta ze wszystkich list i bloków innych reklam ',
	'held' => 'Konto held (festgehalten). Sie k\u00f6nnen keine xatsdays kaufen.',
	'pinbad' => 'PIN-Code ist zu kurz oder falsche Zeichen ',
	'paypal' => 'Paypal',
	'oneonly' => 'PayPal-Zahlungen sollte nur an eine '.XAT_NAME.' ID.',
	'careful' => '(DOKŁADNIE SPRAWDŹ!)',
	'otherids' => 'Andere IDs ersteigern',
	'notavail' => 'Entschuldigung. Nicht verf\u00fcgbar',
	'imgneedauth' => 'Anzeige Bilder m\u00fcssen genehmigt werden <font color="#FF0000">(kostet 50 xats)</font>  <br> Sehen Sie  <b>wiki<a href="//util.'.DOMAIN.'/wiki/index.php?title=Advertise">, bevor Sie fortfahren.</a>',
	'authorize' => 'Autoryzacja',
	'winner' => 'Zwycięzca',
	'soldcol' => 'Sprzedawane i nabyte',
	'p2ends' => 'Faza 2 aukcji:',
	'forgotpass' => 'Jeśli nie pamiętasz hasła, wpisz swój email',
	'wait' => 'Prosze czekać..',
	'buy' => 'Kup',
	'xats2days' => 'Konwertuj xaty na dni',
	'canx2d' => 'Można konwertować niektóre xaty na dni tutaj.',
	'x2drules' => ' <li>Musisz postępować <a href="//'.DOMAIN.'/terms">zgodnie z warunkami</a> </li><li><strong>Trzeba będzie użyć jedną moc X2D na jedną konwersję</strong></li><li>Można konwertować do 2500 XATS na mocy X2D</li><li>Dostaniesz 1 dzień za 13,5 xats</li> ',
	'xatsto' => ''.XAT_NAME.' do konwersji',
	'norequests' => 'Keine Anfragen bisher eingegangenen',
	'pinacc' => 'PIN akzeptiert. Sie werden in K\u00fcrze eine E-Mail erhalten'
]
?>
