<?php
$array = [
	'creategroup' => 'Utwórz Grupe',
	'badpass' => 'Error błąd hasła.',
	'modrules' => 'zmodyfikowana tak, aby spełnić warunki',
	'access' => 'dostęp do istniejących grup tutaj',
	'yourname' => 'Swoje imię:',
	'desc' => 'Opis Grupy:',
	'let2050' => '(20-50 liter)',
	'grt6' => 'Przynajmniej w przypadku sześciu liter - NIE UDOSTEPNIAJ (Hasło jest tylko dla edycji grupy)',
	'noshare' => 'NIE UDOSTEPNIAJ','passonly' => '(Hasło jest tylko dla edycji grupy)',
	'tags' => 'Tagi:',
	'sepcom' => '(Oddzielone przecinkami)',
	'taginfo' => 'Tagi to słowa kluczowe, które opisują swoją grupę tak aby inni mogli ją znaleźć.Na przykład. grupa do wyścigów może być oznaczona: wyścig,tor,samochód.',
	'mustvalid' => 'To musi być poprawny EMAIL ADRES Aby aktywować GRUPE..',
	'grpres' => 'nazwa grupy zarezerwowana',
	'grpexist' => 'nazwa grupy już istnieje',
	'urlinfo' => 'Opcjonalnie - Adres strony internetowej, która znajdą się w celu promowania tej grupy',
	'grpac1' => '<p> Dziękujemy, Twója grupa jest przetworzona. <br /> E-mail został wysłany. Teraz tylko trzeba kliknąć w link w mailu, aby aktywować grupę.</p>  \n<p>N.B jeśli nie otrzymano, sprawdzić e-mail w skrzynce ze spamem.<strong>  </strong> \n</p><p>(Wiadomość e-mail może trwać do 30 minut aby dotrzeć)<strong></strong> </p>Jeśli nadal nie może uzyskać dostępu przez swój e-mail, być może trzeba będzie ponownie wykonać operację. Spróbuj konto na <p><a href="http://gmail.com">Gmail</a>. Jeśli Twój dostawca poczty nie pozwala dostarczyć naszego potwierdzenia nie będzie można dokończyć konfiguracji. ',
	'grpac2' => 'Proszę aktywować '.XAT_NAME.' grupę czatu:%s',
	'grpac3' => 'Witaj, Kliknij poniższy link, aby aktywować grupę, trzeba klikną na link poniżej aby aktywować grupe i stać się włąścicielem:%s (UWAGA: o nome n\u00e3o \u00e9 reservado e que o grupo n\u00e3o ser ativado at\u00e9 que voc\u00ea tenha clicado no link) Outro e-mail ser\u00e1 enviado confirmando a ativa\u00e7\u00e3o.',
	'grpinfo' => 'Czat Grupy dzielone są czaty dla określonego celu. To może być w celu omówienia konkretnego tematu (np muzyki, anime, gry komputerowe), dla określonej grupy wiekowej lub typu osoby (np 20 coś, studenci) lub dla określonego kraju / języka. Możesz <a href="//'.DOMAIN.'/groups.php">uzyskać dostęp do istniejących grup tutaj</a>',
	'az' => 'A-Za-z0-9_ tylko np: AllAboutCats',
	'grpwarn' => '<p> Twoja grupa może być usunięta bez ostrzeżenia lub zmodyfikowana, gdzie: </p><p>Nie prawidłowy adres e-mail</p><p>Jeśli nazwa grupy jest nieodpowiednia (patrz <a href="//'.DOMAIN.'/terms.html" target="_blank">Warunki kożystania z usługi</a>)</p>Grupa nie jest używana lub niemoderowana.',
	'iam14' => 'Mam 14 lat lub więcej, i zgadzam się z <a href="//'.DOMAIN.'/terms.html" target="_blank">warunkami serwisu</a>',
	'sendfbk' => 'Prześlij opinię do rozmowy z właścicielem grupy',
	'contact' => 'Jeśli chcesz skontaktować się z właścicielem grupy %s możesz to zrobić tutaj. Właściciele nie są zobowiązani do odpowiedzi na e-mail, ale na pewno nie, jeśli nie zapewnisz prawidłowego adresu e-mail',
	'grpmess1' => 'grupa '.XAT_NAME.':%s - Wiadomość',
	'grpmes2' => 'Witaj %s Osoba odwiedzająca %s czat grupowy kliknął przycisk Wiadomość i wysłał Ci następujący komunikat. (Zalecane jest , aby nie kliknąć na linki).',
	'noemail' => 'Użytkownik nie dostarczył swój adres e-mail',
	'thxsent' => 'Dziękuję. Twoja wiadomość wysłana',
	'optemail' => 'Opcjonalnie, ale nie dostaniesz odpowiedzi, jeśli to nie jest ważne',
	'message' => 'Wiadomość',
	'send' => 'Wyślij',
	'grpmess2' => 'Witaj %s Osoba odwiedzająca %s czat grupowy kliknął przycisk Wiadomość i wysłał Ci następujący komunikat. (Zalecane jest , aby nie kliknąć na linki).',
	'reportgrp' => 'Zgłoś nieodpowiedni czat',
	'plzsel' => 'Prosze, wybrać ...',
	'badlang' => 'Wulgarny język',
	'scamming' => 'Oszukiwania, phishing czy hacking',
	'badimg' => 'Nieodpowiednie zdjęcia lub wideo',
	'bully' => 'Molestowanie, Cyberbulling, Imposter',
	'unwanted' => 'Niechciany Kontakt',
	'otherissue' => 'Inne terminy Naruszenie (proszę określić)',
	'readcare' => 'Ważne: proszę uważnie przeczytać przed złożeniem raportu',
	'mustsel' => 'należy wybrać odpowiednią kategorię',
	'bademail' => 'e-mail nie jest poprawny',
	'mustchars' => 'powinna wynosić co najmniej 8 liter',
	'complaint' => 'Skarga:',
	'bedetailed' => '(Należy być szczegółowy, aby dalej pomagać nam w raporcie)',
	'nonotify' => 'Nie możesz zostać powiadomiony o wyniku raportu lub o podjętych działaniach.',
	'repimg' => 'Raport zdjęcia',
	'canreport' => 'Możesz zgłosić coś nieodpowiedniego, jeśli narusza nasze <a href="//'.DOMAIN.'/terms.html">Warunki korzystania z usługi</a> Jeśli uważasz, że coś jest niewłaściwe, użyj poniższego pola, aby poinformować nas o przyczynach. Jednak polski'.XAT_NAME.' nie pomoże rozwiązać sporów pomiędzy użytkownikami. Proszę nie zgłaszać bez ważnej przyczyny tego, jeśli wielokrotnie to robisz, możesz zostać zablokowany przez naszą usługę.',
	'addinfo' => 'Dodatkowe informacje: <br /> (Prosimy o jak najdokładniejsze przekazanie nam dodatkowych informacji w raporcie)',
	'reportpro' => 'Zgłoś nieodpowiedni xatspace (profil)',
	'repuser' => 'Raportowanie użytkownika',
	'grpknown' => 'Grupa (jeśli jest znana) ',
	'postcom' => 'Zamieść komentarz',
	'todelete' => 'Trzeba być właścicielem , 
	aby usunąć ten komentarz',
	'topost' => 'Musisz być zarejestrowany aby dodać komentarz',
	'confdel' => 'Potwierdź usunięcie komentarza',
	'typecom' => 'Wpisz tutaj swój komentarz. Można użyć prostego HTML i obrazu. (Limit 5000 bajtów)',
	'delcom' => 'Usuń komentarz','savcom' => 'Zapisz komentarz',
	'activategrp' => 'Aktywacja nowej czat grupy',
	'expired' => 'Aplikacja Twojej grupy wygasła. Możesz spróbować ponownie.',
	'already' => 'Grupa ta została już aktywowana.',
	'taken' => 'Niestety, ta grupa już istnieje. Można spróbować ponownie, używając innej nazwy grupy.',
	'activated' => 'Ta grupa została aktywowana! Zobacz email aby zobaczyć szczegóły. Twój adres grupy to:',
	'grpok1' => 'Aktywacja czat grupy%s jest kompletna',
	'grpok2' => 'Witaj%s, Twója czat grupa $name jest teraz aktywna. Link do Twojej grupy jest:%s Aby edytować %s naciśnij przycisk który jest w prawym dolnym rogu i wprowadź hasło. Aby przywrócić status właściciela, jeśli został on zgubiony wejdz w edycje czatu i kliknij w przycisk Czat Box Ustawienia. Jeśli grupa narusza warunki usługi %s lub jest nieaktywna to może zostać zmieniona lub usunięta. Osoby odpowiedzialne są za materiały które umieszczają w oknie czatu , ale moderatorzy grupy powinni upewnić się, że użytkownicy będą przestrzegać regulamin. Zapraszamy do zabawy i życzymy powodzenia! '.XAT_NAME.'',
	'seachchat' => 'Szukaj na czacie',
	'searchinfo' => 'Czaty prywatne, Prywatne wiadomości, Tylko dla Uzytkowników, Nie umieszczaj i nie Przechowywuj nie można przeszukiwać. <a href="//util.'.DOMAIN.'/wiki/index.php?title=Search">Więcej informacji</a>',
	'moreinfo' => 'Więcej informacji.',
	'nores' => 'Niestety brak wyników',
	'moreresults' => 'Więcej wyników',
	'minsago' => 'temu na',
	'hoursago' => 'temu na',
	'searchingfor' => 'Szukaj dla:',
	'results' => 'Wyniki',
	'search' => 'Szukaj',
	'mustbe' => 'Musi być przynajmniej',
	'letters' => 'liter',
	'unfair' => 'Nieuczciwy Ban',
	'noctrl' => 'Promocja: Nieodpowiednia lub poza kontrolą',
	'addcom' => 'Dodaj komentarz',
	'dispcom' => 'Wyświetl komentarz',
	'delete' => 'Usuń',
	'news' => 'Nowość',
	'events' => 'Wydarzenia',
	'inapp' => 'inappropriate','comments' => 'Komentarze','grid' => 'grade','player' => 'player','' => 'rabisco','translate' => 'tłumacz','games' => 'gry','apps' => 'aplikacje','embed' => 'Embed','chglang' => 'Zmień Język','sellang' => 'Wybierz język:','eventsfor' => 'Chat wydarzenia dla ','oldres' => 'Resultados mais velhos','duration' => 'Trwanie','text' => 'Text','canevents' => 'Możesz wyszukać wydarzenia czatów(zobacz <a href="//util.'.DOMAIN.'/wiki/index.php?title=Events">wiki</a>)','all' => 'Wszystkie','time' => 'Czas','emailsent' => 'E-mail wysłany','needlogin' => 'Prosze się, <a href="//'.DOMAIN.'/login">zalogować</a> aby skorzystać z tej strony.','needevents' => 'Niestety, trzeba moc events lub eventstats aby skorzystać z tej strony','nodays' => 'Przepraszamy nie posiadasz dni.','continue' => 'Kontynuj','name' => 'Nazwa','grassmod' => 'Report  moderatora','feelunfair' => 'Jeśli czujesz, że zostały niesprawiedliwie traktowani przez moderatora może to zgłosić do właściciela grupy. Właściciele nie są zobowiązane do odpowiedzi na e-maile, ale na pewno nie będzie, jeśli nie zapewniają poprawną address.p e-mail.','modrpt1' => 'grupo xat:%s - Relatório do moderador','modrpt2' => 'Ol\u00e1%s, Voc\u00ea recebeu este relatório sobre um moderador em seu grupo','modrpt3' => 'Clique aqui:%s para ver uma transcri\u00e7\u00e3o de eventos..','transcript' => 'Zapis Czatu','youneed' => '<p>Musisz upewnić się, że moderatorzy robią dobrą robotę i są fair w stosunku do użytkowników. Jeśli to tylko jeden zły moderator to doprowadzi do zrujnowania czatu. Jeśli są dobrzy moderatorzy twoje okno czatu będzie stawać się coraz bardziej popularne.</p><p>Prosimy o zapoznanie się z tym zakazem nieuczciwej reklamacji i jeśli nie jesteś z niego zadowolony porozmawiaj z moderatorem o swoich obawach lub ich umiarkowaniu.</p>','banby' => 'został zbanowany przez','clkunmod' => 'Clique para Un-Moderar','unfriendly' => '<p> Uwaga: Ta grupa może być na wykazie, jeśli ty lub twoi moderatorzy są nieprzyjaźni. to znaczy, że nie pojawią się na liście grup lub na popularnej liście polskiegoxatu. </p>','transno' => 'Transcri\u00e7\u00e3o n\u00e3o existe. Ele pode ter sido eliminado. Eles s\u00e3o mantidos por uma semana','unmod' => 'Unmoderar um moderador','yesunmod' => 'Sim - UnModerate','sureunmod' => 'Voc\u00ea tem certeza que quer Un-moderate','chatconf' => 'Por favos fazer  convidado no  chat box','tounmod' => 'Kliknij powyższy link aby Un-Mod','istrans' => 'Poniżej znajduje się zapis komunikatów prowadzących do zakazu','chatid' => 'Chat id:','seeall' => 'Vocu00ea pode ver todas as imagens em um grupo aqui e facilmente relatar quaisquer aqueles inadequados para o host de imagem.'
]
?>