<?php
$array = [
	'00' => '(granted)Twoje [życzenie|żądanie|pragnienie|wymaganie] jest [zgodne|udzielone bezwarunkowo|moim poleceniem].',
	'01' => '(granted)Ty [myślisz|śpisz] mało, ale [OK|Dobra|wporządku].',
	'02' => '(granted)Ale [dziwne|nieparzyste|niezwykle|dziwaczne] [życzenie|żądanie|pragnienie|wymaganie] że mogę je [spełnić|spełnić|spełnić].',
	'03' => '(granted)[Niesamowite|Niezwykłe|Wspaniałe] życzenie! Zgoda.',
	'04' => '(granted)Twoje [życzenie|żądanie|pragnienie|wymaganie] zostało udzielone, należy go używać [mądrze|z dbałością|poprawnie|ostrożnie|z korzyścią dla wszystkich].',
	'05' => '(catch)Twoje [życzenie|żądanie|pragnienie|wymaganie] zostaną przyznane [lecz nie przez jakiś czas|ale nie na chwilę|ale nie od razu|w odległej przyszłości|w pełni czasu|ostatecznie|jednodniowo].',
	'06' => '(catch)Tego życzenia ja [nie spełnię|nie zrobię|odmówię] ale zamiast tego dostaniesz [czego naprawdę chcesz|czego potrzebujesz|o co poprosisz|twoje sekretne pragnienie].',
	'07' => '(catch)Mogę udzielić tylko [połowe|niektóre|część|trochę] tego życzenia.',
	'08' => '(catch)Twoje życzenie jest [przyznane|dozwolone|dopuszczalne|dozwolone] ale tylko [today|na krótki czas|na chwilę].',
	'09' => '(catch)Ja [myślę|wierzę|wiem] że będziesz [żałował tego|rozczarowany] ale dozwolone [wszystkie takie same|mimo to].',
	'10' => '(evil)Twoje życzenie jest przyznane, ale nie [uczyni cię szcześliwym|przyniesie ci radości|wszystko co chcesz].',
	'11' => '(evil)Twoje życzenie zostało przyznane, ale będziesz również przekształcony w [żabe|małpę|wiedzme|dynie|kota|psa|mysz|jaszczurkę|robota|rzeżbę].',
	'12' => '(evil)[OK|Dobrze|W porządku|Akceptowane|Super|Autoryzowane|Do przyjęcia], ale powinieneś być [ostrożny|rozważny|zdenerwowany z powodu] o czym marzysz.',
	'13' => '(refused)Twoje życzenie jest daleko poza moją [funkcje|umiejętność|moc|pojemnośc|zdolnośc|glową].',
	'14' => '(refused)Możesz wymyślić coś [lepszego|wspanialszego|bardziej ambitnego|fajniejszego] niż to.',
	'15' => '(refused)[Brak zgody|Nie ma mowy|Bez szans|Pffft]! [Spróbuj|Trzeba więcej szczęścia za pomocą] [dobych życze\u0144|tortu urodzinowego|spadającej gwiazdy|kości|tęczy].',
	'16' => '(refused)[Przepraszam|Przepraszam|Niestety], Jestem poza wszystkimi życzeniami [dziś|teraz|przez chwilę].',
	'17' => '(refused)(grant)Mógłbym [pozwolić|pozwolić|pozwolić] na to [życzenie|zapytanie|pragnienie|żądanie] ale to prowadzi do [katastrofy|nieszczęścia|katastrofy|niepowodzenia|szkosy|tragedi|przeciwności|ruiny].',
	'18' => '(no)Ja [lubię|kocham|szanuje|podziwiam|pochwalam] to życzenie ale [nie|nie ma szans|daruj sobie].',
	'19' => '(no)Mozesz to [osiągnąć|osiągnąć|osiągnąć|osiągnąć|dostać] na [własną rękę|własną rękę|własną rękę beze mnie].',
	'20' => '(no)[Nie|Nigdy nie|Nie] [|] wydarzy się [kolego|amigo|kolego|przyjacielu|gościu|łobuzie|przyjacielu]!',
	'21' => '(no)Gdyby ktoś zapytał o to [wczoraj|w zeszłym tygodniu] [może|może|może] bym był w stanie ci pomóc..',
	'22' => '(no)Wiesz że nie moge na to [pozwolić|pozwolić|pozwolić].',
	'23' => '(no)Czyżby zabrakło ci życze\u0144!',
	'24' => '(angry)Zapytałeś o [zbyt wiele|więcej niz to jest fair|więcej niz moge pozwolić] więc masz [nic|nic|w ogóle nic].',
	'25' => '(angry)Nie [marnuj mojego czasu|przeszkadzaj] ze swoimi [drobnymi rzeczami|nonsesami|głupotami].',
	'26' => '(angry)[Obudziłeś mnie|Przeszkadzasz mi|Wezwałeś mnie|Wezwałeś mnie] o co chesz zapytać!',
	'27' => '(angry)Mógłbyś [sobie zyczyć|zapytać o|zapytać o|żądać] cokolwiek i co chcesz?',
	'28' => '(angry)Przesta\u0144 sobie życzyć i idż coś zrobić!',
	'29' => '(angry)Co to za [śmieciowe|głupie|idiotyczne|krety\u0144skie|absurdalne|bezwartościowe] [życzenie|prośba|życzenie|prośba]!',
	'30' => '(wisdom)Zamiast tego proponuję [mądrość|porade|prawdę]. [Nigdy nie jedz żółtego śniegu|Lepszy wróbel w garści niż gołąb na dachu|Głupiec i jego pieniądze szybko się rozstają|Prawdziwych przyjaciół poznaje się w biedzie].',
	'31' => '(wisdom)Wiedz że [prace warto zrobić, warto zrobić dobrze|trochę wiedzy jest rzeczą niebezpieczną|ryba psuje się od głowy|lepiej dmuchać na zimne] będzie Ci służyć to lepiej.',
	'32' => '(wisdom)Ty nie [potrzebujesz|chcesz], tylko pamiętaj [nieobecność sprawiają, że serce rośnie bardziej|nieobecność sprawiają, że serce rośnie bardziej|bądż wdzięczny za to, co masz|bądż wdzięczny za to, co masz].',
	'33' => '(wisdom)\u017Byczenia są dla [głupców|przegranych|idiotów], wszystko, co musisz wiedzieć, to [kłamstwo ma krótkie nogi|nie wkładaj wszystkich jaj do jednego koszyka|szczęście sprzyja odważnym|wiedza to potęga].',
	'34' => '(wisdom)Dlaczego [nie myślałem|nie dostałem] tego dla siebie.','35' => '(wisdom)Cóż, to jest życzenie [nowe dla mnie|najdziwniejsze o jakie zostałem poproszony|bardzo dziwne].'
]
?>