<?php
$array = [
	'groups' => 'Grupy',
	'store' => 'Sklep',
	'powers' => 'Powers',
	'xavi' => 'xavi',
	'xatgroup' => 'Transfer Group',
	'shortname' => 'Krótka nazwa',
	'promotion' => 'Promuj chat',
	'auctions' => 'Aukcje',
	'community' => 'Forum',
	'more' => 'Więcej',
	'twitter' => 'Twitter',
	'wiki' => 'Wiki',
	'support' => 'Suport',
	'contact' => 'Kontakt',
	'help' => 'Pomoc',
	'trade' => 'Trade',
	'widgets' => 'Wiecej...',
	'login' => 'Logowanie',
	'language' => 'Język',
	'privacy' => 'Prywatność',
	'terms' => 'Warunki korzystania z usługi',
	'safety' => 'Bezpieczeństwo',
	'rights' => 'Wszelkie prawa zastrzeżone.',
	'buyxats' => 'Kup xaty dni',
	'failed' => 'powiodło',
	'evalid' => 'nieprawidłowy adres e-mail',
	'recaperr' => 'ReCAPTCHA nie została poprawnie wprowadzona. Proszę spróbuj ponownie. (reCAPTCHA twierdzi',
	'notbot' => '... i upewnij się, że nie jesteś botem',
	'numinbox' => 'Wpisz kod weryfikacyjny',
	'cancel' => 'Anuluj',
	'submit' => 'Zatwierdź',
	'wrongnum' => 'jest wpisany nieprawidłowy numer',
	'ayaherr' => 'Proszę udowodnić, że jesteś człowiekiem'
]
?>