<?php
$array = [
     'groups' => 'Groupes',
     'store' => 'Magasin',
     'buyxats' => 'Achat de xats jours',
     'powers' => 'Pouvoirs',
     'xavi' => 'xavi',
     ''.XAT_NAME.'group' => 'groupe '.XAT_NAME.'',
     'shortname' => 'Nom court',
     'promotion' => 'Promotion',
     'auctions' => 'Enchères',
     'community' => 'Communauté',
     'more' => 'Plus',
     'twitter' => 'Twitter',
     'wiki' => 'Wiki',
     'support' => 'Support',
     'contact' => 'Contact',
     'help' => 'Aide',
     'trade' => 'Trade',
     'widgets' => 'Widgets',
     'login' => 'Connexion',
     'language' => 'Langue',
     'privacy' => 'Confidentialité',
     'terms' => 'CGU',
     'safety' => 'Sécurité',
     'failed' => 'échec',
     'evalid' => 'email invalide',
     'recaperr' => 'Le reCAPTCHA n’a pas été entré correctement. Veuillez essayer de nouveau. (reCAPTCHA a dit',
     'notbot' => 'et pour vérifier que vous n’êtes pas un bot',
     'numinbox' => 'Veuillez entrer ce numéro dans la case qui suit',
     'cancel' => 'Annuler',
     'submit' => 'Soumettre',
     'wrongnum' => 'Mauvais numéro entré !',
     'ayaherr' => 'Vous devez prouver que vous êtes humain.'
	 ]
?>