<?php
$array = [
     'quizq1' => 'Vous recevez un message d’une personne qui prétend être un bénévole. Cette personne dit que votre compte est bloqué, pour résoudre le problème, vous devez lui donner votre mot de passe et votre adresse e-mail, autrement votre compte restera bloqué. Que faites-vous ?',
     'quizq1a1' => 'Ne donner aucune information.',
     'quizq1a2' => 'Vous ne voulez pas perdre votre compte '.XAT_NAME.', donc vous donnez les informations demandées.',
     'quizq1a3' => 'Demander une preuve que c’est un véritable bénévole.',
     'quizq1info' => 'Correct ǃ Le personnel de '.XAT_NAME.' et les bénévoles ne demanderont jamais des informations personnelles dans des chats privés. Signalez l’utilisateur en prenant des captures d’écran de son ID et de son message, puis ouvrez un ticket dans la rubrique Report Scam.',
     'quizq1image' => '<br img src="https://util.'.DOMAIN.'/wiki/images/f/f9/Securityimage1.png" class="img-fluid"/>',
     'quizq2' => 'Vous êtes sur le chat Trade en train d’essayer d’acheter des days. Vous êtes contacté par une personne qui vous demande de transférer vos xats en premier. Que faites-vous ?',
     'quizq2a1' => 'Refuser et suggérer d’utiliser l’application Safe Trade, qui est la méthode recommandée.',
     'quizq2a2' => 'Transférer vos xats en premier.',
     'quizq2a3' => 'Leur demander d’abord leurs days.',
     'quizq2info' => 'C’est juste ! Lors de l’achat et de la vente de xats, de days ou de pouvoirs, vous devez toujours utiliser l’application Safe Trade. Grâce à cette application, vous pouvez voir en temps réel ce qui est en train d’être négocié. Ne faites jamais du trade en utilisant la fonctionnalité de transfert car les transactions ne peuvent pas être annulées une fois effectuées.',
     'quizq2image' => '<br img src="https://util.'.DOMAIN.'/wiki/images/c/c0/Securityimage2.png" class="img-fluid"/>',
     'quizq3' => 'Votre fournisseur d’e-mail offre une protection par authentification à 2 facteurs. Devriez-vous activer cette option ?',
     'quizq3a1' => 'Oui. Cela augmentera considérablement la sécurité de l’adresse e-mail.',
     'quizq3a2' => 'Non. Mon mot de passe est suffisamment fort.',
     'quizq3a3' => 'Jamais. Cette protection n’est pas utile.',
     'quizq3info' => 'Correct ! Une authentification à deux facteurs de votre adresse e-mail ajoutera une couche de sécurité supplémentaire (par téléphone) pour garantir que personne d’autre à part vous ne puisse accéder à votre e-mail - même si votre mot de passe est piraté.<br><br>Veuillez contacter votre fournisseur d’adresse e-mail pour savoir comment activer l’authentification pour votre compte e-mail. Pour les comptes Gmail, veuillez voir <a href="https://www.google.com/landing/2step/" target="_blank">cette page</a>.',
     'quizq3image' => '<br img src="https://util.'.DOMAIN.'/wiki/images/7/71/Securityimage3.png" class="img-fluid"/>',
     'quizq4' => 'On vous parle au sujet d’une mise à jour sur la page de connexion de '.XAT_NAME.'. L’utilisateur vous envoie le lien pour le test, qui est https://xaatt.com/login. Que faites-vous ?',
     'quizq4a1' => 'Ne pas cliquer sur ce lien car ce n’est pas un domaine de https://'.DOMAIN.'.',
     'quizq4a2' => 'Cliquer dessus pour voir ce qui a changé.',
     'quizq4info' => 'Correct ǃ Consultez toujours la barre d’adresse pour vous assurer que vous vous trouvez bien sur le domaine de <a href="https://'.DOMAIN.'" target="_blank">https://'.DOMAIN.'</a> avant de vous connecter, de visiter un chat ou de saisir l’une de vos informations relatives à '.XAT_NAME.'.',
     'quizq4image' => '<br img src="https://util.'.DOMAIN.'/wiki/images/7/7d/Securityimage4.png" class="img-fluid"/>',
     'quizq5' => 'Un utilisateur vous propose de doubler vos pouvoirs mais vous devez d’abord lui échanger les vôtres. Que faites-vous ?',
     'quizq5a1' => 'Les pouvoirs ne peuvent pas être dupliqués. Vous ne transférez pas vos pouvoirs.',
     'quizq5a2' => 'Accepter son offre. Deux fois plus de pouvoirs pour deux fois plus de profit ǃ',
     'quizq5a3' => 'Demander la preuve qu’il peut doubler vos pouvoirs.',
     'quizq5info' => 'Bien joué ! Les xats, days et pouvoirs ne peuvent pas être dupliqués. Les escrocs utilisent souvent cette approche pour attirer facilement votre attention et vos pouvoirs. Signalez l’utilisateur en prenant des captures d’écran de son ID et de son message, puis ouvrez un ticket dans la rubrique Report Scam.',
     'quizq5image' => '<br img src="https://util.'.DOMAIN.'/wiki/images/3/35/Securityimage5.png" class="img-fluid"/>',
     'quizq6' => 'Vous recevez un e-mail de info@'.DOMAIN.' indiquant que vos pouvoirs doivent être examinés manuellement par un employé de '.XAT_NAME.'. L’instruction dit que vous devez échanger les pouvoirs dans le chat avec une personne spécifique. Si vous refusez de le faire, votre compte sera bloqué pendant 3 mois. Que faites-vous ?',
     'quizq6a1' => 'Ignorer et signaler l’e-mail en tant que spam.',
     'quizq6a2' => 'Accepter sans se poser de questions. Pas de blocage, S.V.P !',
     'quizq6a3' => 'Répondre à l’e-mail en demandant plus d’informations.',
     'quizq6info' => 'C’est juste ! Vous ne recevrez jamais d’e-mail de la sorte provenant de '.XAT_NAME.'. Toutes les notifications relatives à votre compte '.XAT_NAME.' sont traitées dans le système d’assistance sur <a href="https://'.DOMAIN.'/ticket" target="_blank">'.DOMAIN.'/ticket</a> et nulle part ailleurs.',
     'quizq6image' => '<br img src="https://util.'.DOMAIN.'/wiki/images/3/3b/Securityimage6.png" class="img-fluid"/>',
     'quizq7' => 'Tout le monde sait que les mots de passe sont difficiles à retenir. Donc, pour vous simplifier la vie, vous décidez d’utiliser le même mot de passe pour votre adresse e-mail et votre compte '.XAT_NAME.'. Est-ce sécurisé ?',
     'quizq7a1' => 'Non !',
     'quizq7a2' => 'Certainement oui. Ainsi, vous n’aurez jamais un problème d’oubli de votre mot de passe.',
     'quizq7info' => 'Vous avez raison ! La difficulté peut être récompensée. Utilisez toujours des mots de passe différents pour chacun de vos comptes en ligne afin d’augmenter votre protection.',
     'quizq7image' => '<br img src="https://util.'.DOMAIN.'/wiki/images/2/2b/Securityimage7.png" class="img-fluid"/>',
     'quizq8' => 'Vous apprenez qu’un programme générateur de xats gratuit peut être téléchargé. Que faites-vous ?',
     'quizq8a1' => 'Vous savez que les xats ne peuvent pas être générés, et donc vous l’ignorez.',
     'quizq8a2' => 'Demander plus d’informations.',
     'quizq8a3' => 'Demander une preuve que des xats peuvent être générés.',
     'quizq8info' => 'Vous avez raison ! Les xats ne peuvent pas être générés gratuitement ! Veillez à ne télécharger aucun programme inconnu car ils peuvent être malveillants et peuvent contenir des logiciels dangereux, tels que des virus.',
     'quizq8image' => '<br img src="https://util.'.DOMAIN.'/wiki/images/5/5c/Securityimage8.png" class="img-fluid"/>',
     'quizq9' => 'Vous recevez un message indiquant que votre compte sera bloqué dans les 24 heures à moins que vous ne payiez 10 000 xats. Que faites-vous ?',
     'quizq9a1' => 'Ne pas envoyez de xats et ignorer l’utilisateur.',
     'quizq9a2' => 'Blocage ? Hors de question ! Je paie l’amende.',
     'quizq9a3' => 'Demander une explication.',
     'quizq9info' => 'Correct ǃ Le personnel de '.XAT_NAME.' et les bénévoles ne demanderont jamais de xats. Signalez l’utilisateur en prenant des captures d’écran de son ID et de son message, puis ouvrez un ticket dans la rubrique Report Scam.',
     'quizq9image' => '<br img src="https://util.'.DOMAIN.'/wiki/images/b/b4/Securityimage9.png" class="img-fluid"/>',
     'quizq10' => 'On vous propose une somme attractive de xats pour vos pouvoirs, telle que 50 000 xats. Au cours de l’échange, plusieurs tentatives ont échoué en raison d’un mot de passe incorrect et d’autres erreurs. Que faites-vous ?',
     'quizq10a1' => 'Dire de manière respectueuse à l’utilisateur que vous allez redémarrer le trade.',
     'quizq10a2' => 'Ignorer le problème et continuer le trade.',
     'quizq10a3' => 'Ignorer l’utilisateur.',
     'quizq10info' => 'Correct ǃ Les escrocs essaieront de voler vos xats, vos days ou vos pouvoirs en modifiant la quantité de xats, de days ou de pouvoirs dans l’application.<br><br>Soyez toujours prudent et revérifiez tous les pouvoirs du trade après chaque tentative infructueuse. Faites toujours une vérification supplémentaire de tous les détails du trade avant de cliquer sur confirmer.',
     'quizq10image' => '<br img src="https://util.'.DOMAIN.'/wiki/images/a/a2/Securityimage10.png" class="img-fluid"/>',
     'quizq11' => 'Vous recevez un message privé sur le forum d’une personne prétendant être un employé de '.XAT_NAME.'. Le message vous demande les détails de votre compte (mots de passe et e-mail), autrement votre compte sera bloqué par '.XAT_NAME.'. Que faites-vous ?',
     'quizq11a1' => 'Ignorer l’utilisateur et le signaler au personnel du forum.',
     'quizq11a2' => 'Répondre au message en fournissant les informations demandées.',
     'quizq11a3' => 'Demander plus d’informations sur le blocage.',
     'quizq11info' => 'Correct ǃ Le personnel et les bénévoles de '.XAT_NAME.' ne vous contacteront jamais en privé au sujet de problèmes liés à votre compte '.XAT_NAME.', tels que le blocage. Tous les problèmes de compte sont gérés par le système de support à l’adresse <a href="https://'.DOMAIN.'/ticket" target="_blank">'.DOMAIN.'/ticket</a> et vous devriez signaler les messages privés inappropriés et malveillants.',
     'quizq11image' => '<br img src="https://util.'.DOMAIN.'/wiki/images/7/7a/Securityimage11.png" class="img-fluid"/>',
     'quizq12' => 'Un employé de '.XAT_NAME.' vous demande sur un chat de désactiver la protection par authentification à 2 facteurs de votre adresse électronique. Que faites-vous ?',
     'quizq12a1' => 'Refuser et les ignorer.',
     'quizq12a2' => 'Désactiver l’authentification à 2 facteurs.',
     'quizq12info' => 'Oui, vous avez raison ! Le personnel de '.XAT_NAME.' et les bénévoles ne vous demanderont jamais de désactiver la protection par authentification à 2 facteurs en aucune circonstance. N’hésitez pas à signaler les utilisateurs qui essaient de désactiver les protections de votre compte.',
     'quizq12image' => '<br img src="https://util.'.DOMAIN.'/wiki/images/4/45/Securityimage12.png" class="img-fluid"/>',
     'quizq13' => 'On vous parle d’une page de générateur de xats gratuits sur un site web. Mais pour générer des xats gratuits, vous devez entrer votre mot de passe et votre adresse e-mail. Que faites-vous ?',
     'quizq13a1' => 'Ignorer le site web car vous savez que les xats ne peuvent pas être générés gratuitement.',
     'quizq13a2' => 'Poursuivre et vous connecter.',
     'quizq13a3' => 'Demander une preuve que des xats peuvent être générés.',
     'quizq13info' => 'Vous avez raison ! Les xats ne peuvent pas être générés gratuitement. De plus, n’entrez votre mot de passe '.XAT_NAME.' que sur les pages officielles <a href="https://'.DOMAIN.'" target="_blank">https://'.DOMAIN.'</a>. Vérifiez toujours la barre d’adresse pour vous assurer que vous êtes bien sur <a href="https://'.DOMAIN.'" target="_blank">'.DOMAIN.'</a>.',
     'quizq13image' => '<br img src="https://util.'.DOMAIN.'/wiki/images/5/57/Securityimage13.png" class="img-fluid"/>',
     'quizq14' => 'Vous avez négocié un marché pour acheter des pouvoirs à un utilisateur sur le chat Trade. L’utilisateur déclare qu’il échangera la moitié des pouvoirs maintenant et le reste plus tard. Que faites-vous ?',
     'quizq14a1' => 'Refuser l’offre. Il devrait ajouter tous les objets maintenant.',
     'quizq14a2' => 'Accepter l’offre. Il ne peut rien arriver.',
     'quizq14a3' => 'Lui demander la preuve qu’il possède les pouvoirs restants.',
     'quizq14info' => 'Correct ǃ Les escrocs peuvent tenter d’échelonner les échanges en offrant un montant immédiat et en promettant de payer le reste à l’avenir. Ne croyez jamais ces utilisateurs et n’acceptez que le montant convenu en un seul échange. Il est peu probable que l’utilisateur revienne par la suite.',
     'quizq14image' => '<br img src="https://util.'.DOMAIN.'/wiki/images/5/59/Securityimage14.png" class="img-fluid"/>',
     'quizq15' => 'On vous parle d’un programme gratuit qui crée des avatars animés (des gifs). Une personne sur un chat vous envoie un lien de téléchargement pour le programme qui se trouve sur un site web inconnu. Que faites-vous ?',
     'quizq15a1' => 'Ne jamais télécharger des fichiers inconnus car ils peuvent contenir des virus.',
     'quizq15a2' => 'Télécharger aveuglément.',
     'quizq15info' => 'Correct ǃ Les escrocs vous inciteront à télécharger leurs virus en se faisant passer pour un ami serviable. Soyez prudent à ne pas télécharger des fichiers inconnus. Quelques conseils pour éviter de télécharger des éléments malveillants sont les suivants :<br><br ol><li>Chercher le nom du fichier sur Google (la crédibilité du programme et son existence même).</li><li>Vérifiez des sources alternatives pour le téléchargement.</li><li>Analyser le fichier avec un antivirus.</li></ol>',
     'quizq15image' => '<br img src="https://util.'.DOMAIN.'/wiki/images/1/19/Securityimage15.png" class="img-fluid"/>',
     'quizq16' => 'Une personne rencontrée sur un chat vous demande vos informations personnelles telles que votre nom, votre adresse postale et votre adresse e-mail. Que faites-vous ?',
     'quizq16a1' => 'Changer de sujet en disant que vous ne voulez pas parler de vos informations personnelles.',
     'quizq16a2' => 'Elle semble assez sympa et donc vous répondez à ses questions en lui donnant vos vraies informations.',
     'quizq16a3' => 'Ignorer l’utilisateur.',
     'quizq16info' => 'Bien joué ! Vous ne devriez pas partager vos informations personnelles avec qui que ce soit en ligne. Ne partager jamais votre adresse e-mail ou votre mot de passe !',
     'quizq16image' => '<br img src="https://util.'.DOMAIN.'/wiki/images/d/d9/Securityimage16.png" class="img-fluid"/>',
     'quizq17' => 'Quelqu’un sur un chat vous signale que votre compte a un problème et que vous devez désactiver la protection de votre compte lors de votre prochaine connexion pour le régler. Que faites-vous ?',
     'quizq17a1' => 'Ne jamais désactiver les protections de votre compte parce qu’on vous le demande.',
     'quizq17a2' => 'Vous faites confiance au premier venu. Vous vous connectez pour désactiver les protections.',
     'quizq17a3' => 'Vous leur demandez plus d’information avant de décider.',
     'quizq17info' => 'Correct ǃ Il n’y aucune raison de désactiver vos protections de compte, dans aucune circonstance. Les employés de '.XAT_NAME.' et les bénévoles ne vous demanderont jamais de désactiver ces protections.',
     'quizq17image' => '<br img src="https://util.'.DOMAIN.'/wiki/images/a/ab/Securityimage17.png" class="img-fluid"/>',
     'quizq18' => 'Un de vos amis vous demande s’il peut emprunter votre pouvoir namecolor un petit moment, pour en tester les effets. Que faites-vous ?',
     'quizq18a1' => 'Ne pas le donner. Il est possible qu’il ne vous le rende jamais.',
     'quizq18a2' => 'C’est bon pour cette fois. Il peut vous le rendre à tout moment.',
     'quizq18a3' => 'Meilleurs amis pour la vie ǃ Vous cliquez sur trade et foncez ǃ',
     'quizq18info' => 'C’est juste ! Vos xats, days et pouvoirs relèvent de votre entière responsabilité. La notion de prêt n’existe pas sur '.XAT_NAME.' et cela sera vu comme si vous donniez vos pouvoirs de façon définitive. Si vous acceptez un échange ou un transfert, vous ne pourrez pas l’annuler. Faites très attention. <a href="//util.'.DOMAIN.'/wiki/index.php?title=Special:MyLanguage/Trading" target="_blank">Lisez-en plus ici.</a>',
     'quizq18image' => '<br img src="https://util.'.DOMAIN.'/wiki/images/1/17/Securityimage18.png" class="img-fluid"/>',
     'quizq19' => 'Vous recevez un e-mail de la part de info@'.DOMAIN.' indiquant que vous venez d’acheter avec succès 100000 xats. Il indique également que vous devez confirmer le paiement en cliquant sur un lien. Le lien vous redirige vers une page où vous devez payer 100$ pour enfin recevoir les xats. Que faites-vous ?',
     'quizq19a1' => 'C’est une offre étrange. Si j’ai acheté les xats avec succès, pourquoi dois-je payer plus ? Vous bloquez l’e-mail étant donné que c’est une arnaque.',
     'quizq19a2' => 'L’e-mail provient de la part de info@'.DOMAIN.' mais 100$, c’est beaucoup d’argent. Répondre et demander plus d’informations.',
     'quizq19a3' => 'Je n’avais pas l’intention d’acheter de xats, mais 100000 xats pour 100$ est une bonne affaire. Foncer !',
     'quizq19info' => 'Correct ! '.XAT_NAME.' ne vous demandera JAMAIS d’acheter des xats par e-mail, et le seul endroit sécurisé où vous pouvez acheter des xats pour de l’argent réel est <a href="https://'.DOMAIN.'/buy">https://'.DOMAIN.'/buy</a>. Certains escrocs sont capables de falsifier les adresses électroniques de '.XAT_NAME.', vous ne devez donc jamais continuer, même si cela affiche info@'.DOMAIN.'. Toutefois, si l’accord semble trop beau pour être vrai, ça l’est généralement et vous risquez très probablement d’être victime d’une arnaque.',
     'quizq19image' => '<br img src="https://util.'.DOMAIN.'/wiki/images/f/fe/Securityimage19.png" class="img-fluid"/>',
     'start' => 'démarrer le quiz',
     'desc' => 'Pour obtenir le pouvoir <a href="//util.'.DOMAIN.'/wiki/index.php?title=Special:MyLanguage/Tickle" target="_blank">Tickle</a> gratuitement, vous devez compléter le quiz ci-dessous et répondre à toutes les questions correctement.',
     'wronganswer' => 'C’est incorrect, recommencez.',
     'next' => 'suivant',
     'continuein' => 'Continuer',
     'gratz' => 'Félicitations, vous avez fini le quiz ǃ Vous devriez maintenant en savoir plus sur la sécurité sur '.XAT_NAME.'.',
     'tickle' => 'Vous avez reçu le pouvoir Tickle.',
     'redirect' => 'Nous vous prions de patienter avant d’être redirigés vers la page de connexion.'
	]
?>