<?php


$array = [
     'login' => 'Iniciar Sesión',
     'cancel' => 'Cancelar',
     'logout' => 'Cerrar Sesión',
     'done' => 'Hecho',
     'edit' => 'Editar',
     'searchgroup' => 'Buscar un Grupo',
     'addsmilie' => 'Añadir Smiley',
     'backchats' => '❮ Chats',
     'backmessages' => '❮ Mensajes',
     'backback' => '❮ Atrás',
     'pchats' => 'Chat Privado',
     'search' => 'Buscar',
     'me' => 'Me',
     'actions' => 'Acciones',
     'visitors' => 'Visitantes',
     'groups' => 'Grupos',
     'chats' => 'Chats',
     'friends' => 'Amigos',
     'profile' => 'Perfíl',
     'powers' => 'Powers',
     'favorites' => 'Favoritos',
     'featured' => 'Destacados',
     'popular' => 'Populares',
     'new' => 'Nuevo',
     'standard' => 'Estándar',
     'rare' => 'Raro',
     'epic' => 'Épico',
     'settings' => 'ajustes',
     'help' => 'Ayuda',
     'more' => 'Más',
     'message' => 'Mensaje',
     'close' => 'Cerrar',
     'xats' => ''. XAT_NAME .'s',
     'days' => 'days',
     'store' => 'Tienda',
     'justnow' => 'ahora',
     'minsago' => 'Hace $1 minutos',
     'hoursago' => 'Hace $1 horas',
     'daysago' => 'Hace $1 días',
     'buyxats' => 'Comprar '. XAT_NAME .'s',
     'back' => 'Atrás',
     'minago' => 'Hace $1 minuto',
     'hourago' => 'Hace $1 hora',
     'dayago' => 'Hace $1 día',
     'supported' => 'Soportados'
	 ]
?>