<?php


$array = [
     'quizq1' => 'Recibes un mensaje de una persona que dice ser un voluntario. Ésta persona dice que tu cuenta está bloqueada y para resolver el problema, debes de darle tu contraseña y la dirección de email, o tu cuenta se mantendrá bloqueada. ¿Qué haces?',
     'quizq1a1' => 'No les des nada de información.',
     'quizq1a2' => 'Tu no quieres perder tu cuenta de '. XAT_NAME .', entonces tú les das la información.',
     'quizq1a3' => 'Pide una prueba de que ellos son los verdaderos voluntarios.',
     'quizq1info' => '¡Correcto! Los staff de '. XAT_NAME .' y los voluntarios nunca le pedirán información personal en un chat privado. Reporta el usuario tomando capturas de su ID y el mensaje, abre un ticket bajo el departamento Report Scam.',
     'quizq1image' => '<br img src="https://util.'. DOMAIN .'/wiki/images/f/f9/Securityimage1.png" class="img-fluid"/>',
     'quizq2' => 'Estás en el chat de Trade intentando comprar days. Eres contactado por una persona quien le pide transferir primero tus '. XAT_NAME .'s. ¿Qué haces?',
     'quizq2a1' => 'Rechace y sugiera usar la aplicación Safe Trade, que es el método recomendado.',
     'quizq2a2' => 'Transfiera tus '. XAT_NAME .'s primero.',
     'quizq2a3' => 'Pregúntales primero por sus días, en su lugar.',
     'quizq2info' => '¡Eso es correcto! Mientras compra y vende '. XAT_NAME .'s, days o powers, deberías de usar siempre la aplicación de comercio seguro (Safe Trade app). A través de ésta aplicación, puedes ver en tiempo real lo que se está negociando. Nunca realice transacciones con la función Transfer, ya que las transacciones no se pueden deshacer una vez ya completadas.',
     'quizq2image' => '<br img src="https://util.'. DOMAIN .'/wiki/images/c/c0/Securityimage2.png" class="img-fluid"/>',
     'quizq3' => 'Tu proveedor de correo electrónico ofrece protección de autenticación de 2 factores. ¿Debería de habilitar ésta opción?',
     'quizq3a1' => 'Sí. Ésto aumentará la seguridad de la dirección de correo electrónico.',
     'quizq3a2' => 'No. Mi contraseña es lo suficientemente fuerte.',
     'quizq3a3' => 'Nunca. Esta protección no es útil.',
     'quizq3info' => '¡Correcto! La autenticación de 2factores en su dirección de correo electrónico agregará una capa adicional de seguridad (por teléfono) para garantizar que nadie más que tú, pueda acceder a tu correo electrónico, incluso si tu contraseña ha sido hackeada.<br><br>Por favor, póngase en contacto con su proveedor de su correo electrónico para obtener instrucciones sobre cómo habilitar la autenticación para la cuenta de su correo electrónico. Para las cuentas de Gmail, por favor, mirar <a href="https://www.google.com/landing/2step/" target="_blank">ésta página</a>.',
     'quizq3image' => '<br img src="https://util.'. DOMAIN .'/wiki/images/7/71/Securityimage3.png" class="img-fluid"/>',
     'quizq4' => 'Se le informa sobre una actualización en la página de inicio de sesión de '. XAT_NAME .'. El usuario le envía el enlace para la prueba, que es https://xaatt.com/login. ¿Qué haces?',
     'quizq4a1' => 'No haga clic en ese enlace ya que no es el dominio https://'. DOMAIN .'',
     'quizq4a2' => 'Haga clic en él para ver qué ha cambiado.',
     'quizq4info' => '¡Correcto! Siempre revise la barra del navegador para asegurarse de que está en el dominio de <a href="https://'. DOMAIN .'" target="_blank">https://'. DOMAIN .'</a> antes de iniciar sesión, visitar un chat o ingresar a cualquier información de tu '. XAT_NAME .'.',
     'quizq4image' => '<br img src="https://util.'. DOMAIN .'/wiki/images/7/7d/Securityimage4.png" class="img-fluid"/>',
     'quizq5' => 'Un usuario te ofrece duplicar tus poderes, pero primero debes de hacer trade con el para pasarle los powers. ¿Qué haces?',
     'quizq5a1' => 'Los powers no pueden ser duplicados. No transfieres tus powers.',
     'quizq5a2' => 'Acepta su oferta. Los powers duplicados significan el doble de beneficio.',
     'quizq5a3' => 'Pida una prueba de que pueden duplicar tus items.',
     'quizq5info' => '¡Bien hecho! Los '. XAT_NAME .'s, days y powers no pueden ser duplicados. Los estafadores a menudo utilizan este enfoque para llamar tu atención y tus items con facilidad. Reporta el usuario tomando capturas de su ID y el mensaje, abre un ticket bajo el departamento Report Scam.',
     'quizq5image' => '<br img src="https://util.'. DOMAIN .'/wiki/images/3/35/Securityimage5.png" class="img-fluid"/>',
     'quizq6' => 'Recibes un email de info@'. DOMAIN .' diciendo que tus powers deben ser revisados por un empleado de '. XAT_NAME .'. La instrucción dice que debes intercambiar los powers en el chat con una persona específica. Si se niega a hacerlo, su cuenta será bloqueada por 3 meses. ¿Qué haces?',
     'quizq6a1' => 'Ignorar y reportar el correo electrónico como spam.',
     'quizq6a2' => 'Aceptar sin más preguntas. ¡Bloqueo no, por favor!',
     'quizq6a3' => 'Conteste al email pidiendo más información.',
     'quizq6info' => '¡Eso es correcto! Nunca recibirás un correo electrónico como éste desde '. XAT_NAME .'. Todas las notificaciones relacionadas con su cuenta '. XAT_NAME .' se manejan en el sistema de soporte en <a href="https://'. DOMAIN .'/ticket" target="_blank">'. DOMAIN .'/ticket</a> y no en ninguna otra parte más.',
     'quizq6image' => '<br img src="https://util.'. DOMAIN .'/wiki/images/3/3b/Securityimage6.png" class="img-fluid"/>',
     'quizq7' => 'Todo el mundo sabe qué, esas contraseñas son muy difíciles de recordar. Entonces para hacer tu vida más fácil, decide utilizar la misma contraseña para su dirección de correo electrónico y su cuenta '. XAT_NAME .'. ¿Ésto es seguro?',
     'quizq7a1' => '¡No!',
     'quizq7a2' => 'Definitivamente sí. Así que nunca tendrás el problema de olvidar tu contraseña.',
     'quizq7info' => '¡Lo tienes bien! La dificultad puede ser recompensada. Siempre use contraseñas diferentes para cada una de tus cuentas activas, para incrementar la protección.',
     'quizq7image' => '<br img src="https://util.'. DOMAIN .'/wiki/images/2/2b/Securityimage7.png" class="img-fluid"/>',
     'quizq8' => 'Aprendes sobre un programa generador de '. XAT_NAME .'s gratuito que necesita ser descargado. ¿Qué haces?',
     'quizq8a1' => 'Sabes que los '. XAT_NAME .'s no pueden ser generados, e ignora esto.',
     'quizq8a2' => 'Pida más información.',
     'quizq8a3' => 'Pida una prueba para ver si los '. XAT_NAME .'s pueden ser generados.',
     'quizq8info' => '¡Tienes razón! ¡Los '. XAT_NAME .'s no pueden ser generados de forma gratuita! Ten cuidado de no descargar ningún programa desconocido, ya que puede ser malicioso y puede contener algún software dañino (virus).',
     'quizq8image' => '<br img src="https://util.'. DOMAIN .'/wiki/images/5/5c/Securityimage8.png" class="img-fluid"/>',
     'quizq9' => 'Recibió un mensaje diciendo que su cuenta estará bloqueada dentro de 24 horas al menos que usted pague 10000 '. XAT_NAME .'s. ¿Qué haces?',
     'quizq9a1' => 'No envíe '. XAT_NAME .'s e ignore al usuario.',
     'quizq9a2' => '¿Bloqueado? ¡Ni hablar! Yo pago la multa.',
     'quizq9a3' => 'Pida una explicación.',
     'quizq9info' => '¡Correcto! Los staff de '. XAT_NAME .' y los voluntarios, nunca pedirán '. XAT_NAME .'s. Reporta el usuario tomando capturas de su ID y el mensaje, abre un ticket bajo el departamento Report Scam.',
     'quizq9image' => '<br img src="https://util.'. DOMAIN .'/wiki/images/b/b4/Securityimage9.png" class="img-fluid"/>',
     'quizq10' => 'Se le ofrece una cantidad costosa de '. XAT_NAME .'s para sus powers, como 50000 '. XAT_NAME .'s. Durante el trade, hay varios intentos fallidos debido a que la contraseña es incorrecta y otros errores. ¿Qué haces?',
     'quizq10a1' => 'Respetuosamente diga al usuario que reiniciará el trade.',
     'quizq10a2' => 'Ignorar el problema y continuar con el trade.',
     'quizq10a3' => 'Ignorar el usuario.',
     'quizq10info' => '¡Correcto! Los estafadores intentarán robar sus '. XAT_NAME .'s, days o powers cambiando la cantidad de '. XAT_NAME .'s, days o powers en la aplicación.<br><br>Siempre tenga cuidado y compruebe dos veces todos los powers del trade, después de cada intento fallido. Tómate otro tiempo extra para volver a comprobar todos los detalles del trade antes de hacer click en confirmar.',
     'quizq10image' => '<br img src="https://util.'. DOMAIN .'/wiki/images/a/a2/Securityimage10.png" class="img-fluid"/>',
     'quizq11' => 'Recibes un mensaje privado del foro de una persona que dice ser un trabajador de '. XAT_NAME .'. El mensaje pide los detalles de su cuenta (contraseñas y correo electrónico), de lo contrario, su cuenta quedará bloqueada por '. XAT_NAME .'. ¿Qué haces?',
     'quizq11a1' => 'Ignora al usuario y repórtelo al staff del foro.',
     'quizq11a2' => 'Responda el mensaje proporcionando la información solicitada.',
     'quizq11a3' => 'Pida más información sobre el bloqueo.',
     'quizq11info' => '¡Correcto! Los staff de '. XAT_NAME .' y los voluntarios, nunca se comunicarán con usted de manera privada sobre temas relacionados con la cuenta de '. XAT_NAME .', como bloqueos. Todos los problemas de la cuenta se maneja en el sistema de soorte en <a href="https://'. DOMAIN .'/ticket" target="_blank">'. DOMAIN .'/ticket</a> y tú deberías de reportar los mensajes inapropiados y maliciosos.',
     'quizq11image' => '<br img src="https://util.'. DOMAIN .'/wiki/images/7/7a/Securityimage11.png" class="img-fluid"/>',
     'quizq12' => 'Un empleado de '. XAT_NAME .' le indica en un chat que deshabilite la protección de autenticación de 2factores de su dirección de correo electrónico. ¿Qué haces?',
     'quizq12a1' => 'Denegar e ignorar.',
     'quizq12a2' => 'Deshabilita la autenticación de 2factores.',
     'quizq12info' => '¡Sí, tienes razón! Los staff de '. XAT_NAME .' y los voluntarios, nunca le pedirán que deshabilite la protección de autenticación de 2factores bajo ninguna circunstancia. No dude en reportar a los usuarios que intentan deshabilitar las protecciones de su cuenta.',
     'quizq12image' => '<br img src="https://util.'. DOMAIN .'/wiki/images/4/45/Securityimage12.png" class="img-fluid"/>',
     'quizq13' => 'Te dicen de una página de un generador de '. XAT_NAME .'s gratis en un sitio web. Pero para generar '. XAT_NAME .'s gratis, debes ingresar tú contraseña y tú dirección de correo electrónico. ¿Qué haces?',
     'quizq13a1' => 'Ignorar el sitio web porque como ya sabe, los '. XAT_NAME .'s no se pueden generar de forma gratuita.',
     'quizq13a2' => 'Proceder e iniciar sesión.',
     'quizq13a3' => 'Pida una prueba para ver si los '. XAT_NAME .'s pueden ser generados.',
     'quizq13info' => '¡Tienes razón! Los '. XAT_NAME .'s no pueden ser generados de forma gratuita. Además, sólo ingrese con su contraseña de '. XAT_NAME .' en las páginas oficiales de <a href="https://'. DOMAIN .'" target="_blank">https://'. DOMAIN .'</a>. Siempre verifique la barra del navegador para asegurarse de que usted está en <a href="https://'. DOMAIN .'" target="_blank">'. DOMAIN .'</a>.',
     'quizq13image' => '<br img src="https://util.'. DOMAIN .'/wiki/images/5/57/Securityimage13.png" class="img-fluid"/>',
     'quizq14' => 'Has negociado un acuerdo para comprar powers de un usuario en el chat de Trade. El usuario declara que comercializará (trade) la mitad de los powers ahora y el resto más tarde. ¿Qué haces?',
     'quizq14a1' => 'Rechazarla oferta - ellos deberían de añadir todos los items ahora.',
     'quizq14a2' => 'Aceptar la oferta. Nada puede salir mal.',
     'quizq14a3' => 'Pida una prueba de que tienen los powers restantes.',
     'quizq14info' => '¡Correcto! Los estafadores pueden hacer dudas en los Trades ofreciendo una cantidad por adelantado y prometiendo pagar el resto en el futuro. Nunca crea en éstos usuarios y sólo acepte la cantidad acordada en un trade completo. Es poco probable que el usuario vuelva después.',
     'quizq14image' => '<br img src="https://util.'. DOMAIN .'/wiki/images/5/59/Securityimage14.png" class="img-fluid"/>',
     'quizq15' => 'Te hablan sobre un programa gratuito que hace avatares animados (gifs). Una persona en un chat le envía un enlace de descarga para el programa que está en un sitio web desconocido. ¿Qué haces?',
     'quizq15a1' => 'Nunca descargar archivos desconocidos, ya que, pueden contenter virus.',
     'quizq15a2' => 'Descargarlo a ciegas.',
     'quizq15info' => '¡Correcto! Los estafadores le tentarán a descargar sus virus, haciéndose pasar por un amigo servicial. Ten cuidado, no descarges archivos que desconocidos. Algunos consejos para evitar descargar cosas maliciosas son:<br><br ol><li>Busca el nombre del archivo en Google (credibilidad del programa y si existe).</li><li>Compruebe fuentes alternativas para descargar.</li><li>Ejecuta un análisis de virus sobre el archivo.</li></ol>',
     'quizq15image' => '<br img src="https://util.'. DOMAIN .'/wiki/images/1/19/Securityimage15.png" class="img-fluid"/>',
     'quizq16' => 'Una persona que conoció en un chat le pide su información personal, tal y cómo su nombre, la dirección de dónde vive y el correo electrónico. ¿Qué haces?',
     'quizq16a1' => 'Cambie de tema diciendo que no deseas hablar sobre tu información personal.',
     'quizq16a2' => 'Parecen ser lo suficientemente interesantes como para que respondas sus preguntas con tu información real.',
     'quizq16a3' => 'Ignorar el usuario.',
     'quizq16info' => '¡Bien hecho! No debe compartir su información personal con nadie conectado. ¡Nunca compartas tu dirección de correo electrónico ni tú contraseña!',
     'quizq16image' => '<br img src="https://util.'. DOMAIN .'/wiki/images/d/d9/Securityimage16.png" class="img-fluid"/>',
     'quizq17' => 'Se le notificó en un chat que su cuenta '. XAT_NAME .' tiene un problema y para solucionarlo, debe de desactivar la protección de la cuenta en la página de inicio de sesión de '. XAT_NAME .'. ¿Qué haces?',
     'quizq17a1' => 'Nunca desactive las protecciones de su cuenta de '. XAT_NAME .' cuando se lo digan.',
     'quizq17a2' => 'Confiarás en ningún extraño. Inicia sesión para desactivar las protecciones.',
     'quizq17a3' => 'Pídales más información antes de considerar su solicitud.',
     'quizq17info' => '¡Correcto! Las protecciones de su cuenta de '. XAT_NAME .' no deben de desactivarse bajo ninguna circunstancia. Los empleados y voluntarios de '. XAT_NAME .', nunca le pedirán que desactives las protecciones.',
     'quizq17image' => '<br img src="https://util.'. DOMAIN .'/wiki/images/a/ab/Securityimage17.png" class="img-fluid"/>',
     'quizq18' => 'Un amigo tuyo pregunta si pueden tomar prestado tu power namecolor durante algún tiempo, ya que quieren probar sus efectos. ¿Qué haces?',
     'quizq18a1' => 'No los des. Existe la posibilidad de que no lo recuperes.',
     'quizq18a2' => 'Está bien darlo. Puedes recuperar tus powers en cualquier momento.',
     'quizq18a3' => 'Mejores amigos para siempre. Tu click trade, ¡no hay dudas!',
     'quizq18info' => '¡Eso es correcto! Tus '. XAT_NAME .'s, days y powers son tú responsabilidad. Los préstamos no existen en '. XAT_NAME .', y será visto que tu diste tus items. Si completas un trade o una transferencia, no se podrá deshacer. Ten mucho cuidado todo el tiempo. <a href="//util.'. DOMAIN .'/wiki/index.php?title=Special:MyLanguage/Trading" target="_blank">Lee más aquí.</a>',
     'quizq18image' => '<br img src="https://util.'. DOMAIN .'/wiki/images/1/17/Securityimage18.png" class="img-fluid"/>',
     'quizq19' => 'Recibirá un correo electrónico de info@'. DOMAIN .' indicando que acaba de comprar con éxito 100000 '. XAT_NAME .'s. También indica que necesita confirmar el pago haciendo clic en un enlace. El enlace le redirecciona a una página dónde debe de pagar $100 para recibir finalmente los '. XAT_NAME .'s. ¿Qué haces?',
     'quizq19a1' => 'Esta es una oferta extraña. Si compré '. XAT_NAME .'s satisfactoriamente, ¿por qué debo de pagar más? Bloqueas el correo electrónico ya que ésto es una estafa.',
     'quizq19a2' => 'El correo electrónico viene de info@'. DOMAIN .' pero $100 es mucho dinero. Contestar y pedir más información.',
     'quizq19a3' => 'No planeaba comprar '. XAT_NAME .'s, pero 100000 '. XAT_NAME .'s por $100 es una buena oferta. ¡Ir a por ello!',
     'quizq19info' => '¡Correcto! '. XAT_NAME .' NUNCA le pedirá que compre '. XAT_NAME .'s en un email, y el único lugar seguro donde puedes comprar '. XAT_NAME .'s por dinero real es en <a href="https://'. DOMAIN .'/buy">https://'. DOMAIN .'/buy</a>. Algunos estafadores pueden falsificar la dirección de correo electrónico de '. XAT_NAME .', por lo que nunca debe continuar, incluso si muestra info@'. DOMAIN .'. No obstante, si el trato parece demasiado bueno para ser verdad, usualmente lo es y es muy probable que te estén estafando.',
     'quizq19image' => '<br img src="https://util.'. DOMAIN .'/wiki/images/f/fe/Securityimage19.png" class="img-fluid"/>',
     'start' => 'empezar quiz',
     'desc' => 'Para obtener el power <a href="//util.'. DOMAIN .'/wiki/index.php?title=Special:MyLanguage/Tickle" target="_blank">Tickle</a> gratuitamente, necesitarás completar el quiz de debajo, y contestar cada una de las preguntas correctamente.',
     'wronganswer' => 'Ésto es incorrecto. Por favor, inténtelo de nuevo.',
     'next' => 'siguiente',
     'continuein' => 'Continuar en',
     'gratz' => '¡Felicidades, has completado el quiz! Ahora deberías de tener más conocimiento sobre la seguridad en '. XAT_NAME .'.',
     'tickle' => 'Has recibido el power tickle.',
     'redirect' => 'Por favor, espere mientras se le redirige a la página de inicio de sesión.'
	 ]
?>