<?php


$array = [
     'editpro' => 'Edit your profile',
     'problkd' => 'Profile is blocked.',
     'uploadsearch' => 'Upload or search for image',
     'aboutbkg' => 'About Background - optional (URL):',
     'urlcss' => 'Optional (URL or background CSS)',
     'album' => 'Enter an address of a picture from a <a href="http://photobucket.com">Photobucket</a> album',
     'color' => 'Color',
     'width' => 'Width',
     'outline' => 'About outline',
     'colinfo' => 'Color or hex code, e.g. #FF00FF',
     'albopt' => 'Picture album - optional',
     'wysiwyg' => 'Check this box to use WYSIWYG editing',
     'imagesmust' => 'Note: Images must be on <a target="_blank" href="http://tinypic.com">Tinypic</a>, <a target="_blank" href="http://photobucket.com">Photobucket</a> or <a target="_blank" href="http://imageshack.us">Imageshack</a> see <a href="//util.'. DOMAIN .'/wiki/index.php?title=Images">wiki</a>',
     'enterstuff' => 'Enter stuff for the ’About me’ section of your profile (simple HTML is allowed)',
     'mediastuff' => 'Enter stuff for the media box of your profile (simple HTML and embeds are allowed)',
     'savechanges' => 'Save changes',
     'mins10' => 'View changes. Changes may take up to 10 mins to go live',
     'viewchanges' => 'View changes',
     'editgrp' => 'Edit chat group',
     'addstuff' => 'Add <a href="https://www.youtube.com">videos</a>, <a href="//util.'. DOMAIN .'/wiki/index.php?title=Playlist">music</a> etc. to your group pages here. Just paste the code or write HTML in the media box below',
     'background' => 'Background:',
     'backup' => 'Backup web pages',
     'caseonly' => '(you can change case only)',
     'chatsettings' => 'Chat Box Settings',
     'clkedit' => 'Click to edit',
     'coable' => 'Co-owner Abilities',
     'codel' => 'Check this box to allow co-owners to delete comments',
     'emailno' => 'Email does not match.',
     'file' => 'File to restore from',
     'grpinvalid' => 'Invalid group.',
     'grpnotfound' => 'Group not found.',
     'grptrans' => 'Check this box to make the chat box transparent when on '. XAT_NAME .'group page',
     'inccom' => 'Check this box to include member Comments',
     'labels' => 'Page labels:',
     'mainlang' => 'The main chat language',
     'memcom' => 'Member Comments',
     'misconfigured' => 'Group misconfigured. Please contact '. DOMAIN .'',
     'nottab1' => '$s (Sorry, no longer allowed on first tab)',
     'optional' => '(Optional)',
     'passupd' => 'Password updated.',
     'player2' => 'Start Player',
     'player' => 'Check this box to start the video player when the group page opens',
     'resetinfo' => 'If you have lost control of your group or you want to start again, you can reset the chat box here. IMPORTANT: All owners, moderators and members will cease and you will have to make moderators etc. again. You will automatically be taken to a page that will make you owner again.',
     'reset' => 'Reset chat box',
     'restore' => 'Restore',
     'timedout' => 'Timed out. Please start over.',
     'trans2' => 'Transparent',
     'yourpage' => 'Your page:',
     'foryour' => 'Make a chat room for your web page',
     'nocol' => 'Can’t find color',
     'orclick' => 'or click a picture below to change the background',
     'boxsize' => 'Chat box size:',
     'updprv' => 'Click here to update your settings and preview the chat:',
     'getcode' => 'Update  Get Code',
     'copied' => 'Code now copied to your clipboard. Now paste it into your web page (Ctrl-V)',
     'makegrp' => 'Make this chat box a group',
     'intogrp' => 'Click this button to turn this <br /> chat into a chat group',
     'otherop' => 'Other options',
     'nolist' => 'Don’t include this chat box on any lists or charts.',
     'monlyhint' => 'Note: You can only make members when you or a moderator is online (consider starting with this turned off).',
     'monly' => 'Make this chat for members only.',
     'livemodehint' => 'Not recommended for most chats.',
     'livemode' => 'Live mode: thousands can watch the chat as spectators.',
     'regonlyhint' => 'This will keep unregistered users out unless you member them.',
     'regonly' => 'Make this chat for registered users and members only.',
     'subonlyhint' => 'This will keep non-subscribers out unless you member them.',
     'subonly' => 'Make this chat for subscribers and members only.',
     'nostorehint' => 'If you check this, the chat box won’t remember any messages ever.',
     'nostore' => 'Don’t store chat messages.',
     'fussybanhint' => 'Try to stop unbanning (note: may ban innocent people).',
     'fussyban' => 'Stricter banning.',
     'nosmline' => 'Don’t display the line of Smilies.',
     'sndoff' => 'Default chat box sounds to OFF.',
     'transb' => 'Transparent background (no background image)<span class="style1"> - May require copy/paste embed code change.</span>',
     'deflang' => 'Default language for chat box:',
     'butcol' => 'Button color:',
     'radstat' => 'Radio station:',
     'radiowiki' => 'See <a href="//util.'. DOMAIN .'/wiki/index.php?title=Radio">wiki</a> for example radio stations.',
     'grppow' => 'Group Powers',
     'direct' => 'Direct link - access your chat box without a website',
     'access' => 'To access your chat box directly:',
     'later' => 'To edit your chat box later:',
     'editmy' => 'Edit my '. XAT_NAME .'chat',
     'addfav' => 'Add to Favorites',
     'example' => 'Example',
     'preview' => 'Preview',
     'getcode2' => 'Click ’Update  Get Code’ to preview your chat and to make owner',
     'orcopy' => 'or copy the code below to your page',
     'codechg' => 'Requires copy/paste embed code change',
     'morepics' => 'Click for more or use your own',
     'getpwr' => 'Get Power',
     'assigned' => 'Assigned by',
     'iseasy' => 'Making a '. XAT_NAME .'chat box is easy and completely free. Just choose a background and size, press the Update button and copy and paste the code from the box below into your web page or blog.',
     'morecontrol' => 'For more control and security, please make a <a href="//'. DOMAIN .'/web_gear/chat/creategroup.php">chat group</a>',
     'small' => 'Small',
     'medium' => 'Medium',
     'large' => 'Large',
     'orwid' => 'or Width',
     'height' => 'Height',
     'edit' => 'Edit',
     'updopt' => 'Update these options',
     'canreturn' => 'You can $array = to this page to edit your chat box even after it is on your web site by using the link above. Alternatively, in the chat box you can click the <strong>Edit Your Chat Box</strong> button followed by the <strong>Advanced...</strong> button',
     'extra' => 'Extra Chat Box Features',
     'egred' => 'E.g. #808000 or Red, Blue etc.',
     'passnok' => 'New password not valid! (must be 6 or more letters)',
     'passnoxt' => 'New password not valid! (must not start with XT)',
     'emailnok' => 'Email not valid!',
     'notodo' => 'Nothing to do!',
     'chgpass' => 'Change your password',
     'oldpass' => 'Old password:',
     'passagain' => 'Password again:',
     'livedocs' => 'Full documentation. Please read before setting Live mode',
     'chgyourback' => 'Change your Background Image',
     'searchweb' => 'Search the web for a background image',
     'selectback' => 'Select a default background image',
     'searchterm' => 'Enter a search term or URL here and press the button. (e.g. cat, dog)',
     'getimg' => 'Get Images',
     'clkback' => 'Click on a Background Image Below'
	 ]
?>