<?php


$array = [
     'login' => 'Login',
     'cancel' => 'Cancel',
     'logout' => 'Logout',
     'done' => 'Done',
     'edit' => 'Edit',
     'searchgroup' => 'Search for a Group',
     'addsmilie' => 'Add Smiley',
     'backchats' => '❮ Chats',
     'backmessages' => '❮ Messages',
     'backback' => '❮ Back',
     'pchats' => 'Private Chats',
     'search' => 'Search',
     'me' => 'Me',
     'actions' => 'Actions',
     'visitors' => 'Visitors',
     'groups' => 'Groups',
     'chats' => 'Chats',
     'friends' => 'Friends',
     'profile' => 'Profile',
     'powers' => 'Powers',
     'favorites' => 'Favorites',
     'featured' => 'Featured',
     'popular' => 'Popular',
     'new' => 'New',
     'standard' => 'Standard',
     'rare' => 'Rare',
     'epic' => 'Epic',
     'settings' => 'Settings',
     'help' => 'Help',
     'more' => 'More',
     'message' => 'Message',
     'close' => 'Close',
     'xats' => 'xats',
     'days' => 'days',
     'store' => 'Store',
     'justnow' => 'just now',
     'minsago' => 'mins ago',
     'hoursago' => 'hours ago',
     'daysago' => 'days ago',
     'buyxats' => 'Buy '. XAT_NAME .'s',
     'back' => 'Back'
	 ]
?>