<?php


$array = [
     'nameemail' => 'Name/Email',
     'lost' => 'Lost?',
     'newuser' => 'New User?',
     'register' => 'Register',
     'email' => 'Email',
     'resetpass' => 'Reset password✉️',
     'confirmlogout' => 'Please confirm you want to log out.',
     'name' => 'Name',
     'password' => 'Password',
     'agree' => 'By registering you agree you are 14 years or older and you agree to the',
     'terms' => 'Terms of Service',
     'xatuser' => 'xat User?',
     'buyxats' => 'Buy '. XAT_NAME .'s',
     'reason' => 'Reason',
     'duration' => 'Duration',
     'hours' => 'Hours',
     'bootto' => 'Boot to',
     'editprofile' => 'Edit Profile',
     'avatar' => 'Avatar',
     'homepage' => 'Home Page',
     'save' => 'Save',
     'font' => 'Font size',
     'default' => 'Default',
     'small' => 'Small',
     'medium' => 'Medium',
     'large' => 'Large',
     'extra' => 'Extra large',
     'language' => 'Language',
     'notifications' => 'Notifications',
     'enable' => 'Enable',
     'friends' => 'Friends',
     'disable' => 'Disable',
     'tortoise' => 'Tortoise',
     'animatedsmilies' => 'Animated Smilies',
     'unanimatedsmilies' => 'Unanimated Smilies',
     'indicate' => 'Indicate',
     'all' => 'All',
     'pcs' => 'Private chats',
     'version' => 'Version',
     'nopowers' => 'No powers or out of days',
     'nogifts' => 'There are no gifts here',
     'addfav' => 'To add favorite chat groups, click on the grey star next to a xat group',
     'seewiki' => 'See wiki for details.',
     'wanttobuy' => 'Do you want to buy',
     'buy' => 'Buy',
     'soldout' => 'Sold out',
     'getfail' => 'Sorry. Get powers failed. Please try later.',
     'getpower' => 'Get Power',
     'confirm' => 'Confirm your purchase from xat store',
     'needxatid' => 'You need a xat ID to use xat. Please login or register.',
     'promoted' => 'Promoted'
	 ]
?>