<?php


$array = [
     'quizq1' => 'You receive a message from a person who claims to be a volunteer. This person says that your account is blocked and to resolve the problem you must give them your password and email address, otherwise your account will remain blocked. What do you do?',
     'quizq1a1' => 'Do not give them any information.',
     'quizq1a2' => 'You do not want to lose your '. XAT_NAME .' account, so you give them the information.',
     'quizq1a3' => 'Ask for proof that they’re a real volunteer.',
     'quizq1info' => 'Correct! '. XAT_NAME .' staff and volunteers will never ask for personal information in a private chat. Report the user by taking screenshots of their ID and message, then open a ticket under the Report Scam topic.',
     'quizq1image' => '<br img src="https://util.'. DOMAIN .'/wiki/images/f/f9/Securityimage1.png" class="img-fluid"/>',
     'quizq2' => 'You’re on the Trade chat trying to buy days. You’re contacted by a person who asks you to transfer your '. XAT_NAME .'s first. What do you do?',
     'quizq2a1' => 'Deny and suggest to use the Safe Trade app which is the recommended method.',
     'quizq2a2' => 'Transfer your '. XAT_NAME .'s first.',
     'quizq2a3' => 'Ask them for their days first instead.',
     'quizq2info' => 'That’s right! While buying and selling '. XAT_NAME .'s, days or powers you should always use the Safe Trade app. Through this application, you can see in real time what’s being negotiated. Never trade using the Transfer feature as transactions cannot be undone after completed.',
     'quizq2image' => '<br img src="https://util.'. DOMAIN .'/wiki/images/c/c0/Securityimage2.png" class="img-fluid"/>',
     'quizq3' => 'Your email provider offers 2-factor authentication protection. Should you enable this option?',
     'quizq3a1' => 'Yes. This will highly increase the security of the email address.',
     'quizq3a2' => 'No. My password is strong enough.',
     'quizq3a3' => 'Never. This protection is not useful.',
     'quizq3info' => 'Correct! 2-factor authentication on your email address will add an additional layer of security (by phone) to ensure that no one else but you can access your email - even if your password gets hacked.<br><br>Please contact your email provider for instructions on how to enable authentication for your email account. For Gmail accounts, please see <a href="https://www.google.com/landing/2step/" target="_blank">this page</a>.',
     'quizq3image' => '<br img src="https://util.'. DOMAIN .'/wiki/images/7/71/Securityimage3.png" class="img-fluid"/>',
     'quizq4' => 'You’re told about an update on the '. XAT_NAME .' login page. The user sends you the link for testing which is https://xaatt.com/login. What do you do?',
     'quizq4a1' => 'Do not click on that link since it is not a https://'. DOMAIN .' domain.',
     'quizq4a2' => 'Click on it to see what has changed.',
     'quizq4info' => 'Correct! Always check the address bar to make sure that you are on the <a href="https://'. DOMAIN .'" target="_blank">https://'. DOMAIN .'</a> domain before logging in, visiting a chat or entering any of your '. XAT_NAME .' information.',
     'quizq4image' => '<br img src="https://util.'. DOMAIN .'/wiki/images/7/7d/Securityimage4.png" class="img-fluid"/>',
     'quizq5' => 'A user offers to double your powers but you must trade your powers to them first. What do you do?',
     'quizq5a1' => 'Powers cannot be duplicated. You do not transfer your powers.',
     'quizq5a2' => 'Accept their offer. Double powers mean double profit.',
     'quizq5a3' => 'Ask for proof that they can double your items.',
     'quizq5info' => 'Well done! '. XAT_NAME .'s, days and powers cannot be duplicated. Scammers often use this approach to easily get your attention and your items. Report the user by taking screenshots of their ID and message, then open a ticket under the Report Scam topic.',
     'quizq5image' => '<br img src="https://util.'. DOMAIN .'/wiki/images/3/35/Securityimage5.png" class="img-fluid"/>',
     'quizq6' => 'You receive an email from info@'. DOMAIN .' saying that your powers must be manually reviewed by a '. XAT_NAME .' employee. The instruction says that you must trade the powers on chat to a specific person. If you refuse to do so, your account will be blocked for 3 months. What do you do?',
     'quizq6a1' => 'Ignore and report the email as spam.',
     'quizq6a2' => 'Accept with no further questioning. No block, please!',
     'quizq6a3' => 'Reply to the email asking for more information.',
     'quizq6info' => 'That’s right! You will never receive an email like this from '. XAT_NAME .'. All the notifications regarding your '. XAT_NAME .' account are handled on the support system at <a href="https://'. DOMAIN .'/ticket" target="_blank">'. DOMAIN .'/ticket</a> and nowhere else.',
     'quizq6image' => '<br img src="https://util.'. DOMAIN .'/wiki/images/3/3b/Securityimage6.png" class="img-fluid"/>',
     'quizq7' => 'Everyone knows that passwords are difficult to remember. So to make your life easier you decide to use the same password for your email address and '. XAT_NAME .' account. Is this secure?',
     'quizq7a1' => 'No!',
     'quizq7a2' => 'Definitely yes. So you never have the problem of forgetting your password.',
     'quizq7info' => 'You got it right! Difficulty can be rewarded. Always use different passwords for each of your online accounts to increase your protection.',
     'quizq7image' => '<br img src="https://util.'. DOMAIN .'/wiki/images/2/2b/Securityimage7.png" class="img-fluid"/>',
     'quizq8' => 'You learn about a free '. XAT_NAME .'s generator program that needs to be downloaded. What do you do?',
     'quizq8a1' => 'You know that '. XAT_NAME .'s cannot be generated, so you ignore this.',
     'quizq8a2' => 'Ask for more information.',
     'quizq8a3' => 'Ask for proof if '. XAT_NAME .'s can be generated.',
     'quizq8info' => 'You are right! '. XAT_NAME .'s cannot be generated for free! Be careful not to download any unknown program as they can be malicious and may contain harmful software (viruses).',
     'quizq8image' => '<br img src="https://util.'. DOMAIN .'/wiki/images/5/5c/Securityimage8.png" class="img-fluid"/>',
     'quizq9' => 'You received a message saying that your account is getting blocked within 24 hours unless you pay 10000 '. XAT_NAME .'s. What do you do?',
     'quizq9a1' => 'Do not send '. XAT_NAME .'s and ignore the user.',
     'quizq9a2' => 'Block? No way! I pay the fine.',
     'quizq9a3' => 'Ask for an explanation.',
     'quizq9info' => 'Correct! '. XAT_NAME .' staff and volunteers will never ask for '. XAT_NAME .'s. Report the user by taking screenshots of their ID and message, then open a ticket under the Report Scam topic.',
     'quizq9image' => '<br img src="https://util.'. DOMAIN .'/wiki/images/b/b4/Securityimage9.png" class="img-fluid"/>',
     'quizq10' => 'You’re offered an expensive amount of '. XAT_NAME .'s for your powers such as 50000 '. XAT_NAME .'s. During the trade, there are multiple failed attempts due to wrong password and other errors. What do you do?',
     'quizq10a1' => 'Respectfully tell the user that you will restart the trade.',
     'quizq10a2' => 'Ignore the issue and continue to trade.',
     'quizq10a3' => 'Ignore the user.',
     'quizq10info' => 'Correct! Scammers will try to steal your '. XAT_NAME .'s, days or powers by changing the quantity of '. XAT_NAME .'s, days or powers on the app.<br><br>Always be careful and double check all the powers of the trade after each failed attempt. Take an extra turn to recheck the trade details before clicking confirm.',
     'quizq10image' => '<br img src="https://util.'. DOMAIN .'/wiki/images/a/a2/Securityimage10.png" class="img-fluid"/>',
     'quizq11' => 'You receive a forum private message from a person claiming to be a '. XAT_NAME .' employee. The message asks for your account details (passwords and email), otherwise your account will get blocked by '. XAT_NAME .'. What do you do?',
     'quizq11a1' => 'Ignore the user and report them to the forum staff.',
     'quizq11a2' => 'Answer the message by providing the requested information.',
     'quizq11a3' => 'Ask for more information about the block.',
     'quizq11info' => 'Correct! '. XAT_NAME .' staff and volunteers will never contact you privately about '. XAT_NAME .' account issues such as blocking. All account issues are handled on the support system at <a href="https://'. DOMAIN .'/ticket" target="_blank">'. DOMAIN .'/ticket</a> and you should report inappropriate and malicious private messages.',
     'quizq11image' => '<br img src="https://util.'. DOMAIN .'/wiki/images/7/7a/Securityimage11.png" class="img-fluid"/>',
     'quizq12' => 'You’re told on a chat by a '. XAT_NAME .' employee to disable the 2-factor authentication protection from your email address. What do you do?',
     'quizq12a1' => 'Deny them and ignore.',
     'quizq12a2' => 'Disable the 2-factor authentication.',
     'quizq12info' => 'Yes, you’re right! '. XAT_NAME .' staff and volunteers will never ask you to disable the 2-factor authentication protection under any circumstances. Do not hesitate to report users who try to disable your account protections.',
     'quizq12image' => '<br img src="https://util.'. DOMAIN .'/wiki/images/4/45/Securityimage12.png" class="img-fluid"/>',
     'quizq13' => 'You’re told about a free '. XAT_NAME .'s generator page on a website. But to generate free '. XAT_NAME .'s you must enter your password and email address. What do you do?',
     'quizq13a1' => 'Ignore the website as you know that '. XAT_NAME .'s cannot be generated for free.',
     'quizq13a2' => 'Proceed and log in.',
     'quizq13a3' => 'Ask for proof if '. XAT_NAME .'s can be generated.',
     'quizq13info' => 'You are right! '. XAT_NAME .'s cannot be generated for free. Also, only enter with your '. XAT_NAME .' password on official <a href="https://'. DOMAIN .'" target="_blank">https://'. DOMAIN .'</a> pages. Always check the address bar to make sure you are at <a href="https://'. DOMAIN .'" target="_blank">'. DOMAIN .'</a>.',
     'quizq13image' => '<br img src="https://util.'. DOMAIN .'/wiki/images/5/57/Securityimage13.png" class="img-fluid"/>',
     'quizq14' => 'You’ve negotiated a deal to buy powers from a user on Trade chat. The user states they will trade half of the powers now and the rest later. What do you do?',
     'quizq14a1' => 'Refuse the offer - they should add all of the items now.',
     'quizq14a2' => 'Accept the offer. Nothing can go wrong.',
     'quizq14a3' => 'Ask for proof they have the remaining powers.',
     'quizq14info' => 'Correct! Scammers may try to stagger trades by offering an amount upfront and promising to pay the rest in the future. Never believe these users and only accept the agreed amount in one full trade. The user is unlikely to $array = afterwards.',
     'quizq14image' => '<br img src="https://util.'. DOMAIN .'/wiki/images/5/59/Securityimage14.png" class="img-fluid"/>',
     'quizq15' => 'You’re told about a free program that makes animated avatars (gifs). A person on a chat sends you a download link for the program that is on an unknown website. What do you do?',
     'quizq15a1' => 'Never download unknown files as they may contain viruses.',
     'quizq15a2' => 'Blindly download it.',
     'quizq15info' => 'Correct! Scammers will tempt you to download their viruses by posing as a helpful friend. Be careful not to download unknown files. A few tips to avoid downloading malicious things are:<br><br ol><li>Search for the file name on Google (program credibility and if it even exists).</li><li>Check alternative sources for download.</li><li>Run a virus scan over the file.</li></ol>',
     'quizq15image' => '<br img src="https://util.'. DOMAIN .'/wiki/images/1/19/Securityimage15.png" class="img-fluid"/>',
     'quizq16' => 'A person you met on a chat asks for your personal information such as your name, street address and email address. What do you do?',
     'quizq16a1' => 'Change the subject by saying you do not want to talk about your personal information.',
     'quizq16a2' => 'They seem to be cool enough so you answer their questions with your real information.',
     'quizq16a3' => 'Ignore the user.',
     'quizq16info' => 'Well done! You should not be sharing your personal information with anybody online. Never share your email address or password!',
     'quizq16image' => '<br img src="https://util.'. DOMAIN .'/wiki/images/d/d9/Securityimage16.png" class="img-fluid"/>',
     'quizq17' => 'You are notified on a chat that your '. XAT_NAME .' account has a problem and to fix it you must turn off the account protection on the '. XAT_NAME .' login page. What do you do?',
     'quizq17a1' => 'Never turn off your '. XAT_NAME .' account protections when asked.',
     'quizq17a2' => 'You will trust any stranger. You do log in to turn off protections.',
     'quizq17a3' => 'Ask them for further information before considering their request.',
     'quizq17info' => 'Correct! Your '. XAT_NAME .' account protections are not to be turned off under any circumstances. '. XAT_NAME .' employees and volunteers will never ask for you to turn off the protections.',
     'quizq17image' => '<br img src="https://util.'. DOMAIN .'/wiki/images/a/ab/Securityimage17.png" class="img-fluid"/>',
     'quizq18' => 'A friend of yours asks if they can borrow your namecolor power for some time, as they want to test its effects. What do you do?',
     'quizq18a1' => 'Do not give it away. There’s a chance that you won’t get it back.',
     'quizq18a2' => 'It is ok to give it away. You can get your powers back any time.',
     'quizq18a3' => 'Best friends forever. You click trade, no second thoughts!',
     'quizq18info' => 'That’s right! Your '. XAT_NAME .'s, days and powers are your sole responsibility. Lending does not exist on '. XAT_NAME .', and it will be viewed that you gave your items away. If you complete a trade or a transfer, it cannot be undone. Be very careful at all times. <a href="//util.'. DOMAIN .'/wiki/index.php?title=Special:MyLanguage/Trading" target="_blank">Read more here.</a>',
     'quizq18image' => '<br img src="https://util.'. DOMAIN .'/wiki/images/1/17/Securityimage18.png" class="img-fluid"/>',
     'quizq19' => 'You receive an email from info@'. DOMAIN .' stating you have just successfully purchased 100000 '. XAT_NAME .'s. It also states you need to confirm the payment by clicking on a link. The link redirects you to a page where you need to pay $100 to finally receive the '. XAT_NAME .'s. What do you do?',
     'quizq19a1' => 'This is a strange offer. If I purchased the '. XAT_NAME .'s successfully, why do I need to pay more? You block the email as this is a scam.',
     'quizq19a2' => 'The email comes from info@'. DOMAIN .' but $100 is a lot of money. Reply and ask for more information.',
     'quizq19a3' => 'I wasn’t planning to buy '. XAT_NAME .'s, but 100000 '. XAT_NAME .'s for $100 is a good deal. Go for it!',
     'quizq19info' => 'Correct! '. XAT_NAME .' will NEVER ask you to buy '. XAT_NAME .'s in an email, and the only safe place where you can buy '. XAT_NAME .'s for real money is <a href="https://'. DOMAIN .'/buy">https://'. DOMAIN .'/buy</a>. Some scammers are able to fake '. XAT_NAME .' email addresses, so you should never proceed, even if it shows info@'. DOMAIN .'. Nonetheless, if the deal looks too good to be true, it usually is, and you are very likely being scammed.',
     'quizq19image' => '<br img src="https://util.'. DOMAIN .'/wiki/images/f/fe/Securityimage19.png" class="img-fluid"/>',
     'start' => 'start quiz',
     'desc' => 'To get <a href="//util.'. DOMAIN .'/wiki/index.php?title=Special:MyLanguage/Tickle" target="_blank">Tickle</a> power for free, you need to complete the quiz below and answer each of the questions correctly.',
     'wronganswer' => 'This is incorrect. Please try again.',
     'next' => 'next',
     'continuein' => 'Continue in',
     'gratz' => 'Congratulations, you have completed the quiz! You should now be more knowledgeable about safety on '. XAT_NAME .'.',
     'tickle' => 'You have received the Tickle power.',
     'redirect' => 'Please wait while you are redirected to the login page.'
	 ]
?>