<?php
$array = [
     'groups' => 'Mga Grupo',
     'store' => 'Bilihan',
     'buyxats' => 'Bumili ng xats days',
     'powers' => 'Powers',
     'xavi' => 'xavis',
     'xatgroup' => ''.XAT_NAME.' group',
     'shortname' => 'maikling pangalan',
     'promotion' => 'Promosyon',
     'auctions' => 'Subasta',
     'community' => 'Komunidad',
     'more' => 'Marami pa',
     'twitter' => 'Twitter',
     'wiki' => 'Wiki',
     'support' => 'Suporta',
     'contact' => 'Contact',
     'help' => 'Tulong',
     'trade' => 'Kalakalan',
     'widgets' => 'Mga Widget',
     'login' => 'Login',
     'language' => 'Lenggwahe',
     'privacy' => 'Privacy',
     'terms' => 'Tuntunin',
     'safety' => 'Seguridad',
     'failed' => 'nabigo',
     'evalid' => 'email ay hindi valid',
     'recaperr' => 'Ang reCAPTCHA ay hindi nalagay ng tama. Mangyaring subukang muli. (sabi ng reCAPTCHA',
     'notbot' => 'at para ma-verify ikaw ay hindi bot',
     'numinbox' => 'Mangyaring ilagay ang numero sa box',
     'cancel' => 'Kanselahin',
     'submit' => 'Magsumite',
     'wrongnum' => 'Maling number ang inilagay!',
     'ayaherr' => 'Kailangang patunayan na ikaw ay tao'
	 ]
?>